### ISSUE TITLE
v503 Too high ASK price for BOUGHT_PRICE pair

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#100]
This just happened. Not sure what's going on... The ask price is clearly too high. This was a coin where I had to insert the BOUGHT_PRICE I think.

![screen shot 2017-09-13 at 6 02 46 pm](https://user-images.githubusercontent.com/7082654/30405075-7760d4a4-98af-11e7-98f1-3faedf9a5b2d.png)

![screen shot 2017-09-13 at 6 14 49 pm](https://user-images.githubusercontent.com/7082654/30405077-793bc874-98af-11e7-9a01-395f6d9033c1.png)

**Comment by smportis** [comment]
This may be a 502 issue. Sale was at 2pm, before 503 came out. Cancelling the sell manually.

**Comment by GuntharDeNiro** [comment]
ok then i close this, free to reopen eventually
