### ISSUE TITLE
Feature Request: Ability to configure BTC_TRADING_LIMIT as a percentage of the pot

### ISSUE THREAD

**Issue by jamesburkework** [GuntharDeNiro/BTCT#101]
The ability to configure BTC_TRADING_LIMIT as a percentage of the BTC pot would avoid issues raised with insufficient funds and involve less manual management of funds.

It would have to have a limit, something like minimum amount to make a profit considering settings and after fees.

**Comment by GuntharDeNiro** [comment]
We had this in previous versions of the bot: community proven this is not the right thing to do because it woudnt take in consideration coins priority to invest funds and decided to move to fixed amount per trade.
