### ISSUE TITLE
TV Plugin do not sell

### ISSUE THREAD

**Issue by misson1682** [GuntharDeNiro/BTCT#103]
On v5.0.4
I did Set up TV Plugin
- Created Alert BUY 
BUY_BITTREX_BTC-STRAT
- Created Alert SELL 
SELL_BITTREX_BTC-STRAT
-> bot Did buy the correct amount at the correct time 
But unfortunately BOT did not sell (error as you can see in my screen capture here : 
![error5](https://user-images.githubusercontent.com/31955775/30426318-cea0ea94-9975-11e7-9a9d-35786c1eee9c.png)

**Comment by GuntharDeNiro** [comment]
i will do some more tests on this even tho i received some other users feedback and it appears to work.

**Comment by misson1682** [comment]
After better test from Exquitas, its look like TV PLugin sell when there is profit (is config was "TV_GAIN": 0.6)
So the only problem still not resolved is selling with a loss "TV_GAIN": 0, (error on  my first screen capture)
If we use TV Plugin, we should be able to apply the strategy at 100% with or without profit.

**Comment by GuntharDeNiro** [comment]
@misson1682 the formula is if last price is > bought price + gain then sell. If you set gain at 0 it simply checks any value better than bought price. Do you want to sell at loss with a custom strategy? I dont get this. Tell me more...

**Comment by Exquitas** [comment]
@misson1682 like I told you over PM, the whole purpose of GB is to generate profits. It's senseless to program it in a way where users lose money intentionally or unintentionally

**Comment by misson1682** [comment]
I need to be able to sell at any times to avoid bags. If you use risky strategy and its go wrong you need cut loss asap.

**Comment by GuntharDeNiro** [comment]
fixed in v5.0.5
Thanks for reporting this!
