### ISSUE TITLE
double_up not working

### ISSUE THREAD

**Issue by dotpim** [GuntharDeNiro/BTCT#104]
Averaging down with double_up enabled, is not working for me in this release (or any 5x version).

Relevant Config lines:
The last pair i tried it on:
"BTC_CLAM": {"strategy": "bb","override": { }},

The config for BB:
"bb": {
			"BTC_TRADING_LIMIT": 0.01, 
			"PERIOD": 15, 
			"EMA1": 2, 
			"EMA2": 4, 
			"GAIN": 2, 
			"HIGH_BB": 40, 
			"LOW_BB": 40, 
			"STDV": 2, 
			"SMAPERIOD": 50, 
			"PANIC_SELL": false, 
			"DOUBLE_UP": true, 
			"STOP_LIMIT": 60, 
			"BUY_ENABLED": true, 
			"MIN_VOLUME_TO_BUY": 0.0001, 
			"MIN_VOLUME_TO_SELL": 0.0001 

tried running it overnight, price hit set lower bb value multiple times, definitely. Still no averaging down took place. Nothing in the logs shows that it even consided doing so, the only entries that show for this pair look like:
Nothing changed in BTC_CLAM: Bid/Ask is

Tried the same settings in 4.0.5 afterwards, and it immediately started averaging down.

**Comment by GuntharDeNiro** [comment]
THis is not how double up works: it triggers another buy when the highbb value drops below the bought price (not when the price hits the lowbb).
free to reopen this issue eventually. 
Thanks
