### ISSUE TITLE
Instant rebuy

### ISSUE THREAD

**Issue by GuntharDeNiro** [GuntharDeNiro/BTCT#105]
none posted this here nor i was provided with valid evidences so i'm posting here hoping someone would provide a screenshot of values from the bot console of the instant rebuy.
I have started 40 pairs on stepgain with output in json now.
Hope to catch this.
Thanks!

**Comment by tandyuk** [comment]
Just had this again..
Bittrex BTC-BLK

CLOSED DATE | OPENED DATE | TYPE | BID/ASK | UNITS FILLED BLK | UNITS TOTAL BLK | ACTUAL RATE | COST / PROCEEDS
-- | -- | -- | -- | -- | -- | -- | --
09/18/2017 05:52:08 AM | 09/18/2017 05:52:08 AM | Limit Buy | 0.00003560 | 561.79775280 | 561.79775280 | 0.00003559 | -0.02004998
09/18/2017 05:51:03 AM | 09/18/2017 05:51:00 AM | Limit Sell | 0.00003549 | 568.66647711 | 568.66647711 | 0.00003548 | 0.02013153
09/18/2017 05:49:51 AM | 09/18/2017 05:49:51 AM | Limit Buy | 0.00003517 | 568.66647711 | 568.66647711 | 0.00003516 | -0.02004998



Chart at the time
https://s.tradingview.com/x/J5Hir6n2/


52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B |  ɢՍҊɮØŦ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 06:49:28
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:49:28: BTC-BLK Last Bid/Ask 0.00003532/0.00003537
52|b_BTC-B | 2017/09/18 06:49:29: Got Trading History
52|b_BTC-B | 2017/09/18 06:49:29: Averaged bought price: 0.0000336
52|b_BTC-B | 2017/09/18 06:49:29: Price to sell: 0.000033902399999999996
52|b_BTC-B | 2017/09/18 06:49:29: EMA1: 0.00003598/EMA2: 0.00003604
52|b_BTC-B | 2017/09/18 06:49:29: Price to buy: 0.00003526
52|b_BTC-B | 2017/09/18 06:49:30: Got Open Orders
52|b_BTC-B | 2017/09/18 06:49:30: Last Bid/Price to sell: 0.00003532/0.00003390
52|b_BTC-B | 2017/09/18 06:49:30: Last Ask/Price to buy: 0.00003537/0.00003526
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | EMA1: 0.00003598 == EMA2: 0.00003604
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:49:30: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | 2017/09/18 06:49:30: We are on level 2 to sell (bought/sell at): 0.0000336/0.000033902399999999996
52|b_BTC-B | 2017/09/18 06:49:30: There are some trading opportunities for BTC-BLK at bittrex. Scanning Trade History
52|b_BTC-B | 2017/09/18 06:49:30: Last Bid price BTC-BLK: 0.00003532 | Last Ask: 0.00003537
52|b_BTC-B | 2017/09/18 06:49:30: Balance BTC: 0.0206482
52|b_BTC-B | 2017/09/18 06:49:30: Balance BLK: 0
52|b_BTC-B | 2017/09/18 06:49:30: On Orders BLK: 0
52|b_BTC-B | 2017/09/18 06:49:30: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | Processing strategy STEPGAIN for BTC-BLK on bittrex
52|b_BTC-B | ┌───────────────┬──────────────────────────────────────┬────────────┬──────────────┬────────────┬───────────┬─────┬─────────┐
52|b_BTC-B | │ ɢƱƝßѺŦ v5.0.4 │ EMA1                                 │ EMA2       │ Buy at       │ Last       │ BTC       │ BLK │ Pair    │
52|b_BTC-B | ├───────────────┼──────────────────────────────────────┼────────────┼──────────────┼────────────┼───────────┼─────┼─────────┤
52|b_BTC-B | │ Buy cycle     │ 0.00003598                           │ 0.00003604 │ 0.0000352604 │ 0.00003537 │ 0.0206482 │ 0   │ BTC-BLK │
52|b_BTC-B | ├───────────────┼──────────────────────────────────────┼────────────┴──────────────┴────────────┴───────────┴─────┴─────────┤
52|b_BTC-B | │ Callbacks     │ Waiting to buy: price is too high!!! │                                                                    │
52|b_BTC-B | └───────────────┴──────────────────────────────────────┴────────────────────────────────────────────────────────────────────┘
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B |  ɢƱƝɮØŦ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 06:49:50
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:49:50: BTC-BLK Last Bid/Ask 0.00003502/0.00003517
52|b_BTC-B | 2017/09/18 06:49:51: Got Trading History
52|b_BTC-B | 2017/09/18 06:49:51: Averaged bought price: 0.0000336
52|b_BTC-B | 2017/09/18 06:49:51: Price to sell: 0.000033902399999999996
52|b_BTC-B | 2017/09/18 06:49:51: EMA1: 0.00003598/EMA2: 0.00003604
52|b_BTC-B | 2017/09/18 06:49:51: Price to buy: 0.00003526
52|b_BTC-B | 2017/09/18 06:49:51: Got Open Orders
52|b_BTC-B | 2017/09/18 06:49:51: Last Bid/Price to sell: 0.00003502/0.00003390
52|b_BTC-B | 2017/09/18 06:49:51: Last Ask/Price to buy: 0.00003517/0.00003526
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | EMA1: 0.00003598 == EMA2: 0.00003604
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:49:51: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | 2017/09/18 06:49:51: We are on level 2 to sell (bought/sell at): 0.0000336/0.000033902399999999996
52|b_BTC-B |  ɢՍͶɮ۝Ł v5.0.4  Tips&Tricks: BTC-BLK can be bought, checking balances...
52|b_BTC-B | 2017/09/18 06:49:51: There are some trading opportunities for BTC-BLK at bittrex. Scanning Trade History
52|b_BTC-B | 2017/09/18 06:49:51: Last Bid price BTC-BLK: 0.00003502 | Last Ask: 0.00003517
52|b_BTC-B | 2017/09/18 06:49:51: Balance BTC: 0.0206482
52|b_BTC-B | 2017/09/18 06:49:51: Balance BLK: 0
52|b_BTC-B | 2017/09/18 06:49:51: On Orders BLK: 0
52|b_BTC-B | 2017/09/18 06:49:51: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | Processing strategy STEPGAIN for BTC-BLK on bittrex
52|b_BTC-B | ┌───────────────┬─────────────┬──────────────┬──────────────┬────────────┬───────────┬─────┬─────────┐
52|b_BTC-B | │ ɢƱŋƁøŁ v5.0.4 │ EMA1        │ EMA2         │ Buy at       │ Last       │ BTC       │ BLK │ Pair    │
52|b_BTC-B | ├───────────────┼─────────────┼──────────────┼──────────────┼────────────┼───────────┼─────┼─────────┤
52|b_BTC-B | │ Buy cycle     │ 0.00003598  │ 0.00003604   │ 0.0000352604 │ 0.00003517 │ 0.0206482 │ 0   │ BTC-BLK │
52|b_BTC-B | ├───────────────┼─────────────┼──────────────┼──────────────┼────────────┼───────────┼─────┼─────────┤
52|b_BTC-B | │ Callbacks     │ Time to buy │ 0.00003517   │ BTC-BLK      │            │           │     │         │
52|b_BTC-B | ├───────────────┼─────────────┼──────────────┼──────────────┼────────────┼───────────┴─────┴─────────┤
52|b_BTC-B | │ BOUGHT!!!     │ Amount:     │ 568.66647711 │ Rate:        │ 0.00003517 │                           │
52|b_BTC-B | └───────────────┴─────────────┴──────────────┴──────────────┴────────────┴───────────────────────────┘
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B |  ɢƱΠ฿۝Ŧ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 06:50:58
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:50:58: BTC-BLK Last Bid/Ask 0.00003549/0.00003569
52|b_BTC-B | 2017/09/18 06:51:00: Got Trading History
52|b_BTC-B | 2017/09/18 06:51:00: Averaged bought price: 0.00003517
52|b_BTC-B | 2017/09/18 06:51:00: Price to sell: 0.000035486529999999995
52|b_BTC-B | 2017/09/18 06:51:00: EMA1: 0.00003624/EMA2: 0.00003621
52|b_BTC-B | 2017/09/18 06:51:00: Price to buy: 0.00003549
52|b_BTC-B | 2017/09/18 06:51:00: Got Open Orders
52|b_BTC-B | 2017/09/18 06:51:00: Last Bid/Price to sell: 0.00003549/0.00003549
52|b_BTC-B | 2017/09/18 06:51:00: Last Ask/Price to buy: 0.00003569/0.00003549
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | EMA1: 0.00003624 == EMA2: 0.00003621
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:51:00: Trend for BTC-BLK:    DOWN!!!
52|b_BTC-B | 2017/09/18 06:51:00: We are on level 2 to sell (bought/sell at): 0.00003517/0.000035486529999999995
52|b_BTC-B |  ɢƱÑβØͳ v5.0.4  Tips&Tricks: BTC-BLK can be sold, checking conditions...
52|b_BTC-B | 2017/09/18 06:51:00: There are some trading opportunities for BTC-BLK at bittrex. Scanning Trade History
52|b_BTC-B | 2017/09/18 06:51:00: Last Bid price BTC-BLK: 0.00003549 | Last Ask: 0.00003569
52|b_BTC-B | 2017/09/18 06:51:00: Balance BTC: 0.00090843
52|b_BTC-B | 2017/09/18 06:51:00: Balance BLK: 568.66647711
52|b_BTC-B | 2017/09/18 06:51:00: On Orders BLK: 0
52|b_BTC-B | 2017/09/18 06:51:00: Trend for BTC-BLK:    DOWN!!!
52|b_BTC-B | Processing strategy STEPGAIN for BTC-BLK on bittrex
52|b_BTC-B | 2017/09/18 06:51:00: To sell we need 0.000050454933181584755 BTC for fees - We have: 0.00090843 BTC
52|b_BTC-B | ┌───────────────┬────────────┬────────────┬────────────┬──────────────┬────────────┬─────────┐
52|b_BTC-B | │ ɢՍƝβ۝ͳ v5.0.4 │ EMA1       │ EMA2       │ Last       │ BLK          │ Last Buy   │ Pair    │
52|b_BTC-B | ├───────────────┼────────────┼────────────┼────────────┼──────────────┼────────────┼─────────┤
52|b_BTC-B | │ Sell cycle    │ 0.00003624 │ 0.00003621 │ 0.00003549 │ 568.66647711 │ 0.00003517 │ BTC-BLK │
52|b_BTC-B | └───────────────┴────────────┴────────────┴────────────┴──────────────┴────────────┴─────────┘
52|b_BTC-B | ************************************************************************************************
52|b_BTC-B | Strategy STEPGAIN for BTC-BLK on bittrex -| Selling 568.66647711 of BTC-BLK at rate 0.00003549
52|b_BTC-B | ************************************************************************************************
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B |  ɢƱÑɃøŦ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 06:52:07
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:52:07: BTC-BLK Last Bid/Ask 0.00003548/0.00003560
52|b_BTC-B | 2017/09/18 06:52:08: Got Trading History
52|b_BTC-B | 2017/09/18 06:52:08: Averaged bought price: 0.00003517
52|b_BTC-B | 2017/09/18 06:52:08: Price to sell: 0.000035486529999999995
52|b_BTC-B | 2017/09/18 06:52:08: EMA1: 0.00003651/EMA2: 0.00003650
52|b_BTC-B | 2017/09/18 06:52:08: Price to buy: 0.00003577
52|b_BTC-B | 2017/09/18 06:52:09: Got Open Orders
52|b_BTC-B | 2017/09/18 06:52:09: Last Bid/Price to sell: 0.00003548/0.00003549
52|b_BTC-B | 2017/09/18 06:52:09: Last Ask/Price to buy: 0.00003560/0.00003577
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | EMA1: 0.00003651 == EMA2: 0.00003650
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:52:09: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | 2017/09/18 06:52:09: We are on level 2 to sell (bought/sell at): 0.00003517/0.000035486529999999995
52|b_BTC-B |  ɢՍҊß๏Ŧ v5.0.4  Tips&Tricks: BTC-BLK can be bought, checking balances...
52|b_BTC-B | 2017/09/18 06:52:09: There are some trading opportunities for BTC-BLK at bittrex. Scanning Trade History
52|b_BTC-B | 2017/09/18 06:52:09: Last Bid price BTC-BLK: 0.00003548 | Last Ask: 0.0000356
52|b_BTC-B | 2017/09/18 06:52:09: Balance BTC: 0.02103996
52|b_BTC-B | 2017/09/18 06:52:09: Balance BLK: 0
52|b_BTC-B | 2017/09/18 06:52:09: On Orders BLK: 0
52|b_BTC-B | 2017/09/18 06:52:09: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | Processing strategy STEPGAIN for BTC-BLK on bittrex
52|b_BTC-B | ┌───────────────┬─────────────┬──────────────┬────────────┬───────────┬────────────┬─────┬─────────┐
52|b_BTC-B | │ ɢƱÑɃǾŁ v5.0.4 │ EMA1        │ EMA2         │ Buy at     │ Last      │ BTC        │ BLK │ Pair    │
52|b_BTC-B | ├───────────────┼─────────────┼──────────────┼────────────┼───────────┼────────────┼─────┼─────────┤
52|b_BTC-B | │ Buy cycle     │ 0.00003651  │ 0.00003650   │ 0.00003577 │ 0.0000356 │ 0.02103996 │ 0   │ BTC-BLK │
52|b_BTC-B | ├───────────────┼─────────────┼──────────────┼────────────┼───────────┼────────────┼─────┼─────────┤
52|b_BTC-B | │ Callbacks     │ Time to buy │ 0.0000356    │ BTC-BLK    │           │            │     │         │
52|b_BTC-B | ├───────────────┼─────────────┼──────────────┼────────────┼───────────┼────────────┴─────┴─────────┤
52|b_BTC-B | │ BOUGHT!!!     │ Amount:     │ 561.79775281 │ Rate:      │ 0.0000356 │                            │
52|b_BTC-B | └───────────────┴─────────────┴──────────────┴────────────┴───────────┴────────────────────────────┘
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B |  ɢՍƝβםŦ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 06:53:09
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:53:09: BTC-BLK Last Bid/Ask 0.00003548/0.00003550
52|b_BTC-B | 2017/09/18 06:53:10: Got Trading History
52|b_BTC-B | 2017/09/18 06:53:10: Averaged bought price: 0.0000356
52|b_BTC-B | 2017/09/18 06:53:10: Price to sell: 0.000035920399999999996
52|b_BTC-B | 2017/09/18 06:53:10: EMA1: 0.00003636/EMA2: 0.00003648
52|b_BTC-B | 2017/09/18 06:53:10: Price to buy: 0.00003563
52|b_BTC-B | 2017/09/18 06:53:11: Got Open Orders
52|b_BTC-B | 2017/09/18 06:53:11: Last Bid/Price to sell: 0.00003548/0.00003592
52|b_BTC-B | 2017/09/18 06:53:11: Last Ask/Price to buy: 0.00003550/0.00003563
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | EMA1: 0.00003636 == EMA2: 0.00003648
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:53:11: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | 2017/09/18 06:53:11: We are on level 2 to sell (bought/sell at): 0.0000356/0.000035920399999999996
52|b_BTC-B |  ɢƱͶƁѺŁ v5.0.4  Tips&Tricks: BTC-BLK can be bought, checking balances...
52|b_BTC-B | 2017/09/18 06:53:11: There are some trading opportunities for BTC-BLK at bittrex. Scanning Trade History
52|b_BTC-B | 2017/09/18 06:53:11: Last Bid price BTC-BLK: 0.00003548 | Last Ask: 0.0000355
52|b_BTC-B | 2017/09/18 06:53:11: Balance BTC: 0.02131727
52|b_BTC-B | 2017/09/18 06:53:11: Balance BLK: 561.7977528
52|b_BTC-B | 2017/09/18 06:53:11: On Orders BLK: 0
52|b_BTC-B | 2017/09/18 06:53:11: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | Processing strategy STEPGAIN for BTC-BLK on bittrex
52|b_BTC-B | 2017/09/18 06:53:11: To sell we need 0.00004983146067336 BTC for fees - We have: 0.02131727 BTC
52|b_BTC-B | Waiting to sell: price is too low!!!
52|b_BTC-B | Waiting to sell: trend is still up!!!
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B |  ɢՍΠɃØŁ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 06:53:16
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:53:16: BTC-BLK Last Bid/Ask 0.00003547/0.00003550
52|b_BTC-B | 2017/09/18 06:53:17: Got Trading History
52|b_BTC-B | 2017/09/18 06:53:17: Averaged bought price: 0.0000356
52|b_BTC-B | 2017/09/18 06:53:17: Price to sell: 0.000035920399999999996
52|b_BTC-B | 2017/09/18 06:53:17: EMA1: 0.00003636/EMA2: 0.00003648
52|b_BTC-B | 2017/09/18 06:53:17: Price to buy: 0.00003563
52|b_BTC-B | 2017/09/18 06:53:17: Got Open Orders
52|b_BTC-B | 2017/09/18 06:53:17: Last Bid/Price to sell: 0.00003547/0.00003592
52|b_BTC-B | 2017/09/18 06:53:17: Last Ask/Price to buy: 0.00003550/0.00003563
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | EMA1: 0.00003636 == EMA2: 0.00003648
52|b_BTC-B | ------------------------------------------------------------------------------------------------
52|b_BTC-B | 2017/09/18 06:53:17: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | 2017/09/18 06:53:17: We are on level 2 to sell (bought/sell at): 0.0000356/0.000035920399999999996
52|b_BTC-B |  ɢƱΠɮ๏Ŧ v5.0.4  Tips&Tricks: BTC-BLK can be bought, checking balances...
52|b_BTC-B | 2017/09/18 06:53:17: There are some trading opportunities for BTC-BLK at bittrex. Scanning Trade History
52|b_BTC-B | 2017/09/18 06:53:17: Last Bid price BTC-BLK: 0.00003547 | Last Ask: 0.0000355
52|b_BTC-B | 2017/09/18 06:53:17: Balance BTC: 0.02131727
52|b_BTC-B | 2017/09/18 06:53:17: Balance BLK: 561.7977528
52|b_BTC-B | 2017/09/18 06:53:17: On Orders BLK: 0
52|b_BTC-B | 2017/09/18 06:53:17: Trend for BTC-BLK:    UP!!!
52|b_BTC-B | Processing strategy STEPGAIN for BTC-BLK on bittrex
52|b_BTC-B | 2017/09/18 06:53:17: To sell we need 0.00004981741572954 BTC for fees - We have: 0.02131727 BTC
52|b_BTC-B | Waiting to sell: price is too low!!!
52|b_BTC-B | Waiting to sell: trend is still up!!!



        "period_storage_ticker": 500,
        "interval_ticker_update": 15000,
        "timeout_buy": 60000,
        "timeout_sell": 60000,
        "BOT_DELAY": 40

    "pairs": {
        "bittrex": {
            "BTC-BLK": {
                "strategy": "stepgain",
                "override": {
                    "PERIOD": 5,
                    "BUYLVL1": 1,
                    "BUYLVL2": 2,
                    "BUYLVL3": 20,
                    "SELLLVL1": 0.75,
                    "SELLLVL2": 0.9,
                    "SELLLVL3": 10,
                    "BUYLVL": 2,
                    "SELLLVL": 2,
                    "LASTPOINTS": 5,
                    "AVGPOINTS": 20,
                    "AVGMINIMUM": 1.0e-8,
                    "EMA1": 4,
                    "EMA2": 2,
                    "PANIC_SELL": false,
                    "DOUBLE_UP": false,
                    "STOP_LIMIT": 10
                }
            }
        }
    },
    "strategies": {
        "stepgain": {
            "BTC_TRADING_LIMIT": 0.02,
            "PERIOD": 5,
            "BUYLVL1": 1.5,
            "BUYLVL2": 2.5,
            "BUYLVL3": 4,
            "SELLLVL1": 0.9,
            "SELLLVL2": 1.2,
            "SELLLVL3": 1.9,
            "BUYLVL": 3,
            "SELLLVL": 2,
            "LASTPOINTS": 6,
            "AVGPOINTS": 30,
            "AVGMINIMUM": 1.0e-8,
            "EMA1": 8,
            "EMA2": 4,
            "PANIC_SELL": false,
            "STOP_LIMIT": 90,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001
        }
    },

**Comment by BitFlipp3r** [comment]
Happend with 5.0.4 on Polo.
![screenshot_20170918-142104](https://user-images.githubusercontent.com/2462286/30541892-7ca9a234-9c7d-11e7-9d00-9fd170c1e0eb.jpg)

         "bb": {
                        "BTC_TRADING_LIMIT": 0.05,
                        "PERIOD": 15,
                        "EMA1": 2,
                        "EMA2": 4,
                        "GAIN": 2,
                        "HIGH_BB": 42,
                        "LOW_BB": 38,
                        "STDV": 2,
                        "SMAPERIOD": 50,                                                                   "PANIC_SELL": false,
                        "DOUBLE_UP": false,
                        "STOP_LIMIT": 26,
                        "BUY_ENABLED": true,
                        "MIN_VOLUME_TO_BUY": 0.0001,
                        "MIN_VOLUME_TO_SELL": 0.0001

                },

Double_up is disabled because of #128

**Comment by GuntharDeNiro** [comment]
fixed in v5.0.5
Thanks for reporting this!
