### ISSUE TITLE
Error insuficient funds on sell, 5.0.3 and 5.0.4

### ISSUE THREAD

**Issue by sloaleks** [GuntharDeNiro/BTCT#106]
Processing strategy BB_STEPGAIN for XZECXXBT on kraken
┌───────────────┬────────────┬─────────────┬─────────────┬─────────┬────────────┬─────────────────────┬──────────┐
│ ɢՍͶɮǾŦ v5.0.4 │ SMA        │ LowBB       │ HighBB      │ Last    │ ZEC        │ Last Buy            │ Pair     │
├───────────────┼────────────┼─────────────┼─────────────┼─────────┼────────────┼─────────────────────┼──────────┤
│ Sell cycle    │ 0.05177090 │ 0.051022476 │ 0.052519324 │ 0.05081 │ 0.20399999 │ 0.04900000000000001 │ XZECXXBT │
└───────────────┴────────────┴─────────────┴─────────────┴─────────┴────────────┴─────────────────────┴──────────┘
Error on strategy BB_STEPGAIN for XZECXXBT on kraken while selling -| Error: Order:Insufficient funds
—----------------------------------------------------------------------------------------------
 ɢƱҊɮõͳ v5.0.4  Scanning kraken for trading opportunities 2017/09/15 00:57:31
—---------------------------------------------------------------------------------------

These were the funds

ɢՍÑ฿ØŦ v5.0.4  Tips&Tricks: XZECXXBT can be sold, checking conditions...
2017/09/15 00:57:25: There are some trading opportunities for XZECXXBT at kraken. Scanning Trade History
2017/09/15 00:57:25: Last Bid price XZECXXBT: 0.05081 | Last Ask: 0.05191
2017/09/15 00:57:25: Balance XBT: 0.01646958
2017/09/15 00:57:25: Balance ZEC: 0.20399999
2017/09/15 00:57:25: On Orders ZEC: 0
2017/09/15 00:57:25: Trend for XZECXXBT:    DOWN!!!

**Comment by GuntharDeNiro** [comment]
Not a bug. 0.02*0.05 = 0.01 which is lower than minimum allowed 
Reference: https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

**Comment by sloaleks** [comment]
This sum was bought by the gunbot ...

**Comment by GuntharDeNiro** [comment]
yes raise btc trading limit considering kraken limits + fees for both buy and sell order, referenced link above will be your firend on that.
THis is not a bot bug.

**Comment by sloaleks** [comment]
I dont get it. How could the bot buy 0.2 ZEC then?

**Comment by GuntharDeNiro** [comment]
because your settings or the market availability gave you an amount which was then lowered by fees till it became not sellable anymore. Please this is an issue tracker, not a support chat. Use referenced channels for support requests and/or help.
Thanks!

**Comment by sloaleks** [comment]
OK.

**Comment by balroh** [comment]
Actually,
the limit by Kraken for the XZECXXBT pair as stated in the reference you posted (https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-) is 0.03 ZEC.

> The minimum order size goes by base currency

which in this case is ZEC.

The screenshot above shows a balance 0.2 clearly above the 0.03 limit.

I think you need to reopen the issue.

**Comment by sloaleks** [comment]
Other people having the same problem https://gunthy.org/index.php/topic,1381.0.html
