### ISSUE TITLE
v 5.0.4 with bb standard settings - no buy

### ISSUE THREAD

**Issue by kinxox** [GuntharDeNiro/BTCT#109]
Hi,
my GB dont buy, but selling after manuall trade work as well. 

Config:
	"bot": {
		"debug": false,
		"period_storage_ticker": 2000,
		"interval_ticker_update": 25000,
		"timeout_buy": 60000,
		"timeout_sell": 60000,
		"WATCH_MODE": false,
		"VERBOSE": true,
		"TV_GAIN": 0.6,
		"TV_TRADING_LIMIT": 0.001,
		"BOT_DELAY": 1

Strategy:
		"bb": {
			"BTC_TRADING_LIMIT": 0.001,
			"PERIOD": 15,
			"EMA1": 2,
			"EMA2": 4,
			"GAIN": 1.5,
			"HIGH_BB": 40,
			"LOW_BB": 40,
			"STDV": 2,
			"SMAPERIOD": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.0005,
			"MIN_VOLUME_TO_SELL": 0.0005

ɢƱƝɮøͳ v5.0.4 Scanning bittrex for trading opportunities 2017/09/15 10:59:06
------------------------------------------------------------------------------------------------
2017/09/15 10:59:07: BTC-STEEM Last Bid/Ask 0.00028806/0.00028807
2017/09/15 10:59:07: Got Trading History
2017/09/15 10:59:07: Price to buy: 0.00029005
2017/09/15 10:59:08: Got Open Orders
2017/09/15 10:59:08: Last Bid/Price to sell: 0.00028806/0.00030288
2017/09/15 10:59:08: Last Ask/Price to buy: **0.00028807/0.00029005**
------------------------------------------------------------------------------------------------
HIGH BB: 0.00029784 == SMA: 0.00029135 == LOW BB: 0.00028486

I think I´m not doing anything wrong!?

Br.

**Comment by 3kynox** [comment]
I've got the exact same bb settings and it buy/ sells correctly. Think global market is going down currently due to the btc price dropping.

**Comment by kinxox** [comment]
no, there are big up and downs. I dont know the reason, but the bot dont place any buy order. Sell works great.

**Comment by kinxox** [comment]
hmm, I think my stepgain buy also dont work :/ f***

**Comment by kinxox** [comment]
two pc, two internet, diffrent pairs - no buy :(
![gunthy gui - gunbot no buy](https://user-images.githubusercontent.com/31984930/30500591-4af594f2-9a5f-11e7-9cc0-1fcf985c8b61.jpg)

**Comment by softgripper** [comment]
I am also experiencing this.  I've just checked XRP - and it should have bought, but no trades in the last 24 hours.

I have no trades across 36ish pairs.

**Comment by fahrmairm** [comment]
+1 also no buy with standard bb settings (double_up enabled) for 2 days. stepgain and bbstepgain worked normal. The moment I switched off double_up in bb strategy today, the bot started buying like crazy all the coins that had no bag.
Possibly there is bug that applies double_up strategy condition (higher bb<bought) also for non-bag coins somehow. This is why buy works for all strategies that do not rely on a high bb and it is also gone once you set double_up to false. Just a theory though...

**Comment by softgripper** [comment]
Upon saving the config file with double_up: false I had an immediate buy.

I will keep an eye on this over the next day.

**Comment by kinxox** [comment]
yes, its true. Double up disabled and instalty bb place buy orders.

**Comment by Gnorbe** [comment]
@fahrmairm Have you checked that BB calculated by gunbot are similar to the exchange chart? I have some problems configuring the BB correctly, see here: https: //github.com/GuntharDeNiro/BTCT/issues/97

if BB are calculated incorrectly (but the "last bid" price is correct), gunbot could buy and sell unexpectedly.

**Comment by GuntharDeNiro** [comment]
ok will look at this
