### ISSUE TITLE
Selling at a loss

### ISSUE THREAD

**Issue by IamDassa** [GuntharDeNiro/BTCT#110]
Hey, been playing with 5.0.4. Was trading fine until I used the "BTC_TRADING_LIMIT": 0.01 over ide. You can see when i was trading at 0.005 I made a small amount. But when trading at .01 it traded at a loss. Changed back to 0.005 and profit. Also did double buy and loss

Settings are 
		"bittrex": {
			"BTC-CLOAK": {
				"strategy": "stepgain",
				"override": {}
			},

		},
		"stepgain": {
			"BTC_TRADING_LIMIT": 0.005,
			"PERIOD": 5,
			"BUYLVL1": 1, 
			"BUYLVL2": 2, 
			"BUYLVL3": 20, 
			"SELLLVL1": 0.5, 
			"SELLLVL2": 0.75, 
			"SELLLVL3": 10, 
			"BUYLVL": 2, 
			"SELLLVL": 2, 
			"LASTPOINTS": 5, 
			"AVGPOINTS": 20, 
			"AVGMINIMUM": 0.00000001, 
			"EMA1": 4,
			"EMA2": 2,
			"PANIC_SELL": false,
			"STOP_LIMIT": false,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.005,
			"MIN_VOLUME_TO_SELL": 0.005

![image](https://user-images.githubusercontent.com/20713302/30476406-3d3d4f42-9a4d-11e7-860d-dc401eba9603.png)

**Comment by GuntharDeNiro** [comment]
possible yes: change those sell levels, you are deliberately selling at loss there.
