### ISSUE TITLE
STOP_LIMIT not being honoured

### ISSUE THREAD

**Issue by tandyuk** [GuntharDeNiro/BTCT#111]
So this morning I have been playing with STOP_LIMIT settings.

"STOP_LIMIT": 60, // % from bought price to sell if coin value drops

                        "BTC-ADX": {
                                "strategy": "stepgain",
                                "override": {
                                        "BTC_TRADING_LIMIT": 0.02
                                }
                        }

                "stepgain": {
                        "BTC_TRADING_LIMIT": 0.01,
                        "PERIOD": 5,
                        "BUYLVL1": 2,
                        "BUYLVL2": 4,
                        "BUYLVL3": 8,
                        "SELLLVL1": 0.9,
                        "SELLLVL2": 1.5,
                        "SELLLVL3": 3,
                        "BUYLVL": 3,
                        "SELLLVL": 3,
                        "LASTPOINTS": 5,
                        "AVGPOINTS": 250,
                        "AVGMINIMUM": 1e-8,
                        "EMA1": 2000,
                        "EMA2": 1000,
                        "PANIC_SELL": false,
                        "STOP_LIMIT": 1,
                        "BUY_ENABLED": true,
                        "MIN_VOLUME_TO_BUY": 0.001,
                        "MIN_VOLUME_TO_SELL": 0.001
                },

In my config I have tested both
STOP_LIMIT: 99
STOP_LIMIT: 1

neither of these limits results in the bot selling.

In telegram chat, it has been mentioned that it can take up to 2 days for the bot to actually sell once a coin passes its stop_limit.

Please clarify exactly how STOP_LIMIT behaves, and what time period the bot will sell.

Pair: BTC_ADX
Bought_Price (from bittrex): 0.00015801
Should sell at (or below): 0.00015642

with STOP_LIMIT: 1

------------------------------------------------------------------------------------------------
 ɢՍŋƁםŦ v5.0.4  Scanning bittrex for trading opportunities 2017/09/15 12:24:40
------------------------------------------------------------------------------------------------
2017/09/15 12:24:40: BTC-ADX Last Bid/Ask 0.00014241/0.00014514
2017/09/15 12:24:40: Got Trading History
2017/09/15 12:24:41: Averaged bought price: 0.00015802
2017/09/15 12:24:41: Price to sell: 0.0001627606
2017/09/15 12:24:41: EMA1: 0.00014527/EMA2: 0.00014539
2017/09/15 12:24:41: Price to buy: 0.00013365
2017/09/15 12:24:41: Got Open Orders
2017/09/15 12:24:41: Last Bid/Price to sell: 0.00014241/0.00016276
2017/09/15 12:24:41: Last Ask/Price to buy: 0.00014514/0.00013365
------------------------------------------------------------------------------------------------
EMA1: 0.00014527 == EMA2: 0.00014539
------------------------------------------------------------------------------------------------
2017/09/15 12:24:41: Trend for BTC-ADX:    DOWN!!!
Nothing changed in BTC-ADX: Bid/Ask is 0.00014241/0.00014514. Entry points are: 0.0001336484/0.0001627606

------------------------------------------------------------------------------------------------
 ɢՍƝß۝Ŧ v5.0.4  Scanning bittrex for trading opportunities 2017/09/15 12:24:52
------------------------------------------------------------------------------------------------
2017/09/15 12:24:52: BTC-ADX Last Bid/Ask 0.00014247/0.00014513
2017/09/15 12:24:53: Got Trading History
2017/09/15 12:24:53: Averaged bought price: 0.00015802
2017/09/15 12:24:53: Price to sell: 0.0001627606
2017/09/15 12:24:53: EMA1: 0.00014522/EMA2: 0.00014529
2017/09/15 12:24:53: Price to buy: 0.00013360
2017/09/15 12:24:53: Got Open Orders
2017/09/15 12:24:53: Last Bid/Price to sell: 0.00014247/0.00016276
2017/09/15 12:24:53: Last Ask/Price to buy: 0.00014513/0.00013360
------------------------------------------------------------------------------------------------
EMA1: 0.00014522 == EMA2: 0.00014529
------------------------------------------------------------------------------------------------
2017/09/15 12:24:53: Trend for BTC-ADX:    DOWN!!!
Nothing changed in BTC-ADX: Bid/Ask is 0.00014247/0.00014513. Entry points are: 0.0001336024/0.0001627606

And with STOP_LIMIT:99

------------------------------------------------------------------------------------------------
 ɢƱŋßםͳ v5.0.4  Scanning bittrex for trading opportunities 2017/09/15 12:28:20
------------------------------------------------------------------------------------------------
2017/09/15 12:28:20: BTC-ADX Last Bid/Ask 0.00014506/0.00014516
2017/09/15 12:28:21: Got Trading History
2017/09/15 12:28:21: Averaged bought price: 0.00015802
2017/09/15 12:28:21: Price to sell: 0.0001627606
2017/09/15 12:28:21: EMA1: 0.00014508/EMA2: 0.00014510
2017/09/15 12:28:21: Price to buy: 0.00013347
2017/09/15 12:28:21: Got Open Orders
2017/09/15 12:28:21: Last Bid/Price to sell: 0.00014506/0.00016276
2017/09/15 12:28:21: Last Ask/Price to buy: 0.00014516/0.00013347
------------------------------------------------------------------------------------------------
EMA1: 0.00014508 == EMA2: 0.00014510
------------------------------------------------------------------------------------------------
2017/09/15 12:28:21: Trend for BTC-ADX:    DOWN!!!
Nothing changed in BTC-ADX: Bid/Ask is 0.00014506/0.00014516. Entry points are: 0.0001334736/0.0001627606

------------------------------------------------------------------------------------------------
 ɢՍŋßøŦ v5.0.4  Scanning bittrex for trading opportunities 2017/09/15 12:29:01
------------------------------------------------------------------------------------------------
2017/09/15 12:29:01: BTC-ADX Last Bid/Ask 0.00014506/0.00014516
2017/09/15 12:29:02: Got Trading History
2017/09/15 12:29:02: Averaged bought price: 0.00015802
2017/09/15 12:29:02: Price to sell: 0.0001627606
2017/09/15 12:29:02: EMA1: 0.00014507/EMA2: 0.00014509
2017/09/15 12:29:02: Price to buy: 0.00013346
2017/09/15 12:29:02: Got Open Orders
2017/09/15 12:29:02: Last Bid/Price to sell: 0.00014506/0.00016276
2017/09/15 12:29:02: Last Ask/Price to buy: 0.00014516/0.00013346
------------------------------------------------------------------------------------------------
EMA1: 0.00014507 == EMA2: 0.00014509
------------------------------------------------------------------------------------------------
2017/09/15 12:29:02: Trend for BTC-ADX:    DOWN!!!
Nothing changed in BTC-ADX: Bid/Ask is 0.00014506/0.00014516. Entry points are: 0.0001334644/0.0001627606

**Comment by GuntharDeNiro** [comment]
uhm need to do some tests as in my repo it is working like a charm and i have a lot of users that are reporting a correct behaviour of stop limit.
Will let you know results. If it is a bug, expect a fix pretty soon as the stop limit is literaly 1 line of code and it has been there for a while.

**Comment by GuntharDeNiro** [comment]
fixed in v5.0.5
Thanks for reporting this!
