### ISSUE TITLE
v504 Double Buy

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#112]
Experienced a double buy last night on NAV coin during all its ups and downs. Bittrex. 

You will notice STOP_LIMIT is set at 1% for testing, which did add to the buying and selling.

If you want the log output at that time, LMK.

![screen shot 2017-09-15 at 9 10 23 am](https://user-images.githubusercontent.com/7082654/30486652-d4f4cc9a-99f6-11e7-8be8-bc47af6b540c.png)

Settings: 
"stepgain": {
            "BTC_TRADING_LIMIT": 0.0155,
            "PERIOD": 15,
            "BUYLVL1": 0.5,
            "BUYLVL2": 0.7,
            "BUYLVL3": 3,
            "SELLLVL1": 0.7,
            "SELLLVL2": 1.6,
            "SELLLVL3": 3.5,
            "BUYLVL": 2,
            "SELLLVL": 2,
            "LASTPOINTS": 5,
            "AVGPOINTS": 250,
            "AVGMINIMUM": 0.00000001,
            "EMA1": 2,
            "EMA2": 4,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "STOP_LIMIT": 1,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001
            
        },

**Comment by lucidqdreams** [comment]
I can confirm the same experience with double_up set to false

**Comment by GuntharDeNiro** [comment]
ok will look at it
