### ISSUE TITLE
Request: Make Sells easier to find in Terminal output

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#113]
Next time you are banging around in the sell area, will you make it easier to see a sell when scanning the terminal output? You can see the tables for when it is looking to buy or sell, but not when it actually sells. 

You have this: 
******************************************************************************************
Strategy STEPGAIN for BTC-NAV on bittrex -| Selling 87.13083673 of BTC-NAV at rate 0.00019975
******************************************************************************************

It's kind of like, wah, wah, we sold. So what. Put a box around it, make it red, put the GB logo on it, something - this is what we are all here for!! This is the premier event! (Silly, I know, but we all go looking for the sales, and especially while debugging and testing it is nice to find this visually rather than searching for "on bittrex -| Selling" which just isn't any fun).

**Comment by GuntharDeNiro** [comment]
it is actually marked like this indeed:

***********************************************************************************************************
Strategy STEPGAIN for BTC-NAV on bittrex -| Selling 87.13083673 of BTC-NAV at rate 0.00019975
***********************************************************************************************************

and the aserisks are all green

I can add some fireworks tho.
