### ISSUE TITLE
v5.0.4 Stepgain strategy returns "price to buy" always at 0

### ISSUE THREAD

**Issue by afhdyt** [GuntharDeNiro/BTCT#117]
![untitled](https://user-images.githubusercontent.com/1044127/30510178-55342fc0-9ae9-11e7-9708-8777162e057c.png)

"price to buy" is always at 0

		"stepgain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUYLVL1": 0.6, 
			"BUYLVL2": 2, 
			"BUYLVL3": 70, 
			"SELLLVL1": 0.6, 
			"SELLLVL2": 2, 
			"SELLLVL3": 70, 
		
			"LASTPOINTS": 5, 
			"AVGPOINTS": 250, 
			"AVGMINIMUM": 0.00000001, 
			"EMA1": 2000,
			"EMA2": 1000,
			"PANIC_SELL": false,
			"STOP_LIMIT": 99,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001

**Comment by thejeremywhite** [comment]
Needs 
"BUYLVL": 1, ( or 2 or 3)
"SELLLVL": 1, ( or 2 or 3)

**Comment by GuntharDeNiro** [comment]
what @thejeremywhite is correct
