### ISSUE TITLE
[Feature Request]  - Logging to a file

### ISSUE THREAD

**Issue by lucidqdreams** [GuntharDeNiro/BTCT#119]
Can we have a way to log to file for each pair.  This way during bug exploration we can simply find the section relating to the buy or whatever or submit the log for the pair that has the issue.  Would really help trying to understand why the bot acted the way it did.

**Comment by softgripper** [comment]
Seconded ^ 👍

**Comment by tandyuk** [comment]
Thirded :)
In the mean time, I've written a php script to deploy bots using pm2.
Each bot has its own log courtesy of pm2.
https://github.com/tandyuk/gblauncher

**Comment by GuntharDeNiro** [comment]
useless, this version was born with websocket in mind which are now pushed in master and the gui that is coming out logs everything.
Logs in console will be nulled.
