### ISSUE TITLE
v504 timeout_buy and timeout_sell seem to work sporadically - Bittrex

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#120]
Sometimes orders cancel, and sometimes they do not at Bittrex. Seems sporadic. Another user reports they never seem to cancel, I have seen about 80% success rate on cancelling. 

I have default settings 60000 for both. Other user has 20000 for timeout_buy and 60000 for sell. 

Other settings available as needed.

**Comment by captaincheckov** [comment]
waiting for cancelling too for hours on bittrex. i manually cancel them for now.

**Comment by GuntharDeNiro** [comment]
it is not a timeout to cancel orders, it is an internal timeout for the process of buy/sell
