### ISSUE TITLE
Error on strategy BB for BTC_DOGE on poloniex while getting trades -| Error: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by schuetzophren** [GuntharDeNiro/BTCT#122]
I am getting this error on two pairs with different strategies, while other pairs running fine on that strategies.

Its BTC_DOGE and BTC_ZRX on poloniex

Log:

------------------------------------------------------------------------------------------------
 ɢՍΠƁםŁ v5.0.4  Scanning poloniex for trading opportunities 2017/09/17 14:25:37
------------------------------------------------------------------------------------------------
2017/09/17 14:25:37: BTC_DOGE Last Bid/Ask 0.00000022/0.00000023
Error on strategy BB for BTC_DOGE on poloniex while getting trades -| Error: Cannot read property 'error' of undefined
------------------------------------------------------------------------------------------------
 ɢՍͶɮ๏Ł v5.0.4  Scanning poloniex for trading opportunities 2017/09/17 14:26:04
------------------------------------------------------------------------------------------------
2017/09/17 14:26:04: BTC_ZRX Last Bid/Ask 0.00005552/0.00005600
2017/09/17 14:26:05: Got Trading History
2017/09/17 14:26:06: Averaged bought price: 0.00006406
2017/09/17 14:26:06: Price to sell: 0.00006534120000000001
2017/09/17 14:26:06: EMA1: 0.00005551/EMA2: 0.00005551
2017/09/17 14:26:06: Price to buy: 0.00005384
Error on strategy STEPGAIN for BTC_ZRX on poloniex while checking open orders -| Error: Cannot read property 'error' of undefined
------------------------------------------------------------------------------------------------

config:

"BTC_DOGE": {
				"strategy": "bb",
				"override": {
					"LOW_BB": 5,
					"HIGH_BB": 70,
					"BTC_TRADING_LIMIT": 0.005,
					"BOUGHT_PRICE": 0.00000028
				}
"BTC_ZRX": {
				"strategy": "stepgain",
				"override": {
					"BTC_TRADING_LIMIT": 0.005,
					"BOUGHT_PRICE": 0.00006406
				}
...
"strategies": {
		"bb": {
			"BTC_TRADING_LIMIT": 0.005,
			"PERIOD": 15,
			"EMA1": 2,
			"EMA2": 4,
			"GAIN": 2,
			"HIGH_BB": 40,
			"LOW_BB": 40,
			"STDV": 2,
			"BUY_LEVEL": 0.1, 
			"SMAPERIOD": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": false,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
		},
	"stepgain": {
			"BTC_TRADING_LIMIT": 0.005,
			"PERIOD": 15,
			"BUYLVL": 2,
			"BUYLVL1": 0.6,
			"BUYLVL2": 3,
			"BUYLVL3": 42,
			"SELLLVL": 2,
			"SELLLVL1": 0.6,
			"SELLLVL2": 2,
			"SELLLVL3": 50,
			"DOUBLE_UP": false,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"PANIC_SELL": false,
			"LASTPOINTS": 5,
			"AVGPOINTS": 250,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 2000,
			"EMA2": 1000
		},
		
Both pairs have set "BOUGHT_PRICE" value ? May this make problems ?

**Comment by GuntharDeNiro** [comment]
not a bug: timeouts from exchange, it resolves it after some minutes
