### ISSUE TITLE
Bot does not make USDT_BTC trade

### ISSUE THREAD

**Issue by mstfimi** [GuntharDeNiro/BTCT#123]
I tried with different versions with different strategies. USDT_BTC does not make any trade.

For example:
//  PRIMARY SETTINGS  
DEFAULT_MARKET_NAME: 'bittrex',
BUYLVL1: 2,
BUYLVL2: 4,
BUYLVL3: 6,
SELLLVL1: 2,
SELLLVL2: 3,
SELLLVL3: 5,
BUY_STRATEGY: 'BB',
SELL_STRATEGY: 'BB',
LOW_BB: 45,
HIGH_BB: 45,
PINGPONG_BUY: 0.12345678,
PINGPONG_SELL: 0.12345678,
BUY_LEVEL: 2,
GAIN: 2,
BTC_TRADING_LIMIT: 0.005,
SECURITY_MARGIN: 90,
MIN_VOLUME_TO_BUY: 0.0005,

It doesn't have any problems with other coins. Have you experienced with this before?

**Comment by GuntharDeNiro** [comment]
@mstfimi Based on what u posted here you are missing buylvl and selllvl settings

**Comment by mstfimi** [comment]
How? Which parameter is wrong and causes to miss the buylevel and sell level? It makes a lot of trade with other coins. What settings do you suggest for USDT_BTC?

**Comment by GuntharDeNiro** [comment]
This is from 3.3.2 which isnt in this issue tracker. Please follow up on telegram for help on this,
Thanks!
