### ISSUE TITLE
webGUI localhost connections

### ISSUE THREAD

**Issue by tandyuk** [GuntharDeNiro/BTCT#124]
Hi,

I'm seeing line 1692 of /listener/bittrex/BTC-ARK (dynamically generated) javascript is
    var exampleSocket = new WebSocket("wss://127.0.0.1:5000/?gui=native");

There's 2 problems here

First, the web browser making the request may not be the same machine, so this needs to be a routeable ip and not localhost.

Second, this assumes the bot is listening on port 5000, rather than taking the ws port from config.js

**Comment by tandyuk** [comment]
https://github.com/GuntharDeNiro/BTCT/blob/5a2e1d1d18b8823bd5682b73eb18ba6b8810d531/public/js/listener.js#L132
https://github.com/GuntharDeNiro/BTCT/blob/5a2e1d1d18b8823bd5682b73eb18ba6b8810d531/public/js/listener.lib.js#L1692

For those trying to get the gui working, those are the lines that need changing to your own ip and websocket port.
Then launch node app.js and connect to http://your-ip:3000/listener/
Select your exchange and pair, and hit change.
Now be patient, it takes a while for data to start coming in.

I'm also seeing the following event, so maybe a version needs updating somewhere..
{event: "gunbot", version: "4.0.4", time: 1505669184015}

And finally, my license is invalid apparantly, but otherwise it seems to be working.
{event: "check_license", exchange: "bittrex", valid: false, time: 1505669421757}

**Comment by GuntharDeNiro** [comment]
merged thanks!
