### ISSUE TITLE
Make failed buys timeout (faster) - bittrex

### ISSUE THREAD

**Issue by tandyuk** [GuntharDeNiro/BTCT#127]
Ok, so i have an issue where sometimes the bot places a buy order for eg 500 X.
buy order is processed, but after a while only 300 units of X have been bought, the other 200 are pending.

Eg, this SNGLS order:

ORDER DATE | TYPE | BID/ASK | UNITS FILLED SNGLS | UNITS TOTAL SNGLS | ACTUAL RATE | ESTIMATED TOTAL BTC |  
-- | -- | -- | -- | -- | -- | -- | --
09/18/2017 03:22:58 AM | Limit Buy | 0.00004511 | 434.59576411 | 443.36067390 | 0.00004510 | 0.02005000

Its now 03:51, and the bot is logging

89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S |  ɢƱҊ฿õͳ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 04:51:41
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | 2017/09/18 04:51:41: BTC-SNGLS Last Bid/Ask 0.00004545/0.00004577
89|b_BTC-S | 2017/09/18 04:51:41: Got Trading History
89|b_BTC-S | 2017/09/18 04:51:42: Averaged bought price: 0
89|b_BTC-S | 2017/09/18 04:51:42: Price to sell: 0
89|b_BTC-S | 2017/09/18 04:51:42: EMA1: 0.00004687/EMA2: 0.00004692
89|b_BTC-S | 2017/09/18 04:51:42: Price to buy: 0.00004593
89|b_BTC-S | 2017/09/18 04:51:42: Got Open Orders
89|b_BTC-S | 2017/09/18 04:51:42: Last Bid/Price to sell: 0.00004545/0.00000000
89|b_BTC-S | 2017/09/18 04:51:42: Last Ask/Price to buy: 0.00004577/0.00004593
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | EMA1: 0.00004687 == EMA2: 0.00004692
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | 2017/09/18 04:51:42: Trend for BTC-SNGLS:    UP!!!
89|b_BTC-S | 2017/09/18 04:51:42: We are on level 2 to sell (bought/sell at): 0/0
89|b_BTC-S |  ɢƱΠβםͳ v5.0.4  Tips&Tricks: BTC-SNGLS can be bought, checking balances...
89|b_BTC-S | 2017/09/18 04:51:42: There are some trading opportunities for BTC-SNGLS at bittrex. Scanning Trade History
89|b_BTC-S | 2017/09/18 04:51:42: Last Bid price BTC-SNGLS: 0.00004545 | Last Ask: 0.00004577
89|b_BTC-S | 2017/09/18 04:51:42: Balance BTC: 0.0738647
89|b_BTC-S | 2017/09/18 04:51:42: Balance SNGLS: 434.59576411
89|b_BTC-S | 2017/09/18 04:51:42: On Orders SNGLS: 0
89|b_BTC-S | 2017/09/18 04:51:42: Trend for BTC-SNGLS:    UP!!!
89|b_BTC-S | Processing strategy STEPGAIN for BTC-SNGLS on bittrex
89|b_BTC-S | 2017/09/18 04:51:42: To sell we need 0.00004938094369699876 BTC for fees - We have: 0.0738647 BTC
89|b_BTC-S | WARNING: we couldnt get a BOUGHT PRICE for BTC-SNGLS, Please manually override it using config.js

![untitled](https://user-images.githubusercontent.com/82787/30527899-9d148b7c-9c25-11e7-8b93-694f3123bea1.png)

Chart shows the exact buy time (perfect), but the incomplete order made it miss a great sell opportunity.
(although not with this strategy)

Now I manually cancel the order.
Price at this point is up to 0.00004592

89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S |  ɢƱÑβõͳ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 04:59:38
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | 2017/09/18 04:59:38: BTC-SNGLS Last Bid/Ask 0.00004573/0.00004601
89|b_BTC-S | 2017/09/18 04:59:38: Got Trading History
89|b_BTC-S | 2017/09/18 04:59:39: Averaged bought price: 0.00004511
89|b_BTC-S | 2017/09/18 04:59:39: Price to sell: 0.00004551599
89|b_BTC-S | 2017/09/18 04:59:39: EMA1: 0.00004682/EMA2: 0.00004689
89|b_BTC-S | 2017/09/18 04:59:39: Price to buy: 0.00004588
89|b_BTC-S | 2017/09/18 04:59:42: Got Open Orders
89|b_BTC-S | 2017/09/18 04:59:42: Last Bid/Price to sell: 0.00004573/0.00004552
89|b_BTC-S | 2017/09/18 04:59:42: Last Ask/Price to buy: 0.00004601/0.00004588
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | EMA1: 0.00004682 == EMA2: 0.00004689
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | 2017/09/18 04:59:42: Trend for BTC-SNGLS:    UP!!!
89|b_BTC-S | 2017/09/18 04:59:42: We are on level 2 to sell (bought/sell at): 0.00004511/0.00004551599
89|b_BTC-S | 2017/09/18 04:59:42: There are some trading opportunities for BTC-SNGLS at bittrex. Scanning Trade History
89|b_BTC-S | 2017/09/18 04:59:42: Last Bid price BTC-SNGLS: 0.00004573 | Last Ask: 0.00004601
89|b_BTC-S | 2017/09/18 04:59:42: Balance BTC: 0.01411222
89|b_BTC-S | 2017/09/18 04:59:42: Balance SNGLS: 434.59576411
89|b_BTC-S | 2017/09/18 04:59:42: On Orders SNGLS: 0
89|b_BTC-S | 2017/09/18 04:59:42: Trend for BTC-SNGLS:    UP!!!
89|b_BTC-S | Processing strategy STEPGAIN for BTC-SNGLS on bittrex
89|b_BTC-S | 2017/09/18 04:59:42: To sell we need 0.00004968516073187575 BTC for fees - We have: 0.01411222 BTC
89|b_BTC-S | Waiting to sell: trend is still up!!!

and a little later

89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S |  ɢՍƝɃõŦ v5.0.4  Scanning bittrex for trading opportunities 2017/09/18 05:03:17
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | 2017/09/18 05:03:17: BTC-SNGLS Last Bid/Ask 0.00004503/0.00004571
89|b_BTC-S | 2017/09/18 05:03:18: Got Trading History
89|b_BTC-S | 2017/09/18 05:03:18: Averaged bought price: 0.00004511
89|b_BTC-S | 2017/09/18 05:03:18: Price to sell: 0.00004551599
89|b_BTC-S | 2017/09/18 05:03:18: EMA1: 0.00004682/EMA2: 0.00004689
89|b_BTC-S | 2017/09/18 05:03:18: Price to buy: 0.00004588
89|b_BTC-S | 2017/09/18 05:03:19: Got Open Orders
89|b_BTC-S | 2017/09/18 05:03:19: Last Bid/Price to sell: 0.00004503/0.00004552
89|b_BTC-S | 2017/09/18 05:03:19: Last Ask/Price to buy: 0.00004571/0.00004588
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | EMA1: 0.00004682 == EMA2: 0.00004689
89|b_BTC-S | ------------------------------------------------------------------------------------------------
89|b_BTC-S | 2017/09/18 05:03:19: Trend for BTC-SNGLS:    UP!!!
89|b_BTC-S | 2017/09/18 05:03:19: We are on level 2 to sell (bought/sell at): 0.00004511/0.00004551599
89|b_BTC-S |  ɢՍŋ฿øŦ v5.0.4  Tips&Tricks: BTC-SNGLS can be bought, checking balances...
89|b_BTC-S | 2017/09/18 05:03:19: There are some trading opportunities for BTC-SNGLS at bittrex. Scanning Trade History
89|b_BTC-S | 2017/09/18 05:03:19: Last Bid price BTC-SNGLS: 0.00004503 | Last Ask: 0.00004571
89|b_BTC-S | 2017/09/18 05:03:19: Balance BTC: 0.01411222
89|b_BTC-S | 2017/09/18 05:03:19: Balance SNGLS: 434.59576411
89|b_BTC-S | 2017/09/18 05:03:19: On Orders SNGLS: 0
89|b_BTC-S | 2017/09/18 05:03:19: Trend for BTC-SNGLS:    UP!!!
89|b_BTC-S | Processing strategy STEPGAIN for BTC-SNGLS on bittrex
89|b_BTC-S | 2017/09/18 05:03:19: To sell we need 0.000048924618144683255 BTC for fees - We have: 0.01411222 BTC
89|b_BTC-S | Waiting to sell: price is too low!!!
89|b_BTC-S | Waiting to sell: trend is still up!!!

Personally I'd just like an 'auto-cancel order after X minutes' option.

**Comment by GuntharDeNiro** [comment]
ok
