### ISSUE TITLE
3.3.4 windows error "cannot read property indicators"

### ISSUE THREAD

**Issue by muzzy124** [GuntharDeNiro/BTCT#13]
![default](https://user-images.githubusercontent.com/23397163/28650023-6e634c6c-72ab-11e7-8b3c-9cc3bcfec3b5.PNG)
3.3.4 is not working with this error

**Comment by samcus** [comment]
@muzzy124 @GuntharDeNiro What was the solution? I'm having this error on my Mac as well.
