### ISSUE TITLE
5.0.4 Incoherent buying prices, and missing sales

### ISSUE THREAD

**Issue by paramecie** [GuntharDeNiro/BTCT#131]
All BB transactions Low 30, High 45 (I tried a different settings than my usual ones):

Please see where Gunbot buys, far in the HIGHBB band, higher than any average, moving or not:
![2017-09-19 22_32_09-gunthy gui](https://user-images.githubusercontent.com/32078594/30615887-a2bad68c-9d90-11e7-9aa8-cfa77daeecf1.png)

Then a few minutes later, please see the buying price !
![2017-09-19 23_06_58-gunthy gui](https://user-images.githubusercontent.com/32078594/30615924-c8ec73ec-9d90-11e7-9275-59a8604380c8.png)

It seems close to this problem:
https://gunthy.org/index.php/topic,1390.0.html

Note: I know those GUI pictures show a 5 minutes period, not 15 - but it's the same thing, incoherent buying price, it just makes a nicer display.

Configuration (extracts):

	"bot": {
		"debug": false,
		"period_storage_ticker": 2000,
		"interval_ticker_update": 25000,
		"timeout_buy": 60000,
		"timeout_sell": 60000,
		"WATCH_MODE": false,
		"VERBOSE": true,
		"TV_GAIN": 0.6,
		"TV_TRADING_LIMIT": 0.001,
		"BOT_DELAY": 50
	},

		"bb": {
			"BTC_TRADING_LIMIT": 0.006,
			"PERIOD": 15,
			"EMA1": 2,
			"EMA2": 4,
			"GAIN": 0.8,
			"HIGH_BB": 45,
			"LOW_BB": 30,
			"STDV": 2,
			"SMAPERIOD": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": false,
			"STOP_LIMIT": 99,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.0001,
			"MIN_VOLUME_TO_SELL": 0.0001
		},

		"gain": {
			"BTC_TRADING_LIMIT": 0.006,
			"PERIOD": 15,
			"BUY_LEVEL": 5,
			"GAIN": 0.8,
			"EMA1": 200,
			"EMA2": 50,
			"HIGH_BB": 45,
			"LOW_BB": 30,
			"STDV": 2,
			"SMAPERIOD": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": false,
			"STOP_LIMIT": 99,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
		},

Selling - why didn't it sell here:
![2017-09-19 22_37_14-gunthy gui](https://user-images.githubusercontent.com/32078594/30616748-94e4f350-9d93-11e7-93c7-abf5c3f48dd4.png)

And there:
![2017-09-19 23_38_38-gunthy gui](https://user-images.githubusercontent.com/32078594/30616818-d22cd3e0-9d93-11e7-99fe-3ea6d58a7843.png)

Thanks for your consideration!

**Comment by Gnorbe** [comment]
You have to check BB output from the bot not in the graph, because they can often be different. If the BB calculated by Gunbot are different than bittrex chart, the bot could buy and sell unexpectedly.. See here #118

**Comment by paramecie** [comment]
I'm very aware of this possible difference.
But I would find VERY strange it's such a difference (see the buying price on top)?
Ahhh I reread this post, and Guntar said: fixed in v5.0.5

YES! Thank you!

**Comment by GuntharDeNiro** [comment]
fixed in 505

**Comment by MikeLumpan** [comment]
is there any eta for 505? coz i think thats quiet critical
