### ISSUE TITLE
WebGUI socket support hosting issues

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#133]
I'm testing out the latest GUI from this repo. I've immediately hit a wall. The main issue is that I run gunbot (and the GUI) from a VPS at <insert provider>, as I'm sure do >75% of other bot owners. Most providers have every inbound port blocked by default (except for maybe RDP and SSH). My VPS only has eth0 as an internal IP (172.*) and lo. The public IP to my VPS is NAT'd by my provider to the internal IP.

gunbot binds the new websocket listener to all interfaces. I changed the gui config to bind to my internal IP instead lo, otherwise I cannot access the gui from my browser. I also changed the port to 8080 and added a VPS rule to allow this traffic.

Great. Now the GUI loads. Next issue. `/listener/gethost` gives this config:
`var config = {"port":5001,"clientport":8080,"hostname":"172.31.35.58"};`

That's a problem because the 172 address is un-routable and therefore the GUI websockets cannot make a connection to the bot.

Suggestions: A) add config option to GUI allowing to set this hostname or B) have wss connect back to 8080 and have the node app relay local wss connections. A is probably easier BUT it will require people to open another port on their host firewall. There should be notes of all this in the wiki/setup guide.

I would also recommend that in the GUI itself, you add a 'WSS Status: Connected' line much like how bittrex.com does.

**Comment by 3kynox** [comment]
Hello and thanks for suggestions. I'll make few tests on my VPS soon and return to you with workarounds.

ps : You got the `wss status connected` on the console.

**Comment by utdrmac** [comment]
Ideally this will be ran from something like pm2 or systemd so console output won't be seen directly.  or some will launch node inside screen/tmux and disconnect from session. Still won't be able to see any console output. Gunthar has made it clear that future development will be GUI-only, so status bars / reconnect buttons/etc in the GUI will be paramount.

**Comment by utdrmac** [comment]
@3kynox Hey. Just pulled the latest nightly build and this is still a problem. I cannot use the GUI because the GUI is attempting to access WSS over the internal IP of my VPS. There needs to be a parameter to override this. Thanks.

**Comment by 3kynox** [comment]
Hello Matthew,

a small status; I started to add a different hostname parameter but after few tests it do not work as expected. I have doubts about ssl so I'll investigate further and get it to work then coming back to you.
