### ISSUE TITLE
Enhancement: buy price and comment in Trading view plugin

### ISSUE THREAD

**Issue by wheeeee** [GuntharDeNiro/BTCT#135]
It would be really nice to set a buy price as well, when ordering with the tv plugin. I want to be able to invest differently depending on the indicator.

maybe like BUY_BITTREX_BTC-ETH_0.0123
so there would be room for a price added at the end.

Also it would be really nice if the bot would ignore everything after the "BUY_BITTREX_BTC-ETH_0.0123" syntax. Right now if you put anything behind it, the bot gets an error and does not buy. But I would find it very useful if i could add what i want after a space and the bot would just ignore it.

**Comment by GuntharDeNiro** [comment]
buy price can be set in alerts

**Comment by wheeeee** [comment]
i didnt mean at what price the bot should buy. of course thats whats tv for.

but for how many bitcoins it should buy. 

i have different kind of alerts for different analysis. and with some i would like to invest more if the signal triggers than with others.
