### ISSUE TITLE
Constant Timeouts on Poloniex for some days with 5.0.4

### ISSUE THREAD

**Issue by jkomar** [GuntharDeNiro/BTCT#140]
Am experiencing timeouts constantly with Poloniex since upgrading to 5.0.4 from 4.0.5. It seems that Gunbot is having trouble correcting on its own. Previous versions seemed to correct from timeouts pretty well.

Manually killing the bot and restarting will sometimes let Gunbot retrieve data for a short time, but then the timeouts start again.

./gunthy-linx64
Loading config...
INVALID LICENSE FOR KRAKEN!!! Please contact Gunthar!
INVALID LICENSE FOR BITTREX!!! Please contact Gunthar!
INVALID LICENSE FOR CRYPTOPIA!!! Please contact Gunthar!
Loading exchange poloniex
------------------------------------------------------------------------------------------------
 ɢƱÑßõŁ v5.0.4  Scanning poloniex for trading opportunities 2017/09/22 19:49:24
------------------------------------------------------------------------------------------------
Error on strategy BB_STEPGAIN for BTC_DASH on poloniex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...
------------------------------------------------------------------------------------------------
 ɢƱͶɮØͳ v5.0.4  Scanning poloniex for trading opportunities 2017/09/22 19:50:26
------------------------------------------------------------------------------------------------
Error on strategy BB_STEPGAIN for BTC_ETH on poloniex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...
------------------------------------------------------------------------------------------------
 ɢՍҊßõŁ v5.0.4  Scanning poloniex for trading opportunities 2017/09/22 19:51:30
------------------------------------------------------------------------------------------------
Error on strategy BB_STEPGAIN for BTC_XRP on poloniex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...
------------------------------------------------------------------------------------------------
 ɢƱÑ฿۝Ŧ v5.0.4  Scanning poloniex for trading opportunities 2017/09/22 19:52:31
------------------------------------------------------------------------------------------------
Error on strategy BB_STEPGAIN for BTC_LTC on poloniex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...
------------------------------------------------------------------------------------------------
 ɢՍΠβõŁ v5.0.4  Scanning poloniex for trading opportunities 2017/09/22 19:53:39
------------------------------------------------------------------------------------------------
Error on strategy STEPGAIN for BTC_ETC on poloniex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...
------------------------------------------------------------------------------------------------
 ɢƱΠɮ๏Ŧ v5.0.4  Scanning poloniex for trading opportunities 2017/09/22 19:54:41
------------------------------------------------------------------------------------------------
Error on strategy STEPGAIN for BTC_GAS on poloniex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...
------------------------------------------------------------------------------------------------
 ɢՍҊƁʘͳ v5.0.4  Scanning poloniex for trading opportunities 2017/09/22 19:55:48
------------------------------------------------------------------------------------------------
Error on strategy BB_STEPGAIN for BTC_BCH on poloniex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...
------------------------------------------------------------------------------------------------
 ɢƱҊɮםͳ v5.0.4  Scanning poloniex for trading opportunities 2017/09/22 19:56:58
------------------------------------------------------------------------------------------------
Error on strategy BB_STEPGAIN for BTC_ZEC on poloniex while getting order book -| Error: The connection with the exchange timed out: arming Gunbot again...

**Comment by 3kynox** [comment]
Hello,

I have no problem at all with this, and many from the community as well. I see this message sometimes (and other ones like ... property of undefined). This message in particular can have two source : 

- Poloniex not responding at the moment of the time_out error
- Your internet connection

Please try to make further test by checking in a long manner the exact behavior (occuring all the time ? Doing a ping to poloniex or another host respond fastly and correctly ?) and come back here with your reports. Without further details, I'm not able to investigate more on this.

**Comment by BitFlipp3r** [comment]
I have this error as well but it is not constant. But it looks like a bug because if there's a timeout and you stop and restart the bot, the next polo call always works. Then after some time, timeouts happen again. I also noticed that bot_delay does increase the "arming" time.

**Comment by 3kynox** [comment]
How many pairs are you using ?

bot_delay value is in milliseconds. You'll see significant changes by increasing it correctly.

For example, I'm with 25 pairs on polo, bot_delay is at 15 for me. Close to no errors. No bans from poloniex so far for me.

**Comment by jkomar** [comment]
I'm on a VPS at Linode running Debian Stretch. I was previously running Gunbot 4.0.5 and not seeing this behavior.

I'm getting good ping times:

ping poloniex.com
PING poloniex.com (104.20.13.48) 56(84) bytes of data.
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=1 ttl=61 time=0.868 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=2 ttl=61 time=1.42 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=3 ttl=61 time=0.972 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=4 ttl=61 time=0.947 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=5 ttl=61 time=1.12 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=6 ttl=61 time=1.57 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=7 ttl=61 time=0.949 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=8 ttl=61 time=0.994 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=9 ttl=61 time=1.24 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=10 ttl=61 time=0.961 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=11 ttl=61 time=1.87 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=12 ttl=61 time=0.995 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=13 ttl=61 time=0.964 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=14 ttl=61 time=0.974 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=15 ttl=61 time=0.958 ms
64 bytes from 104.20.13.48 (104.20.13.48): icmp_seq=16 ttl=61 time=0.982 ms

Is there a way to turn on debugging or capture the API responses to see if there is some more useful information?

Thanks,
Jason

**Comment by GuntharDeNiro** [comment]
@jkomar it is not ping matter, those are rate limits by cloudflare, solved in v505 thanks!

**Comment by jkomar** [comment]
Thanks Gunthar. Is there something I can do in settings to throttle Gunbot to not exceed the Cloudflare rate limits while we wait for version 5.0.5?

Thanks again,
Jason

**Comment by GuntharDeNiro** [comment]
@jkomar "attempt" to raise BOT_DELAY
