### ISSUE TITLE
Enhancement: Time delay to prevent buying after STOP_LIMIT has been engaged

### ISSUE THREAD

**Issue by wildcowboy23** [GuntharDeNiro/BTCT#141]
When STOP_LIMIT has been engaged market may be in a downwards spiral. Setting a delay time (in hours) allows the market to cool down and prevent buying again too soon. This in effect temporarily sets BUY_ENABLED to false internally for a set time specified by a new variable STOP_LIMIT_BUY_DELAY or with a similar name. 

**Why this is important:**
A new trading strategy. This function allows for the user to accept a small loss (say STOP_LIMIT = 5%) to prevent avoid holding on to bags of altcoins that have dropped significantly while opportunities to trade are ignored. The user can decide that performing more trades to make up for the loss taken from the stop limit is favorable. Or the user can decide that after a stop limit was engaged, manual action has to be taken before trading can start again on that market.

**Examples of how this works:**
'STOP_LIMIT_BUY_DELAY' : 0
The default setting. The delay is zero and everything works as before.

'STOP_LIMIT_BUY_DELAY' : 1
After STOP_LIMIT has been engaged the bot waits for one hour on that specific market until it starts buying again.

'STOP_LIMIT_BUY_DELAY' : Infinity
After STOP_LIMIT has been engaged the bot doesn't buy again until the user interferes by setting STOP_LIMIT_BUY_DELAY to 0.

**Comment by paramecie** [comment]
I would do it easier and universal:

"NEXT_TRADE_DELAY"=300

Means; DO NOT make ANY trade before at least N seconds (here 5 minutes) from the previous trade (buy or sell).

In short, completely ignore all BB, GAINS, etc - and wait N seconds, minutes, before trying anything.

My 0.02 satoshis.

**Comment by wildcowboy23** [comment]
That is a very good idea in and of itself and deserves a separate feature request!

One of the main reasons why I would like this feature request is the ability to stop buying (STOP_LIMIT_BUY_DELAY = Infinity) on a market when a stop limit has occurred. That allows for inspecting what went wrong before trading again.

The reason I chose a time delay is because I expect it would be easy to implement into the program and be as versatile as possible.

**Comment by paramecie** [comment]
OK, you're right on both - I make a separated feature request.

**Comment by GuntharDeNiro** [comment]
disabled buy if stop limit is hit (v505)

**Comment by sylance** [comment]
Ooops, I added a comment to an incorrect item.  This is the feature I want.  Many of my bags are from crashes so I'm interested in the micro stop loss strategy.
