### ISSUE TITLE
Changes not detected with custom config

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#143]
Start gunbot like this `./gunthy-linx64 --config=bittrex-config.js`
Now, modify a setting or two in that config. The change is not detected by bot. If you use the default config.js, changes ARE detected.

**Comment by GuntharDeNiro** [comment]
the command line option is not implemented.

**Comment by utdrmac** [comment]
Then what's the point of having custom configs in the first place if you aren't going to have the same behavior? Where is it documented that "Only the default config.js is monitored for changes. You must restart the bot for custom config changes to take affect."

**Comment by GuntharDeNiro** [comment]
@utdrmac i dont understand where and when you have seen we implemented a custom config file?

**Comment by utdrmac** [comment]
@GuntharDeNiro https://github.com/GuntharDeNiro/BTCT/releases/tag/4.0.4

> Implemented command line option to load config.js from external url: add param --config=http[s]// to use it. Example: ./gunthy-linx64 --config=https://gunthy.org/config.js

**Comment by utdrmac** [comment]
Using it like I am `./gunthy-linx64 --config=bittrex-config.js` works fine. The file is read and only my bittrex stuff is used. But I have to restart the bot if I make changes. One would expect all config files, whether default or specified, to behave the same.

**Comment by GuntharDeNiro** [comment]
yes that's not a custom, that was a feature request to load normal config.js from a remote location, which is not under fs.watch tho.
I suggest you to post what you want as a feature request so i can work on a task for it

**Comment by utdrmac** [comment]
Wouldn't a remote location also be a custom config?

**Comment by GuntharDeNiro** [comment]
@utdrmac it is not implemented as custom...
