### ISSUE TITLE
Enhancement: NEXT_TRADE_DELAY

### ISSUE THREAD

**Issue by paramecie** [GuntharDeNiro/BTCT#144]
Example of config:

"NEXT_TRADE_DELAY"=300

Means; DO NOT make ANY trade, for ANY reason/algorithm before at least N seconds (here 5 minutes) from the previous trade (buy or sell).

A default value of 0 would mean no specific delay.

The idea here is to be able to set a safety in case of pumps or dumps, for instance waiting a minimum of half an hour before the next trade...

**Comment by sylance** [comment]
+1 to this, but I'm really asking for a separate setting for a stop-loss delay.  Say a coin is crashing and triggers stop-loss, I want Gunbot to chill for a few hours until the coin stables out.
