### ISSUE TITLE
DOUBLE_UP: true does not enable feature

### ISSUE THREAD

**Issue by mekkanizm** [GuntharDeNiro/BTCT#145]
Hi,

When i have doubel_up false in bb settings the CMD output shows lots of pairs can be averaged/bought.

When i set double up to true in bb settings (all pairs are running pure bb), or in the overide section under pairs, the CMD output no long shows any pairs that can be averaged and no buys take place.

Any idea why this might be?

"strategies": {
		"bb": {
			"BTC_TRADING_LIMIT": 0.02, 
			"PERIOD": 15, 
			"EMA1": 200, 
			"EMA2": 50, 
			"GAIN": 1, 
			"HIGH_BB": 40, 
			"LOW_BB": 30, 
			"STDV": 2, 
			"SMAPERIOD": 720, 
			"PANIC_SELL": false, 
			"DOUBLE_UP": true, 
			"STOP_LIMIT": 75, 
			"BUY_ENABLED": true, 
			"MIN_VOLUME_TO_BUY": 0.0005, 
			"MIN_VOLUME_TO_SELL": 0.0005

**Comment by paramecie** [comment]
It won't buy (anyway) because price is > SMA - BUY_LEVEL% ?

**Comment by mekkanizm** [comment]
Bot definitely buys and sells correctly with those SMA settings, based on this thread
https://gunthy.org/index.php/topic,1417.0.html

Just strange how averaging opportunities are available with double up false, then aren't available with double up true.

**Comment by BitFlipp3r** [comment]
See #128

**Comment by mekkanizm** [comment]
thanks

**Comment by GuntharDeNiro** [comment]
referenced to #128 fixed in v505
