### ISSUE TITLE
Auto-cancel trades after X minutes/hours

### ISSUE THREAD

**Issue by caogeoge** [GuntharDeNiro/BTCT#146]
Hi Gunthar,

I'm trading on Bittrex and sometimes I notice my GunBot's sell & buy orders get stuck for hours due to nobody buying or selling my coins at that price (the price volatility is too quick), respectively. Some other people have encountered this too. I especially encounter this delay during my sleep (so this morning I got 3 pairs stuck for 4-5 hours). This results in missing trades since the funds are held till those orders are proceeded. Thus, it would be great if we can have GunBot automatically cancel trades after X minutes/hours have passed by. Or maybe cancel pending buys if it has been 1-2 hours since the price dropped lower than BUYLVL, or cancel pending sells if it has been 1-2 hours since the price rised higher than SELLLVL.

**Comment by caogeoge** [comment]
Of course this applies to orders not filled yet. For partially-filled orders, the users can choose to manually cancel or wait.

**Comment by grubbins2** [comment]
FYI - I see this happen as well. Not certain of the frequency yet, but occurred once in a 24h period so far. Thanks

**Comment by CallMeAldy** [comment]
I've never seen this happen to me so far. What pairs did it happen with and what strategy were you both using?

**Comment by grubbins2** [comment]
`BTC-NEO` pair
`bb` strategy

**Comment by tandyuk** [comment]
https://github.com/tandyuk/gunbotscripts

bittrex-govenor.php in this repo provides that functionality.
Its set to 5 minutes by default, but I run mine as a cronjob to cancel any trade left open for more than 60 seconds.

+1 for this to be a core basic function of the bot.
