### ISSUE TITLE
TV Pyramid Solution

### ISSUE THREAD

**Issue by allanster** [GuntharDeNiro/BTCT#147]
Gunthar, I've been thinking about TV integration and seems we need 2 variables for trade amount otherwise Pyramid won't work properly on sells (Gunbot will sell full balance instead of contract)...

TV_TRADING_LIMIT needs to be:

TV_TRADING_LIMIT_BUY

TV_TRADING_LIMIT_SELL

**Comment by smportis** [comment]
Agree. This is needed. Pyramiding is a key component to profitable scheme implementation on TV.

**Comment by GuntharDeNiro** [comment]
done
