### ISSUE TITLE
IMAP listener multiple mails loop bug

### ISSUE THREAD

**Issue by Finnfj** [GuntharDeNiro/BTCT#148]
When I get 2 notifications from TV on 5.0.4 the same time there seems to be an error processing them.
The following continues to loop until the bot eventually does nothing:

2017/09/25 08:17:11 Checking for new emails ɢƱΠβøͳ v5.0.4 TRADINGVIEWS Edition
Nothing to fetch
__[__ { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' },
  { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LTC' },
  { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LTC' },
  { timestamp: 1506320163225,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' } __]__
[ { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' },
  { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LTC' },
  { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LTC' },
  { timestamp: 1506320163225,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' } ]
2017/09/25 08:17:13 Checking for new emails ɢƱΠɮםŦ v5.0.4 TRADINGVIEWS Edition
Nothing to fetch
[ { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' },
  { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LTC' },
  { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LTC' },
  { timestamp: 1506320163225,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' } ]
[ { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' },
  { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LTC' },
  { timestamp: 1506320161334,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LTC' },
  { timestamp: 1506320163225,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-ETH' } ]

**Comment by Finnfj** [comment]
due to the big brackjets [] I assume that it somehow tries to put them together in one order

**Comment by Finnfj** [comment]
Ok now it suddenly works but I get 
`2017/09/25 12:46:20 Checking for new emails ɢƱΠɃõͳ v5.0.4 TRADINGVIEWS Edition
2017/09/25 12:46:20 Done
2017/09/25 12:46:20 Done fetching all messages!
emailParsed { timestamp: 1506336380423,
  type: 'sell',
  exchange: 'bittrex',
  pair: 'BTC-LSK' }
[ { timestamp: 1506336380436,
    type: 'sell',
    exchange: 'bittrex',
    pair: 'BTC-LSK' } ]
2017/09/25 12:46:22: Looking for pending orders...
2017/09/25 12:46:22 Checking for new emails ɢՍÑßѺͳ v5.0.4 TRADINGVIEWS Edition
Nothing to fetch
2017/09/25 12:46:22: Checking prices...
2017/09/25 12:46:22: Received a sell order...
Error: TypeError: Cannot read property 'available' of undefined
    at errorHandler (C:\snapshot\Gunbot-master\bittrex.js:0:0)
    at <anonymous>
undefined`

**Comment by wouterman** [comment]
I'm sure it's being fixed however just to confirm: This still happens as of 5.0.5.5.

Doesn't seem to matter if it is one or multiple emails. Gunbot just starts looping like the message from the first post without actually placing any orders.

Doesn't matter if RETRY_TV_ORDER is true or false.
