### ISSUE TITLE
sell level calculating incorrect, thus bot not selling

### ISSUE THREAD

**Issue by flyingnadda** [GuntharDeNiro/BTCT#149]
the bot is not calculating the current sell level correctly. 
using stepgain, v504, with gui .99

config settings:
sell level 1: 0.9
sell level 2: 1.7
sell level 3: 4.9

sell LVL: 1

it doesnt want to sell even when the top of the climb had been reached and trend is going down. 

the top of the climb was 12750 (buy price: 11980), this is a 6% price increase and the bot was still thinking it was on level 1. 

in below picture (after the peak of 12750) the current level was still above level 3 (5.4% potential profit), the trend kept going down and the bot did not want to sell, even though there were multiple sell possibilities. 

<img width="557" alt="schermafbeelding 2017-09-24 om 23 34 01" src="https://user-images.githubusercontent.com/32265737/30808223-7ff65560-a1fd-11e7-84b8-2f106d9488c1.png">

**Comment by paramecie** [comment]
Depends your GAIN parameter?
But also 5.0.4 has plural buy/sell bugs, corrected in 5.0.5 (which seems to be imminent...)
