### ISSUE TITLE
[5.0.5.1] Bot sells at loss on Bittrex (no override)

### ISSUE THREAD

**Issue by caogeoge** [GuntharDeNiro/BTCT#150]
Hi Gunthar,

My bot has been selling at loss twice today on Bittrex for some reasons. Attached are the screenshots:

![screenshot from 2017-09-25 21-16-04](https://user-images.githubusercontent.com/31834334/30842407-10274638-a237-11e7-96c5-fcafd6521db1.png)
![screenshot from 2017-09-25 21-16-45](https://user-images.githubusercontent.com/31834334/30842411-11e5b4be-a237-11e7-9a0c-bd855aaebdcc.png)

I'm not sure if this is already fixed in 5.0.5. I'm using pure SG/SG with modification of Diesel's settings (no OVERRIDE):

<pre><code>
"bot": {
	"debug": false,
	"period_storage_ticker": 500,
	"interval_ticker_update": 15000,
	"timeout_buy": 60000,
	"timeout_sell": 60000,
	"WATCH_MODE": false,
	"VERBOSE": true,
	"TV_GAIN": 0.6,
	"TV_TRADING_LIMIT": 0.001,
	"BOT_DELAY": 1
},
"strategies": {
	"stepgain": {
		"BTC_TRADING_LIMIT": 0.001,
		"PERIOD": 5,
		"BUYLVL1": 1.5,
		"BUYLVL2": 1.6,
		"BUYLVL3": 70,
		"SELLLVL1": 1.5,
		"SELLLVL2": 1.6,
		"SELLLVL3": 70,
		"BUYLVL": 2,
		"SELLLVL": 2,
		"LASTPOINTS": 4,
		"AVGPOINTS": 20,
		"AVGMINIMUM": 1e-8,
		"EMA1": 4,
		"EMA2": 2,
		"PANIC_SELL": false,
		"STOP_LIMIT": 60,
	        "BUY_ENABLED": true,
	        "MIN_VOLUME_TO_BUY": 0.00051,
		"MIN_VOLUME_TO_SELL": 0.0009
	}
}
</pre></code>

I'm also running 20 instances of GunBots to trade all pairs on Bittrex (the guide was written by Krypto in the wiki).

**Comment by caogeoge** [comment]
Hi Gunthar so I'm having another sale at loss for BTC-BTS. It looks like this problem is coin-specific (or maybe some wrong calculation with certain types of curve/coin?). Anyway here is the screenshot including all BTC-BTS sale loss. You can probably catch this by using the same settings that I have and trade BTC-BTS and BTC-GLD:

![screenshot from 2017-09-25 22-53-53](https://user-images.githubusercontent.com/31834334/30844568-7a1c4fcc-a244-11e7-8015-b211064f0e8f.png)

**Comment by caogeoge** [comment]
This morning I recorded another sale at loss for BTC-MUSIC. So BTC-MUSIC, BTC-BTS, BTC-GLD are the pairs you can try to reproduce the problem:

![screenshot from 2017-09-26 07-50-43](https://user-images.githubusercontent.com/31834334/30866975-908b4416-a28f-11e7-8b60-c3d240df0075.png)

**Comment by paramecie** [comment]
Are you sure the config shouldn't be more like:

			"LASTPOINTS": 5, 
			"AVGPOINTS": 250, 
			"AVGMINIMUM": 0.00000001, 
			"EMA1": 2000,
			"EMA2": 1000,

?

**Comment by caogeoge** [comment]
@paramecie I'm trying the default config for this pair & I would let you know.

**Comment by Hailthebagwan** [comment]
I'm having the exact same problem. It seems to be using the previous sell price as the new buy price ie. not updating the buy price. If you resrt the bot or refresh it fixes itself, but it means you have to be around for every transaction in case it happens again (3 for me today). Paramecie, an EMA1 of 2000 would be unusable and pretty much a straight line. I did a quick test and it doesn't even appear on the charts at 2000. 500 is a straight line. I'm using ema of 4 and 2 as well. Wonder if that's the problem. Regardless would be nice to have it fixed as it's costing me.

**Comment by Hailthebagwan** [comment]
Also I'm using version 5.0.4
