### ISSUE TITLE
5.0.4 sells at loss when coin was bought >30days ago and doubled up <30days ago

### ISSUE THREAD

**Issue by fahrmairm** [GuntharDeNiro/BTCT#151]
I think I found the reason for gunbot selling at a loss sometimes:

if the coins 1st buy was longer than 30 days ago (on poloniex) but there was a second buy (double up manually or automatically) less than 30 days ago, then gunbot only sees the second buy's price. This means gunboat is selling at a potentially quite considerable loss!!!
![screenshot at sep 26 10-36-04](https://user-images.githubusercontent.com/3747259/30850698-a1733092-a2a6-11e7-99a1-2b4aae4c158f.png)

**Comment by Horhel** [comment]
can we ask GunBot to save our trading history local so that it wont lose older trades?

**Comment by fahrmairm** [comment]
not sure if it is related to a Poloniex API problem. In my project I have a similar problem. Querying returnTradeHistory('all',start, end) seems to not return data older than 30 days, while returnTradeHistory('BTC_POT',start, end) does correctly work for start timestamps > 30days

**Comment by Omega246** [comment]
Interesting. I have/had the same problem. I thought it depends on the settings you used. It happend on bittrex as well. See: https://github.com/GuntharDeNiro/BTCT/issues/129

Maybe some other people can provide more input on this situation.

**Comment by realWiZ** [comment]
Confirmed on Bittrex. It was an old bag:

![image](https://user-images.githubusercontent.com/32036096/30961222-c4fab7a6-a445-11e7-925e-85ae323a081c.png)

**Comment by realWiZ** [comment]
Another one: I am stopping the pairs that I partially averaged less than 1 month ago

![image](https://user-images.githubusercontent.com/32036096/30962077-a7bf3c2c-a448-11e7-9094-609dd0b65908.png)
