### ISSUE TITLE
TradingView stuck Loading exchange bittrex

### ISSUE THREAD

**Issue by OnlyC** [GuntharDeNiro/BTCT#154]
This happen today, tried restart or run another GB but it still there. Yesterday it works fine.

**Comment by rkhambatta** [comment]
I am experiencing the same issue. As of approximately 7 hours ago, Gunbot stopped outputting "checking for new mail" logs.

I have tried extracting a whole new Gunbot instance on a new virtual machine, and the problem exists.

The issue appears to be external to the local machine.

**Comment by xx420xxmlg** [comment]
Same for me. I think it happened 7-10 hours ago after "Invalid response from license server"

**Comment by rkhambatta** [comment]
I would also like to add that in addition to my comment above, I have also switched email provider and updated the TV settings in config.js and the issue still exists.

It had been previously been operating flawlessley.  (In saying that, I only had it running for maybe 9 hours before as that is when my API licence was activated by Gunthar.

**Comment by OnlyC** [comment]
just tried to create a new imap password (not work) and figured out that GB did not send any request to Gmail from yesterday.
![imap](https://user-images.githubusercontent.com/1250580/30956379-55a404c2-a461-11e7-9c8e-ae946e4543cb.png)

**Comment by tekspirit** [comment]
I have had gunbot run with the tv extension without problem until yesterday.  Stopped and started it, and the isssue of hanging at "loading exchange bittrex" began.  If I turn imap_listener from true to false, everything works normal (but no tradingview integration).
I have switched email providers from imap.google.com to imap.fastmail.com to confirm it is not a google problem, and know it is a server side issue.  I have two bittrex keys registered with you, and I've tried both of them with the same hanging response.

**Comment by ReynaldoJose** [comment]
Thanks for reaching out to us on this issue. Sorry to hear you are having issues setting up an IMAP service. Currently the account has no restrictions that would impact this. We are always willing to offer guidance on issues that you may encounter, but we can only directly assist with platform related issues. All other support will be primarily guidance and references to external resources that can help you towards a resolution.

Depending on the nature of the issue, it could be anything from the service/application not binding to the public interface and port, or the internal firewall causing issues. Do you see any errors in the logs or the state of the connections ( such as through the ss or netstat command ) to validate what the application or service is supposed to be doing?

Keep us posted if you need any further guidance with this and if there are further questions or concerns please don't hesitate to reply with them.

Sincerely,
Javier
DigitalOcean Platform Support Specialist

**Comment by tekspirit** [comment]
Here is the directory listing of this installation.  Which log file should
I look at to see if things are working/ not working?
[image: Inline image 1]

Here is a plain netstat command while gunbot tv is hung at "loading
exchange bittrex":
Here is the directory listing of this installation.  Which log file should
I look at to see if things are working/ not working?

root@Ubuntu-1704-zesty-64-minimal /var/log # netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 Ubuntu-1704-zesty-6:ssh ip-64-134-190-204:27685
ESTABLISHED
tcp        0      0 Ubuntu-1704-zesty-6:ssh ip-64-134-190-204.:1876
ESTABLISHED
tcp        0    200 Ubuntu-1704-zesty-6:ssh ip-64-134-190-204.:6825
ESTABLISHED
tcp        0      0 Ubuntu-1704-zesty:58440 104.17.153.108:https
ESTABLISHED
udp        0      0 Ubuntu-1704-zesty:38981 ns2-coloc.hetzne:domain
ESTABLISHED
udp        0      0 Ubuntu-1704-zesty:45854 ns2-coloc.hetzne:domain
ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         DGRAM                    14852
/run/systemd/journal/syslog
unix  2      [ ]         DGRAM                    18882
/run/user/0/systemd/notify
unix  3      [ ]         DGRAM                    14795
/run/systemd/notify
unix  2      [ ]         DGRAM                    14797
/run/systemd/cgroups-agent
unix  8      [ ]         DGRAM                    14826
/run/systemd/journal/dev-log
unix  8      [ ]         DGRAM                    14837
/run/systemd/journal/socket
unix  3      [ ]         STREAM     CONNECTED     17154
/var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     17985
unix  3      [ ]         STREAM     CONNECTED     15696
unix  3      [ ]         STREAM     CONNECTED     15941
/var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    18866
unix  3      [ ]         STREAM     CONNECTED     15697
/run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     15552
/run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     15939
/run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    18627
unix  3      [ ]         DGRAM                    14800
unix  3      [ ]         STREAM     CONNECTED     17778
unix  3      [ ]         STREAM     CONNECTED     13186
unix  3      [ ]         DGRAM                    18884
unix  3      [ ]         STREAM     CONNECTED     16213
/var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     18846
unix  2      [ ]         DGRAM                    19651
unix  3      [ ]         STREAM     CONNECTED     15814
unix  3      [ ]         DGRAM                    14799
unix  3      [ ]         STREAM     CONNECTED     19653
/run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     18637
unix  3      [ ]         STREAM     CONNECTED     16287
/run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    13179
unix  2      [ ]         DGRAM                    13067
unix  3      [ ]         STREAM     CONNECTED     17484
unix  2      [ ]         DGRAM                    18873
unix  3      [ ]         STREAM     CONNECTED     17651
/run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    17557
unix  2      [ ]         DGRAM                    17638
unix  3      [ ]         STREAM     CONNECTED     15628
/run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    1793
unix  3      [ ]         STREAM     CONNECTED     17641
unix  3      [ ]         STREAM     CONNECTED     1675
unix  2      [ ]         DGRAM                    12574
unix  3      [ ]         STREAM     CONNECTED     18533
unix  3      [ ]         STREAM     CONNECTED     17620
unix  3      [ ]         DGRAM                    1794
unix  3      [ ]         STREAM     CONNECTED     17642
unix  3      [ ]         STREAM     CONNECTED     12605
/run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     16283
/run/systemd/journal/stdout
unix  2      [ ]         STREAM     CONNECTED     249158
unix  3      [ ]         DGRAM                    16698
unix  3      [ ]         DGRAM                    17554
unix  3      [ ]         DGRAM                    17555
unix  3      [ ]         STREAM     CONNECTED     15938
unix  2      [ ]         DGRAM                    16277
unix  2      [ ]         DGRAM                    271442
unix  2      [ ]         DGRAM                    17548
unix  3      [ ]         DGRAM                    16699
unix  3      [ ]         DGRAM                    17556
unix  3      [ ]         STREAM     CONNECTED     772395
unix  3      [ ]         STREAM     CONNECTED     17644
/var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    15100
unix  3      [ ]         STREAM     CONNECTED     15261
unix  2      [ ]         DGRAM                    760695
unix  3      [ ]         STREAM     CONNECTED     16896
unix  3      [ ]         STREAM     CONNECTED     14096
/run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     772396
unix  3      [ ]         STREAM     CONNECTED     15495
/run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    18885
unix  3      [ ]         STREAM     CONNECTED     15096
unix  3      [ ]         STREAM     CONNECTED     766157
unix  3      [ ]         STREAM     CONNECTED     766156
root@Ubuntu-1704-zesty-64-minimal /var/log #

**Comment by gregmca** [comment]
I also have the same problem, it was working for about 8 hours no hangs at 
Loading exchange bittrex

**Comment by ReynaldoJose** [comment]
Contact gunthar.. Fail2ban banned your ip

**Comment by gregmca** [comment]
thanks,
