### ISSUE TITLE
(5.0.4) cannot read 'available' of undefined

### ISSUE THREAD

**Issue by tsatsatsa** [GuntharDeNiro/BTCT#155]
When TV sends a BUY order gunbot works has intended and buys the crypto. Conversely, when it receives a sell order, it is not able to detect the balance on the exchange and does not sell. 
It happened on windows 10 with bittrex:
![image](https://user-images.githubusercontent.com/32352578/30951393-099d23f8-a423-11e7-8c9f-a26d59edf97a.png)

**Comment by rkhambatta** [comment]
FYI I have observed this issue with GB 5.0.1 under Linux, (Debian 8) but it is does not occur with GB 5.0.4 (also under Linux, Debian 8)
