### ISSUE TITLE
[5.0.5] on windows- bot issue - BB not calculated properly for a kraken pair

### ISSUE THREAD

**Issue by tocheto** [GuntharDeNiro/BTCT#157]
[config-temp.txt](https://github.com/GuntharDeNiro/BTCT/files/1344786/config-temp.txt)

![gb505_issue_3](https://user-images.githubusercontent.com/5599169/31021941-015e060a-a4fd-11e7-82f7-ad2dbf498a8c.png)

![gb505_issue_2](https://user-images.githubusercontent.com/5599169/31021932-fce48f54-a4fc-11e7-809d-fa47142e8605.png)
BB are way off even after the bot collected enough price data (around 8 hours)
Details: When I started v5.0.5 for the pair DASH/EUR on Kraken, the BB were calculated immediately as low_bb: 100 eur/ high_bb: ~430 eur, of actual price of ~270 eur.
The bot was left overnight and now the bands are still the same - low bb: 103.18 / high_bb: 426.31 / sma: 265. Actual price is 277.4.

Issue: BB are calculated as- low_bb: ~100 / high_bb: ~ 430 / sma: ~ 265
Expected: BB to be calculatedas-  low_bb: ~274 / high_bb: ~282/ sma: ~278
![gb505_issue_1](https://user-images.githubusercontent.com/5599169/31021923-f8816388-a4fc-11e7-81be-2e813c3dea35.png)

**Comment by paramecie** [comment]
FYI:
"BB are way off even after the bot collected enough price data (around 8 hours)"

It's not true anymore, it has already ALL the data just when you run it.
The history is downloaded on a gunbot server.

In short, you don't have to wait to see how it behaves.

Note that comparing a marketplace BB, EMA and so on to gunbot's one may still be an approximation, or ven completely false depending both settings...

**Comment by tocheto** [comment]
Thanks,
I understood that part and posted on telegram after the initial 5 minutes, but decided to wait anyway before posting this issue as a bug.
About the values - price to buy of 134 eur is not adequate for a coin with current price of 277 eur, no matter what. Do you agree on this?

**Comment by paramecie** [comment]
Sure - but as here I can't even run it more than 15 minutes that I'm not astonished.
But here I didn't notice those strange BBs. May depend your config, or luck.

**Comment by tocheto** [comment]
Probably it is related with the fact that kraken gives awful amount of errors with v5.0.5. If the bot considers the error as last bid/last ask of 0 instead of the last known price, then it becomes a soup of numbers...Just thinking out loud
