### ISSUE TITLE
[5.0.5] Bot hangs after connection reset attempting to pull BB history

### ISSUE THREAD

**Issue by dzazzo** [GuntharDeNiro/BTCT#160]
The bot appears to hang when trying to retrieve EMA history and runs into an issue - in this case, a TCP connection refused issue seems to cause the bot to stop processing.

Logs leading up to the exception:

29|gunbot| | ------------------------------------------------------------------------------------------------
29|gunbot| |  ɢՍΠɮǾŁ v5.0.5  Scanning bittrex for trading opportunities 2017/09/30 06:35:14
29|gunbot| | ------------------------------------------------------------------------------------------------
29|gunbot| | 2017/09/30 06:35:14: BTC-NAV Last Bid/Ask 0.00022200/0.00022330
29|gunbot| | 2017/09/30 06:35:19: Got Trading History
29|gunbot| | 2017/09/30 06:35:19: Price to buy: 0.00022033
29|gunbot| | 2017/09/30 06:35:19: Got Open Orders
29|gunbot| | 2017/09/30 06:35:19: Last Bid/Price to sell: 0.00022200/0.00022311
29|gunbot| | 2017/09/30 06:35:19: Last Ask/Price to buy: 0.00022330/0.00022033
29|gunbot| | ------------------------------------------------------------------------------------------------
29|gunbot| | HIGH BB: 0.00022607 == SMA: 0.00022224 == LOW BB: 0.00021842
29|gunbot| | ------------------------------------------------------------------------------------------------
29|gunbot| | 2017/09/30 06:35:19: Trend for BTC-NAV:    DOWN!!!   
29|gunbot| | Nothing changed in BTC-NAV: Bid/Ask is 0.000222/0.0002233. Entry points are: 0.00022032928775082394/0.00022311071999999997
29|gunbot| | ------------------------------------------------------------------------------------------------
29|gunbot| |  ɢՍŋßǾŁ v5.0.5  Scanning bittrex for trading opportunities 2017/09/30 06:35:19
29|gunbot| | ------------------------------------------------------------------------------------------------
29|gunbot| | 2017/09/30 06:35:19: BTC-DGD Last Bid/Ask 0.01842048/0.01847575
29|gunbot| | { RequestError: Error: connect ECONNREFUSED 138.197.69.201:3001
29|gunbot| |     at new RequestError (/snapshot/gunbot-build/node_modules/request-promise-core/lib/errors.js:14:15)
29|gunbot| |     at Request.module.exports.plumbing.callback (/snapshot/gunbot-build/node_modules/request-promise-core/lib/plumbing.js:87:29)
29|gunbot| |     at Request.RP$callback [as _callback] (/snapshot/gunbot-build/node_modules/request-promise-core/lib/plumbing.js:46:31)
29|gunbot| |     at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
29|gunbot| |     at emitOne (events.js:115:13)
29|gunbot| |     at Request.emit (events.js:210:7)
29|gunbot| |     at Request.onRequestError (/snapshot/gunbot-build/node_modules/request/request.js:884:8)
29|gunbot| |     at emitOne (events.js:115:13)
29|gunbot| |     at ClientRequest.emit (events.js:210:7)
29|gunbot| |     at Socket.socketErrorListener (_http_client.js:399:9)
29|gunbot| |     at emitOne (events.js:115:13)
29|gunbot| |     at Socket.emit (events.js:210:7)
29|gunbot| |     at emitErrorNT (internal/streams/destroy.js:62:8)
29|gunbot| |     at _combinedTickCallback (internal/process/next_tick.js:102:11)
29|gunbot| |     at process._tickCallback (internal/process/next_tick.js:161:9)
29|gunbot| |   name: 'RequestError',
29|gunbot| |   message: 'Error: connect ECONNREFUSED 138.197.69.201:3001',
29|gunbot| |   cause: 
29|gunbot| |    { Error: connect ECONNREFUSED 138.197.69.201:3001
29|gunbot| |        at Object.exports._errnoException (util.js:1026:11)
29|gunbot| |        at exports._exceptionWithHostPort (util.js:1049:20)
29|gunbot| |        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
29|gunbot| |      code: 'ECONNREFUSED',
29|gunbot| |      errno: 'ECONNREFUSED',
29|gunbot| |      syscall: 'connect',
29|gunbot| |      address: '138.197.69.201',
29|gunbot| |      port: 3001 },
29|gunbot| |   error: 
29|gunbot| |    { Error: connect ECONNREFUSED 138.197.69.201:3001
29|gunbot| |        at Object.exports._errnoException (util.js:1026:11)
29|gunbot| |        at exports._exceptionWithHostPort (util.js:1049:20)
29|gunbot| |        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
29|gunbot| |      code: 'ECONNREFUSED',
29|gunbot| |      errno: 'ECONNREFUSED',
29|gunbot| |      syscall: 'connect',
29|gunbot| |      address: '138.197.69.201',
29|gunbot| |      port: 3001 },
29|gunbot| |   options: 
29|gunbot| |    { method: 'POST',
29|gunbot| |      uri: 'http://api.gunthy.org:3001/ohlc',
29|gunbot| |      body: '{"exchange":"bittrex","pair":"BTC-DGD","start":1506766520,"end":9999999999,"period":900}',
29|gunbot| |      headers: { 'content-type': 'text/plain' },
29|gunbot| |      callback: [Function: RP$callback],
29|gunbot| |      transform: undefined,
29|gunbot| |      simple: true,
29|gunbot| |      resolveWithFullResponse: false,
29|gunbot| |      transform2xxOnly: false },
29|gunbot| |   response: undefined }

**Comment by paramecie** [comment]
Please read before writing - but thanks for the log.
https://github.com/GuntharDeNiro/BTCT/issues/156

The Forum is also dead for hours today - the whole server/s are overloaded.

**Comment by utdrmac** [comment]
+1 here. I lost the entire evening of trading because of this. Maintenance was done middle of my night while I was sleeping. Bot needs retry code here or ignore/continue code.

It was my understanding that the bot only needed to contact gunthy servers initially, then everything after that would come from exchanges. So why did my bot halt when it had been running for hours+? It should not have needed to contact gunthy servers according to what has been explained to us.

**Comment by dzazzo** [comment]
Yeah, I posted and then discovered the scheduled maintenance... so, this ought to be re-written to be a feature request to be able to log and move on (or somehow alert that Gunthar's server was inaccessible).

**Comment by paramecie** [comment]
>It was my understanding that the bot only needed to contact gunthy servers initially, then everything after that would come from exchanges. 

Yes/no: it for sure checks the gunbot licence from time to time, otherwise Gunthar wouldn't be able to remove a licence if the bot is running permanently...

>Either way, it would be a nice feature to have to have it 'fail-safe' with pre-5.0.5

Simply make the bot retry every once in a while, and do NOT do anything before having correct data would already be nice.
Reliability is the ultimate quality.

**Comment by paramecie** [comment]
>Yeah, I posted and then discovered the scheduled maintenance...

Where ? The forum is dead.
