### ISSUE TITLE
v5.0.5.1 Tickers array is empty!!!

### ISSUE THREAD

**Issue by thejeremywhite** [GuntharDeNiro/BTCT#162]
Occassional error when GB 505.1 receiving ticker data. Array is empty.
Tested both 505 and 504 in the last few minutes and neither is having this error. So, I don't think it is with Bittrex. I'm running windows 10, no GUI. GB still buys and sells great but just can't get ticker data occasionally for random coins, then it receives the ticker fine. Please check my output in PasteBin
https://pastebin.com/Z6j3VmBj

**Comment by thejeremywhite** [comment]
Exactly what I am doing. It's working fine otherwise. Thank you.

**Comment by paramecie** [comment]
Same report here on BTC-IOP. Waiting, seems to work for now, but too recently ran to tell.

**Comment by paramecie** [comment]
45 minutes later, 5.0.5.1 didn't hang, very speed. 
Made a nice sell in stepgain. 
For now, what an evolution, thanks Gunthar!

Ah, please describe what BOT_DELAY does :-(
I set it to 40, seems to be cooler than 1.

**Comment by GuntharDeNiro** [comment]
@paramecie it slows down your bot, it is useful for when you get api calls limit warning at poloniex or when you run only a few pairs.

**Comment by paramecie** [comment]
Yes, what the setting name seemed to mean. OK thank you.
I don't have had any warning from Bittrex for now, but I prefer not to take any risk.
I'll reduce it progressively.
Good evening!
