### ISSUE TITLE
GUI - Assumes gunbot isn't running. Doesn't verify.

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#164]
When you start the GUI, it assumes gunbot isn't running even if it already is. The GUI should be doing some `ps -Af | grep gunthy` to determine if it is already running or not and present a proper status.

**Comment by 3kynox** [comment]
Hey Mathew !

I get all of your issues, that's ok, this have to be managed, you're right.
Missing time dude :) I have another work close to GB.

Important thing for now is the first issue you posted : #133 

Incoming a better architecture also of the whole Gunbot & Gui too using some great node tech where we will have client / server separated. That will be better to maintain and permit everyones to have native os / mobile gui.

Stay around :)
