### ISSUE TITLE
[Bug] - Data usage is ridiculous on 5055

### ISSUE THREAD

**Issue by softgripper** [GuntharDeNiro/BTCT#165]
Data usage is ridiculous on 5055

Running the same pairs as all previous versions of 5x.  And basically the same config (diesel stepgain)

I've been running the bot for 2 months.  Changed to 5055 a couple of days ago.  This is the data usage from my VPS.

It will be over 300gb in 4 days.
![data-usage](https://user-images.githubusercontent.com/26377893/31305715-f6e607c8-ab8b-11e7-96b2-9faf5a041a06.jpg)

**Comment by miwi-fbsd** [comment]
Not that we have to care about traffic but we have to agree that the traffic is quiet high since we run 5.0.5.5

<img width="411" alt="traffic" src="https://user-images.githubusercontent.com/6657176/31310164-b06c4c6e-abc5-11e7-8541-f17ec2d76b19.png">

**Comment by utdrmac** [comment]
Yep. You can clearly see the 3x increase since 5.05 came out.

![bandwidthusage](https://user-images.githubusercontent.com/4413670/31311014-1b60a4be-ab69-11e7-8694-da64040c20d9.png)

**Comment by miwi-fbsd** [comment]
GB 5.0.5.5RC vs 5.0.4

all GUNTHY_API calls are false

<img width="640" alt="screenshot at oct 09 20-59-02" src="https://user-images.githubusercontent.com/6657176/31339464-85a17bc8-ad35-11e7-8e7d-2caf3be247af.png">

**Comment by benbeton** [comment]
![2017-10-10_15-28-34](https://user-images.githubusercontent.com/1405209/31389987-ef6661ac-add2-11e7-9931-ac215195a73d.png)

GB 5055 traffic in 24h (35 pairs)

**Comment by allanster** [comment]
I concur v5055_RC_8ab53b2 has SERIOUS bandwidth issues that MUST be addressed. I just examined usage on LAN on same VM same pure stepgain settings comparing v504 to v5055_RC_8ab53b2 and the usage is insane, there is definitely something wrong here!...

14Gb -> v504 with 9 pair 24 hours on 10/8 = 1.55GB/pair/day

43.3Gb -> v5055_RC_8ab53b2 with 3 pair 16 hours on 10/10 = 21.65GB/pair/day

I am seeing a 1400% increase in data usage! At this rate only 3 pairs would consume 2TB of bandwidth which exceeds the cap of most US home internet providers as well as many VPS providers. PLEASE look into this ASAP!

![bandwidth5 0 5 5rc_8ab53b2](https://user-images.githubusercontent.com/32180061/31413593-a63041a8-addf-11e7-92ce-cfc5fa041741.jpeg)

![bandwidth504](https://user-images.githubusercontent.com/32180061/31413594-a641b276-addf-11e7-9ba3-c4663b7cb7ca.jpeg)

**Comment by Dangerous-Mind** [comment]
Hi just to complement and compare.  

I have a Rig with the Gunbot, Gunbot Gui and Claymore miner working 24/7.
Last shutdown was almost 8 days ago and have 21 Gb
Another Rig working for 10 days has 1 Gb.

![image](https://user-images.githubusercontent.com/31196073/31414859-cf32e064-ae17-11e7-9dc2-a3df2cb64551.png)

I'm running only one instance with around 12 pairs most of the time. 
I have GUNTHY_API = false.

In my case particularly bandwidth is not a problem. But it might be a little high.

**Comment by paramecie** [comment]
@Dangerous-Mind I would *NOT* put a miner (especially a closed source) on a PC with an API connected to a marketplace.

This bandwidth problem is maybe because gunthy downloads the full 200 (ex) previous trades every period - instead of downloading the 200 first for the SMA for example, then only the very last one(s) ?
Just an idea...
