### ISSUE TITLE
v5.0.5.5 Gunbot Doubles Up when Trend is down

### ISSUE THREAD

**Issue by fahrmairm** [GuntharDeNiro/BTCT#168]
catching gunbot to double-up while trend is down (in strategy bbstepgain). Shouldn't it wait with the double-up until the trend reverses?
<img width="771" alt="screenshot at oct 09 00-28-30" src="https://user-images.githubusercontent.com/3747259/31321643-4096b054-ac89-11e7-9609-b2469819a4ce.png">

**Comment by murm78** [comment]
@fahrmairm If double up is true, we'll enter another buy cycle when the high bollinger band drops below the previous bought price. Some times this happens before the trend reverses, it depends on your SMAPERIOD
