### ISSUE TITLE
wiki_image_assets

### ISSUE THREAD

**Issue by dotpim** [GuntharDeNiro/BTCT#174]
![bb-strategy-detail](https://user-images.githubusercontent.com/2372008/31969233-2cebf586-b914-11e7-98a0-49471b29051a.png)
![gain-strategy-detail](https://user-images.githubusercontent.com/2372008/31969234-2d25414c-b914-11e7-9b87-b425113dce00.png)
![stepgain-strategy-detail](https://user-images.githubusercontent.com/2372008/31969235-2d6e0efe-b914-11e7-8531-39721fa35e33.png)

**Comment by dotpim** [comment]
![gunthar---logo](https://user-images.githubusercontent.com/2372008/32069438-76597c18-ba89-11e7-8722-b92e52e959d2.png)
![ema](https://user-images.githubusercontent.com/2372008/32069470-900b0cd0-ba89-11e7-93f1-fbdfa80b3001.png)

**Comment by dotpim** [comment]
![gunthar---logo](https://user-images.githubusercontent.com/2372008/32069628-fc0f5efe-ba89-11e7-9b73-9fc6ff4cb147.png)

**Comment by dotpim** [comment]
![bbrsi](https://user-images.githubusercontent.com/2372008/32072320-747219f6-ba92-11e7-8398-92914bda90e0.png)

**Comment by utdrmac** [comment]
There's a lot of extra lines on that BB chart. Can that be cleaned up to reduce confusion?

**Comment by dotpim** [comment]
![bbrsi](https://user-images.githubusercontent.com/2372008/32081580-a1cfb1f0-bab6-11e7-9590-8f4b2a501ac3.png)

**Comment by dotpim** [comment]
![bbrsi](https://user-images.githubusercontent.com/2372008/32081627-e1ee9e7c-bab6-11e7-9a86-9596ad6f78ad.png)

**Comment by dotpim** [comment]
![double-up](https://user-images.githubusercontent.com/2372008/32096078-95baa8ee-bb05-11e7-8f07-266a7a3952b1.jpg)

**Comment by dotpim** [comment]
![ui-settings-example](https://user-images.githubusercontent.com/2372008/32149952-5ee24274-bd0c-11e7-8d24-81e5ac1ab4f4.png)
![ui-setup](https://user-images.githubusercontent.com/2372008/32149954-5f302156-bd0c-11e7-84a2-8011305c6f04.png)
![ui-setup-example-bearish](https://user-images.githubusercontent.com/2372008/32149955-5f89230a-bd0c-11e7-89b9-9281c1d5432c.png)
![ui-setup-example-bullish](https://user-images.githubusercontent.com/2372008/32149956-5fc94ae8-bd0c-11e7-9766-f728e7f14e00.png)
![ui-setup-example-dashboard](https://user-images.githubusercontent.com/2372008/32149957-60289e76-bd0c-11e7-8432-c53530a20e1e.png)
![ui-setup-example-sideways](https://user-images.githubusercontent.com/2372008/32149958-60803532-bd0c-11e7-8def-d8de5e79bb15.png)
![ui-strategies](https://user-images.githubusercontent.com/2372008/32149960-60d66b96-bd0c-11e7-975d-8e8e45d65cb0.png)
![ui-api-keys](https://user-images.githubusercontent.com/2372008/32149961-61313436-bd0c-11e7-99e8-cf6d5fb28f5f.png)
![ui-append-override](https://user-images.githubusercontent.com/2372008/32149962-6157d618-bd0c-11e7-811d-44147f2026ec.png)
![ui-dashboard](https://user-images.githubusercontent.com/2372008/32149963-61875064-bd0c-11e7-927e-8fe5a3b723a9.png)

**Comment by dotpim** [comment]
![logo-home](https://user-images.githubusercontent.com/2372008/32150606-69fdd412-bd15-11e7-8005-64d2a1a9fe61.png)

**Comment by dotpim** [comment]
![logo-home](https://user-images.githubusercontent.com/2372008/32150659-0afdc89a-bd16-11e7-8d62-0ecb7cf0c90d.png)

**Comment by dotpim** [comment]
![tssl](https://user-images.githubusercontent.com/2372008/32302927-a52c4c60-bf65-11e7-9b57-731ff4ca629f.png)

**Comment by dotpim** [comment]
![photo5467403371519518836](https://user-images.githubusercontent.com/2372008/32368726-09fbe2d2-c087-11e7-95b5-385c2913aabf.jpg)

**Comment by dotpim** [comment]
![gui-override](https://user-images.githubusercontent.com/2372008/32993701-2b77d718-cd5c-11e7-9c5a-833a0b329974.gif)

**Comment by dotpim** [comment]
![gain-strategy-detail](https://user-images.githubusercontent.com/2372008/33532461-3e59d7c0-d89a-11e7-8010-bfe1dce777bb.png)

**Comment by dotpim** [comment]
![masterkey](https://user-images.githubusercontent.com/2372008/34016571-b5eb853c-e122-11e7-87e5-bb13e0becb4f.png)
![setup701](https://user-images.githubusercontent.com/2372008/34016572-b60de050-e122-11e7-9cab-8e274d871f35.png)

**Comment by dotpim** [comment]
![macos-installation](https://user-images.githubusercontent.com/2372008/34313103-28a55d5e-e769-11e7-9be1-5ac2872c1d1f.gif)

**Comment by dotpim** [comment]
![windows-installation](https://user-images.githubusercontent.com/2372008/34314841-5677bce0-e778-11e7-8ecf-fdad6caaa0dc.gif)

**Comment by dotpim** [comment]
![step09b](https://user-images.githubusercontent.com/2372008/34905990-172b2958-f864-11e7-87d1-f5c9d1491ff4.png)
![step09a](https://user-images.githubusercontent.com/2372008/34905991-17446ca6-f864-11e7-9043-359c3919c4cb.png)
![step03](https://user-images.githubusercontent.com/2372008/34905992-175e0cf6-f864-11e7-98a7-a440e713f32e.png)
![step09](https://user-images.githubusercontent.com/2372008/34905993-1776fb4e-f864-11e7-83a4-aaff739005af.png)

**Comment by dotpim** [comment]
![override](https://user-images.githubusercontent.com/2372008/36449655-b4fc264c-168b-11e8-8eb8-10d3f05ca7ba.gif)

**Comment by dotpim** [comment]
![reversal-trading-diagram_v4](https://user-images.githubusercontent.com/2372008/36509213-3af928c0-175f-11e8-8edf-b16eb6333b55.PNG)

**Comment by dotpim** [comment]
![reversal-trade-example](https://user-images.githubusercontent.com/2372008/36511037-885d60da-1765-11e8-8b64-5f6bf89a1048.PNG)

**Comment by dotpim** [comment]
![reversal-trading-simplified](https://user-images.githubusercontent.com/2372008/38331646-13c489aa-3854-11e8-95b4-8b9143edf69b.PNG)

**Comment by dotpim** [comment]
![reversal-trading-diagram_v7](https://user-images.githubusercontent.com/2372008/38333198-32a59c16-3858-11e8-9fbc-0e0e529faffa.PNG)

**Comment by dotpim** [comment]
![supported-periods](https://user-images.githubusercontent.com/2372008/39113320-9f285a5e-46db-11e8-8b51-f234935479b7.PNG)

**Comment by dotpim** [comment]
![screen shot 2018-04-23 at 10 56 21](https://user-images.githubusercontent.com/2372008/39117089-62947ba8-46e6-11e8-9d88-dae33a2420a2.png)
![screen shot 2018-04-23 at 10 57 44](https://user-images.githubusercontent.com/2372008/39117125-7b8bec22-46e6-11e8-8a60-802f40f44c6a.png)
![screen shot 2018-04-23 at 11 00 10](https://user-images.githubusercontent.com/2372008/39117138-8d925b4a-46e6-11e8-9525-41bdc0f9bf5c.png)
![screen shot 2018-04-23 at 11 02 02](https://user-images.githubusercontent.com/2372008/39117166-a00f564c-46e6-11e8-9f32-2c69f43b9977.png)
![screen shot 2018-04-23 at 11 03 11](https://user-images.githubusercontent.com/2372008/39117176-a9018a2c-46e6-11e8-8128-102c9de6c909.png)

**Comment by dotpim** [comment]
![supported-periods](https://user-images.githubusercontent.com/2372008/39126253-24505206-4702-11e8-8417-7a1abd3479f0.PNG)

**Comment by dotpim** [comment]
![bb](https://user-images.githubusercontent.com/2372008/39154276-f5483e5a-474d-11e8-89c2-769df8dcc982.png)
![bb-stoch](https://user-images.githubusercontent.com/2372008/39154340-296e3946-474e-11e8-9bfc-94af094423dc.png)

**Comment by dotpim** [comment]
![emotionless-trades](https://user-images.githubusercontent.com/2372008/39172683-c6f6bd10-47a2-11e8-8860-bf22b47854a7.png)

**Comment by dotpim** [comment]
![logs-grid](https://user-images.githubusercontent.com/2372008/40058143-8b78baa4-5850-11e8-9b03-54795686dff5.png)
![logs-opportunities](https://user-images.githubusercontent.com/2372008/40058144-8b9451ec-5850-11e8-9fe6-02e82af4fa41.png)
![logs-trailing](https://user-images.githubusercontent.com/2372008/40058145-8bb2da9a-5850-11e8-96fc-c2b9d8203d1d.png)

**Comment by dotpim** [comment]
![sell-trailing](https://user-images.githubusercontent.com/2372008/40186557-b0887252-59f5-11e8-896b-849a5fed897f.png)
![buy-trailing](https://user-images.githubusercontent.com/2372008/40186558-b0a5f818-59f5-11e8-8566-307546866c61.PNG)

**Comment by dotpim** [comment]
![supported-periods](https://user-images.githubusercontent.com/2372008/40494763-ed45509a-5f75-11e8-9725-1c037ae42510.PNG)

**Comment by dotpim** [comment]
![gain](https://user-images.githubusercontent.com/2372008/40631012-76d296c8-62d8-11e8-8f09-6319b349955d.PNG)

**Comment by dotpim** [comment]
![stepgain](https://user-images.githubusercontent.com/2372008/40718216-8e63121c-640f-11e8-917d-719104990195.PNG)

**Comment by dotpim** [comment]
![bollinger-bands](https://user-images.githubusercontent.com/2372008/40925551-4a0d684c-681a-11e8-8ea6-f0e6fba1af56.PNG)

**Comment by dotpim** [comment]
![bollinger-bands-ta](https://user-images.githubusercontent.com/2372008/40925897-196d6510-681b-11e8-94ac-99757f46ab7b.PNG)

**Comment by dotpim** [comment]
![ichimoku](https://user-images.githubusercontent.com/2372008/41095948-5e9511ee-6a53-11e8-973c-8146ed802da4.PNG)

**Comment by dotpim** [comment]
![adx](https://user-images.githubusercontent.com/2372008/41104321-62650c44-6a6b-11e8-8d26-8e8941efbd3d.PNG)

**Comment by dotpim** [comment]
![emaspread](https://user-images.githubusercontent.com/2372008/41104585-01701d7e-6a6c-11e8-9a99-33432958ce73.PNG)

**Comment by dotpim** [comment]
![macd](https://user-images.githubusercontent.com/2372008/41107283-5ba76206-6a72-11e8-88ef-ecf39e1ce953.PNG)

**Comment by dotpim** [comment]
![macdh](https://user-images.githubusercontent.com/2372008/41107941-a4e7da44-6a73-11e8-9cfd-861e4dc12a46.PNG)

**Comment by dotpim** [comment]
![smacross](https://user-images.githubusercontent.com/2372008/41108606-4c435920-6a75-11e8-913a-07ef8e06a39a.png)

**Comment by dotpim** [comment]
![reversal-trading-bb](https://user-images.githubusercontent.com/2372008/41157582-8f2bcb44-6b26-11e8-979f-569932e1188d.png)
![reversal-trading-stepgain](https://user-images.githubusercontent.com/2372008/41157583-8f4cc06a-6b26-11e8-90b9-4aa2fa77a3f3.png)
![reversal-trading-gain](https://user-images.githubusercontent.com/2372008/41157584-8f689132-6b26-11e8-81b0-4515091d8ea2.png)

**Comment by dotpim** [comment]
![reversal-trading-stepgain](https://user-images.githubusercontent.com/2372008/41161526-7782e7fe-6b33-11e8-8253-3b62e7554d05.png)

**Comment by dotpim** [comment]
![logo](https://user-images.githubusercontent.com/2372008/41244930-ed15604e-6da6-11e8-91ad-25f1ced850c4.png)

**Comment by dotpim** [comment]
![logo](https://user-images.githubusercontent.com/2372008/41245451-59331202-6da8-11e8-8c00-b1a313acb6b8.png)

**Comment by dotpim** [comment]
![binance](https://user-images.githubusercontent.com/2372008/41608791-a2958df2-73e9-11e8-9546-eb5d51c57cef.png)
![bitfinex](https://user-images.githubusercontent.com/2372008/41608792-a2b74dac-73e9-11e8-9388-40e856dd1bc9.png)
![bittrex](https://user-images.githubusercontent.com/2372008/41608793-a2eecc6e-73e9-11e8-8535-693c9fb48e90.png)
![cex](https://user-images.githubusercontent.com/2372008/41608794-a3136f1a-73e9-11e8-9785-40bc7b28c4cc.png)
![cryptopia](https://user-images.githubusercontent.com/2372008/41608795-a3382698-73e9-11e8-8b42-a8e6974f6631.png)
![gdax](https://user-images.githubusercontent.com/2372008/41608796-a3668b32-73e9-11e8-9897-85cb73ef029f.jpg)
![kraken](https://user-images.githubusercontent.com/2372008/41608797-a3892250-73e9-11e8-930a-aac6d5dc9c1d.png)
![kucoin](https://user-images.githubusercontent.com/2372008/41608799-a3a57c02-73e9-11e8-9deb-e7bbe24ae87c.png)
![poloniex](https://user-images.githubusercontent.com/2372008/41608801-a3c41af4-73e9-11e8-8b8b-039c28d5cc7b.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/41924015-3d28d2e6-7969-11e8-8cab-4637c23f70fb.png)
![image](https://user-images.githubusercontent.com/2372008/41924087-5e62f810-7969-11e8-9967-6b6299c1bba3.png)

**Comment by dotpim** [comment]
![preview](https://user-images.githubusercontent.com/2372008/42699999-b743c0d4-86c2-11e8-8571-2f300379e5e4.png)

**Comment by dotpim** [comment]
![coinbase](https://user-images.githubusercontent.com/2372008/43724347-063e0ed0-999a-11e8-9370-6bbf43fbdce7.png)

**Comment by dotpim** [comment]
![emo-new](https://user-images.githubusercontent.com/2372008/43881542-cb280ebc-9bac-11e8-8fc8-6f1955467ab0.PNG)

**Comment by dotpim** [comment]
![double-up](https://user-images.githubusercontent.com/2372008/43907676-55eda770-9bf6-11e8-8124-60fb0d8d893d.PNG)

**Comment by dotpim** [comment]
![bollinger-bands-ta](https://user-images.githubusercontent.com/2372008/44024741-7cb2ccaa-9eee-11e8-8f71-2cd7b2c31dd9.PNG)

**Comment by dotpim** [comment]
![v10-macos-installation](https://user-images.githubusercontent.com/2372008/44027471-e26c3e20-9ef6-11e8-8287-8be2fc9be162.gif)

**Comment by dotpim** [comment]
![v10-win-installation](https://user-images.githubusercontent.com/2372008/44029067-500ed8de-9efc-11e8-9012-3d5767b295b2.gif)

**Comment by dotpim** [comment]
![supported-periods](https://user-images.githubusercontent.com/2372008/44311695-4d57a900-a3ec-11e8-81b0-7f979c91940e.PNG)

**Comment by dotpim** [comment]
![emotionless-trades](https://user-images.githubusercontent.com/2372008/44547052-27971080-a71a-11e8-8919-c47ecbfc54ef.png)

**Comment by dotpim** [comment]
![reversal-trading-stepgain](https://user-images.githubusercontent.com/2372008/44715288-b360c200-aab7-11e8-9578-bf4400c9570d.png)

**Comment by dotpim** [comment]
![step 01 chart](https://user-images.githubusercontent.com/2372008/45930634-0452c180-bf63-11e8-95db-0a34c1a88254.png)
![step 02 settings](https://user-images.githubusercontent.com/2372008/45930636-0b79cf80-bf63-11e8-893c-d3133b377050.png)
![step 03 dark theme](https://user-images.githubusercontent.com/2372008/45930637-12084700-bf63-11e8-81b2-6c31d37d4169.png)
![step 04 select pair period indicator](https://user-images.githubusercontent.com/2372008/45930641-19c7eb80-bf63-11e8-88d3-5ed978c66d2a.png)
![step 05 load indicators](https://user-images.githubusercontent.com/2372008/45930642-1fbdcc80-bf63-11e8-8335-a18a4824778c.png)
![step 06 strategy tester](https://user-images.githubusercontent.com/2372008/45930648-26e4da80-bf63-11e8-9786-4e797e152dae.png)
![step 07 drag open pane](https://user-images.githubusercontent.com/2372008/45930650-306e4280-bf63-11e8-9f5f-9038f0fcb165.png)
![step 08 format](https://user-images.githubusercontent.com/2372008/45930652-35cb8d00-bf63-11e8-8c98-098a42a2228f.png)
![step 09 commission](https://user-images.githubusercontent.com/2372008/45930654-3d8b3180-bf63-11e8-8a6a-68745edd3edf.png)
![step 10 arrange](https://user-images.githubusercontent.com/2372008/45930655-43811280-bf63-11e8-8fd3-9a70183db8dd.png)
![step 11 exchange source](https://user-images.githubusercontent.com/2372008/45930657-48de5d00-bf63-11e8-8e4c-3633a77cebe2.png)
![step 12 data window](https://user-images.githubusercontent.com/2372008/45930661-53005b80-bf63-11e8-835f-9927b3350668.png)
![step 13 gtc](https://user-images.githubusercontent.com/2372008/45930662-58f63c80-bf63-11e8-97e6-59555eb5d9cf.png)
![step 14 prices](https://user-images.githubusercontent.com/2372008/45930668-63183b00-bf63-11e8-8f3d-dffba89b503a.png)
![step 15 markers](https://user-images.githubusercontent.com/2372008/45930672-690e1c00-bf63-11e8-91f1-ae5a1ebb13cf.png)
![step 16 alerts](https://user-images.githubusercontent.com/2372008/45930675-6e6b6680-bf63-11e8-94ec-d21fac09b974.png)
![step 14 prices revised](https://user-images.githubusercontent.com/2372008/45930681-817e3680-bf63-11e8-8323-dc8fb4aa4c9f.png)

**Comment by dotpim** [comment]
![save-settings](https://user-images.githubusercontent.com/2372008/46599730-5f9abd00-cae8-11e8-98c3-2af0ac9df37e.PNG)

**Comment by dotpim** [comment]
![rt-flowchart-stepgain-v11](https://user-images.githubusercontent.com/2372008/47029956-02001380-d16d-11e8-89f3-5d88c6f80513.PNG)
![rt-flowchart-bb-v11](https://user-images.githubusercontent.com/2372008/47029957-02001380-d16d-11e8-8cd6-f661deadf73d.PNG)
![rt-flowchart-gain-v11](https://user-images.githubusercontent.com/2372008/47029958-02001380-d16d-11e8-8f7d-9f146fbbf24b.PNG)

**Comment by dotpim** [comment]
![rt-flowchart-basic-v11](https://user-images.githubusercontent.com/2372008/47073892-8f894500-d1f9-11e8-9098-a4b469bb1311.PNG)

**Comment by dotpim** [comment]
![gain](https://user-images.githubusercontent.com/2372008/47171108-23e1cd80-d308-11e8-8bf3-22f5e461d8ab.PNG)

**Comment by dotpim** [comment]
![stepgain](https://user-images.githubusercontent.com/2372008/47218318-a66f9900-d3ab-11e8-858c-e4d2959a7371.PNG)

**Comment by dotpim** [comment]
![bb](https://user-images.githubusercontent.com/2372008/47218525-504f2580-d3ac-11e8-86b6-eacc10011737.PNG)

**Comment by dotpim** [comment]
![bbta](https://user-images.githubusercontent.com/2372008/47218852-65788400-d3ad-11e8-8100-1ab21cbc70dd.PNG)

**Comment by dotpim** [comment]
![tssl](https://user-images.githubusercontent.com/2372008/47219307-c3f23200-d3ae-11e8-9dff-a8222360efd3.PNG)

**Comment by dotpim** [comment]
![adx](https://user-images.githubusercontent.com/2372008/47219802-2697fd80-d3b0-11e8-871a-5f5ebfaeb2de.PNG)

**Comment by dotpim** [comment]
![atrts](https://user-images.githubusercontent.com/2372008/47224087-f99d1800-d3ba-11e8-8f67-2f611244769b.PNG)

**Comment by the-scott-davis** [comment]
It would be great if people could post what their strategy configs are for these charts so some of the less informed users could understand how to achieve similar results.

**Comment by dotpim** [comment]
![macd](https://user-images.githubusercontent.com/2372008/47229545-41766c00-d3c8-11e8-989f-67ab1b50b653.PNG)

**Comment by dotpim** [comment]
> It would be great if people could post what their strategy configs are for these charts so some of the less informed users could understand how to achieve similar results.

@the-scott-davis 
That's exactly the reason why I'm putting up these examples :)
Check one of the strategy pages (for example gain) on the gunbot wiki and click the link beneath the example.

**Comment by dotpim** [comment]
![smacross](https://user-images.githubusercontent.com/2372008/47293427-6a863f00-d60a-11e8-9c26-0a5e9e2cf979.PNG)
![ichimoku](https://user-images.githubusercontent.com/2372008/47293428-6b1ed580-d60a-11e8-867b-3e565ed58752.PNG)
![macdh](https://user-images.githubusercontent.com/2372008/47293430-6b1ed580-d60a-11e8-9270-821289d9a1ec.PNG)

**Comment by dotpim** [comment]
![huobi](https://user-images.githubusercontent.com/2372008/48340559-2fa48380-e66b-11e8-978a-242b4bdca5ff.PNG)

**Comment by dotpim** [comment]
![gunbot-charts](https://user-images.githubusercontent.com/2372008/48616770-ddc66b00-e994-11e8-8ffb-850b176c1c7d.PNG)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/48698251-e9a96b80-ebe6-11e8-9cc0-173ef0679c53.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/49085039-5bba2a00-f251-11e8-87b9-6eb76dd93e3a.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51086242-8e0de100-1744-11e9-8214-866cd2ecfa13.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51135811-30a88b80-183b-11e9-8e23-de4e62cdc046.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51178181-1a91de00-18c2-11e9-8f83-9f8254887f0f.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51180120-c25dda80-18c7-11e9-8a5c-da0f25c7dac2.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51180279-529c1f80-18c8-11e9-9372-a65482eeed4c.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51180319-73fd0b80-18c8-11e9-8476-99e858267c8b.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51180811-c5f26100-18c9-11e9-80b3-59805a60f43a.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51181077-6f395700-18ca-11e9-99fe-502e4da0bfc9.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51181206-d22aee00-18ca-11e9-8d87-4dc53c653a42.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51181359-406fb080-18cb-11e9-8b5d-9bd307180660.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51181438-72811280-18cb-11e9-9eb4-3794b2d4e84f.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51181737-3f8b4e80-18cc-11e9-9f92-ff32210a77fa.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51181789-6184d100-18cc-11e9-910b-7e4810d843af.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51182006-128b6b80-18cd-11e9-8771-7d5469c43a66.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51182045-30f16700-18cd-11e9-9a33-a6c4b25aee90.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51182092-541c1680-18cd-11e9-97b3-4f70322d5fd8.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51186704-87b16d80-18da-11e9-87cb-8fb30fc209c9.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51242033-5179f980-197f-11e9-98cf-cc85cc856fbb.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51429589-530e2080-1c10-11e9-8210-b6babe4014b2.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51614430-efdd0080-1f25-11e9-8460-7b4f3b17f85d.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51671836-3c7a1780-1fca-11e9-842c-8f298223e6d5.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51674789-f628b680-1fd1-11e9-92e7-c9c943e47db8.png)

**Comment by dotpim** [comment]
![dashboard](https://user-images.githubusercontent.com/2372008/51684831-406b6100-1fed-11e9-8f10-4bd11391e058.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51685458-a4daf000-1fee-11e9-95d3-307735930b7e.png)

**Comment by dotpim** [comment]
![dashboard](https://user-images.githubusercontent.com/2372008/51690263-a01b3980-1ff8-11e9-98fe-cf3ad7bd5c54.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51696638-3c980880-2006-11e9-8cd6-04a57751a5f0.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51697234-a238c480-2007-11e9-8db4-42a61668f8cb.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51699048-137a7680-200c-11e9-86af-5842f26e23c3.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51699364-dcf12b80-200c-11e9-8d0e-f3815471fa85.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51753012-154e4380-20b9-11e9-936f-79c1566fddd1.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51757361-724ef700-20c3-11e9-8690-3b957b96a75b.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51761865-792f3700-20ce-11e9-8a4e-ba331b806136.png)

**Comment by dotpim** [comment]
![image](https://user-images.githubusercontent.com/2372008/51761890-8ea46100-20ce-11e9-90ea-4eb69773d510.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51822566-0c3dbc00-22dd-11e9-9726-995813c81dce.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828069-0ea71280-22eb-11e9-9968-2f2055c495e2.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828247-7d846b80-22eb-11e9-8518-9a674da534c1.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828315-9d1b9400-22eb-11e9-8d49-9af35587503e.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828387-c63c2480-22eb-11e9-9c9c-8d5fff91be52.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828436-e53ab680-22eb-11e9-91f0-d0a96bba89bb.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828771-9a6d6e80-22ec-11e9-8953-db6aee776c52.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828827-b3761f80-22ec-11e9-914a-35aa96a2891b.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828870-d1dc1b00-22ec-11e9-977d-a4f978b7c8ad.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51828922-e9b39f00-22ec-11e9-8953-f98f5832a8d3.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51829027-15368980-22ed-11e9-9fab-9d65fd081fb2.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51829158-4b740900-22ed-11e9-9788-fe27db2d6df3.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/51904004-d45a7580-23bd-11e9-99e2-6460114659b0.png)

**Comment by boekenbox** [comment]
![dashboard](https://user-images.githubusercontent.com/2372008/52167539-aefe9c00-271c-11e9-9f1e-5be6b1d224e4.png)

**Comment by boekenbox** [comment]
![exchange-keys](https://user-images.githubusercontent.com/2372008/52206416-707ef380-287a-11e9-8f93-881abdbe9e5b.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/52208512-32390280-2881-11e9-96fb-29367a31d618.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/52209089-15053380-2883-11e9-9e71-1476b536210b.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53181299-98e74b80-35f7-11e9-8585-76dc2db48a02.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53234786-9b49b400-3690-11e9-80b5-b44fa490bd61.png)

gain, margin, non-mr, short

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53238728-5aef3380-369a-11e9-9baa-392087bb0c01.png)

gain, margin, mr, long

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53239781-3183d700-369d-11e9-85d4-2e5b35afd86b.png)

gain, margin, mr, short

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53249924-93523a00-36b9-11e9-82dd-c052533d27f9.png)

bbta, margin, short

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53252180-9dc30280-36be-11e9-8eb2-a5dcca61f1ad.png)

bbta, margin, long

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53286202-1c757980-376b-11e9-9721-73e807febd64.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53409188-a4a08c80-39c0-11e9-8a8a-d5b8941985e4.png)

bb, margin, mr, long

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53409188-a4a08c80-39c0-11e9-8a8a-d5b8941985e4.png)

bb, margin, mr, long

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53412737-7162fb00-39ca-11e9-94d3-3963512f3a56.png)

bb, margin, mr, short

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53418819-ed643f80-39d8-11e9-8055-a781f0b038c0.png)

tssl, margin, mr, short

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53428867-d713af00-39eb-11e9-87b6-f853f39d3641.png)

tssl, margin, mr, long

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53483654-3f14d480-3a82-11e9-986f-98d2cb74bd2f.png)

pp, margin, mr, long

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53484739-c5321a80-3a84-11e9-8533-19b39b9f5e89.png)

pp, margin, long

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53487073-cfefae00-3a8a-11e9-92c8-329ef27e0aa5.png)

pp, margin, short

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53487369-b8fd8b80-3a8b-11e9-996a-26ba327902f1.png)

pp, margin, mr, short

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/53732827-5affe800-3e7f-11e9-9884-ed1e15d3acb8.png)

**Comment by boekenbox** [comment]
![image](https://user-images.githubusercontent.com/2372008/54634366-5b54d180-4a82-11e9-918f-dc4ef9e47809.png)
