### ISSUE TITLE
[XT] Open Log View in Fullscreen?

### ISSUE THREAD

**Issue by nomad5am** [GuntharDeNiro/BTCT#178]
I would love to be able to enter the log view output in fullscreen. Should be just a little JS hack. Would be great to see this coming :)

**Comment by equalgeek** [comment]
I like this idea.. or at least the ability to allow reviewing of the log without it scrolling to the bottom when new items scroll by. Then if you scroll to the bottom it continues to scroll like it is setup now or maybe a fly out down arrow button that you can click that sets up the log window to act like it is now. I haven't looked at the code but if there is some kind of max length regarding the div overflow style and the log gets chopped as it is flowing through then maybe a show/hide on click of a button of a temp capture of the out log for the last hour? Just throwing ideas out.. Thanks!!

**Comment by adidonato** [comment]
in the meantime you could hack this in the browser console, it will expand the logs height and expand it in full screen 
`e = $$('.logs')[0]; e.style.height = '100%'; e.webkitRequestFullscreen();`
