### ISSUE TITLE
INVALID RESPONSE FROM LICENSE SERVER!!! Please contact Gunthar

### ISSUE THREAD

**Issue by duchuynhbc** [GuntharDeNiro/BTCT#180]
I worked smooth at 5.05, with 5.06 I have this issue.  I attached screenshot in here.
http://prntscr.com/h70cyn
http://prntscr.com/h74y5p
http://prntscr.com/h755p4

**Comment by Luke555** [comment]
I have the same problem. Emailed my API. Got a response saying that it should be registered. Still not working however...

**Comment by GuntharDeNiro** [comment]
@Luke555 you can contact me directly on telegram @gunthardeniro or at bitcointalk https://bitcointalk.org/index.php?action=profile;u=817682 or by email gunthardeniro@gmail.com
