### ISSUE TITLE
Pair name settings missing "/" required for bitfenix

### ISSUE THREAD

**Issue by callej1** [GuntharDeNiro/BTCT#182]
Hitting black screen for the gunthy.exe and looked at known issues one of which suggests to insure pairing format matches platform used. Bitfinex uses BTC/ETC and if you try and add this via pair name it fails to display the ticker correctly. If you add with BTC-ETC it shows the ticker/graph but if you look at the symbol on bitfenix they all use "/".. which leads me to think this might be related to the black screen issue I'm seeing on Windows 10 64 with gunthy.exe, and gui set to run as admin, with ports open. Also tested on High Sierra (Mac) where its not displaying any logs and also will not find anything with "/"... It looks like the pairing for bitfenix is not acting correctly and wont work at all for trading right now with Bitfenix

![bitfenix](https://user-images.githubusercontent.com/31236384/32605095-67c57310-c550-11e7-9664-397572d41d1f.JPG)
![blank](https://user-images.githubusercontent.com/31236384/32605106-7383c512-c550-11e7-883c-8c97964045b9.JPG)
![invalid](https://user-images.githubusercontent.com/31236384/32605107-73a52590-c550-11e7-8615-3b6cb2109752.JPG)
![xt601 pair bitfenix](https://user-images.githubusercontent.com/31236384/32605109-73d7e372-c550-11e7-8c0d-70e640523af8.JPG)

**Comment by Exquitas** [comment]
@callej1 the correct pair setting for Bitfinex is:
IOT-BTC
ETH-BTC
DAT-BTC
and so on

**Comment by CultureCrypto** [comment]
@Exquitas Except that it's an underscore as in IOT_BTC

**Comment by Exquitas** [comment]
@CultureCrypto well on mine it works with IOT-BTC o.o

**Comment by CultureCrypto** [comment]
@Exquitas Interesting

**Comment by callej1** [comment]
You sure? I'm confused a bit it looks like some show up in graphs under pairing for example if I take OMG-ETH its an invalid symbol. If I add ETH-OMG it shows up as OMG ETH on the chart which would be fine if it worked.  If you add OMG/ETH (as on bitfenix site) no error occurs no complaints about invalid symbol, you can save but nothing happens stuck at loading but nothing happens in my case on window or mac and I'm fairly savvy at troubleshooting things..

**Comment by callej1** [comment]
What versions are you guys using with Bitfenix?

**Comment by crypticotrader** [comment]
anyone can help me with Bitfinex?, i cant get buys orders, i dont know why. I use XT on Linux VPS, when i buy manually GB sell with no problems, but it does not buy by itself, I have it working for about 5 days.
From time to time I get the message "HEARTBEAT", and i get "RSI: Undefined" too.
