### ISSUE TITLE
Gunbot 6 not selling

### ISSUE THREAD

**Issue by johnnycash1** [GuntharDeNiro/BTCT#183]
Hi, i set the bot up to run a single pair last night and watched it for a while, it reached buy price but didnt buy after several drops below buy, a order finally showed up on bittrex but the log never showed a buy, so overnight it sold that buy at a good profit and bought another round and still hasnt sold it even though the price has climbed beyond the sell price multiple times.. I am running straight bb strategy.  Please help me figure this out. Thanks

**Comment by johnnycash1** [comment]
i went in and manually sold and as soon as i sold the bot rebought.  Whats going on

**Comment by GuntharDeNiro** [comment]
@johnnycash1 hi this is not meant for support requests but to report acknoledged and reproducible bugs. Also: please update to latest sstble release. Thanks
