### ISSUE TITLE
[XT 6.0.1] "TSSL" Can't get the bought price >30days, ignore manual bought price/stoplimit > sell at loss

### ISSUE THREAD

**Issue by Omega246** [GuntharDeNiro/BTCT#184]
Version: XT 6.0.1 Windows NO GUI POLO AND BITTREX

It seems, that the tssl strategy cant get the price if it 30+ days old. Stepgain for example got no problem with this.

For example the XEL coin(i got this "error" on polo and on bittrex:

> 09/16/2017 07:14:22 PM | 09/16/2017 07:14:22 PM | Limit Buy | 0.00014500

pure STEPGAIN:

> GBXT_v6.0.1 BTC-XEL Round # 2
> 
> ?????T XT Edition Scanning bittrex for trading opportunities 2017/11/09 16:20:
> 30

> 2017/11/09 16:20:30: BTC-XEL Last Bid/Ask 0.00004496/0.00004497
> EMA1: 0.00004628 === EMA2: 0.00004606
 HIGH BB: 0.00004859 == SMA: 0.00004550 == LOW BB: 0.00004241

>  2017/11/09 16:20:36: Got Trading History
>  2017/11/09 16:20:36: Checking Open Orders
>  2017/11/09 16:20:36: Price to buy: 0.00004514
>  2017/11/09 16:20:36: Last Bid/Strategy Exit Point: 0.00004496/NaN
>  2017/11/09 16:20:36: Last Ask/Strategy Entry Point: 0.00004497/0.00004514
>  2017/11/09 16:20:36: XTrend for BTC-XEL:    DOWN!!!
>  No new opportunities found...
>  
> 

PURE TSSL:

> Price to sell is not in TSSL range
> 2017/11/09 16:17:43: Price to buy: 0.00004606
> 2017/11/09 16:17:43: Last Bid/Strategy Exit Point: 0.00004540/0.00000000
> 2017/11/09 16:17:43: Last Ask/Strategy Entry Point: 0.00004579/0.00004606
> 2017/11/09 16:17:43: There are some trading opportunities for BTC-XEL at bittrex
> . Scanning Trade History
>  ??Ñ??T XT Edition  Tips&Tricks: BTC-XEL can be sold!!!
> 2017/11/09 16:17:43: Last Bid price BTC-XEL: 0.0000454 | Last Ask: 0.00004579
> 2017/11/09 16:17:43: Balance BTC: 0.10621704
> 2017/11/09 16:17:43: Balance XEL: 68.96551724
> 2017/11/09 16:17:43: On Orders XEL: 0
> Processing strategy tssl for BTC-XEL on bittrex
> 2017/11/09 16:17:43: Entering sell cycle
> WARNING: we couldnt get a BOUGHT PRICE for BTC-XEL, Please manually override it
> using config.js

If i know put the bought price manually in the config, the bot sells the coin at loss, despite Stop Limit 99. 

>  "bittrex": {                       
>             "BTC-XEL": {
>                 "strategy": "tssl",
>                 "override": {"BOUGHT_PRICE": 0.00014500}
>             }   
> 

It looks like that:

> 2017/11/09 16:46:59: StopLoss limit     0.00000000
> --------------------------------------------------------------------------------
> ----------------
> Price to sell is not in TSSL range
> 2017/11/09 16:46:59: Price to buy: 0.00004565
> 2017/11/09 16:46:59: Last Bid/Strategy Exit Point: 0.00004503/0.00000000
> 2017/11/09 16:46:59: Last Ask/Strategy Entry Point: 0.00004538/0.00004565
> 2017/11/09 16:46:59: There are some trading opportunities for BTC-XEL at bittrex
> . Scanning Trade History
>  ???ß?? XT Edition  Tips&Tricks: BTC-XEL can be sold!!!
> 2017/11/09 16:46:59: Last Bid price BTC-XEL: 0.00004503 | Last Ask: 0.00004538
> 2017/11/09 16:46:59: Balance BTC: 0.10621704
> 2017/11/09 16:46:59: Balance XEL: 68.96551724
> 2017/11/09 16:46:59: On Orders XEL: 0
> Processing strategy tssl for BTC-XEL on bittrex
> 2017/11/09 16:46:59: Entering sell cycle
> ┌───────────────────┬────────────┬────────────────┬────────────────┬────────────
> ┬─────────────┬──────────┬─────────┐
> │ ?????T XT Edition │ SMA        │ LowBB          │ HighBB         │ Last
> │ XEL         │ Last Buy │ Pair    │
> ├───────────────────┼────────────┼────────────────┼────────────────┼────────────
> ┼─────────────┼──────────┼─────────┤
> │ Sell cycle        │ 0.00004641 │ 0.000045141212 │ 0.000047676788 │ 0.00004503
> │ 68.96551724 │ 0        │ BTC-XEL │
> └───────────────────┴────────────┴────────────────┴────────────────┴────────────
> ┴─────────────┴──────────┴─────────┘
> ********************************************************************************
> ****************
> Waiting to sell...Safety Switch is on...
> ********************************************************************************
> ****************

I stoped it before it could sell, but at the RISE coin. It sold at loss.

09/24/2017 12:39:51 AM | 09/24/2017 12:39:51 AM | Limit Buy | 0.00013699

11/08/2017 02:20:12 AM | 11/08/2017 02:20:12 AM | Limit Sell | 0.00003456

config is default(With 99 Stoplimit):

> "tssl": {
>             "NAME": "tssl",
>             "BUY_LEVEL": 0.1,
>             "GAIN": 0.6,
>             "TRADING_LIMIT": 0.001,
>             "PERIOD": 5,
>             "BUY_RANGE": 0.6,
>             "SELL_RANGE": 0.6,
>             "EMA1": 24,
>             "EMA2": 12,
>             "HIGH_BB": 45,
>             "LOW_BB": 45,
>             "STDV": 2,
>             "SMAPERIOD": 50,
>             "PANIC_SELL": false,
>             "DOUBLE_UP": false,
>             "DOUBLE_UP_CAP": 1,
>             "TSSL_TARGET_ONLY": true,
>             "STOP_LIMIT": 99,
>             "BUY_ENABLED": true,
>             "MIN_VOLUME_TO_BUY": 0.0001,
>             "MIN_VOLUME_TO_SELL": 0.0001,
>             "TRADES_TIMEOUT": 600
> 

What is so different between these strategies, that this is happening? if i remember correctly sell at loss with tssl happend to me four times (ignores stoplimit) with old coins below 30d, but i got no logs about that.

**Comment by GuntharDeNiro** [comment]
òplease can you post here the logs of the sale from gunbot? Thank you

**Comment by Omega246** [comment]
If i remember correctly the bot does not save the logs anymore? And i am on windows so i have no "log command" or something like that. So i am sorry, i dont have the logs from the RISE Sell. But i can reproduce the process if you want. Just say me a way how i get you a proper log and i will let the bot sell the XEL Coin.

**Comment by denish888** [comment]
I had the same issue with kmd coin....

**Comment by Omega246** [comment]
@GuntharDeNiro 

Logfile: 

http://www60.zippyshare.com/v/fflYzsWO/file.html

The bot sold two coins at loss now:

> XMR Coin:

Buy:
> 09/17/2017 08:22:59 AM | 09/17/2017 08:22:59 AM | Limit Buy | 0.02560000 | 0.39062500 | 0.39062500 | 0.02560000 | -0.01002500

Sell:
> 11/14/2017 09:54:10 PM | 11/14/2017 09:54:06 PM | Limit Sell | 0.01832927 | 0.39062500 | 0.39062500 | 0.01832926 | 0.00714198


> bittrex": {                       
>             "BTC-XMR": {
>                 "strategy": "tssl",
>                 "override": {"BOUGHT_PRICE": 0.02560000,"DOUBLE_UP": true}
>             },

XEL Coin:

Buy:
> 09/16/2017 07:14:22 PM | 09/16/2017 07:14:22 PM | Limit Buy | 0.00014500 | 68.96551724 | 68.96551724 | 0.00014497 | -0.01002306

Sell:

> 
11/14/2017 09:54:01 PM | BTC-XEL | Limit Sell | 0.00004455 | 63.77340067 | 68.96551724 | 0.00004454 | 0.00306473

> "BTC-XEL": {
>                 "strategy": "tssl",
>                 "override": {"BOUGHT_PRICE": 0.00014500}
>             }
> 



> "tssl": {
>             "NAME": "tssl",
>             "BUY_LEVEL": 0.1,
>             "GAIN": 0.6,
>             "TRADING_LIMIT": 0.001,
>             "PERIOD": 5,
>             "BUY_RANGE": 0.6,
>             "SELL_RANGE": 0.6,
>             "EMA1": 24,
>             "EMA2": 12,
>             "HIGH_BB": 45,
>             "LOW_BB": 45,
>             "STDV": 2,
>             "SMAPERIOD": 50,
>             "PANIC_SELL": false,
>             "DOUBLE_UP": false,
>             "DOUBLE_UP_CAP": 1,
>             "TSSL_TARGET_ONLY": true,
>             "STOP_LIMIT": 99,
>             "BUY_ENABLED": true,
>             "MIN_VOLUME_TO_BUY": 0.0001,
>             "MIN_VOLUME_TO_SELL": 0.0001,
>             "TRADES_TIMEOUT": 600
>
