### ISSUE TITLE
6.0.1 Mac OS version Cannot find module 'bitfinex-api-node'

### ISSUE THREAD

**Issue by fahrmairm** [GuntharDeNiro/BTCT#187]
------------
Loading exchange bitfinex
Unhandled rejection Error: Cannot find module 'bitfinex-api-node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
-------

Linux package works fine

**Comment by callej1** [comment]
Linux with bitfinex? I've tried on Windows 10, OSX, and just tried on Kali Linux. I cant for the life of me get past "loading exchange bitfenix" its not a license issue since if I change the key to something invalid its coming back with license errors. Anyone have a working config OS, version for bitfinex? Please? :)

**Comment by Exquitas** [comment]
@callej1 What's your VPS Server provider?

**Comment by fahrmairm** [comment]
if it hangs on loading then you may have old version (I had that maybe on rc2 of 6.). Download latest linux package from github. Mac package not working. Potentially GUI not yet fully compatible with bitfinex strange pair syntax. I used core only, edit config.js. Other than that I have standard config. Only catch is that all tickers can only be 3 digit, so DASH-USD becomes DSH-USD. Trial an error. If you get constant heartbeat on some pair that means that pair ticker is incorrect. However bitfinex is new. orders are postonly so maybe 90% get cancelled by bitfinex. Gunthar said he will look into it.

         "BTC-USD": {
               "strategy": "bbrsi",
               "override": {}
          },
         "LTC-USD": {
               "strategy": "bbrsi",
               "override": {}
          },
         "ETH-USD": {
               "strategy": "bbrsi",
               "override": {}
          },
         "ETC-USD": {
               "strategy": "bbrsi",
               "override": {}
          },
         "ZEC-USD": {
               "strategy": "bbrsi",
               "override": {}
          },
         "XMR-USD": {
               "strategy": "bbrsi",
               "override": {}
          },
         "DSH-USD": {
               "strategy": "bbrsi",
               "override": {}
          },
         "XRP-USD": {
               "strategy": "bbrsi",
               "override": {}
          },
         "IOT-USD": {
               "strategy": "bbrsi",
               "override": {}
          },

--------

**Comment by callej1** [comment]
Thanks I'll give it a go. Think  one could probably configure the pairs via gui then run the core. At least when I looked in the config I saw changes there. Anyway I'll give it a go later. Will also try support via telegram  

    On Friday, November 10, 2017 1:54 PM, Michael Fahrmair <notifications@github.com> wrote:
 

 if it hangs on loading then you may have old version (I had that maybe on rc2 of 6.). Download latest linux package from github. Mac package not working. Potentially GUI not yet fully compatible with bitfinex strange pair syntax. I used core only, edit config.js. Other than that I have standard config. Only catch is that all tickers can only be 3 digit, so DASH-USD becomes DSH-USD. Trial an error. If you get constant heartbeat on some pair that means that pair ticker is incorrect. However bitfinex is new. orders are postonly so maybe 90% get cancelled by bitfinex. Gunthar said he will look into it.     "BTC-USD": {
           "strategy": "bbrsi",
           "override": {}
      },
     "LTC-USD": {
           "strategy": "bbrsi",
           "override": {}
      },
     "ETH-USD": {
           "strategy": "bbrsi",
           "override": {}
      },
     "ETC-USD": {
           "strategy": "bbrsi",
           "override": {}
      },
     "ZEC-USD": {
           "strategy": "bbrsi",
           "override": {}
      },
     "XMR-USD": {
           "strategy": "bbrsi",
           "override": {}
      },
     "DSH-USD": {
           "strategy": "bbrsi",
           "override": {}
      },
     "XRP-USD": {
           "strategy": "bbrsi",
           "override": {}
      },
     "IOT-USD": {
           "strategy": "bbrsi",
           "override": {}
      },

**Comment by callej1** [comment]
Thanks! Its the pairing in the end as you commented and its a bug in the GUI with the pairs not displaying charts. I assumed incorrectly that if the GUI could not find or query the pairs that it would not work. So trial and error and don't rely on the GUI for verifying pairs. Just enter them how they are on Bitfenex with "-" and ignore invalid symbol error and know that the chart wont display in the gui.

**Comment by wejo13** [comment]
You have to use ETH-BTC (for exmaple) as a pair, even it signals invalid symbol
