### ISSUE TITLE
bbrsitssl is not selling!  "TSSL_TARGET_ONLY": false

### ISSUE THREAD

**Issue by bleedr** [GuntharDeNiro/BTCT#189]
"TSSL_TARGET_ONLY": false
Never the less when price drops under "SELL_RANGE" (below bought price), it just doesn't sell!
"Price to sell is not in price range" -> yeah it went below that. Now there is no limit how far it can drop!
 "STOP_LIMIT" doesn't seem to work either, they are 1.5% apart and the price dropped below both of them.

**Comment by useR210961** [comment]
anyone can confirm that? I did not yet upgrade...

**Comment by bleedr** [comment]
As of some suggestions, it might be related to PERIOD. Tried it with PERIOD = 5 on poloniex. Probably it works with PERIOD = 15 and PERIOD = 30, which for me is a no go on that strategy. Yes, please someone confirm.

**Comment by rigide** [comment]
"TSSL_TARGET_ONLY"=false does nothing for me too. Drops below "SELL_RANGE" repeatedly and won't sell. "Last Price" lower than "StopLoss limit".. does nothing.
Setting "STOP_LIMIT" to 1 or 2 will sell if it drops 1% or 2% below bought price though.
However, sell range seems to work if it has first met the target sell point and is trailing profits waiting for the low point tolerance.
Reaching your STOP_LIMIT causes a different safety switch to trigger though. Not the regular TRADES_TIMEOUT". This causes a seemingly forever loop of messages between Waiting to trade and Callbacks.

**Comment by dotsoftware** [comment]
Gunthar just said in the telegram group that we might be missing GAIN parameter. I was surprised because the prebuilt config didn't contain GAIN on bbrsitssl strategy, so I just added it manually. I'll come back to tell if it worked.
