### ISSUE TITLE
Apparently working on polo but the only thing it does is kicking poloniex

### ISSUE THREAD

**Issue by lupeto77** [GuntharDeNiro/BTCT#19]
Was connected for 3 days and I did not make any transactions.
![1](https://user-images.githubusercontent.com/23246234/28908771-596d6430-77f3-11e7-8014-cee9da76bf68.png)

**Comment by BitFlipp3r** [comment]
The same thing happend to me although the bot was working fine for a few hours. A restart fixed it.

**Comment by BitFlipp3r** [comment]
I need to restart the bot everyday because it stops looking for trading opportunities after 10 - 12 hours.

**Comment by BitFlipp3r** [comment]
I noticed just now that the bot was only kicking again. But a liitle later it reloaded the config and started working again on its own. So maybe it's possible that an error reloading the config file results in endless kicking?


2017/08/05 01:01:43: Kicking poloniex, receiving new tickers...
┌───────────────┬─────────────────┬────────────┬────────────┬────────────┬────────────┬──────────────┬─────────┐
│ ɢƱŋƁѺͳ v3.3.4 │ LowBB           │ HighBB     │ Buy at     │ Last       │ BTC        │ XEM          │ Pair    │
├───────────────┼─────────────────┼────────────┼────────────┼────────────┼────────────┼──────────────┼─────────┤
│ TStop         │ 0.00000051      │ 0.00000053 │ 0.00008113 │ 0.00008113 │ 0.00536625 │ 119.06799269 │ BTC_XEM │
├───────────────┼─────────────────┼────────────┼────────────┼────────────┼────────────┼──────────────┴─────────┤
│ Callbacks     │ Not enough BTC. │            │            │            │            │                        │
└───────────────┴─────────────────┴────────────┴────────────┴────────────┴────────────┴────────────────────────┘
------------------------------------------------------------------------------------------------
 ɢՍΠɮǾŦ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:01:45
------------------------------------------------------------------------------------------------
No new opportunities found...
------------------------------------------------------------------------------------------------
 ɢՍͶɮøŁ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:01:48
------------------------------------------------------------------------------------------------
No new opportunities found...
------------------------------------------------------------------------------------------------
 ɢՍҊɃõŦ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:01:49
------------------------------------------------------------------------------------------------
2017/08/05 01:01:53: Kicking poloniex, receiving new tickers...
No new opportunities found...
------------------------------------------------------------------------------------------------
 ɢƱͶƁѺŁ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:01:54
------------------------------------------------------------------------------------------------
No new opportunities found...
------------------------------------------------------------------------------------------------
 ɢƱΠ฿øŦ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:01:55
------------------------------------------------------------------------------------------------
No new opportunities found...
------------------------------------------------------------------------------------------------
 ɢՍŋβõŦ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:02:03
------------------------------------------------------------------------------------------------
2017/08/05 01:02:03: Kicking poloniex, receiving new tickers...
2017/08/05 01:02:21: Kicking poloniex, receiving new tickers...
2017/08/05 01:02:37: Kicking poloniex, receiving new tickers...
No new opportunities found...
------------------------------------------------------------------------------------------------
 ɢƱƝɃǾŁ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:02:46
------------------------------------------------------------------------------------------------
2017/08/05 01:02:47: Kicking poloniex, receiving new tickers...
2017/08/05 01:02:57: Kicking poloniex, receiving new tickers...
2017/08/05 01:03:07: Kicking poloniex, receiving new tickers...
2017/08/05 01:03:17: Kicking poloniex, receiving new tickers...
2017/08/05 01:03:27: Kicking poloniex, receiving new tickers...
2017/08/05 01:03:37: Kicking poloniex, receiving new tickers...
2017/08/05 01:03:47: Kicking poloniex, receiving new tickers...
2017/08/05 01:03:57: Kicking poloniex, receiving new tickers...
2017/08/05 01:04:07: Kicking poloniex, receiving new tickers...
2017/08/05 01:04:17: Kicking poloniex, receiving new tickers...
2017/08/05 01:04:27: Kicking poloniex, receiving new tickers...
2017/08/05 01:04:37: Kicking poloniex, receiving new tickers...
Loading config...
Loading exchange poloniex
2017/08/05 01:04:47: Kicking poloniex, receiving new tickers...
------------------------------------------------------------------------------------------------
 ɢƱƝɃøͳ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:04:48
------------------------------------------------------------------------------------------------
No new opportunities found...
------------------------------------------------------------------------------------------------
 ɢՍÑɃѺŦ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 01:04:55

**Comment by BitFlipp3r** [comment]
I was able to locate the last output after the bot stopped working:

```
No new opportunities found...
--------------------------------------------------------------------------------
 ɢƱŋɮøŦ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 17:11:16
--------------------------------------------------------------------------------
No new opportunities found...
--------------------------------------------------------------------------------
 ɢƱŋβØŁ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 17:11:19
--------------------------------------------------------------------------------
2017/08/05 17:11:23: Kicking poloniex, receiving new tickers...
2017/08/05 17:11:33: Kicking poloniex, receiving new tickers...
2017/08/05 17:11:43: Kicking poloniex, receiving new tickers...
No new opportunities found...
--------------------------------------------------------------------------------
 ɢՍƝβѺŁ v3.3.4  Scanning poloniex for trading opportunities 2017/08/05 17:11:53
--------------------------------------------------------------------------------
2017/08/05 17:11:57: Kicking poloniex, receiving new tickers...
2017/08/05 17:12:07: Kicking poloniex, receiving new tickers...
2017/08/05 17:12:17: Kicking poloniex, receiving new tickers...
2017/08/05 17:12:27: Kicking poloniex, receiving new tickers...
2017/08/05 17:12:37: Kicking poloniex, receiving new tickers...
2017/08/05 17:12:47: Kicking poloniex, receiving new tickers...
2017/08/05 17:12:57: Kicking poloniex, receiving new tickers...
2017/08/05 17:13:27: Kicking poloniex, receiving new tickers...
2017/08/05 17:13:37: Kicking poloniex, receiving new tickers...
2017/08/05 17:13:47: Kicking poloniex, receiving new tickers...
Loading config...
Loading exchange poloniex
2017/08/05 17:13:54: Kicking poloniex, receiving new tickers...
2017/08/05 17:14:04: Kicking poloniex, receiving new tickers...
Getting tickers for poloniex catch error: Cannot read property 'error' of undefi
2017/08/05 17:14:14: Kicking poloniex, receiving new tickers...
2017/08/05 17:14:24: Kicking poloniex, receiving new tickers...
2017/08/05 17:14:34: Kicking poloniex, receiving new tickers...
2017/08/05 17:14:44: Kicking poloniex, receiving new tickers...
2017/08/05 17:14:54: Kicking poloniex, receiving new tickers...
2017/08/05 17:15:04: Kicking poloniex, receiving new tickers...
2017/08/05 17:15:14: Kicking poloniex, receiving new tickers...
2017/08/05 17:15:24: Kicking poloniex, receiving new tickers...
2017/08/05 17:15:34: Kicking poloniex, receiving new tickers...
2017/08/05 17:15:44: Kicking poloniex, receiving new tickers...
2017/08/05 17:15:54: Kicking poloniex, receiving new tickers...
2017/08/05 17:16:04: Kicking poloniex, receiving new tickers...
2017/08/05 17:16:14: Kicking poloniex, receiving new tickers...
2017/08/05 17:16:24: Kicking poloniex, receiving new tickers...
2017/08/05 17:16:34: Kicking poloniex, receiving new tickers...
2017/08/05 17:16:44: Kicking poloniex, receiving new tickers...
2017/08/05 17:16:54: Kicking poloniex, receiving new tickers...
2017/08/05 17:17:04: Kicking poloniex, receiving new tickers...
2017/08/05 17:17:14: Kicking poloniex, receiving new tickers...
2017/08/05 17:17:24: Kicking poloniex, receiving new tickers...
2017/08/05 17:17:34: Kicking poloniex, receiving new tickers...
2017/08/05 17:17:44: Kicking poloniex, receiving new tickers...
2017/08/05 17:17:54: Kicking poloniex, receiving new tickers...
2017/08/05 17:18:04: Kicking poloniex, receiving new tickers...
```

**Comment by BitFlipp3r** [comment]
I noticed that I had an error in my config file. I specified the pair "BTC_BTC" by mistake. Since I removed this the bot is running without any problems.
