### ISSUE TITLE
UI Enhancement: XT v6.0.1 Be able to freeze log screen when viewing

### ISSUE THREAD

**Issue by iAmVaeVictus** [GuntharDeNiro/BTCT#197]
It would be VERY helpful to be able to freeze the log screen so that it does not scroll back to the bottom every time there is an update (which is every 5 seconds or so). 

It would also be nice to be able to dynamically resize the log and error windows on the html page by dragging the bottom or corner of the box.

**Comment by sschleicher** [comment]
This is very much needed!  I keep having to do CTRL-A (select all) + CTRL-c (copy) and paste the log info into MS Word (landscape orientation) so I review what is going on.

Is there a non-text viewer/editor that the log file can be opened with in order to see all the colors and proper formatting?

**Comment by dotpim** [comment]
@sschleicher to open your out.log file in proper formatting you could use https://sourceforge.net/projects/ansifilter/

**Comment by tandyuk** [comment]
In cPanel, they pipe logs out to the client in a very similar way.
However you can click the output window to pause/resume auto scroll.
That would be an excellent addition to the gunbot gui.

**Comment by dotpim** [comment]
Fixed in v8 GUI.
Logs can be paused on the dashboard.
