### ISSUE TITLE
UI Enhancement: v6.0.1. See list of trades 

### ISSUE THREAD

**Issue by iAmVaeVictus** [GuntharDeNiro/BTCT#198]
Great job on the UI! We love it so much that now we want more features!! 

It would be very nice to see a list of recent purchases and sells, and current coins held after purchase but not sold yet. Opening the exchange and going to the "Orders" screen is less than ideal, as well as coins that are being watched more closely, nearing buy or sell limits.

**Comment by Exquitas** [comment]
@smportis Already in the works, so "Very soon(TM)"

**Comment by smportis** [comment]
Sweet. If it get's a trademarked "Very Soon" then we are all good.

**Comment by dotpim** [comment]
Fixed in v9: dashboard now has native charts for each pair with recent trades shown right in the charts.

Further improvements to be expected for later releases.
