### ISSUE TITLE
license problem

### ISSUE THREAD

**Issue by sidkfree** [GuntharDeNiro/BTCT#2]
hi,

i got this problem : INVALID LICENSE!!! Please contact Gunthar!

Could you help please

**Comment by Kahana82** [comment]
I had the same problem when upgrading to version 3.
Send him a message on the bitcointalk forums, he'll help you out.
https://bitcointalk.org/index.php?action=profile;u=817682

**Comment by utdrmac** [comment]
@sidkfree @Kahana82 are you guys good? Can this be closed?

**Comment by Kahana82** [comment]
Gunthar sorted it out for me on version 3, but I haven't using it for some time since v3.1.
I suppose it is still working though, are there any updates since ?

**Comment by utdrmac** [comment]
@Kahana82 Yes. 3.3.2 is out. And a new version is due out this week, per communications in Telegram. @sidkfree You good?

**Comment by utdrmac** [comment]
@sidkfree Can you close this?
