### ISSUE TITLE
[XT Enhancement] Suppress the green color on log

### ISSUE THREAD

**Issue by Singman33** [GuntharDeNiro/BTCT#200]
Please suppress that green color on the log (or make the text black), it's unreadable. Not the 1st time someone ask you about that. Dont put bright text with a bright background.
Thanks.

**Comment by murm78** [comment]
@Singman33 @LadyDKitty wake up @GuntharDeNiro this issue is top priority

**Comment by Singman33** [comment]
Not sure if you are ironic or not, but green messages a important ones, the buy or sell orders. If you cant read them, it's useless.

**Comment by tandyuk** [comment]
I remember raising this one months ago :)
