### ISSUE TITLE
Price calculation errors

### ISSUE THREAD

**Issue by Utone** [GuntharDeNiro/BTCT#202]
Gunbot does not see manual sells and keeps the old balance.

Also it counts partial fills as a whole filled order, when buy order is manually cancelled.

![screenshot 2017-11-12 18 36 37](https://user-images.githubusercontent.com/5865016/32701675-3d0fc436-c7da-11e7-8961-3899b0476253.png)
![screenshot 2017-11-12 18 37 58](https://user-images.githubusercontent.com/5865016/32701676-3d277360-c7da-11e7-8475-002aff91665b.png)
![screenshot 2017-11-12 17 02 44](https://user-images.githubusercontent.com/5865016/32701677-3d3c38fe-c7da-11e7-9e24-56b6109af969.png)
![screenshot 2017-11-12 18 14 54](https://user-images.githubusercontent.com/5865016/32701678-3d504bfa-c7da-11e7-94bf-a0e33a89127e.png)
[DNT price calculation.xlsx](https://github.com/GuntharDeNiro/BTCT/files/1464943/DNT.price.calculation.xlsx)

Today I also saw half my balance of a pair not show up until i closed gGUI, ran it in console, which didn't state any amount, then restarted the gGUI and it did read the balance.

So sometimes it counts what it DOESN'T have but assumed got filled, but not what it DOES have...

**Comment by GuntharDeNiro** [comment]
there is actually an issue with websocket that sGui receives from GB: please use gGui or console only screenshots.

**Comment by Utone** [comment]
@GuntharDeNiro then why does the bot sell the bag, this isn't GUI related because it immediately sold my bag because it calculated a big manual double_up or_ more) that only got partially filled as completely filled i see this happening over and over and can send you the excel sheets i need to make to get the correct price for each bag as is the current situation when you manually buy sell anything partial.
