### ISSUE TITLE
Bot reports purchase of 7.03026038 BCH but actually bought 2.08543883 BCH.

### ISSUE THREAD

**Issue by sschleicher** [GuntharDeNiro/BTCT#206]
Trading on poloniex.  At 11:08 this morning the says it bought 7.03026038 BCH at a price of 1422.42242242.  

![image](https://user-images.githubusercontent.com/6667774/32704407-23a222ce-c7ca-11e7-9568-840baced1314.png)

However, at 11:10 the bot reports a BCH balance of 2.08543883.  

![image](https://user-images.githubusercontent.com/6667774/32704426-5922d75e-c7ca-11e7-893e-acbaaf126420.png)

There are no buys or sells in between.  See attached log file.
[out .log](https://github.com/GuntharDeNiro/BTCT/files/1465186/out.log)

Looking at my trade history on Poloniex it shows a buy of 2.09066549 BCH at 1422.42242242 with a fee of 0.00522666 BCH.  Poloniex shows a net of 2.08543883 BCH.  

![image](https://user-images.githubusercontent.com/6667774/32704446-b7264624-c7ca-11e7-98d7-06ba1b129b33.png)

But the bot said it bought 7.03026038 BCH!!!  

Config settings:
            "USDT_BCH": {
                "strategy": "tssl",
                "override": {
                    "TRADING_LIMIT": 10000,
                    "MIN_VOLUME_TO_BUY": 10000,
                    "MIN_VOLUME_TO_SELL": 100
                }
            }

        "tssl": {
            "NAME": "tssl",
            "BUY_LEVEL": 0.1,
            "GAIN": 0.6,
            "TRADING_LIMIT": 0.001,
            "PERIOD": 5,
            "BUY_RANGE": 1,
            "SELL_RANGE": 1,
            "EMA1": 24,
            "EMA2": 12,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "TSSL_TARGET_ONLY": true,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 600
        }

**Comment by sschleicher** [comment]
I was giving this some thought as I've been watching how the bot behaves and tweaking configuration settings.  I'm wondering if the bot put in a buy order for 7.03026038 BCH but Poloniex was only able to fulfill 2.08543883 BCH before the buy order timed out?  If that is what actually happened, then this seems to only be a messaging error.  The bot should have said it was placing a buy order for 7.03026038 BCH instead of saying "BOUGHT!!! Amount: 7.03026038".  Further, it would be even better if it also logged that the buy order was cancelled due to a time out and suggest that the "Timeout Buy" setting  can be adjusted.

**Comment by GuntharDeNiro** [comment]
this is what the bot got filled from original order, not a bug: the balance will be set at what the exchange filled.
