### ISSUE TITLE
HEARTBEAT Issue

### ISSUE THREAD

**Issue by tcomeau16** [GuntharDeNiro/BTCT#209]
I was getting a HEARTBEAT message when the bot was in a buy cycle. No buy orders were going through. I had lowered the TRADING_LIMIT from 0.001 to 0.0001 so only really low orders could get placed while I tested out the different strategies and coins. After changing the TRADING_LIMIT back to 0.001 the HEARTBEAT error went away. Hopefully this helps someone else. Problem solved.

**Comment by EdsSpecial** [comment]
Ive had this very intermittently. Cant tell why? Running on Win10 with GUI and just exe also. If I make any change to the config file and save it, it fixes problem (even no change to any parameters just saving file same settings).

**Comment by GuntharDeNiro** [comment]
heartbeat message is lack of communication with exchange's api server: it is temporary and it solves itself.
