### ISSUE TITLE
TSSL improvement/request GAIN as a minimum, baby increments from there on..

### ISSUE THREAD

**Issue by Utone** [GuntharDeNiro/BTCT#212]
After some chatting on tssl Astridbot.io made me aware of a config she used on a pair with "SELL_RANGE": 1 I immediately asked "how many times does that get triggered?"

"Astridbot.io, [11.11.17 16:48]
I don't get many multiple steps. I run 30 pairs with the same strategy, only like 10 have the volatility to trigger buys, and some trade significantly more often than others.
Usually I get a 1% gain, or a sell on the first step. 2/10 trades have more steps, higher % gains. 1/10 trades hits my 5% stop_loss"

She luckily corrected a typo I made in my config it was set to "SELL_RANGE": 0.1 which would result in a loss (if not triggered at least 6 times), this all made me think:

What a shame and missed opportunity!
In my mind the small additional steps are the strategies strength.. So why such a crude number, set a minimum gain, then let tssl do its magic...?

Could GAIN be used as minimum gain after which (or during) starts with tssl with baby steps 0.01 if yoy like, not sure about the performance vs stepgain in speed with flash crashes and fast collapsing pumps..So fill me in on what is the best candidate for the job and i will think different...

**Comment by GuntharDeNiro** [comment]
TSSL has already GAIN setting.
