### ISSUE TITLE
Sold for under bought price on a few occassions

### ISSUE THREAD

**Issue by chimera80** [GuntharDeNiro/BTCT#213]
On Bittrex, Using BBREITSSL, on about 1 out of 20 trades, the bot sold the coins minutes after purchasing it at about 0.03% loss. I set the minimum gain at 1.25% and stoploss at 60% so I’m not sure what is triggering it

**Comment by chimera80** [comment]
Bbrsitssl*

**Comment by GuntharDeNiro** [comment]
@chimera80 tell me these 2 settings you have there please: GAIN and TRADE_TIMEOUTS

**Comment by chimera80** [comment]
Hi Gunthar, thanks for the super quick reply.


this is exactly what i am using
      "bbrsitssl": {
            "NAME": "bbrsitssl",
            "TRADING_LIMIT": 0.005,
            "PERIOD": 5,
            "RSI_BUY_LEVEL": 30,
            "SELL_RANGE": 0.9,
            "EMA1": 24,
            "EMA2": 12,
            "HIGH_BB": 30,
            "LOW_BB": 15,
            "STDV": 2,
            "SMAPERIOD": 25,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "TSSL_TARGET_ONLY": true,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 600
        },

**Comment by GuntharDeNiro** [comment]
missing GAIN parameter
