### ISSUE TITLE
CMD Box Flashes Repeatedly When Run GunBot Attempted

### ISSUE THREAD

**Issue by trendline789** [GuntharDeNiro/BTCT#215]
Problem: CMD box repeatedly flashes on screen after "Run GunBot" is selected in web GUI.

I followed the gunbot wiki install steps and everything seems to be fine until I actually try to run gunbot.  That's when the small cmd box flashes repeatedly occurs and nothing else happens.

Help?

**Comment by GuntharDeNiro** [comment]
not a bug, please submit the question to the support channels, this is a bug tracker.
