### ISSUE TITLE
Bug! No buys while in buy target for minutes, console is shows placing buy orders but none go through..

### ISSUE THREAD

**Issue by Utone** [GuntharDeNiro/BTCT#218]
Shows  buy order attempts over and over, none come through..
Using bbrsistepgain. Timeout set to 60 seconds. 2 pairs per instance.

![screenshot 2017-11-14 02 12 22](https://user-images.githubusercontent.com/5865016/32758143-279a02d8-c8e3-11e7-91a6-119399c623f0.png)

11 minutes later:.....
![screenshot 2017-11-14 02 23 18](https://user-images.githubusercontent.com/5865016/32758144-27e4ff04-c8e3-11e7-9219-3b222d2d3109.png)

**Comment by GuntharDeNiro** [comment]
sorry i'm unable to debug using sjakill gui
