### ISSUE TITLE
Feature request: Cancel_after

### ISSUE THREAD

**Issue by tandyuk** [GuntharDeNiro/BTCT#219]
I'd like to request a new config setting, which affects how long the bot will allow an open buy/sell order to sit on the orderbook.

something like

cancel_after: 300    // Time in seconds to cancel an unfulfilled buy/sell order

So when the bot places a buy/sell order, and it is not fulfilled after <cancel_after> seconds, the bot cancels the order.
If market conditions allow, the bot should place a new buy/sell order after timeout_[buy|sell] milliseconds.

This will stop trading opportunities being missed because of outstanding buy/sell orders.

**Comment by bennygrahn** [comment]
@GuntharDeNiro have this on his todo list. We have talked about it and he is on it.

**Comment by tandyuk** [comment]
In the meantime, the following script oversees this:
https://github.com/tandyuk/gunbotscripts/blob/master/bittrex-govenor.php

**Comment by tandyuk** [comment]
Duplicate of #146
