### ISSUE TITLE
v3.3.4:  Error running on a Raspberry Pi

### ISSUE THREAD

**Issue by bigwest60** [GuntharDeNiro/BTCT#22]
This has been happening on multiple pairs.  Receiving this error on 3.3.4 running on a Raspberry Pi:

Error on strategy BB for BTC-ANS on bittrex while selling -| Error: HttpApiError: INSUFFICIENT_FUNDS

**Comment by mikebussy3334** [comment]
They're going to tell you to use 3.3.5 but I don"t like that version
