### ISSUE TITLE
TSSL lagging and GAIN does not work as supposed.

### ISSUE THREAD

**Issue by wirmola** [GuntharDeNiro/BTCT#223]
Both issues in XT, linux, tssl.
When out.log gets too large (around 200Mb) XT starts lagging and missing trades.
temp fix : Add BOUGHT_PRICE in override for the coins you are waiting to sell, delete out.log, restart.
GAIN does not work currently as supposed.
example: USDT/BCH with GAIN 1.1 and SELL_RANGE 0.7
                                   bought price: 174,97529023
                                   sell price: 176.19349622
                                   176.19349622÷174,97529023= 1,00696216
@wirmola

**Comment by dotpim** [comment]
Log size problem is a recognized problem that will be worked on. 
Can you explain what the relation of changing BOUGHT_PRICE is to this problem? In my experience, renaming out.log (or removing it) already fixes the issue.

**Comment by dotpim** [comment]
About your issue with GAIN in TSSL: this is not an actual problem. 

Minimum profit = GAIN - SELL_RANGE - Exchange fees

(See updated Wiki article on TSSL, more users had questions about this)

**Comment by wirmola** [comment]
using BOUGHT_PRICE so it will not sell of the bags after deleting out.log. It was just a safeguard since I have no idea if gunbot stores buy data anywhere else then log file..

Will take another peek at wiki.. thx..

**Comment by dotpim** [comment]
Bought prices are pulled from the exchanges, not from logs. It's safe to remove out.log.

**Comment by dotpim** [comment]
Log related GUI-performance issues will be fixed in v6.0.2.
