### ISSUE TITLE
Bitfinix: Waiting for open orders.. after postonly is canceled

### ISSUE THREAD

**Issue by roelvde** [GuntharDeNiro/BTCT#224]
GB places buy order for ZEC, but order (postonly) gets canceled right after. 
In the next cycles GB is still waiting for open orders.

![schermafbeelding 2017-11-14 om 20 39 00](https://user-images.githubusercontent.com/643462/32801886-aee6422e-c97e-11e7-8bfe-00371e259b09.png)

![schermafbeelding 2017-11-14 om 20 56 10](https://user-images.githubusercontent.com/643462/32801891-b159ecd6-c97e-11e7-8ea4-1685311bc61a.png)
Orders are postonly but not executed and canceled after placed

**Comment by GuntharDeNiro** [comment]
OK old thing: postonly is off oour algo now.
Thanks for reporting!
~Gun
