### ISSUE TITLE
[XT 6.0.1] Gunbot does not recognice the balance of a coin Strategy Exit Point: NaN

### ISSUE THREAD

**Issue by Omega246** [GuntharDeNiro/BTCT#225]
Version: XT 6.0.1, Windows, NO GUI, POLO AND BITTREX

This problem maybe correlates with my other problem:
https://github.com/GuntharDeNiro/BTCT/issues/184

Because i thought on pure tssl he showed:
"WARNING: we couldnt get a BOUGHT PRICE for BTC-XEL, Please manually override it
using config.js"

and on stepgain not it would be ok but "Pim" or "boekenbox" told me: 

> "should only be a value  when you have balance for that pair, when it is looking to sell and seeks for an exit point"

I hope i understood him right, but i have balance on this coins, despite that it shows NaN.

For example (default stepgain-strategy):

LGD:

Legends | LGD | 33.50195986 | 0.00000000 | 0.00000000 | 33.50195986 | 0.00426547

09/28/2017 05:00:02 AM | 09/28/2017 04:59:48 AM | Limit Buy | 0.00029849 | 33.50195986 | 33.50195986 | 0.00029848 | -0.01002498

LTC:

Litecoin | LTC | 0.71710290 | 0.00000000 | 0.00000000 | 0.71710290 | 0.00663048

09/17/2017 08:39:28 PM | 09/17/2017 08:39:28 PM | Limit Buy | 0.01394500 | 0.71710290 | 0.71710290 | 0.01394498 | -0.01002498

> 2017/11/15 00:39:17: BTC-LTC Last Bid/Ask 0.00924887/0.00927141
> ---------------------------------------------------------------------------
> ----------------
> EMA1: 0.00946386 === EMA2: 0.00942222
> ---------------------------------------------------------------------------
> ----------------
> ---------------------------------------------------------------------------
> ----------------
> HIGH BB: 0.00963004 == SMA: 0.00947315 == LOW BB: 0.00931627
> ---------------------------------------------------------------------------
> ----------------
> 2017/11/15 00:39:19: Got Trading History
> 2017/11/15 00:39:19: Checking Open Orders
> 2017/11/15 00:39:19: Price to buy: 0.00923377
> 2017/11/15 00:39:19: Last Bid/Strategy Exit Point: 0.00924887/**NaN**
> 2017/11/15 00:39:19: Last Ask/Strategy Entry Point: 0.00927141/0.00923377
> 2017/11/15 00:39:19: XTrend for BTC-LTC:    DOWN!!!
> No new opportunities found...
> GBXT_v6.0.1 BTC-LGD Round # 1
> ---------------------------------------------------------------------------
> ----------------
>  ??π??? XT Edition  Scanning bittrex for trading opportunities 2017/11/15 0
> 21
> ---------------------------------------------------------------------------
> ----------------
> 2017/11/15 00:39:21: BTC-LGD Last Bid/Ask 0.00012732/0.00012735
> ---------------------------------------------------------------------------
> ----------------
> EMA1: 0.00012677 === EMA2: 0.00012634
> ---------------------------------------------------------------------------
> ----------------
> ---------------------------------------------------------------------------
> ----------------
> HIGH BB: 0.00013265 == SMA: 0.00012568 == LOW BB: 0.00011871
> ---------------------------------------------------------------------------
> ----------------
> 2017/11/15 00:39:23: Got Trading History
> 2017/11/15 00:39:23: Checking Open Orders
> 2017/11/15 00:39:23: Price to buy: 0.00012382
> 2017/11/15 00:39:23: Last Bid/Strategy Exit Point: 0.00012732/**NaN**
> 2017/11/15 00:39:23: Last Ask/Strategy Entry Point: 0.00012735/0.00012382
> 2017/11/15 00:39:23: XTrend for BTC-LGD:    DOWN!!!

So, now i testet it with manual bought price on this strategy. Now it works.

LGD:

2017/11/15 00:57:28: BTC-LGD Last Bid/Ask 0.00012732/0.00012735
-------------------------------------------------------------------------
----------------
EMA1: 0.00012677 === EMA2: 0.00012634
-------------------------------------------------------------------------
----------------
-------------------------------------------------------------------------
----------------
HIGH BB: 0.00013265 == SMA: 0.00012568 == LOW BB: 0.00011871
-------------------------------------------------------------------------
----------------
2017/11/15 00:57:30: Got Trading History
2017/11/15 00:57:30: Checking Open Orders
2017/11/15 00:57:30: Price to buy: 0.00012382
2017/11/15 00:57:30: Last Bid/Strategy Exit Point: 0.00012732/0.00030446
2017/11/15 00:57:30: Last Ask/Strategy Entry Point: 0.00012735/0.00012382
2017/11/15 00:57:30: XTrend for BTC-LGD:    DOWN!!!

Now i tested es with pure bb: same result. LTC NaN, LGD (with manual bought price) "0.00030446".

**Comment by GuntharDeNiro** [comment]
THis is not an issue with "balance", it is an issue about not being able to receive buy orders oldier than X days: use bought price override if you have these kind of issues. Exschanges api servers do not always send oldier  trades, that's why we mlemented the BOUGHT_PRICE override.
Thanks!
~Gun
