### ISSUE TITLE
Default BBRSIGAIN Strategy Entry Point Error

### ISSUE THREAD

**Issue by selevanm** [GuntharDeNiro/BTCT#229]
Using the default settings for BBRSIGAIN strategy, the bot doesnt appear to be buying in the correct spot.  
![image](https://user-images.githubusercontent.com/414673/32868635-0204407e-ca28-11e7-821a-aa22dfc85dfd.png)

When I change the period to 15 on my chart it appears that is closer but the config settings are set for period: 5

"bbrsigain": {
            "NAME": "bbrsigain",
            "TRADING_LIMIT": 0.002,
            "PERIOD": 5,
            "RSI_BUY_LEVEL": 30,
            "GAIN": 2,
            "EMA1": 24,
            "EMA2": 12,
            "HIGH_BB": 1,
            "LOW_BB": 1,
            "STDV": 2,
            "SMAPERIOD": 50,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 600
        },

**Comment by selevanm** [comment]
Happened with another coin here.

![image](https://user-images.githubusercontent.com/414673/32870520-28b7fda6-ca31-11e7-8a9f-eaa20a2e007f.png)

**Comment by GuntharDeNiro** [comment]
Hello in both cases there is an issue in your bot that is not receiving the right datas from the exchange: both pictures show one of the entry points as NaN.
Please move this to support before to proceed to tag this as a bug: i would need yur out.log and err.log.
You can PM me directly on Telegram @gunthardeniro or send me an email gunthardeniro@gmail.com
Thanks!
~Gun
