### ISSUE TITLE
bbrsi strategy overrides stop limit and refuses to sell - bug with potential for massive losses

### ISSUE THREAD

**Issue by h-parks** [GuntharDeNiro/BTCT#233]
If you use BBRSI on 6.0.2 you should not expect the STOP_LIMIT variable to work properly right now. 

Gunbot will see that RSI is still below your RSI_SELL_LEVEL and refuse to sell your coin. 
![like if you are a big beautiful bbrsi who dont need no stop loss](https://user-images.githubusercontent.com/22692852/32928899-2d702190-cb1a-11e7-80a7-4ad46637be7e.png)

**Comment by bennygrahn** [comment]
Same issue in strategy BBRSISTEPGAIN. Stop_limit is not trigger.

**Comment by GuntharDeNiro** [comment]
good catch! Fixed!
Thanks guys!
