### ISSUE TITLE
No Trades on Bittrex

### ISSUE THREAD

**Issue by Morne14** [GuntharDeNiro/BTCT#234]
Good Day Community

I have set up the Gunbot XT and it is running and showing bid/ask prices.  It has done #5478 rounds in the last 10 hours.  I am trading BTC-LSK but it is not doing any trades in Bittrex.

I have checked my API and secret key and it matches in Gunbot settings.

Your assistance will be appreciated.

Many Thanks,

Morne

**Comment by GuntharDeNiro** [comment]
Please this is an issue tracker: message me directly on telegram @GuntharDeNiro or send me an email gunthardeniro@gmail.com for support requests.
Thanks!
~Gun
