### ISSUE TITLE
Wiki typo?

### ISSUE THREAD

**Issue by Utone** [GuntharDeNiro/BTCT#237]
HIGH_BB | 45 | Values: numerical – represents a percentage. Relevant: when bb is used as selling strategy & when DOUBLE_UP is activated. This sets the target for selling with bb as selling strategy. The bot will sell when the price hits a point 40% from HIGH_BB.
-- | -- | --
LOW_BB | 45 | Values: numerical – represents a percentage. Relevant: only when bb is used as buying strategy. This sets the target for buying with bb as buying strategy. The bot will buy when the price hits a point 40% from LOW_BB.

Shouldn't this be either: 
HIGH_BB | 45 =  The bot will sell when the price hits a point 45% from HIGH_BB, 
LOW_BB | 45 = The bot will buy when the price hits a point 45% from LOW_BB
Or:
HIGH_BB | 40 =  The bot will sell when the price hits a point 40% from HIGH_BB, 
LOW_BB | 40 = The bot will buy when the price hits a point 40% from LOW_BB
?

**Comment by dotpim** [comment]
Thanks. Will be fixed in the next wiki commit.
