### ISSUE TITLE
v6 Bandwidth usage

### ISSUE THREAD

**Issue by tandyuk** [GuntharDeNiro/BTCT#239]
Can we get some details on what gunbot is supposed to do per pair/cycle in terms of api requests.

I'm seeing my gunbot box, running 85 pairs on 85 seperate instances use upwards of 750GB downstream and 20GB upstream bandwidth per day.
This seems excessively high, and significantly higher than v5 did.

**Comment by GuntharDeNiro** [comment]
it is by ohlc datas you collect to calculate close values of candles

**Comment by tandyuk** [comment]
This needs a MUCH more detailed explanation than this.

Why does the bandwidth use steadily grow per pair, rather than being relatively constant?

How is a home user, or AWS free tier even supposed to run the bot, let alone trade if these are the new bandwidth requirements?

What is the expected required bandwidth for a single pair, looking at 15min candlesticks, over a 24 hour period?
