### ISSUE TITLE
[Bug] [TV] Orders don't get executed on Poloniex

### ISSUE THREAD

**Issue by rene-re** [GuntharDeNiro/BTCT#241]
Current situation:
Gunbot 5505 or 601 or 602 receives an incoming email alert through the imap listener. The email is correctly parsed. However, GB does not execute anything after successfully parsing the email.

See example down below
![capture](https://user-images.githubusercontent.com/1926425/32986232-083d5ed2-ccce-11e7-91eb-35d082341b68.PNG)

Expected situation: BUY or SELL order placed after the email got parsed.

What I tried to far:
* enough $$ on the main pair
* prior manual trade on the pair

**Comment by gregmca** [comment]
I have the same issue on Bitfinex, reported

**Comment by EdsSpecial** [comment]
Me too. Polo - Win10. Tried just exe and gui. Same on both. My 602 says 6.0.2_BETA TRADINGVIEWS Edition.
