### ISSUE TITLE
Orders not executed on Bitfinex (tradingview plugin)

### ISSUE THREAD

**Issue by gregmca** [GuntharDeNiro/BTCT#244]
Orders are read with gunbot but not executed, log attached and also a screenshot of the error when starting the bot. 

13|gunthy- |     at module.exports.Market.getBalances.Promise.bfx.wallet_balances (/snapshot/gunbot-build/bitfinex.js:0:0)
13|gunthy- |     at Request.rest.make_request.request [as _callback] (/snapshot/gunbot-build/node_modules/bitfinex-api-node/rest.js:68:12)
13|gunthy- |     at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
13|gunthy- |     at emitTwo (events.js:125:13)
13|gunthy- |     at Request.emit (events.js:213:7)
13|gunthy- |     at Request.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
13|gunthy- |     at emitOne (events.js:115:13)
13|gunthy- |     at Request.emit (events.js:210:7)
13|gunthy- |     at IncomingMessage.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
13|gunthy- |     at Object.onceWrapper (events.js:312:19)
13|gunthy- |     at emitNone (events.js:110:20)
13|gunthy- |     at IncomingMessage.emit (events.js:207:7)
13|gunthy- |     at endReadableNT (_stream_readable.js:1045:12)
13|gunthy- |     at _combinedTickCallback (internal/process/next_tick.js:102:11)
13|gunthy- |     at process._tickCallback (internal/process/next_tick.js:161:9)

config:
 },
    "bot": {
        "debug": false,
        "BOT_DELAY": 1,
        "interval_ticker_update": 25000,
        "period_storage_ticker": 2000,
        "timeout_buy": 60000,
        "timeout_sell": 60000,
        "TV_GAIN": 0.6,
        "TV_TRADING_LIMIT_BUY": 25,
        "TV_PYRAMID": true,
        "TV_TRADING_LIMIT_SELL": 100,
        "TV_PROTECTION": true,
		"TV_TRADING_LIMIT_CAP": 110,
		"TV_STOPLOSS_PERCENTAGE": 60,
        "VERBOSE": true,
        "WATCH_MODE": false
    },
    "ws": {

[gunthy-linx64-out-13.log](https://github.com/GuntharDeNiro/BTCT/files/1486319/gunthy-linx64-out-13.log)
![screenshot from 2017-11-20 14-48-12](https://user-images.githubusercontent.com/30435063/32999906-b7bd694c-ce09-11e7-816b-87e94bcdf760.png)
![screenshot from 2017-11-20 20-13-12](https://user-images.githubusercontent.com/30435063/33006454-4b8748e4-ce2f-11e7-9973-0b83ba307ca9.png)

**Comment by Finnfj** [comment]
Here's another one that happens on Bitfinex: UnhandledPromiseRejectionWarning
![image](https://user-images.githubusercontent.com/28825397/33567187-a2d2a456-d922-11e7-8dc1-17590e12c4ea.png)

**Comment by cre8ergb** [comment]
Same Issue Here on both Bittrex and Poloniex XT 7.0.2

Bittrex: Orders are read and a timestamp buy or sell shows on screen, but no orders are actually placed
Poloniex: Same thing, except an ECONNRESET error shows up shorlty after order is received

![poloniex tv error 2](https://user-images.githubusercontent.com/35176460/34643171-43eed0ae-f2e5-11e7-8607-0da6f4c0dfdd.png)
