### ISSUE TITLE
602_RC2 Mac OS GUI not starting bot

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#245]
The RC2 gui is not starting the bot. No output in the Log window. Bot does not launch. No out.log files or err.log files generated. 

Starting the bot in its own terminal window without the GUI works normally. 

Screen shot showing blank log window with bot "running" (according to Stop button being visible):
![screen shot 2017-11-19 at 9 26 20 pm](https://user-images.githubusercontent.com/7082654/33001834-ef1c38da-cd75-11e7-9989-35e2e5f54d6b.png)

**Comment by dotpim** [comment]
This is not a bug, but a support issue.
Please check https://github.com/GuntharDeNiro/BTCT/wiki/Troubleshooting
