### ISSUE TITLE
Gunbot 601 ARM - GUI password issue

### ISSUE THREAD

**Issue by seriouslylost** [GuntharDeNiro/BTCT#264]
Hi,

I upgraded from 5055 ARM to 601 ARM.
When I open localhost:5000 I get a login screen. I click generate password. I click login.
I am just returned to the login page. Endless circle.

Either I am not typing the correct password or something is wrong in the ARM edition.

regards,
Helge

**Comment by dotpim** [comment]
This issue usually happens when a non-modern browser is being used (Internet Explorer for example). Please try a different browser, preferably the newest Chrome or Firefox version

**Comment by seriouslylost** [comment]
I am using Raspberry PI 3.

Updated Chromium according to https://raspberrypi.stackexchange.com/questions/41603/installing-chrome-on-raspbian

It was already up to date.

Did fresh install of Gunthy 601

Still not able to get past login screen.

Any special subscription necessary?


regards,

Helge




________________________________

**Comment by dotpim** [comment]
try to delete db.sqlite (this will clear your settings) and set a new password.
