### ISSUE TITLE
Non-BTC pairs prices not set

### ISSUE THREAD

**Issue by premghinde** [GuntharDeNiro/BTCT#265]
I may well be going outside of the bounds of what Gunbot was designed for, but I thought I'd give throwing the bot at non-BTC pairs a go to see what happens on Poloniex. The idea being that if BTC_ETH, BTC_BCH and ETH_BCH are set up, the bot could trade between them as appropriate.

Trades seem to be found but cannot execute.

```2017/11/27 03:25:49: There are some trading opportunities for ETH_BCH at poloniex. Scanning Trade History
 ɢՍÑɃʘͳ XT Edition  Tips&Tricks: ETH_BCH can be sold!!! 
2017/11/27 03:25:49: Last Bid price ETH_BCH: 3.64243577 | Last Ask: 3.64243584
2017/11/27 03:25:49: Balance ETH: 0.18438661
2017/11/27 03:25:49: Balance BCH: 0.05037044
2017/11/27 03:25:49: On Orders BCH: 0.00000000
Processing strategy tssl for ETH_BCH on poloniex
WARNING: we couldnt get a BOUGHT PRICE for ETH_BCH, Please manually override it using config.js
```

Feel free to tell me this is not possible :)

**Comment by GuntharDeNiro** [comment]
ahah no i will not tell you this is not possible: bitRage will do this tho!
stay tuned
