### ISSUE TITLE
Question for dotpim: When to stop GB and go Manual

### ISSUE THREAD

**Issue by oldskoolnix** [GuntharDeNiro/BTCT#266]
Saw your update on this page:  https://github.com/GuntharDeNiro/BTCT/wiki/When-To-Stop-GunBot-And-Go-Manual

Been running the bot on windows at home and very pleased, but will be bringing some old *nix servers online for trading soon instead.

What is the gunbot price updater?  Is it part of the 6.0.2 package?  Is there a windows.exe I can d/l and test?

Thanks

**Comment by dotpim** [comment]
This article is about a legacy Gunbot version. I believe the "price updater" is referring to price updates in the console logs from that version - which would still exist in any modern Gunbot version.

I tagged the article as being about a legacy version now. Please note that every relevant article about the current version of Gunbot will always be linked in the sidebar navigation on the wiki.
