### ISSUE TITLE
Tracking Session Profits in 6.0.2 on windoze

### ISSUE THREAD

**Issue by oldskoolnix** [GuntharDeNiro/BTCT#268]
I'm running 6.0.2 gui on windoze until I can get some old *nix rackmounts I have online.

Aside from pouring through the logs.  Is anyone aware of a setting or third party tool that will provide
the:

"Total Profit BTC:0.00000000"

I used to look forward to seeing on every trading pair in 3.3.2?

**Comment by GuntharDeNiro** [comment]
alright

**Comment by oldskoolnix** [comment]
Thank you.

I was thinking this a.m.  Given trade pairs:  BTC-ETH, BTC-XMR, BTC-XRP & ETH-DASH for example

In 3.3.2, the total profit counter would be reset if the trading pair was stopped.  Not a problem.  

In 6.0.2, say you make changes to your pair strategies, click the "Apply" button, then go back to the Dashboard to Update changes to the Setup.

Could a log entry be made similar to the following:

Total Profits Previous Session:  [SESSION_#] [TIMESTAMP]
**********************************************************
BTC-ETH              BTC: 0.00000000000
BTC-XMR             BTC: 0.00000000000 
BTC-XRP              BTC: 0.00000000000
ETH-DASH           ETH: 0.00000000000

That records the last sessions profits prior to the counters being reset for the new session?
