### ISSUE TITLE
Bitfinex Bot can't see Dash Coin Balance, Never sells due to it.

### ISSUE THREAD

**Issue by Mydogisbetter** [GuntharDeNiro/BTCT#271]
I am trading DASH-USD which is really DSH-USD on Bitfinex. The bot does buy but never sells.. as it never can see the Dash coins it bought.

2017/11/28 08:15:17: Balance DSH: 0.0 
2017/11/28 08:15:17: On Orders DSH: 0 <-- Should be 0.48694182 DSH Coins.
Processing strategy stepgain for DSH-USD on bitfinex.

**Comment by GuntharDeNiro** [comment]
Fixed in v603
Thanks for reporting this
