### ISSUE TITLE
6.0.2 not making trades

### ISSUE THREAD

**Issue by horrorhound** [GuntharDeNiro/BTCT#272]
I download 6.0.2 (windows) and copied my poloniex keys, pairs and modified my bbstepgain strat to match my 5.0.4 settings.  However ran 6.0.2 for a day and no trades were ever made, but when I load up 5.0.4 the bot sees multiple trades to make while it's waiting for the startup timeout to expire.

**6.0.2 Strat.**
"bbstepgain": {
            "NAME": "bbstepgain",
            "TRADING_LIMIT": 0.100,
            "PERIOD": 15,
            "BUY_LEVEL": 0.1,
            "GAIN": 2,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 40,
            "LOW_BB": 40,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SELLLVL1": 2,
            "SELLLVL2": 5,
            "SELLLVL3": 70,
            "SELLLVL": 2,
            "PANIC_SELL": false,
            "DOUBLE_UP": true,
            "DOUBLE_UP_CAP": 1,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "OKKIES_MODE": false,
            "BTC_MONEY_FLOW": 35,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 600
        }

**5.0.4 Strat:**
"bbstepgain": {
            "NAME": "bbstepgain",
            "TRADING_LIMIT": 0.100,
            "PERIOD": 15,
            "BUY_LEVEL": 0.1,
            "GAIN": 2,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 40,
            "LOW_BB": 50,
            "STDV": 2,
            "SMAPERIOD": 50,
            "SELLLVL1": 2,
            "SELLLVL2": 5,
            "SELLLVL3": 70,
            "SELLLVL": 2,
            "PANIC_SELL": false,
            "DOUBLE_UP": true,
            "DOUBLE_UP_CAP": 1,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 600
        },

**Comment by Zoro98** [comment]
I'm having the same problem.

**Comment by dimmyr** [comment]
Same here.  Fired up 601 again, and trading no problem.
