### ISSUE TITLE
not making trades

### ISSUE THREAD

**Issue by kerrygarringer** [GuntharDeNiro/BTCT#274]
running 6.0.2 and bot is not making trades.  there are multiple opportunities
![gunbot - snip strategy](https://user-images.githubusercontent.com/31719459/33325898-2d77acc8-d419-11e7-8403-bcd1f2272d1d.PNG)
![gunbot - snip](https://user-images.githubusercontent.com/31719459/33325899-2d99892e-d419-11e7-8297-789735d41a9c.PNG)

 and no order is being placed.  Attached strategy settings and snip of latest 'entering buy cycle'.  Is there a setting i am missing or something that needs to be reset?

**Comment by Zoro98** [comment]
I'm having the exact same problem. I bought Gunbot and it did this with 601,602 beta and now 602 stable. I've also tried out LT. I'm left with all of these bags. Changing the cache refresh didn't work either.
