### ISSUE TITLE
Bitfinex exchange not buying 

### ISSUE THREAD

**Issue by ketonatus** [GuntharDeNiro/BTCT#278]
I've found that manually buying pairs on Bitfinex helps Gunbot to start a sell cycle.
Before the bot did nothing and only reported what the pairs are doing.

This still means buying is not working seems on Bitfinex.

Selling is working when: 
- buying a pair manually and 
- entering the BOUGHT_PRICE into the config.js (this is optional i guess)

* Exchange holds coins in Trading.
* API is set for all, except withdrawal.
* TSSL is used, and all BOUGT_PRICE are filled.

Version 6.0.2

"tssl":_ {
            "NAME": "tssl",
            "BUY_LEVEL": 0.1,
            "GAIN": 2,
            "TRADING_LIMIT": 0.004,
            "PERIOD": 5,
            "BUY_RANGE": 0.6,
            "SELL_RANGE": 0.6,
            "EMA1": 24,
            "EMA2": 12,
            "HIGH_BB": 45,
            "LOW_BB": 45,
            "STDV": 2,
            "SMAPERIOD": 50,
            "PANIC_SELL": false,
            "DOUBLE_UP": true,
            "DOUBLE_UP_CAP": 1,
            "TSSL_TARGET_ONLY": true,
            "STOP_LIMIT": 99,
            "BUY_ENABLED": true,
            "OKKIES_MODE": true,
            "BTC_MONEY_FLOW": 35,
            "MIN_VOLUME_TO_BUY": 0.0005,
            "MIN_VOLUME_TO_SELL": 0.0005,
            "TRADES_TIMEOUT": 60

**Comment by ketonatus** [comment]
Missing balance also, while I have BTC in Exchange wallet.

2017/11/30 11:14:17: Balance BTC: 0
2017/11/30 11:14:17: Balance OMG: 3.2930845

**Comment by GuntharDeNiro** [comment]
fixed in v603
