### ISSUE TITLE
[Enhancement request] OKKIES MODE should log when buy was prevented

### ISSUE THREAD

**Issue by cryptowally** [GuntharDeNiro/BTCT#281]
> BTC pump protection: automatically prevent buy orders from being placed when BTC price and volume are under high pressure. This is configurable per strategy or pair using OKKIES_MODE and BTC_MONEY_FLOW.

When buy orders are prevented, there should be a log of some sort that indicates that it happened.  That way, users who don't see trades happening can see that it was their configuration that is saving them grief instead of "gunbot not working".  Or, perhaps they can measure how often the buys are prevented over time, along with the money flow measurements.

Then they can either choose to change their config, be thankful, or live with the existing setting.

**Comment by GuntharDeNiro** [comment]
it does
