### ISSUE TITLE
Get DO NOT BUY!!! Stop limit is hit!!!, event several day after the stop limit has been reached

### ISSUE THREAD

**Issue by Hercule007** [GuntharDeNiro/BTCT#282]
I have a small stop limit ( 7%)
And on some pair it has been hit. Event after 2 days I still have the message
************************************************************************************************
DO NOT BUY!!! Stop limit is hit!!!
************************************************************************************************
Hypothesis: I suppose resuming the TRADES_TIMEOUT after restarting gunbot has some problems
Or a parameter I don't understand :)

![stoplimit](https://user-images.githubusercontent.com/2413253/33504991-11f1b52e-d6ea-11e7-84fa-0333024d30c7.png)

        "bbstepgain": {
            "NAME": "bbstepgain",
            "TRADING_LIMIT": 0.001,
            "PERIOD": 15,
            "BUY_LEVEL": 0.1,
            "GAIN": 0.6,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 40,
            "LOW_BB": 0,
            "STDV": 2,
            "SMAPERIOD": 20,
            "SELLLVL1": 0.6,
            "SELLLVL2": 10,
            "SELLLVL3": 70,
            "SELLLVL": 1,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "STOP_LIMIT": 7,
            "BUY_ENABLED": true,
            "OKKIES_MODE": true,
            "BTC_MONEY_FLOW": 35,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 60
        },

    "bot": {
        "debug": false,
        "BOT_DELAY": 1,
        "BOT_CCLEAN": 5,
        "interval_ticker_update": 25000,
        "period_storage_ticker": 2000,
        "timeout_buy": 60000,
        "timeout_sell": 60000,
        "TV_GAIN": 0.6,
        "TV_TRADING_LIMIT_BUY": 0.001,
        "TV_PYRAMID": true,
        "TV_TRADING_LIMIT_SELL": 0.001,
        "TV_PROTECTION": true,
        "TV_TRADING_LIMIT_CAP": 0.9,
        "TV_STOPLOSS_PERCENTAGE": 60,
        "VERBOSE": true,
        "WATCH_MODE": false

**Comment by Tripozide** [comment]
Is guess this is why:

"A common way to prevent accumulating bags is to cut your losses fast. With Gunbot you can set a STOP_LIMIT to sell a pair automatically after it loses x% of it's value. To prevent getting into a negative spiral of consecutive buy orders and stop limit orders, no further buy orders will be placed until the price reaches a point again that is above the level of that of the stop limit sell order."

Its just not very practical, when BTC rises so much. I ran into the same issue.
