### ISSUE TITLE
GB rebuying coins already in wallet.

### ISSUE THREAD

**Issue by yoshilee** [GuntharDeNiro/BTCT#283]
Hello there,
i still watch GB rebuying coins i got already in stock. Actual i think it is due to the minimum buy/sell setting=0,001. 
I also have this as trade limit; it seems when i buy a coin for 0,001 and it drops just a few % GB reacts in order to fullfill the minimum of 0,001 and does another buy instead of just waiting for the coin to raise. Anyone can confirm that behaviour?

btw, double_up=false

**Comment by KryptoGB** [comment]
anything under minimum sell amount will be considered dust.  either raise trade limit or lower min volume to sell.

**Comment by yoshilee** [comment]
Thanks, that makes everything clear :) !
