### ISSUE TITLE
7.0.1 b0912 TV Plugin error on incoming signals

### ISSUE THREAD

**Issue by Finnfj** [GuntharDeNiro/BTCT#294]
I expect the error persists even on b1012 since there was no TV related commit
Buy:

> 2017/12/10 14:01:01 Checking for new emails ɢƱͶβ۝Ł v7.0.1_beta (Build 0912) TRADINGVIEWS Edition
> 2017/12/10 14:01:01 Done
> emailParsed { timestamp: 1512914461675,
>   type: 'sell',
>   exchange: 'bittrex',
>   pair: 'BTC-GCR' }
> 2017/12/10 14:01:01 Done fetching all messages!
> [ { timestamp: 1512914461676,
>     type: 'sell',
>     exchange: 'bittrex',
>     pair: 'BTC-GCR' } ]
> 2017/12/10 14:01:01: Looking for pending orders...
> 2017/12/10 14:01:02: Checking prices...
> 2017/12/10 14:01:02: Received a sell order...
> Error: Cannot read property 'available' of undefined
>     at errorHandler (/snapshot/gunbot-build/ctx-wrapper.js:0:0)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:169:7)
> undefined

Sell:

> 2017/12/10 15:00:07 Checking for new emails ɢՍŋɮ๏Ŧ v7.0.1_beta (Build 0912) TRADINGVIEWS Edition
> 2017/12/10 15:00:07 Done
> emailParsed { timestamp: 1512918007370,
>   type: 'buy',
>   exchange: 'bittrex',
>   pair: 'BTC-NEO' }
> 2017/12/10 15:00:07 Done fetching all messages!
> [ { timestamp: 1512918007370,
>     type: 'buy',
>     exchange: 'bittrex',
>     pair: 'BTC-NEO' } ]
> 2017/12/10 15:00:08: Looking for pending orders...
> 2017/12/10 15:00:08: Checking prices...
> 2017/12/10 15:00:08: Received a BUY order...
> [ { timestamp: 1512918007370,
>     type: 'buy',
>     exchange: 'bittrex',
>     pair: 'BTC-NEO' } ]
> 2017/12/10 15:00:09 Checking for new emails ɢƱƝßØŦ v7.0.1_beta (Build 0912) TRADINGVIEWS Edition
> Nothing to fetch
> Error: Cannot read property 'available' of undefined
>     at errorHandler (/snapshot/gunbot-build/ctx-wrapper.js:0:0)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:169:7)
> undefined
> 2017/12/10 15:00:11 Checking for new emails ɢƱͶƁǾŁ v7.0.1_beta (Build 0912) TRADINGVIEWS Edition
> Nothing to fetch
> 2017/12/10 15:00:13 Checking for new emails ɢՍͶß๏Ŧ v7.0.1_beta (Build 0912) TRADINGVIEWS Edition

Thanks to Chad for providing logs

**Comment by Finnfj** [comment]
> 2017/12/13 10:18:45 Checking for new emails ɢƱÑƁøŁ v7.0.1_beta (Build 1212) TRADINGVIEWS Edition
Nothing to fetch
2017/12/13 10:18:46: Checking prices...
2017/12/13 10:18:46: Received a sell order...
Error: Cannot read property 'available' of undefined
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
undefined

**Comment by Kolinee** [comment]
v.7.0.1_beta (Build 1212)
the same ussue "Cannot read property 'available' of undefined"

Gunthar, please make a working version for TV
They all unstable - tried 5.0.5.5, 6.0.2, 7.01

**Comment by rene-re** [comment]
Using 7.0.2 final, I still get the same error. Using TV and Bittrex

`
2018/01/03 08:30:24: Checking prices...
2018/01/03 08:30:24: Received a BUY order...
[ { timestamp: 1514968223692,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-DASH' } ]
Error: [object Object]
    at errorHandler (/snapshot/gunbot-build/ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
undefined
undefined
`

**Comment by COSMIC-COCO** [comment]
@rene-re - I had the same error using USDT. I had to increase the limit to resolve. I increased as such:

        "TV_TRADING_LIMIT_BUY": 25.0,
        "TV_PYRAMID": true,
        "TV_TRADING_LIMIT_SELL": 25.0,
