### ISSUE TITLE
6.0.2 stuck on "waiting for open orders" funding wallet confuses bot

### ISSUE THREAD

**Issue by deesun** [GuntharDeNiro/BTCT#301]
the bot does not work on cryptos involved with funding orders on bitfinex.
looks like it counts the funding orders as open exchange order and it waits until the funding ends... 
its waiting for days now on every pair which involves a crypto i have a funding order open.
this can take up to 30 days and i cannot "close" a provided funding order.

i got coinlend running on the same bitfinex account, this means coinlend blocks gunbot from doin its work.
gunbot needs to differentiate the funding (and margin) balance from the exchange or to ignore funding orders.

i need to add a fact:

if all the open funding orders are closed, the bot comes over the "waiting for open orders" callback but hits the next issue:

> 2017/12/16
> 
>  03:31:27: XRP-USD Last Bid/Ask 0.75401000/0.75500000
> ------------------------------------------------------------------------------------------------
> EMA1: 0.7518881944974358 === EMA2: 0.7570218905495729
> ------------------------------------------------------------------------------------------------
> ------------------------------------------------------------------------------------------------
> HIGH BB: 0.76784826 == SMA: 0.75208190 == LOW BB: 0.73631555
> ------------------------------------------------------------------------------------------------
> 2017/12/16 03:31:39: Got Trading History
> 2017/12/16 03:31:41: Checking Open Orders
> 2017/12/16 03:31:41: Price to buy: 0.7413617597744717
> 2017/12/16 03:31:41: Last Bid/Strategy Exit Point: 0.75401000/0.49686
> 2017/12/16 03:31:41: Last Ask/Strategy Entry Point: 0.75500000/0.7413617597744717
> 2017/12/16 03:31:41: XTrend for XRP-USD:    DOWN!!!   
> 2017/12/16 03:31:41: There are some trading opportunities for XRP-USD at bitfinex. Scanning Trade History
>  ɢƱÑɃøŦ XT Edition  Tips&Tricks: XRP-USD can be sold!!! 
> 2017/12/16 03:31:41: Last Bid price XRP-USD: 0.75401 | Last Ask: 0.755
> 2017/12/16 03:31:41: Balance USD: 0.10601522
> 2017/12/16 03:31:41: Balance XRP: 0.16832123
> 2017/12/16 03:31:41: On Orders XRP: 0
> Processing strategy stepgain for XRP-USD on bitfinex
> 2017/12/16 03:31:41: Entering sell cycle
> ┌───────────────────┬────────────┬────────────┬────────────┬─────────┬────────────┬──────────┬─────────┐
> │ ɢՍΠβ۝Ł XT Edition │ SMA        │ LowBB      │ HighBB     │ Last    │ XRP        │ Last Buy │ Pair    │
> ├───────────────────┼────────────┼────────────┼────────────┼─────────┼────────────┼──────────┼─────────┤
> │ Sell cycle        │ 0.75208190 │ 0.73631555 │ 0.76784826 │ 0.75401 │ 0.16832123 │ 0.49     │ XRP-USD │
> └───────────────────┴────────────┴────────────┴────────────┴─────────┴────────────┴──────────┴─────────┘
> [HEARTBEAT] Sending message to exchanges we are alive
> Cannot read property 'error' of undefined

looks like it cannot read the balance because i still something on the funding wallet.

**Comment by deesun** [comment]
...it also reads the whole balance of my account wrong. as you can see in the log, it says 
> Balance USD: 0.10601522
> Balance XRP: 0.16832123
but this is wrong. this is the balance of my funding wallet, not the exchange.

i need to wait until the funding orders are closed, to transfer the funding balance to the exchange wallet.
but its seems, the bot gets confused by the funding wallet.

**Comment by deesun** [comment]
ok it turns out, the bot still reads the balance of my funding wallet and not the exchange wallet, even AFTER i removed the API rights for this.
it also is still "waiting for open orders" as soon as a funding order is open... this means the bot does not work when a funding order is open on the involved crypto.
it does not care about the exchange wallet balance, it only reads the funding wallet, even without r/w rights??

**Comment by GuntharDeNiro** [comment]
I have informed the exchange developer, they will get back on this issue asap.

**Comment by GuntharDeNiro** [comment]
fixed in v7, please upgrade
