### ISSUE TITLE
Fixed - Linux 7.0.1 error on loading

### ISSUE THREAD

**Issue by chiefstack** [GuntharDeNiro/BTCT#304]
Hey,

Getting this error below on startup, all working normally for 6.0.2.

Loading config...
Loading the exchange - poloniex
(node:5361) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: statusCode 403
(node:5361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BitFlipp3r** [comment]
Same here. Using Node 8.9.1

`
(node:1572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: statusCode 403
(node:1572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by BitFlipp3r** [comment]
I could fix this by setting both key and masterkey in config.

**Comment by chiefstack** [comment]
Thanks BitFlipp3r that sorted it out for me.

**Comment by rudarmajdanpek** [comment]
Hi I have the same problem on windows.Can you please explain me how you fix it.Thanks

**Comment by chiefstack** [comment]
Hi, In the config.js file down the bottom there is a master key and a key they both must be filled out, if you only have one key put them both in, no need for 2 different keys.

		"bittrex": {
			"masterkey": "123456",
			"mastersecret": "123456789",
			"key": "123456",
			"secret": "123456789"
		},
