### ISSUE TITLE
Emotionless Strategy making double purchases with double_up disabled

### ISSUE THREAD

**Issue by eMadman** [GuntharDeNiro/BTCT#306]
Emotionless made a number of double purchases throughout the night.  All very close together in terms of timing.  Double_up is disabled and this doesn't look like double-up behavior.  Default settings are being used on the strategy.

id | market | order type | bought rate | actual rate | quantity | price | commission | total costs | profit (btc) | profit (%) | opened | closed
BTC-STRAT | LIMIT_BUY |   | 0.0006547834548 | 1.52720719 | 0.00099999 | 0.00000249 | -0.00100248 |   |   | 2017-12-18T09:07:40.683 | 2017-12-18T09:07:40.98
BTC-VTC | LIMIT_BUY |   | 0.0004848951516 | 2.06228088 | 0.00099999 | 0.00000249 | -0.00100248 |   |   | 2017-12-18T09:13:16.61 | 2017-12-18T09:13:16.673
BTC-STRAT | LIMIT_BUY |   | 0.000652963473 | 1.53146392 | 0.00099999 | 0.00000249 | -0.00100248 |   |   | 2017-12-18T09:17:56.153 | 2017-12-18T09:17:56.263
BTC-VTC | LIMIT_BUY |   | 0.0004820151806 | 2.07460271 | 0.00099999 | 0.00000249 | -0.00100248 |   |   | 2017-12-18T09:31:54.143 | 2017-12-18T09:31:54.177
BTC-MCO | LIMIT_BUY |   | 0.0008587272057 | 1.16279069 | 0.00099852 | 0.00000249 | -0.00100101 |   |   | 2017-12-18T11:56:47.863 | 2017-12-18T11:56:47.94
BTC-MCO | LIMIT_BUY |   | 0.0008553014505 | 1.16916673 | 0.00099999 | 0.00000249 | -0.00100248 |   |   | 2017-12-18T12:14:46.557 | 2017-12-18T12:14:47.04
BTC-NXT | LIMIT_BUY |   | 0.00005484969812 | 18.2248952 | 0.00099963 | 0.00000249 | -0.00100212 |   |   | 2017-12-18T13:13:39.45 | 2017-12-18T13:13:39.48
BTC-NXT | LIMIT_BUY |   | 0.00005376946232 | 18.59773107 | 0.00099999 | 0.00000249 | -0.00100248 |   |   | 2017-12-18T13:24:23.197 | 2017-12-18T13:24:23.34

**Comment by dotpim** [comment]
I think your TRADE_LIMIT is so close to MIN_VOLUME_TO_BUY, that after fees, you end up with just enough balance for Gunbot to consider buying again. 

Try setting TRADE_LIMIT slightly higher.

**Comment by eMadman** [comment]
You might be right.  Minimum volume to buy and Trading limit were both default to 0.001.  I hadn't experienced this issue with BBRSITSSL on 6.x.
