### ISSUE TITLE
Multiple Exchange not seeming to work with 7.0.1

### ISSUE THREAD

**Issue by charlesastwood** [GuntharDeNiro/BTCT#308]
I might be missing something but on 7.0.1 I don't seem to be able to have multiple exchanges working. I have set up keys for Poloniex and Bittrex in the settings, using the GUI going to setups and "new setup" I only seem to be able to select one exchange for all coins setup here, whereas before you could select the exchange when making a new coin pair.

If I make two setups one for poloniex and one for bittrex, if I start one, it stops the other

**Comment by dhiren1987** [comment]
I have the same issue, apparently you need to set up a second bot, something about pm2 and changing the outgoing port.
I am trying to work this out from the link below but not sure how to do it.
https://github.com/GuntharDeNiro/BTCT/wiki

**Comment by dhiren1987** [comment]
I meant to paste this link. 
https://github.com/GuntharDeNiro/BTCT/wiki/Advanced-usage
pm2 is only for Linux,
You need to open the config file in Notepad++ and change the port

**Comment by dotpim** [comment]
Fixed in v8. 
The gui can now launch multiple instances, one for each exchange.
