### ISSUE TITLE
[7.0.1] BUG: Bitfinex FIAT pairs issue

### ISSUE THREAD

**Issue by Mydogisbetter** [GuntharDeNiro/BTCT#310]
Due to the new format of entering pairs, I am supposed to enter my pairs as:

USDT-ETH
USDT-EOS
This does not work. I get stuck on a black loading screen.
I also tried:
USD-ETH
USD-EOS

Still doesn't work.

It will only get past the loading screen if I enter them as:

ETH-USD
EOS-USD

Also using USDT-ETH the trading view chart states invalid symbol as well.

**Comment by deesun** [comment]
this is because you entered wrong pairs. there is not USDT on Bitfinex right now.
only ETH-USD and EOS-USD are working because the others are NOT on Bitfinex.

**Comment by Mydogisbetter** [comment]
If you follow their wiki its not how they want them to be entered, USD is my base and ETH be my market...

I already know, ETH-USD  works but again, it doesn't state that on their wiki 

Pairs
In the pairs sections you can configure which pairs to use, on which exchange and which strategy should be used, optional overrides are possible. You need to remove any example pairs in the config.js file that you are not planning to use. Pairs need to be written in CAPS.

The set market coin is the one you want to accumulate. You use the base coin to buy another asset, and sell it back for profit in the base currency.

Gunbot normalizes pair notation, so all pairs for all exchanges follow the same logic:

BASECOIN-MARKETCOIN

All pairs with BTC as base currency are written like:

BTC-ETH, BTC-OK, BTC-XLM

All pairs with USDT as base currency are written like:

USDT-BTC, USDT-ETH, USDT-XMR

For a few coins on Bitfinex, the API display name is required. These are:

IOTA = IOT

DASH = DSH

QTUM = QTM

DATA = DAT

QASH = QSH

**Comment by deesun** [comment]
yea but if you enter them like in the wiki, they dont match with the pairs on bitfinex, so it wont work.
i just wanted to show examples, dont enter pairs which cross each other.
if your base is USD then you can add all ....-USD pairs then each sell will give you USD back.
