### ISSUE TITLE
[7.0.1] BUG: Bitfinex Error: 429

### ISSUE THREAD

**Issue by Mydogisbetter** [GuntharDeNiro/BTCT#311]
Error: 429
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:169:7)

I keep getting the above error as well, I have even increased my bot to 5seconds to see if maybe it was hitting the API too hard, I still got the same error.

**Comment by ketonatus** [comment]
Same here, with debug enabled it shows:

GBXT_v7.0.1BTC-BTG Round # 1
 ------------------------------------------------------------------------------------------------
  ɢƱͶ฿øŦ XT Edition  Scanning bitfinex for trading opportunities 2017/12/18 15:02:16
 ------------------------------------------------------------------------------------------------
 2017/12/18 15:02:18: BTC-BTG Last Bid/Ask 0.01621100/0.01630000
 Error: Nonce is too small. See https://github.com/bitfinexcom/bitfinex-api-node/blob/master/README.md#nonce-too-small for help
     at errorHandler (/snapshot/gunbot-build/ctx-wrapper.js:0:0)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:169:7)
 ------------------------------------------------------------------------------------------------
 EMA1: 0.01602334055191496 === EMA2: 0.016170228553018008
 ------------------------------------------------------------------------------------------------
 ------------------------------------------------------------------------------------------------
 HIGH BB: 0.01648706 == SMA: 0.01554052 == LOW BB: 0.01459398
 ------------------------------------------------------------------------------------------------
 ------------------------------------------------------------------------------------------------
 BTC/USD Money Flow Index is: 54.61103312270756
 ------------------------------------------------------------------------------------------------
 ------------------------------------------------------------------------------------------------
 RSI: 58.287108829052116
 ------------------------------------------------------------------------------------------------
 Error: Nonce is too small. See https://github.com/bitfinexcom/bitfinex-api-node/blob/master/README.md#nonce-too-small for help
     at errorHandler (/snapshot/gunbot-build/ctx-wrapper.js:0:0)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:169:7)
 Error: Nonce is too small. See https://github.com/bitfinexcom/bitfinex-api-node/blob/master/README.md#nonce-too-small for help
     at errorHandler (/snapshot/gunbot-build/ctx-wrapper.js:0:0)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:169:7)
 [GUNBOT XT] No orders to recalculate

**Comment by ketonatus** [comment]
In the github readme it states:

"If you need to go parallel, you have to use multiple API keys right now.""
I've setup a second API in the key/secret combination and that is a **HOTFIX** for now.

**Comment by Mydogisbetter** [comment]
I have a 2nd key already added, I am still getting the error... :/
