### ISSUE TITLE
[7.0.1] BUG TSSL (FUCKTIMEOUT) Bitfinex

### ISSUE THREAD

**Issue by antoniojoaojr** [GuntharDeNiro/BTCT#313]
![image](https://user-images.githubusercontent.com/1307333/34138173-61e73568-e455-11e7-93e5-2a74672ebc1d.png)

The buyer not completed, let the price escape! and restart buyer cicle,

this erros also appears

![image](https://user-images.githubusercontent.com/1307333/34138242-b6842e50-e455-11e7-9bee-4bb5368da21f.png)

**Comment by vicdr** [comment]
That's in debug mode... If 7 is the same as 6, it will not buy and sell in debug mode... I got caught out like this waiting for bot to buy or sell for days.

**Comment by antoniojoaojr** [comment]
I put the debug off, but the error continues appears, and the buy not complet! 

![image](https://user-images.githubusercontent.com/1307333/34138801-99dd40d6-e458-11e7-9d5b-203a18ea5c3f.png)

**Comment by antoniojoaojr** [comment]
THE SAME BUG IN THE BB STEPGAIN!!!!!
FUCKTIMEOUT its problem with bitfinex?

**Comment by antoniojoaojr** [comment]
Same error in stepgain
![image](https://user-images.githubusercontent.com/1307333/34141250-214d65ce-e467-11e7-9ad7-ce4f5fefdb1b.png)

**Comment by lucidqdreams** [comment]
![image](https://user-images.githubusercontent.com/6086602/34275909-1cf7c5ec-e704-11e7-8587-0b0f34d3b642.png)
same error on Bittrex using TSSL.

**Comment by Bruttagente** [comment]
I got the same FUCKTIMEOUT error on poloniex using stepgain; I had the error on my computer and switched to AWS, the error it's still here

**Comment by terrywest** [comment]
I get the same error FUCKTIMEOUT in v8.0.3, using Bitfinex on a Linux Debian system with bb trading.

This was working for me on v7.0.1 using the same config on the same system.

**Comment by adidonato** [comment]
Same error on 8.0.3 since yesterday. Did not change anything, being running this setup for a month. What's going on? **Why no response from Devs?**

**Comment by gustavolira** [comment]
any news?
