### ISSUE TITLE
V7.0.1 Is not selling with BBStepgain

### ISSUE THREAD

**Issue by BenAccinelli** [GuntharDeNiro/BTCT#319]
I'm using BBStepgain with 3 sell levels

Lvl1: 0.6
Lvl2: 1.8
Lvl3: 70

The bot won't sell even after the trend is going down. Luckily the market is going up, but there are ample opportunities for it to sell, rebuy when it's below the lower BB and sell again after 3-5% to increase my gains.

I'm running 10 pairs and none of them sell even after crossing beyond Lvl2 multiple times.

I've even deleted my gunbot and downloaded a fresh zip file and it's still not selling.

All ports are open 3000; 5000; and 5001

it's not in debug mode.

I get feedback that "Price is not in stepgain level yet ! ! ! Waiting to sell" and it's clearly beyond my Lvl2.

Has anyone else had this issue?
<img width="1378" alt="screen shot 2017-12-20 at 8 33 35 am" src="https://user-images.githubusercontent.com/34720026/34221951-0dfb9598-e577-11e7-9561-11a5ea4f8d01.png">

![screen shot 2017-12-20 at 11 10 28 am](https://user-images.githubusercontent.com/34720026/34221963-1c9dc0e4-e577-11e7-8396-473d11f64183.png)

<img width="323" alt="screen shot 2017-12-20 at 11 19 57 am" src="https://user-images.githubusercontent.com/34720026/34222141-ca0a6958-e577-11e7-9852-844bee2efc8a.png">

**Comment by imastud71** [comment]
I had the exact same issue. The bot kept buying until I had no BTC left and never sold after running for 48 hours. I switched back to 6.0.2 and the bot sold everything within an hour.

**Comment by vicdr** [comment]
In my humble opinion, having tried stepgain sell myself, i had to set sma period to shorter value so it sees the trend switch to "down" sooner... it won't sell whilst still on an uptrend
. I've switch to "tssl" for sell and much better result as proven on my live spreadsheet tracking

**Comment by imastud71** [comment]
The BBStepgain settings I had were exactly the same in 7.0.1 and 6.0.2 yet they would not sell in V7 and sold right away in V6. Seems like a bug to me. I have been hearing about tssl a lot and will certainly check it out.

**Comment by esalter** [comment]
I'm having this same issue.  Nothing has sold ever since I moved to 7.0.1.  I'm on a mix of emotionless, bbrsistepgain, and bbstepgain. Luckily, everything has been on an overall uptrend, but even if the bot sees a downtrend it has not sold.

**Comment by Nuschnusch** [comment]
Same here. I get the message that the "Price is not in stepgain level yet", also it is clearly above step 2 price. Exactly the same settings work perfectly in Gunbot 6.0.2. I did not get one sale in 3 whole days with bbstepgain in version 7.
However, I love the speed of the new version!

**Comment by BenAccinelli** [comment]
Thanks for letting me know that I'm not the only one. I just switched to 6.0.1 and that has been selling. I'm pretty sure there's a bbstepgain bug in 7.0.1.

Thanks for the TSSL recommendation, I'm gonna have to try that one out.

**Comment by kobkrit** [comment]
@GuntharDeNiro The problem is solved in 7.0.2?

**Comment by kobkrit** [comment]
@GuntharDeNiro I still have this problem on 7.0.2. bbstepgain is never sell.

**Comment by kobkrit** [comment]
@GuntharDeNiro 7.0.2 Haha. My bad. I set DEBUG = true. It disabled the selling. Problem solved!
I thought that DEBUG is only show the extra messages.

**Comment by ferninus** [comment]
Set DEBUG = true to enable selling, or false?
I am having the same issue with 7.0.2 bbStepgain not selling.

**Comment by sdhardy** [comment]
@ferninus debug=true disables selling, it's not mentioned in the Wiki but
it does. Make sure verbose=true if you want more output.

For The selling issue, try extracting into a new directory and moving your
configs over and start the bot in the new. Fixed the selling issue for me
on linux.

On Jan 8, 2018 6:46 PM, "ferninus" <notifications@github.com> wrote:

Set DEBUG = true to enable selling, or false?
I am having the same issue with 7.0.2 bbStepgain not selling.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GuntharDeNiro/BTCT/issues/319#issuecomment-356163431>,
or mute the thread

**Comment by ferninus** [comment]
Still having issue.  Fresh download, extract, default configs. Using 12 pairs all show charts in setup when added.

**Comment by ferninus** [comment]
Still having issue.  Fresh download, extract, default configs. Using 12 pairs all show charts in setup when added.

**Comment by GTrannoy** [comment]
Same issue with V7.0.2 with debug=false.

Something strange...
