### ISSUE TITLE
7.0.1 stuck after "Got Trading History" on pairs never traded via tssl on kraken

### ISSUE THREAD

**Issue by odgrim** [GuntharDeNiro/BTCT#320]
Steps to reproduce:
Open a fresh account on kraken with a minimal seed fund
Set up any trading pair on gunbot using tssl
set bot interval to 6 seconds to avoid their noob tier rate limit
run gunbot

to verify negative test:
destroy first trading pair config
buy an unrelated pair from the first on kraken
set up pair in gunbot using tssl
wait a few minutes for order to flush and be visible in trading history
run gunbot

out.log of a "previously traded pair" with a "non-traded pair" after ~20 minutes below... note how it goes right through BCT-BCH with no problems but hangs on BCT-LTC... Since my account was entirely unused I've been struggling to get gunbot to do something past initialization until I decided to test curl a bct-bch order to see if it was gunbot or kraken's fault.

>[32mLoading config...[39m
[32mLoading the exchange - kraken[39m
GBXT_v7.0.1BTC-BCH Round # 1
[90m------------------------------------------------------------------------------------------------[39m
 [33mɢ[39m[32mƱ[39m[34mƝ[39m[35mɃ[39m[31mØ[39m[33mŦ[39m[90m XT Edition  Scanning kraken for trading opportunities [39m2017/12/20 10:08:49
[90m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:08:56[39m[33m: BTC-BCH Last Bid/Ask 0.22709000/0.22995000[39m
[90m------------------------------------------------------------------------------------------------[39m
HIGH BB: 0.24822156 == SMA: 0.20725200 == LOW BB: 0.16628244
[90m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[36m: Checking Open Orders[39m
Last trade P/L for BTC-BCH was: 0.000 %
[31m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[33m: TrailingBuy limit [39m[42m0.22213820[49m
[31m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[36m: Last price         [39m[37m0.22995000[39m[90m   | [39m[36m Target to buy:   [39m0.22347907
[31m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[33m: Stop limit     [39m[41m0.22347907[49m
[31m------------------------------------------------------------------------------------------------[39m
[44mPrice to buy is not in TSSL range[49m
[32m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[33m: TrailingStop limit [39m[42m0.23773148[49m
[32m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[36m: Last price         [39m[37m[4m0.22709000[24m[39m[90m   | [39m[36m Target to sell:   [39m0.23631360
[32m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[33m: StopLoss limit     [39m[41m0.23489572[49m
[32m------------------------------------------------------------------------------------------------[39m
[44mPrice to sell is not in TSSL range[49m
[90m2017/12/20 10:09:35[39m[33m: Price to buy: 0.22347907[39m
[90m2017/12/20 10:09:35[39m[33m: Last Bid/Strategy Exit Point: 0.22709000/0.2363136[39m
[90m2017/12/20 10:09:35[39m[36m: Last Ask/Strategy Entry Point: 0.22995000/0.22347907[39m
[90m┌───────────────────[39m[90m┬────────────────[39m[90m┬────────────[39m[90m┬─────────────[39m[90m┬────────────[39m[90m┬─────────────┐[39m
[90m│[39m[31m [31mɢ[31m[33mƱ[31m[32mÑ[31m[34mƁ[31m[35m๏[31m[31mŦ[31m[90m XT Edition[31m [39m[90m│[39m[31m [90mStop limit hit[31m [39m[90m│[39m[31m [90mCan we buy[31m [39m[90m│[39m[31m [90mCan we sell[31m [39m[90m│[39m[31m [90mPanic sell[31m [39m[90m│[39m[31m [90mCan average[31m [39m[90m│[39m
[90m├───────────────────[39m[90m┼────────────────[39m[90m┼────────────[39m[90m┼─────────────[39m[90m┼────────────[39m[90m┼─────────────┤[39m
[90m│[39m Core checks       [90m│[39m [41m      NO      [49m [90m│[39m [41m    NO    [49m [90m│[39m [41m     NO    [49m [90m│[39m [41m    NO    [49m [90m│[39m [41m     NO    [49m [90m│[39m
[90m└───────────────────[39m[90m┴────────────────[39m[90m┴────────────[39m[90m┴─────────────[39m[90m┴────────────[39m[90m┴─────────────┘[39m
[90m2017/12/20 10:09:35[39m: Last Bid price BTC-BCH: [42m0.22709[49m | Last Ask: [41m0.22995[49m
[90m2017/12/20 10:09:35[39m: Balance BTC: [33m0.07087761[39m
[90m2017/12/20 10:09:35[39m: Balance BCH: [33m0.002[39m
[90m2017/12/20 10:09:35[39m: On Orders BCH: [33m0[39m
[36mProcessing strategy tssl for BTC-BCH on kraken[39m
BUY CYCLE
[90m2017/12/20 10:09:35[39m[36m: Entering buy cycle[39m
[31m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[33m: TrailingBuy limit [39m[42m0.22213820[49m
[31m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[36m: Last price         [39m[37m0.22995000[39m[90m   | [39m[36m Target to buy:   [39m0.22347907
[31m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:35[39m[33m: Stop limit     [39m[41m0.22347907[49m
[31m------------------------------------------------------------------------------------------------[39m
[44mPrice to buy is not in TSSL range[49m
[90m┌───────────────────[39m[90m┬──────────────────────────────────────[39m[90m┬────────────[39m[90m┬────────────[39m[90m┬─────────[39m[90m┬────────────[39m[90m┬───────[39m[90m┬─────────┐[39m
[90m│[39m[31m [31mɢ[31m[33mƱ[31m[32mҊ[31m[34mɃ[31m[35mʘ[31m[31mŁ[31m[90m XT Edition[31m [39m[90m│[39m[31m LowBB                                [39m[90m│[39m[31m HighBB     [39m[90m│[39m[31m Buy at     [39m[90m│[39m[31m Last    [39m[90m│[39m[31m BTC        [39m[90m│[39m[31m BCH   [39m[90m│[39m[31m Pair    [39m[90m│[39m
[90m├───────────────────[39m[90m┼──────────────────────────────────────[39m[90m┼────────────[39m[90m┼────────────[39m[90m┼─────────[39m[90m┼────────────[39m[90m┼───────[39m[90m┼─────────┤[39m
[90m│[39m Buy cycle         [90m│[39m 0.16628244                           [90m│[39m 0.24822156 [90m│[39m 0.22347907 [90m│[39m 0.22995 [90m│[39m 0.07087761 [90m│[39m 0.002 [90m│[39m [41mBTC-BCH[49m [90m│[39m
[90m├───────────────────[39m[90m┼──────────────────────────────────────[39m[90m┼────────────┴────────────┴─────────┴────────────┴───────┴─────────┤[39m
[90m│[39m Callbacks         [90m│[39m Waiting to buy: price is too high!!! [90m│[39m                                                                  [90m│[39m
[90m└───────────────────[39m[90m┴──────────────────────────────────────[39m[90m┴──────────────────────────────────────────────────────────────────┘[39m
GBXT_v7.0.1BTC-LTC Round # 1
[90m------------------------------------------------------------------------------------------------[39m
 [33mɢ[39m[32mՍ[39m[34mÑ[39m[35mɃ[39m[31mѺ[39m[33mͳ[39m[90m XT Edition  Scanning kraken for trading opportunities [39m2017/12/20 10:09:43
[90m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:09:47[39m[33m: BTC-LTC Last Bid/Ask 0.01882400/0.01883900[39m
[90m------------------------------------------------------------------------------------------------[39m
EMA1: 0.018693985182948663 === EMA2: 0.018698806500313928
[90m------------------------------------------------------------------------------------------------[39m
[90m------------------------------------------------------------------------------------------------[39m
HIGH BB: 0.01955584 == SMA: 0.01892002 == LOW BB: 0.01828420
[90m------------------------------------------------------------------------------------------------[39m
[90m2017/12/20 10:10:11[39m[33m: Got Trading History[39m

**Comment by vicdr** [comment]
Yes, I'm getting this on Bittrex too... with pairs never traded before
