### ISSUE TITLE
i whan't lice

### ISSUE THREAD

**Issue by vulcoo** [GuntharDeNiro/BTCT#322]
Hello
i want a gunbot license code
how can I receive it
I also want to become a bot dealer
how this can happen

**Comment by useR210961** [comment]
have a look into the forum

**Comment by dotpim** [comment]
Hi @vulcoo 

feel free to contact me on Telegram, I am an authorized reseller and can get you a license fast. https://telegram.me/boekenbox

We can also talk about how to become a reseller if you want.
