### ISSUE TITLE
[Security] Poloniex Resticted IPs

### ISSUE THREAD

**Issue by joemccann** [GuntharDeNiro/BTCT#325]
So I learned this the hard way.  I set the my API key in Poloniex to only allow connections from my IP addresses and it killed all buying and sell (authenticated API calls).  It would be helpful to know in the configuration that you _cannot_ restrict IPs with Gunbot or to say it another way, Gunbot requires you to allow Poloniex to have traffic from any IP.

Not the end of the world, but hopefully this helps someone else in the future.

**Comment by dotpim** [comment]
Hi,

to be fair, this is not a Gunbot issue. When you would run the bot on a server with a permanent IP address (like many users do), you could definitely restrict the key to your IP address.

best regards
Pim

**Comment by joemccann** [comment]
Ok cool! So Gunbot doesn't proxy the requests?  That's what I was
assuming.  Thanks!
