### ISSUE TITLE
Memory leak in new install

### ISSUE THREAD

**Issue by victor-stone** [GuntharDeNiro/BTCT#326]
Steps:
reboot EC2/AWS machine
Download 7.0.1 
unzip
start 'screen'
chmod +x gun*
./gunthy-gui-linx64 
browse to http://<ip>:5000
click on 'Settings'
Enter Bittrex key/secret - save
click on 'Dashboard'
Stack fault 
```
Security context: 0x1423512298b9 <JS Object>
    2: /* anonymous */ [/snapshot/gunbot-autoconfig/node_modules/sqlite3/lib/sqlite3.js:14] [pc=0x2712bb7eae2e](this=0x3520fb6191 <a Database with map 0x9efea1e139>,sql=0x39217aafe7d1 <String[26]: PRAGMA table_info(`users`)>)
    3: arguments adaptor frame: 2->1
    4: /* anonymous */ [/snapshot/gunbot-autoconfig/node_modules/sqlite3/lib/trace.js:31] [pc=0x2712bb87decf](this=0x3520fb6191 <a Dat...

FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: node::Abort() [./gunthy-gui-linx64]
 2: 0x127f65c [./gunthy-gui-linx64]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [./gunthy-gui-linx64]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [./gunthy-gui-linx64]
 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [./gunthy-gui-linx64]
 6: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [./gunthy-gui-linx64]
 7: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [./gunthy-gui-linx64]
 8: v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [./gunthy-gui-linx64]
 9: 0x2712bac8437d
Aborted
```

**Comment by victor-stone** [comment]
Update: even if I manage to get past the setup phase, the bot will hang (roughly same stack as above) after about 10-15 minutes. It chokes the machine completely and have to reboot. The software is unusable.

**Comment by deesun** [comment]
i got the same error. but my issue was just closed without comment (missing log, i guess). the bot hangs also if i try to start a strategy.

**Comment by victor-stone** [comment]
Which log? the error.log is empty. It's readily repeatable with a very vanilla setup. I'm happy to give access to my ec2 box to devs that want to instrument it.

**Comment by victor-stone** [comment]
Sorry to report this is still happening with 7.0.2 - after 2 hours:

> <--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkingDeque::EnsureCommitted Allocation failed - process out of memory
 1: node::Abort() [./gunthy-gui-linx64]
 2: 0x127f65c [./gunthy-gui-linx64]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [./gunthy-gui-linx64]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [./gunthy-gui-linx64]
 5: v8::internal::MarkingDeque::StartUsing() [./gunthy-gui-linx64]
 6: v8::internal::MarkCompactCollector::MarkLiveObjects() [./gunthy-gui-linx64]
 7: v8::internal::MarkCompactCollector::CollectGarbage() [./gunthy-gui-linx64]
 8: v8::internal::Heap::MarkCompact() [./gunthy-gui-linx64]
 9: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [./gunthy-gui-linx64]
10: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [./gunthy-gui-linx64]
11: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [./gunthy-gui-linx64]
12: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [./gunthy-gui-linx64]
13: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [./gunthy-gui-linx64]
14: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [./gunthy-gui-linx64]
15: 0x129b6b6 [./gunthy-gui-linx64]
16: 0xd4936765d05
Aborted

**Comment by nordashi** [comment]
Size of swap on instance? 
I got Gunbot running on micro instance (free tier) with Ubuntu 16.04, 2GB swap.
free -m
              total        used        free      shared  buff/cache   available
Mem:            990         279         105           2         605         552
Swap:          2047          33        2014

Can you provide info which linux image you used and which instance type?

**Comment by victor-stone** [comment]
Amazon Linux AMI 
t2.small

total|used|free|shared |buffers|cached
--|--|--|--|--|--
2001|313|1688|0|11|244


`-/+ buffers/cache:         57       1944`
`Swap:            0          0          0`

**Comment by nordashi** [comment]
Tbh; thats more than enough memory.
Could you try adding swap https://www.photographerstechsupport.com/tutorials/adding-swap-space-ec2-amazon-linux-instance/ - or any swap creation guide.
1 or 2GB would suffice.

**Comment by victor-stone** [comment]
I did that and it definitely extended the life of the bot for several more hours but sometime during the night the machine choked off and I had to reboot it so I couldn't get to it in time to capture the stack trace - but the behavior is exactly the same so I'm assuming it was the memory leak.

**Comment by victor-stone** [comment]
shoot - I actually added the swap to a t2.tiny instance - I'm trying it now on the t2.small. to state the obvious: I'm sure we can come up with a machine config large enough to run the thing for a while but that doesn't solve the bug - i.e. the leak is still there no matter how big the box

**Comment by codepushr** [comment]
@victor-stone I can only agree - larger boxes aren't solving anything. The memory leak has to be fixed ASAP.

**Comment by codepushr** [comment]
Also out of memory - but from another position:
```
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: node::Abort() [/home/ubuntu/gunbot/setups/47110c84-cf9f-4e31-9cba-c5047dd36fc5/gunthy-linx64]
 2: 0x1213ecc [/home/ubuntu/gunbot/setups/47110c84-cf9f-4e31-9cba-c5047dd36fc5/gunthy-linx64]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/home/ubuntu/gunbot/setups/47110c84-cf9f-4e31-9cba-c5047dd36fc5/gunthy-linx64]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/ubuntu/gunbot/setups/47110c84-cf9f-4e31-9cba-c5047dd36fc5/gunthy-linx64]
 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/ubuntu/gunbot/setups/47110c84-cf9f-4e31-9cba-c5047dd36fc5/gunthy-linx64]
 6: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/ubuntu/gunbot/setups/47110c84-cf9f-4e31-9cba-c5047dd36fc5/gunthy-linx64]
 7: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/home/ubuntu/gunbot/setups/47110c84-cf9f-4e31-9cba-c5047dd36fc5/gunthy-linx64]
 8: v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/home/ubuntu/gunbot/setups/47110c84-cf9f-4e31-9cba-c5047dd36fc5/gunthy-linx64]
 9: 0x119e5e80463d
```

**Comment by dotpim** [comment]
Fixed in the v9 GUI.

Memory usage is drastically reduced and stays stable even when running for weeks.
