### ISSUE TITLE
TSSL - statusCode 422 -   at process._tickCallback (internal/process/next_tick.js:169:7)

### ISSUE THREAD

**Issue by sschleicher** [GuntharDeNiro/BTCT#328]
ɢՍƝɃ۝Ŧ XT Edition  Scanning poloniex for trading opportunities 2017/12/22 07:53:49
------------------------------------------------------------------------------------------------
2017/12/22 07:53:51: USDT-REP Last Bid/Ask 51.85002225/52.60000000
------------------------------------------------------------------------------------------------
EMA1: 57.42375177961136 === EMA2: 55.378277638256364
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
HIGH BB: 62.87668983 == SMA: 54.50985202 == LOW BB: 46.14301421
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
BTC/USD Money Flow Index is: undefined
------------------------------------------------------------------------------------------------
2017/12/22 07:53:52: Got Trading History
2017/12/22 07:53:53: Checking Open Orders
Last trade P/L for USDT-REP was: -3.111 %
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: TrailingBuy limit 53.26845968
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Last price         52.60000000   |  Target to buy:   55.23983194
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Stop limit     53.91153967808
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Price of           USDT-REP is going   DOWN  
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Moving Stop limit to     52.91560000
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Moving TrailingBuy limit to 52.28440000
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: TrailingStop limit 45.19032480
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Last price         51.85002225   |  Target to sell:   44.92080000
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: StopLoss limit     44.65127520
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Price of           USDT-REP is going   UP  
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Moving StopLoss limit to     51.53892212
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Moving TrailingStop limit to 52.16112238
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Price to buy: 55.23983194
2017/12/22 07:53:53: Last Bid/Strategy Exit Point: 51.85002225/44.9208
2017/12/22 07:53:53: Last Ask/Strategy Entry Point: 52.60000000/55.23983194
┌───────────────────┬────────────────┬────────────┬─────────────┬────────────┬─────────────┐
│ ɢƱŋßǾŦ XT Edition │ Stop limit hit │ Can we buy │ Can we sell │ Panic sell │ Can average │
├───────────────────┼────────────────┼────────────┼─────────────┼────────────┼─────────────┤
│ Core checks       │       NO       │     YES    │      NO     │     NO     │      NO     │
└───────────────────┴────────────────┴────────────┴─────────────┴────────────┴─────────────┘
2017/12/22 07:53:53: Last Bid price USDT-REP: 51.85002225 | Last Ask: 52.6
2017/12/22 07:53:53: Balance USDT: 3985.17287593
2017/12/22 07:53:53: Balance REP: 0.00000000
2017/12/22 07:53:53: On Orders REP: 0.00000000
Processing strategy tssl for USDT-REP on poloniex
BUY CYCLE
2017/12/22 07:53:53: Entering buy cycle
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: TrailingBuy limit 52.28440000
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Last price         52.60000000   |  Target to buy:   55.23983194
------------------------------------------------------------------------------------------------
2017/12/22 07:53:53: Stop limit     52.915600000000005
------------------------------------------------------------------------------------------------
Price of USDT-REP is STEADY 
TrailingBuy limit is 52.28440000
Stop limit is 52.915600000000005
[GUNBOT XT] No orders to recalculate
Error: statusCode 422
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:169:7)
GBXT_v7.0.1USDT-STR Round # 231

**Comment by AntonyC1703** [comment]
If you are using Bittrex, you must to IP Whitelist.
