### ISSUE TITLE
Issue with 7.0.2 and 7.0.1 windows

### ISSUE THREAD

**Issue by Chasewyatt** [GuntharDeNiro/BTCT#343]
When ever I try to start the bot I get this message:

(node:11132) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Response code 400

(node:11132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rudarmajdanpek** [comment]
Hi ,I have the same issue.I belive it is a user mistake but i can not figure out what. I found a post for linux https://github.com/GuntharDeNiro/BTCT/issues/304 and its about API.I tryed to make an extra API on Bittrex ( NON master ) but it doesnt work.I

**Comment by Dave-Cox** [comment]
same here

**Comment by IzakLamprecht** [comment]
Same here any fixes jet ??

**Comment by rudarmajdanpek** [comment]
i just got a responce from chiefstak who solve the problem on linux.it shoul be the same on windows.At my case it still dont solve my problem. please let me know if this was helpfull.thanks

 "chiefstack
Hi, In the config.js file down the bottom there is a master key and a key they both must be filled out, if you only have one key put them both in, no need for 2 different keys.

	"bittrex": {
		"masterkey": "123456",
		"mastersecret": "123456789",
		"key": "123456",                          "
		"secret": "123456789"
	},

**Comment by johnnysan116** [comment]
same here...

**Comment by rudarmajdanpek** [comment]
any solution ?

**Comment by rudarmajdanpek** [comment]
solved .In my case was a wrong key-secret
