### ISSUE TITLE
Setup gunbot server to run over https

### ISSUE THREAD

**Issue by RobertButera** [GuntharDeNiro/BTCT#346]
Hi,

I'm setting up an Amazon EC2 server with Gunbot running on it.  I would like to bind gunbot to the public IP and have it run over https, and then connect to it from my local browser.

I can't see any instructions on how to setup gunbot to run over https.  Am I missing something?  Is this a bad idea?

**Comment by dotpim** [comment]
@GuntharDeNiro imo this can be closed. V10 GUI natively supports https.
