### ISSUE TITLE
7.0.2 Windows BBStepgain 422 Error

### ISSUE THREAD

**Issue by sschleicher** [GuntharDeNiro/BTCT#347]
I've tried both TSSL & now BBStepGain on 7.0.2.  The bot won't make a buy.  It gets this 422 error every time:

GBXT_v7.0.2 USDT-NXT Round # 13
------------------------------------------------------------------------------------------------
 ɢƱΠßõŁ XT Edition  Scanning poloniex for trading opportunities 2017/12/26 08:50:52
------------------------------------------------------------------------------------------------
2017/12/26 08:50:53: USDT-NXT Last Bid/Ask 1.41224015/1.41224104
------------------------------------------------------------------------------------------------
EMA1: 1.5137578141485375 === EMA2: 1.4987193425849719
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
HIGH BB: 1.60393064 == SMA: 1.50061852 == LOW BB: 1.39730640
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
BTC/USD Money Flow Index is: undefined
------------------------------------------------------------------------------------------------
2017/12/26 08:50:54: Got Trading History
2017/12/26 08:50:55: Checking Open Orders
Last trade P/L for USDT-NXT was: 2.960 %
2017/12/26 08:50:55: Price to buy: 1.4799561
2017/12/26 08:50:55: Last Bid/Strategy Exit Point: 1.41224015/0.7739266598000001
2017/12/26 08:50:55: Last Ask/Strategy Entry Point: 1.41224104/1.4799561
2017/12/26 08:50:55: XTrend for USDT-NXT:    DOWN!!!   
false
┌───────────────────┬────────────────┬────────────┬─────────────┬────────────┬─────────────┐
│ ɢƱÑ฿Øͳ XT Edition │ Stop limit hit │ Can we buy │ Can we sell │ Panic sell │ Can average │
├───────────────────┼────────────────┼────────────┼─────────────┼────────────┼─────────────┤
│ Core checks       │       NO       │     YES    │      NO     │     NO     │      NO     │
└───────────────────┴────────────────┴────────────┴─────────────┴────────────┴─────────────┘
2017/12/26 08:50:55: Last Bid price USDT-NXT: 1.41224015 | Last Ask: 1.41224104
2017/12/26 08:50:55: Balance USDT: 3985.17287593
2017/12/26 08:50:55: Balance NXT: 0.00000000
2017/12/26 08:50:55: On Orders NXT: 0.00000000
Processing strategy bbstepgain for USDT-NXT on poloniex
BUY CYCLE
2017/12/26 08:50:55: Entering buy cycle
Error: statusCode 422
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by anouar-zh** [comment]
Same issue here. Since christmas having mamy issues with 7.0.2 And 7.0.1. Have never used it more than a few houres because of these errors.

Verry irritating since it costed me a lot of money.

**Comment by sschleicher** [comment]
Start from a fresh install and make sure to set Master Key to true when you enter your first (or only) key.  I finally got 7.0.2 working by starting completely fresh.  Wish there was a way to copy one setup to another so I could just change strategies on the new copy pairs and be done.
