### ISSUE TITLE
no sell cycle on bittrex

### ISSUE THREAD

**Issue by lucidqdreams** [GuntharDeNiro/BTCT#348]
[NoSellCycle.zip](https://github.com/GuntharDeNiro/BTCT/files/1587803/NoSellCycle.zip)

I have 4 instances, pol, bin, bit, bitf.  All show sell cycle except bittrex.  It was working yesterday morning, 26th (NZD time zone) and appears to have stopped working the night of the 26th and I have found it the morning of the 27th.  attached are the files requested.  I have tried launching this several ways and still no sell cycle

![image](https://user-images.githubusercontent.com/6086602/34363598-650a39f0-eae2-11e7-8d1f-9512cb2a60b6.png)

**Comment by andremrtc** [comment]
me too, this version is terrible

**Comment by andremrtc** [comment]
![bugged](https://user-images.githubusercontent.com/32331400/34389602-b88425a2-eb21-11e7-8da8-a879fd96f69c.png)

**Comment by ferninus** [comment]
Having the same issue.  Tried downgrading to 7.01 and having same issue.  May need to go back to an older version.

**Comment by lucidqdreams** [comment]
I was told it was because it was outside of the sell range.  But I have collected bags that are still in sell cycle and the brought price is so much higher and the pair is still in "sell cycle".  Probably the easy test is to add BROUGHT-PRICE to the pair config and see if sell cycle occurs appears regardless of price.  I was also running 7.0.2 RC3 which I have since been told not to run.  7.0.2 stable was recommended as the better version to run.

**Comment by tenhercules** [comment]
Same Issue. All indication was to sell. Using BBRSI. 
BB_LOW=0, BB_HIGH=0, RSI 70,30. DGB was going trought to roof but gunbot Said no new opp found. Price was above the BB_HIGH 0 and RSI 81. But no Sell. 
reinstalled Gunbot but no luck :(. Having issue with more then one coin.
