### ISSUE TITLE
Selling with a loss (emotionless)

### ISSUE THREAD

**Issue by balroh** [GuntharDeNiro/BTCT#352]
Using version 7.0.2 with emotionless strategy. Even though the GAIN is set at 1, the bot sells at much lower level. Some times, it is so low, that the exchange charges cost more making the trade a loss rather than profit.

Below I am including the strategy setup and a couple of trades which resulted at a loss even though the market was profitable.

```
"emotionless": {
            "NAME": "emotionless",
            "TRADING_LIMIT": 0.005,
            "FUNDS_RESERVE": 0.001,
            "PERIOD": 15,
            "BUY_LEVEL": 0.6,
            "GAIN": 1,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 49,
            "LOW_BB": 49,
            "STDV": 2,
            "SMAPERIOD": 50,
            "PANIC_SELL": false,
            "DOUBLE_UP": true,
            "DOUBLE_UP_CAP": 1,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.0001,
            "MIN_VOLUME_TO_SELL": 0.0001,
            "TRADES_TIMEOUT": 60,
            "MICROTRADES": true
        }
```

![btc_xrp](https://user-images.githubusercontent.com/32099620/34420125-7143ff74-ec10-11e7-8b33-de84ddb134c2.png)

**Comment by stabenfeldt** [comment]
I experience the same, even though I've set `GAIN` to *6*.

**Comment by stabenfeldt** [comment]
Can anyone confirm that emotionless actually works? 
Please post your settings if they differ from the default. I've tested the default values except that I've lowered **TRADING_LIMIT** to `0.0003`. I want to see that it works before I put more money on it.

The [wiki states](https://github.com/GuntharDeNiro/BTCT/wiki/Emotionless) that:
>With this strategy, you don't need to think about setting the right or best parameters: it's all there already. You only need to set the basics like your trading limit and choose on which pairs you want to trade.

I had Gunbot run with emotionless the whole day on the following pairs _without any sales or buys_:
- BTC-ETH
- BTC-LTC
- BTC-ADA
- BTC-ZLC

**Comment by andyedward** [comment]
I had been running Emotionless since 25/12/2017, and it's working. The bot has done 208 trades so fare

**Comment by pi9eon** [comment]
@andyedward .Hey Andy, could you provide some info about your config. Maybe your settings in 'emotionless' and the pairs you're trading?

@balroh 
I've been running 'emotionless' slightly modified for my pairs (5 of them) which are all USD pairs. It's done the following in 2 days intermittent trading;

XMR/USD | Exchange | Limit | 0.53 | XMR | 370.89 | Executed
XMR/USD | Exchange | Limit | -0.54 | XMR | 374.51 | Executed
XMR/USD | Exchange | Limit | 0.54 | XMR | 370 | Executed
DASH/USD | Exchange | Limit | 0.17 | DASH | 1131.9 | Executed
LTC/USD | Exchange | Limit | -0.78 | LTC | 253.9 | Executed
XMR/USD | Exchange | Limit | -0.55 | XMR | 362.3 | Executed
ETC/USD | Exchange | Limit | 6.2 | ETC | 32.001 | Executed
ETC/USD | Exchange | Limit | -6.3 | ETC | 31.779 | Executed
ETC/USD | Exchange | Limit | -6.3 | ETC | 31.837 | Canceled
ETC/USD | Exchange | Limit | 6.3 | ETC | 31.456 | Executed
DASH/USD | Exchange | Limit | -0.18 | DASH | 1109 | Executed
DASH/USD | Exchange | Limit | 0.18 | DASH | 1096.1 | Executed
ETC/USD | Exchange | Limit | -6.5 | ETC | 30.922 | Executed
XMR/USD | Exchange | Limit | -0.55 | XMR | 362.05 | Canceled
ETC/USD | Exchange | Limit | 6.5 | ETC | 30.434 | Executed
DASH/USD | Exchange | Limit | -0.18 | DASH | 1105.9 | Executed
XMR/USD | Exchange | Limit | 0.55 | XMR | 357.8 | Executed
DASH/USD | Exchange | Limit | -0.18 | DASH | 1106 | Canceled
XRP/USD | Exchange | Limit | -94 | XRP | 2.1208 | Executed

This is my config;
        "_PG_emotionless": {
            "NAME": "_PG_emotionless",
            "TRADING_LIMIT": 200,
            "FUNDS_RESERVE": 0,
            "PERIOD": 15,
            "BUY_LEVEL": 0.6,
            "GAIN": 1,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 49,
            "LOW_BB": 49,
            "STDV": 2,
            "SMAPERIOD": 50,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "DOUBLE_UP_CAP": 1,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001,
            "TRADES_TIMEOUT": 300,
            "MICROTRADES": true
        },

DISCLAIMER: I'm a complete newb and am not happy with the results i'm getting from this config. I am in the process of changing it as we speak.....but it is working.... i think.
