### ISSUE TITLE
pyramiding does not work on version 7.0.2

### ISSUE THREAD

**Issue by gunbotuser** [GuntharDeNiro/BTCT#359]
when running gunbot the message "we own enough" shows even though the max buy limit has not been hit

-Either way you guys are awesome and made a great product!

**Comment by snahsiub** [comment]
It's the same for v7.03 RC1:

2018/01/12 11:05:07: Checking prices...
2018/01/12 11:05:08: Received a BUY order...
2018/01/12 11:05:08 Checking for new emails ɢƱƝɃõŁ v7.0.3_beta (Build 1001) TRADINGVIEW Edition 
Nothing to fetch
Not buying: we already bought enough
undefined

Love to help you guys out.
