### ISSUE TITLE
V4.0.3  not selling 

### ISSUE THREAD

**Issue by mikebussy3334** [GuntharDeNiro/BTCT#36]
When version 4.0.3 on Bittrex is running, I'll get a message that one of my pairs can be sold, yet It is not selling.

**Comment by Jverse** [comment]
Same thing,

1|gbot4    |  ɢՍͶɃםŁ v4.0.2  Tips&Tricks: BTC-NEO can be sold!!!
1|gbot4    | 2017/08/14 14:49:34: There are some trading opportunities for
BTC-NEO at bittrex. Scanning Trade History
1|gbot4    | 2017/08/14 14:49:34: Last Bid price BTC-NEO: 0.01115534 | Last
Ask: 0.01115536
1|gbot4    | 2017/08/14 14:49:34: Balance BTC:
1|gbot4    | 2017/08/14 14:49:34: Balance NEO: 0.30523543
1|gbot4    | 2017/08/14 14:49:34: On Orders NEO: 0

**Comment by adradr** [comment]
Hey,

I have the same issue, both on Windows and Mac. I have been running the 4.0.3 all night and it sold nothing, only bought a bunch of stuff and holding.

 ɢƱҊƁʘŁ v4.0.3  Tips&Tricks: BTC-STRAT can be sold!!! 
2017/08/16 03:43:26: There are some trading opportunities for BTC-STRAT at bittrex. Scanning Trade History
2017/08/16 03:43:26: Last Bid price BTC-STRAT: 0.00154358 | Last Ask: 0.00154646
2017/08/16 03:43:26: Balance BTC: 0.00331161
2017/08/16 03:43:26: Balance STRAT: 20.0012
2017/08/16 03:43:26: On Orders STRAT: 0
Processing strategy BB for BTC-STRAT on bittrex
┌───────────────┬────────────┬──────────────┬──────────────┬────────────┬─────────┬────────────┬───────────┐
│ ɢƱҊɃ۝ͳ v4.0.3 │ SMA        │ LowBB        │ HighBB       │ Last       │ STRAT   │ Last Buy   │ Pair      │
├───────────────┼────────────┼──────────────┼──────────────┼────────────┼─────────┼────────────┼───────────┤
│ Sell cycle    │ 0.00151987 │ 0.0014963516 │ 0.0015433839 │ 0.00154358 │ 20.0012 │ 0.00149991 │ BTC-STRAT │
└───────────────┴────────────┴──────────────┴──────────────┴────────────┴─────────┴────────────┴───────────┘

It shows me that it can be sold, and gives me a sell cycle but no order is placed on Bittrex.

**Comment by mikebussy3334** [comment]
I changed the gain to 0.1 nothing changed. Been selling manually.

**Comment by adradr** [comment]
@mikebussy3334 Can you post your config file?

**Comment by mikebussy3334** [comment]
{
	"pairs": {
		"poloniex": {
			"BTC_XMR": {
				"strategy": "bb",
				"override": {}
			}
		},
		"kraken": {
			"DASHEUR": {
				"strategy": "bb",
				"override": {}
			}
		},
		"bittrex": {
			"BTC-STRAT": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-ETH": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-PAY": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-TKN": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-WINGS": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-TIME": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-CVC": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-XDN": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-LUN": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-MCO": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-NEO": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-OMG": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-XEM": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-LTC": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-XEL": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-ZCL": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-LMC": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-CLOAK": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-ADX": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-OMG": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-PAY": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-WINGS": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-CVC": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-XEM": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-WAVES": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-XEL": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-OMG": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-BAT": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-FUN": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-ANT": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-LTC": {
				"strategy": "bbgain",
				"override": {}
			},
			"BTC-LUN": {
				"strategy": "gain",
				"override": {}
			},
			"BTC-DAR": {
				"strategy": "gain",
				"override": {}
			},
			"BTC-QWARK": {
				"strategy": "gain",
				"override": {}
			},
			"BTC-SEQ": {
				"strategy": "gain",
				"override": {}
			},
			"BTC-AMP": {
				"strategy": "gain",
				"override": {}
			},
			"BTC-ARK": {
				"strategy": "gain",
				"override": {}
			},
			"BTC-XZC": {
				"strategy": "gain",
				"override": {}
			},
			"BTC-NXS": {
				"strategy": "gain",
				"override": {}
			},
			
			"BTC-ION": {
				"strategy": "gain",
				"override": {}
			}
			},
		"cryptopia": {
			"SIGT_BTC": {
				"strategy": "gain",

				"override": {}
			}
		}
	},

	"exchanges": {
		"poloniex": {
			"key": "",
			"secret": ""
		},
		"kraken": {
			"key": "",
			"secret": ""
		},
		"bittrex": {
			"key": "",
			"secret": ""
		},
		"cryptopia": {
			"key": "",
			"secret": ""
		}
		
	},

	"bot": {
		"debug": true,

		"period_storage_ticker": 300,
		"interval_ticker_update": 25000,

		"timeout_buy": 60000,
		"timeout_sell": 60000,

		"WATCH_MODE": false
	},

	"strategies": {
		"bb": {
			"BTC_TRADING_LIMIT": 0.001,
			"PERIOD": 15,
			"BUY_LEVEL": 0.01,
			"GAIN": 0.1,
			"HIGH_BB": 35,
			"LOW_BB": 35,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"gain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUY_LEVEL": 0.1,
			"GAIN": 0.8,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": false,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"pp": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"PP_BUY": 0.00000001,
			"PP_SELL": 0.12345678,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"stepgain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUYLVL1": 1,
			"BUYLVL2": 3,
			"BUYLVL3": 5,
			"SELLLVL1": 2,
			"SELLLVL2": 5,
			"SELLLVL3": 10,
			"BUYLVL": 2,
			"SELLLVL": 2,
			"LASTPOINTS": 1,
			"AVGPOINTS": 10,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"bbgain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"GAIN": 0.1,
			"LOW_BB": 40,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"gainbb": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUY_LEVEL": 0.1,
			"GAIN": 0.1,
			"HIGH_BB": 40,
			"LOW_BB": 40,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"bbstepgain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"GAIN": 0.1,
			"HIGH_BB": 40,
			"LOW_BB": 40,
			"SELLLVL1": 2,
			"SELLLVL2": 5,
			"SELLLVL3": 10,
			"SELLLVL": 2,
			"LASTPOINTS": 1,
			"AVGPOINTS": 10,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"stepgainbb": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUY_LEVEL": 0.1,
			"GAIN": 0.1,
			"HIGH_BB": 40,
			"LOW_BB": 40,
			"BUYLVL1": 1,
			"BUYLVL2": 3,
			"BUYLVL3": 5,
			"BUYLVL": 2,
			"LASTPOINTS": 1,
			"AVGPOINTS": 10,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"bbpp": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUY_LEVEL": 0.1,
			"GAIN": 0.1,
			"HIGH_BB": 40,
			"LOW_BB": 40,
			"PP_BUY": 0.00000001,
			"PP_SELL": 0.12345678,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"ppbb": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUY_LEVEL": 0.1,
			"GAIN": 0.1,
			"HIGH_BB": 40,
			"LOW_BB": 40,
			"PP_BUY": 0.00000001,
			"PP_SELL": 0.12345678,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"gainstepgain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"SELLLVL1": 2,
			"SELLLVL2": 5,
			"SELLLVL3": 10,
			"SELLLVL": 2,
			"BUY_LEVEL": 0.1,
			"GAIN": 0.1,
			"LASTPOINTS": 1,
			"AVGPOINTS": 10,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"stepgaingain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUYLVL1": 1,
			"BUYLVL2": 3,
			"BUYLVL3": 5,
			"BUYLVL": 2,
			"GAIN": 0.1,
			"LASTPOINTS": 1,
			"AVGPOINTS": 10,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"gainpp": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUY_LEVEL": 0.1,
			"PP_SELL": 0.12345678,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"ppgain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"GAIN": 2,
			"PP_BUY": 0.12345678,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"stepgainpp": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"BUYLVL1": 1,
			"BUYLVL2": 3,
			"BUYLVL3": 5,
			"BUYLVL": 2,
			"PP_SELL": 0.1,
			"LASTPOINTS": 1,
			"AVGPOINTS": 10,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		},
		"ppstepgain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"SELLLVL1": 2,
			"SELLLVL2": 5,
			"SELLLVL3": 10,
			"SELLLVL": 2,
			"PP_BUY": 0.00000001,
			"LASTPOINTS": 1,
			"AVGPOINTS": 10,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
		}


	},

	"optionals": {
		"toOverride": {
			"BOUGHT_PRICE": 0.104744
 
		}
	}


}

**Comment by mikebussy3334** [comment]
sorry about that

**Comment by adradr** [comment]
could you remove the unnecessary lines? 
what OS are you using? 
Can you post some output of the bot?

**Comment by mikebussy3334** [comment]
I'm using Windows 10,


"bot": {
		"debug": true,

		"period_storage_ticker": 300,
		"interval_ticker_update": 25000,

		"timeout_buy": 60000,
		"timeout_sell": 60000,

		"WATCH_MODE": false
	},

	"strategies": {
		"bb": {
			"BTC_TRADING_LIMIT": 0.001,
			"PERIOD": 15,
			"BUY_LEVEL": 0.01,
			"GAIN": 0.1,
			"HIGH_BB": 35,
			"LOW_BB": 35,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			"bbgain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"GAIN": 0.1,
			"LOW_BB": 40,
			"EMA1": 200,
			"EMA2": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
			
	 ɢƱҊ฿๏Ŧ v4.0.3  Scanning bittrex for trading opportunities 2017/08/16 10:57:56
------------------------------------------------------------------------------------------------
 ɢՍƝβםŦ v4.0.3  Tips&Tricks: BTC-BAT can be bought!!!
2017/08/16 10:58:47: There are some trading opportunities for BTC-BAT at bittrex. Scanning Trade History
2017/08/16 10:58:47: Last Bid price BTC-BAT: 0.00005048 | Last Ask: 0.00005051
2017/08/16 10:58:47: Balance BTC: 0.03739319
2017/08/16 10:58:47: Balance BAT: 0
2017/08/16 10:58:47: On Orders BAT: 256.32193
Processing strategy BB_GAIN for BTC-BAT on bittrex
┌─────────────────┬─────────────────────┬─────────────────────────┬────────────────┬─────────┐
│ ɢՍƝ฿øŦ v4.0.3   │ SMA                 │ LowBB                   │ HighBB         │ Pair    │
├─────────────────┼─────────────────────┼─────────────────────────┼────────────────┼─────────┤
│ Sell cycle      │ 0.00005098          │ 0.000049284573          │ 0.000052674094 │ BTC-BAT │
├─────────────────┼─────────────────────┼─────────────────────────┼────────────────┼─────────┤
│ GUNBOT CALLBACK │ 2017/08/16 10:58:47 │ Waiting for open orders │                │         │
└─────────────────┴─────────────────────┴─────────────────────────┴────────────────┴─────────┘
2017/08/16 10:58:47: Kicking bittrex, receiving new tickers...
------------------------------------------------------------------------------------------------
 ɢՍͶ฿øŦ v4.0.3  Scanning bittrex for trading opportunities 2017/08/16 10:58:48
------------------------------------------------------------------------------------------------

 It seems like it wants to sell and looking at the chart it should be selling it just don't. it really bums me out, this software can be so awesome.

**Comment by adradr** [comment]
Based on this line I think there's an open sell order on your account. Can you check it on the webbased exchange (bittrex) ? I think there's an open order which is waiting for a buyer, and thats why there's no sell. 
**2017/08/16 10:58:47: On Orders BAT: 256.32193**

**Comment by mikebussy3334** [comment]
Thanks, I canceled any open orders, and its still not selling. Now it said something can be bought but its now waiting on open orders.

**Comment by Skytec** [comment]
Any idea on how you solved this? I get this all the time on my bot too. Just opportunities and scanning.
