### ISSUE TITLE
Getting "Result: Not defined" in 7.0.2

### ISSUE THREAD

**Issue by zawasp** [GuntharDeNiro/BTCT#360]
I just noticed for a pair I get this message, and it doesn't do average down at all (even though it's at -19%). Using "emotionless" with standard setting with Double Up enabled:
Check the "Result : Not defined" message.

Last trade P/L for BTC-NXT was: 146.4 %
2017/12/30 08:53:15: Entering sell cycle
┌───────────────────┬────────────┬───────────────────────┬────────────────┬─────────────┬──────────────┬────────────────────────┬─────────┐
│ ɢƱҊƁØŁ XT Edition │ SMA        │ LowBB                 │ HighBB         │ Last        │ NXT          │ Last Buy               │ Pair    │
├───────────────────┼────────────┼───────────────────────┼────────────────┼─────────────┼──────────────┼────────────────────────┼─────────┤
│ Sell cycle        │ 0.00003969 │ 0.000036325265        │ 0.000043060335 │ 0.00003765  │ 437.07762766 │ 0.00004652024276794049 │ BTC-NXT │
├───────────────────┼────────────┼───────────────────────┼────────────────┼─────────────┼──────────────┴────────────────────────┴─────────┤
│ GUNBOT CALLBACK   │ Sell price │ 0.0000472180464094596 │ Result         │ Not defined │                                                 │
└───────────────────┴────────────┴───────────────────────┴────────────────┴─────────────┴─────────────────────────────────────────────────┘

**Comment by balroh** [comment]
I am also experiencing this. Also using emotionless. It seems to occur when a pair is at a loss.

**Comment by monochromat13** [comment]
Same... using BB strategy on Binance.

```
GBXT_v7.0.2 BTC-ARK Round # 1
------------------------------------------------------------------------------------------------
 ɢƱŋƁ๏Ŧ XT Edition  Scanning binance for trading opportunities 2018/01/15 22:07:39
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
EMA1: 0.0005757168998175311 === EMA2: 0.0005746455597766435
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
HIGH BB: 0.00058903 == SMA: 0.00057598 == LOW BB: 0.00056293
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
BTC/USD Money Flow Index is: undefined
------------------------------------------------------------------------------------------------
Last trade P/L for BTC-ARK was: 2.705 %
┌───────────────────┬────────────────┬────────────┬─────────────┬────────────┬─────────────┐
│ ɢƱҊß๏Ŧ XT Edition │ Stop limit hit │ Can we buy │ Can we sell │ Panic sell │ Can average │
├───────────────────┼────────────────┼────────────┼─────────────┼────────────┼─────────────┤
│ Core checks       │       NO       │     NO     │      NO     │     NO     │     YES     │
└───────────────────┴────────────────┴────────────┴─────────────┴────────────┴─────────────┘
2018/01/15 22:07:41: Last Bid price BTC-ARK: 0.0005707 | Last Ask: 0.0005759
2018/01/15 22:07:41: Balance BTC: 0.75838852
2018/01/15 22:07:41: Balance ARK: 179.0944
2018/01/15 22:07:41: On Orders ARK: 0
Processing strategy bb for BTC-ARK on binance
SELL CYCLE
Averaged bought price: 0.0006117502652297728
┌───────────────────┬────────────┬───────────────┬───────────────┬─────────────┬──────────┬───────────────────────┬─────────┐
│ ɢƱŋƁØͳ XT Edition │ SMA        │ LowBB         │ HighBB        │ Last        │ ARK      │ Last Buy              │ Pair    │
├───────────────────┼────────────┼───────────────┼───────────────┼─────────────┼──────────┼───────────────────────┼─────────┤
│ Sell cycle        │ 0.00057598 │ 0.00056293177 │ 0.00058902823 │ 0.0005707   │ 179.0944 │ 0.0006117502652297728 │ BTC-ARK │
├───────────────────┼────────────┼───────────────┼───────────────┼─────────────┼──────────┴───────────────────────┴─────────┤
│ GUNBOT CALLBACK   │ Sell price │ 0.00061664427 │ Result        │ Not defined │                                            │
└───────────────────┴────────────┴───────────────┴───────────────┴─────────────┴────────────────────────────────────────────┘
```

**Comment by Alekseyt84** [comment]
I think I understood what the problem is.
My default config for this strategy was :
   "strategies": {
      "emotionless": {
          "NAME": "emotionless",
          "TRADING_LIMIT": 0.01,
          "FUNDS_RESERVE" : 0.001,
          "PERIOD": 15,
          "BUY_LEVEL": 0.6,
          "GAIN": 0.6,
          "EMA1": 16,
          "EMA2": 8,
          "HIGH_BB": 49,
          "LOW_BB": 49,
          "STDV": 2,
          "SMAPERIOD": 50,
          "PANIC_SELL": false,
          "DOUBLE_UP": false,
          "DOUBLE_UP_CAP": 1,
          "STOP_LIMIT": 60,
          "BUY_ENABLED": true,
          "MIN_VOLUME_TO_BUY": 0.0001,
          "MIN_VOLUME_TO_SELL": 0.0001,
          "TRADES_TIMEOUT": 600,
          "MICROTRADES" : true
      },
, this config I downloaded along with the bot.

and there were not these settings :
            "DU_CAP_COUNT": 3,

            "DU_METHOD": "HIGHBB",

            "DU_BUYDOWN": 2,

after I added them, the errors disappeared, the bot began to work and make averaging (I mean double_up).

My guess is that without these settings, the bot does not understand how to do "double_up"
and shows an error

I hope this helps someone.

**Comment by arttus** [comment]
this is still an issue in 8.0.3

**Comment by davepro305** [comment]
I have all the double_up settings correctly but still got the not defined error. Any other reason?
