### ISSUE TITLE
GB says trading but no trades show up on exchange

### ISSUE THREAD

**Issue by Crypt0Fun** [GuntharDeNiro/BTCT#367]
I'm using cryptopia and until about 18hrs ago gunbot was selling/buying. But now I get this message in att.
![image](https://user-images.githubusercontent.com/34981743/34461396-bb14d76c-ee28-11e7-8788-3a001e75ba17.png)
 on one of my pairs (no errors only this over and over again) without the sell actually taking place.

 Tried changing strategy, cleaning, restarting and new install of latest version of gunbot. Now things got worse and GB throws error:

(node:10608) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: unable to verify the first certificate
(node:10608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Using win version of GB.

**Comment by kerrygarringer** [comment]
I had exactly same thing happen

**Comment by kerrygarringer** [comment]
I reset API with new.  Same error.
I did a complete fresh install. same error.

**Comment by kerrygarringer** [comment]
Cryptopia working now.  Issue must have been at Cryptopia site.

**Comment by Crypt0Fun** [comment]
GB is running again indeed. no errors when starting but not sure if it's trading now. 12 pairs and running for 6+ hours without a single trade. Could be market conditions not sure.
I'll know if I seeing sell msg without sell actually happening.

**Comment by Crypt0Fun** [comment]
Problem still not fixed, getting sell msg on multiple pairs but no sells happening.
![arc2](https://user-images.githubusercontent.com/34981743/34477781-e046c282-ef9c-11e7-9472-7e1eb330afd5.PNG)

**Comment by bigcman27** [comment]
I am still having the same issue as of now. It has no issues buying but it will not sell ANYTHING. I have tried everything I can think of but still having no luck. Any update??
