### ISSUE TITLE
Error immediately after entering buy cycle when using bbstepgain –  [7.0.2]

### ISSUE THREAD

**Issue by stabenfeldt** [GuntharDeNiro/BTCT#373]
I'm running gunbot on Bittrex.
Any idea what might be wrong here?

**LOGS**
```
2018/01/02 10:19:22: XTrend for BTC-ETH:    DOWN!!!                                                                                                                                                [49/1885]
false
┌───────────────────┬────────────────┬────────────┬─────────────┬────────────┬─────────────┐
│ ɢՍΠßǾͳ XT Edition │ Stop limit hit │ Can we buy │ Can we sell │ Panic sell │ Can average │
├───────────────────┼────────────────┼────────────┼─────────────┼────────────┼─────────────┤
│ Core checks       │       NO       │     YES    │      NO     │     NO     │      NO     │
└───────────────────┴────────────────┴────────────┴─────────────┴────────────┴─────────────┘
2018/01/02 10:19:22: Last Bid price BTC-ETH: 0.06152001 | Last Ask: 0.06160999
2018/01/02 10:19:22: Balance BTC: 0.0072466
2018/01/02 10:19:22: Balance ETH: 0
2018/01/02 10:19:22: On Orders ETH: 0
Processing strategy bbstepgain for BTC-ETH on bittrex
BUY CYCLE
2018/01/02 10:19:22: Entering buy cycle
Error: [object Object]
    at errorHandler (/snapshot/gunbot/ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**CONFIG**

```
568         "bbstepgain": {
569             "NAME": "bbstepgain",
570             "TRADING_LIMIT": 0.0003,
571             "FUNDS_RESERVE": 0.001,
572             "PERIOD": 5,
573             "BUY_LEVEL": 0.1,
574             "GAIN": 3,
575             "EMA1": 16,
576             "EMA2": 8,
577             "HIGH_BB": 20,
578             "LOW_BB": 15,
579             "STDV": 2,
580             "SMAPERIOD": 50,
581             "SELLLVL1": 0.6,
582             "SELLLVL2": 1.6,
583             "SELLLVL3": 10,
584             "SELLLVL": 2,
585             "PANIC_SELL": false,
586             "DOUBLE_UP": false,
587             "DOUBLE_UP_CAP": 1,
588             "DU_CAP_COUNT": 3,
589             "DU_METHOD": "HIGHBB",
590             "DU_BUYDOWN": 2,
591             "RSI_BUY_ENABLED": false,
592             "RSI_SELL_ENABLED": false,
593             "RSI_BUY_LEVEL": 30,
594             "RSI_SELL_LEVEL": 70,
595             "STOP_LIMIT": 60,
596             "BUY_ENABLED": true,
597             "OKKIES_MODE": true,
598             "BTC_MONEY_FLOW": 35,
599             "MIN_VOLUME_TO_BUY": 0.0005,
600             "MIN_VOLUME_TO_SELL": 0.001,
601             "TRADES_TIMEOUT": 600
602         },
```

**Comment by vcyu08** [comment]
Getting similar error.  Looks like there is some issue with placing buy order with Gunbot XT Edition, v7.0.2.  First it's waiting to trading.  After timeout is over, the error occurred.  The strategy used was Emotionless.

GBXT_v7.0.2 ETH-XLM Round # 4
------------------------------------------------------------------------------------------------
 ɢՍͶ฿Ǿͳ XT Edition  Scanning bittrex for trading opportunities 2018/01/03 20:04:02
------------------------------------------------------------------------------------------------
Last trade P/L for ETH-XLM was: 0.000 %
************************************************************************************************
Waiting to trade...Safety Switch is on...
************************************************************************************************

GBXT_v7.0.2 ETH-XLM Round # 5
------------------------------------------------------------------------------------------------
 ɢՍҊɃøͳ XT Edition  Scanning bittrex for trading opportunities 2018/01/03 20:04:16
------------------------------------------------------------------------------------------------
Last trade P/L for ETH-XLM was: 0.000 %
Error: [object Object]
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by vcyu08** [comment]
Also trading in bittrex.

**Comment by anouar-zh** [comment]
Same issue here. Since christmas having mamy issues with 7.0.2 And 7.0.1. Have never used it more than a few houres because of these errors.

Verry irritating since it costed me a lot of money.

**Comment by vcyu08** [comment]
The error message could be more descriptive in 7.0.2.  I tried 7.0.1 and got a more descriptive error message.  Was able to resolve my particular issue given that more descriptive message.  Discussed the issue in the following thread.  Thanks!
[](https://github.com/GuntharDeNiro/BTCT/issues/377#issuecomment-355270318)

**Comment by vcyu08** [comment]
https://github.com/GuntharDeNiro/BTCT/issues/377#issuecomment-355270318

**Comment by vcyu08** [comment]
https://github.com/GuntharDeNiro/BTCT/issues/377
