### ISSUE TITLE
INVALID LICENSE FOR BITTREX!!! Please contact Gunthar

### ISSUE THREAD

**Issue by kiingawaiz** [GuntharDeNiro/BTCT#375]
Please help with this as I am not sure what I am doing wrong here, its new setup

**Comment by S-w-o-r-d-F-i-s-h** [comment]
Just make sure your api is enabled by one of the official resellers you bought from, read the wiki and proceed on

**Comment by ferninus** [comment]
Bittrex evidently deletes all your api keys when you change 2FA, like when you buy a new phone and need to move it over.

**Comment by ijusss** [comment]
Did you solved your problem?

**Comment by enea1982** [comment]
hello the gunbot gives me an error what it means: NVALID LICENSE FOR BITTREX !!! Please contact Gunthar!
can you help me please?

**Comment by ferninus** [comment]
It means your API key for Bittrex is not registered for your license.  If you have paid for Gunbot, contact your seller, give him the transaction ID for your payment and all the API keys you want to register

**Comment by enea1982** [comment]
but I would like to do a test before paying to see if it works as it should

**Comment by ferninus** [comment]
There's currently no trial version as far as I know.  I can tell you it works very well.

**Comment by enea1982** [comment]
where I can register my API license I get all the licenses of Bitrex
poloniex and the others or register me only for bitrex


2018-05-30 0:24 GMT+02:00 ferninus <notifications@github.com>:
