### ISSUE TITLE
unable to sign in to localhost:5000

### ISSUE THREAD

**Issue by cryptokorn** [GuntharDeNiro/BTCT#376]
Hey there,
I am new here and don't know if this is the right place to write about this but I really need some help.

I just installed Gunbot and wanted to get started on localhost:5000. There was a button saying "create password" and I pressed it. Apparently I was supposed to type something in but I didn't. Now I cannot access the website even if I type in nothing. Please help.

Thank you for your support

**Comment by uprel** [comment]
This is from the Wiki:
If you forget the password for Gunthy GUI, remove the file db.sqlite to create a new one. You will lose your settings by doing so.
