### ISSUE TITLE
JSON dumped when requesting prices, for any currency pair, randomly

### ISSUE THREAD

**Issue by Putricide** [GuntharDeNiro/BTCT#38]
`Error on strategy BB for BTC_XRP on poloniex while getting prices -| Error: [{"globalTradeID":209488474,"tradeID":11859231,"date":"2017-08-15 05:22:31","type":"sell","rate":"0.00003729","amount":"9746.88566036","total":"0.36346136"},{"globalTradeID":209488454,"tradeID":11859230,"date":"2017-08-15 05:22:26","type":"sell","rate":"0.00003729","amount":"3846.29803500","total":"0.14342845"}.....`

Version: 4.0.3 patched

**Comment by Kuppi74** [comment]
+1 I have same with BTC_XEM

**Comment by MrG4dget** [comment]
+1 same here

**Comment by fahrmairm** [comment]
+1

**Comment by Putricide** [comment]
Caused missed trade opportunity as well, according to rules in config.js it just didn't happen right when the last JSON dumped to console.

**Comment by Putricide** [comment]
Likely connected with issue #39

**Comment by Putricide** [comment]
Confirmed to happen on any strategy used.

**Comment by Putricide** [comment]
No longer reproducible as of 4.0.4, well done!

**Comment by fahrmairm** [comment]
I still have the exact problem:

Processing strategy BB for BTC_EMC2 on poloniex
┌─────────────────┬────────────┬─────────────────┬────────────────┬───────────────────────┬──────────────┬────────────┬──────────┐
│ ɢƱÑ฿øŁ v4.0.4   │ SMA        │ LowBB           │ HighBB         │ Last                  │ EMC2         │ Last Buy   │ Pair     │
├─────────────────┼────────────┼─────────────────┼────────────────┼───────────────────────┼──────────────┼────────────┼──────────┤
│ Sell cycle      │ 0.00001004 │ 0.0000095918733 │ 0.000010493847 │ 0.00000957            │ 927.04460993 │ 0.00001076 │ BTC_EMC2 │
├─────────────────┼────────────┼─────────────────┼────────────────┼───────────────────────┼──────────────┴────────────┴──────────┤
│ GUNBOT CALLBACK │ Sell price │ 0.00001082456   │ Result         │ DOUBLE_UP is disabled │                                      │
└─────────────────┴────────────┴─────────────────┴────────────────┴───────────────────────┴──────────────────────────────────────┘
------------------------------------------------------------------------------------------------
 ɢՍΠ฿ʘŁ v4.0.4  Scanning poloniex for trading opportunities 2017/08/18 12:35:21
------------------------------------------------------------------------------------------------
Error on strategy BB for BTC_XEM on poloniex while getting prices -| Error: [{"globalTradeID":211352167,"tradeID":3578818,"date":"2017-08-18 10:34:54","type":"sell","rate":"0.00005742","amount":"3006.90596253","total":"0.17265654"},{"globalTradeID":211352166,"tradeID":3578817,"date":"2017-08-18 10:34:54","type":"sell","rate":"0.00005744","amount":"2276.59749304","total":"0.13076776"},{"globalTradeID":211352165,"tradeID":3578816,"date":"2017-08-18 10:34:54","type":"sell","rate":"0.00005745","amount":"2.95326950","total":"0.00016966"},{"globalTradeID":211352164,"tradeID":3578815,"date":"2017-08-18 10:34:54","type":"sell","rate":"0.00005745","amount":"597.35892025","total":"0.03431826"},{"globalTradeID":211351287,"tradeID":3578814,"date":"2017-08-18 10:33:14","type":"buy","rate":"0.00005742","amount":"771.49144990","total":"0.

**Comment by fahrmairm** [comment]
happen when getting trading history:

 ɢՍҊƁʘŦ v4.0.4  Scanning poloniex for trading opportunities 2017/08/18 12:39:24
------------------------------------------------------------------------------------------------
2017/08/18 12:39:24: BTC_STEEM Last Bid/Ask 0.00024794/0.0002502
2017/08/18 12:39:25: STEEM balance: 26.63725234/BTC balance: 0.23496062
2017/08/18 12:39:25: Got Trading History
Error on strategy BB for BTC_STEEM on poloniex while getting prices -| Error: [{"globalTradeID":211353046,"tradeID":2316020,"date":"2017-08-18 10:37:43","type":"buy","
