### ISSUE TITLE
Ability to turn SELL cycle off

### ISSUE THREAD

**Issue by NoPhaseNoKill** [GuntharDeNiro/BTCT#380]
You should be able to turn the sell cycle off. We currently have the ability to turn BUY off, but not SELL.

The problems I'm facing which would be fixed by this change are:

1) If there's dust leftover in a pairing, it defaults to sell cycle (which is not what you want, because if the buy order wasn't filled correctly/expires - which happens regularly, you're not actually wanting to have to sell it to get back to the buy cycle and complete your full trade)

2) You may want to just use the bot to buy an alt coin (XLM for example). Currently, this will default to sell cycle (due to you having an amount in XLM), and mean that you can't accumulate the alt-coin if you wish.

**Comment by BobWatson** [comment]
This would be really good a a pair option - nonetssl / nonestepgain / bbnone / stepgainnone / etc. - on both the buy and the sell side. That way you can rid yourself of holdings you don't want at a good price, and accumulate pairs you think are good value for non-price reasons.

**Comment by NoPhaseNoKill** [comment]
I believe this should be a global option, which defaults to SELL_CYCLE 'on', but one that you can override/turn off for pairs/strategies. That way you can use it how you wish

**Comment by recyclix** [comment]
You can!
Set "MIN_VOLUME_TO_SELL" to 20 or something.
Coin won't sell unless you have 20 BTC worth of it.
Use in override for any coin.

**Comment by vicdr** [comment]
MIN_VOLUME_TO_SELL does not work correctly in 7.0.2 ...

I tried it the other night to accumulate at lower prices with min volume to sell set at 500, using double up, and it went on a haywire buying spree whilst not observing the double up parameters that it normally does.

![screenshot 104](https://user-images.githubusercontent.com/31399317/34519056-4bd49666-f0bd-11e7-8f49-9cb5525edd27.png)

**Comment by cryptowally** [comment]
I would also like this option.

**Comment by chenh3** [comment]
I think in 7.0.2, you can set "TRADING_LIMIT":0, then it won't sell anything.

**Comment by chenh3** [comment]
I think you can set "MIN_VOLUME_TO_SELL":99999999 (a large value), then it won't sell anything.
