### ISSUE TITLE
MIN_COIN_TO_BUY needed for some exchanges

### ISSUE THREAD

**Issue by cryptowally** [GuntharDeNiro/BTCT#383]
We have 
```
                        "MIN_VOLUME_TO_BUY": 0.001,
                        "MIN_VOLUME_TO_SELL": 0.001,
```
Which is expressed in terms of funding currency - ie, 0.001 BTC for BTC-XXX pairs.

However, some exchanges, like Bitfinex, also require minimum order amounts in terms of coins that you buy.  See https://api.bitfinex.com/v1/symbols_details 

Example:
```
pair | "omgbtc"
-- | --
price_precision | 5
initial_margin | "30.0"
minimum_margin | "15.0"
maximum_order_size | "100000.0"
minimum_order_size | "2.0"
expiration | "NA"
```
This says that an order must be 2.0 OMG large.  In order to make MIN_VOLUME_TO_BUY correct, we must reverse engineer the OMG price to BTC (0.00132825), then multiply by the minimum order size (2.0), then possibly add some buffer, and then put that in for `MIN_VOLUME_TO_BUY`.

I see two solutions here - 
1. Allow `MIN_COIN_TO_BUY` as a new, optional variable to be set globally on a strategy as well as an override per coin.
2. Add the symbols_details url to the `exchanges` definitions so that gunbot can query it upon startup and learn the right order sizes and minimums, and then be overridden by user-supplied `MIN_COIN_TO_BUY` variables

**Comment by BobWatson** [comment]
This exists via the API for Binance at least (GET /api/v1/exchangeInfo) - detail of minimum buys, minimum increments, etc. If we can pull it straight from the exchange, that would be awesome, so we don't need to think about it.
