### ISSUE TITLE
errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)

### ISSUE THREAD

**Issue by vcyu08** [GuntharDeNiro/BTCT#386]
Getting the following error with Emotionless strategy.  Also getting the similar error when using bbstepgains strategy when trying to fill a buy order.  Not sure what's causing the issue and how to resolve it.  Thanks!

GBXT_v7.0.2 ETH-XLM Round # 40
------------------------------------------------------------------------------------------------
 ɢՍÑɃØŁ XT Edition  Scanning bittrex for trading opportunities 2018/01/03 17:13:14
------------------------------------------------------------------------------------------------
Last trade P/L for ETH-XLM was: 0.000 %
Error: [object Object]
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by anouar-zh** [comment]
Same issue here. Since christmas having mamy issues with 7.0.2 And 7.0.1. Have never used it more than a few houres because of these errors.

Verry irritating since it costed me a lot of money.

**Comment by vcyu08** [comment]
The error message could be more descriptive in 7.0.2. I tried 7.0.1 and got a more descriptive error message. Was able to resolve my particular issue given that more descriptive message. Discussed the issue in https://github.com/GuntharDeNiro/BTCT/issues/377. Thanks!
