### ISSUE TITLE
Gunbot passing negative timestamps to polo

### ISSUE THREAD

**Issue by YoJeff** [GuntharDeNiro/BTCT#39]
When gunbot requests the private trade history from polo -- it passes a negative timestamp.   This would cause polo to return more data than required.

Sample params:

returnTradeHistory BTC_ETC -1089179534.166

**Comment by GuntharDeNiro** [comment]
aknowledged fixing it in 4.0.6

**Comment by GuntharDeNiro** [comment]
Fixed in v5. Thanks for reporting this!
