### ISSUE TITLE
Price to buy rounded :(

### ISSUE THREAD

**Issue by andremrtc** [GuntharDeNiro/BTCT#393]
I can not negotiate IOT / BTC with GunBot on Bitfinex.

He always makes a purchase order the moment I want, but he rounds the value so the order is always canceled.

What do I do? I'm sad about this problem.

Tried to buy IOTA at 0.00026734767, but rounded to 0.00026, so the order was canceled. He always does this, with all coins.

![1](https://user-images.githubusercontent.com/32331400/34600935-ff979864-f1e0-11e7-9884-cbed74dbd719.png)
![2](https://user-images.githubusercontent.com/32331400/34600939-01aca8a6-f1e1-11e7-8a87-3e4d8516bc44.png)

**Comment by CiscoXL** [comment]
I'm having the same issue in Bitfinex. I moved over to the USD-XXX pairs.
It only seems to be related to Bitfinex, as I can see in the Telegram group, no other markets seem to have this issue.
Is there a reason why it rounds both the amount as the price? It's not a limitation for the market as another bot I use can place orders in Bitfinex without rounding the price/amount.
