### ISSUE TITLE
[Enhancement][GunthyGUI] Pair reordering

### ISSUE THREAD

**Issue by Nocoderdude** [GuntharDeNiro/BTCT#394]
Implement pair reordering in GunthyGUI, either by drag-and-drop, or by an arrow style control "move pair left/right".

Reason: when dealing with a lot of pairs, it is easier to manage them if they can be ordered alphabetically or by base-pair.

**Comment by mobiledan121** [comment]
This is be great - Thanks Dan

**Comment by dotpim** [comment]
Improved pair handling is already in the gui backlog, therefore closing this ticket.
