### ISSUE TITLE
Callbacks: No new opportunities found

### ISSUE THREAD

**Issue by syerragunta** [GuntharDeNiro/BTCT#396]
Hello,

I tried using bb and bbstepgain, both strategies my sell cycle not started even its going above bb and stepgain %, Only i can see is Callback - No new opportunities found with blank low BB and high BB values. my bbstepgain config here..

NAME	:	bbstepgain
TRADING_LIMIT	:	0.01
FUNDS_RESERVE	:	0.001
PERIOD	:	15
BUY_LEVEL	:	0.1
GAIN	:	2
EMA1	:	16
EMA2	:	8
HIGH_BB	:	40
LOW_BB	:	40
STDV	:	2
SMAPERIOD	:	50
SELLLVL1	:	0.6
SELLLVL2	:	2
SELLLVL3	:	70
SELLLVL	:	2
PANIC_SELL	:	false
DOUBLE_UP	:	false
DOUBLE_UP_CAP	:	1
DU_CAP_COUNT	:	3
DU_METHOD	:	HIGHBB
DU_BUYDOWN	:	2
RSI_BUY_ENABLED	:	false
RSI_SELL_ENABLED	:	false
RSI_BUY_LEVEL	:	30
RSI_SELL_LEVEL	:	70
STOP_LIMIT	:	60
BUY_ENABLED	:	true
OKKIES_MODE	:	true
BTC_MONEY_FLOW	:	35
MIN_VOLUME_TO_BUY	:	0.001
MIN_VOLUME_TO_SELL	:	0.001
TRADES_TIMEOUT	:	600
<img width="790" alt="callback-no new opportunities found" src="https://user-images.githubusercontent.com/20783051/34631311-5b48f7c6-f235-11e7-9d30-5674f0232bce.png">
Thanks
Sreedhar Y

**Comment by GTrannoy** [comment]
I have the same issue.

Very frustrating. Gunbot buy as it should but never sell !

Exemple with RSI condition, but the same with RSI disable: 

![xvg_behavior](https://user-images.githubusercontent.com/12541742/35411892-c3d8b11a-021a-11e8-8840-5a5c9adfb01d.jpg)

**Comment by GTrannoy** [comment]
I believed XTrend has difficulties on Binance with default parameters. PERIOD 15 and SMAPERIOD 50 => ~12 hours

I try to reduce to PERIOD 5 and SMAPERIOD 5 => ~25 min.
XTrend is more ractive, but even if it changes from 'UP' to 'DOWN' just after reaching a maximum, no sell order is placed...

**Comment by ludalex** [comment]
Any news with this?

**Comment by NickA1195** [comment]
Im having the same problem.  any fix yet?

**Comment by mvu8912** [comment]
May I know if this problem is fixed? Why it is closed? Any further information please? GunthqrDeNiro

**Comment by GuntharDeNiro** [comment]
This issue has not been reported in v9.5.1 build 523. 
Please confirm
