### ISSUE TITLE
[BUG]Gunbot doesn't buy because of RSI which is disabled in configuration

### ISSUE THREAD

**Issue by lazyghost77** [GuntharDeNiro/BTCT#397]
When you restart Gunbot, it on some occasions shows that it can't buy because RSI is too high, but it's disabled in the config!  After restarting the Gunbot several times the false message disappears. The problem is that it doesn't buy when that happens :/
I have both RSI buy and sell disabled in the config and im using BB for buy and Stepgain for sell:
"RSI_BUY_ENABLED": false,
"RSI_SELL_ENABLED": false
If you need whole config, PM me!

![image](https://user-images.githubusercontent.com/25801048/34639022-55be6f10-f2e0-11e7-9c20-e19d259baaf1.png)

**Comment by Nocoderdude** [comment]
Apparently you are using bbrsistepgain. Which uses RSI by default. This is deprecated in version 7. Use plain bbstepgain.

**Comment by lazyghost77** [comment]
Its a bit confusing in picture. It haven't changed the name of strategy because i started with bbrsistepgain, but like I said i use BB for buying and stepgain for selling hence strategy is BBSTEPGAIN.

**Comment by chrisfarrell** [comment]
I had a similar issue, only on the selling end. Using 'bbstepgain' strategy I had:
"RSI_BUY_ENABLED": true,
"RSI_SELL_ENABLED": false
And got an error along the lines of:
"...RSI is too low!!! Waiting to sell"
I ended up conducting a manual sale for profit.
