### ISSUE TITLE
[BUG] Error on lot of Binance pairs 

### ISSUE THREAD

**Issue by lazyghost77** [GuntharDeNiro/BTCT#398]
Error appears after a while, when happens Gunbot skips the pair. This morning i had it on 20 of 28 pairs..
For whole config, PM me!
![image](https://user-images.githubusercontent.com/25801048/34639065-3a23d7c6-f2e1-11e7-8344-2e4004490b89.png)

**Comment by GuntharDeNiro** [comment]
fixed in v703

**Comment by lazyghost77** [comment]
When is the v703 expected, mate?
