### ISSUE TITLE
[BUG] 7.0.2 "UnhandledPromiseRejectionWarning" Status Code 422 on Poloniex

### ISSUE THREAD

**Issue by joemccann** [GuntharDeNiro/BTCT#400]
I have been running 6.0.2 for a month and am trying to upgrade. I do not, nor was ever given a `masterkey` or `mastersecret`, yet I keep getting an obvious Node.js error:

```bash
N|S ~/work/personal/crypto/gunbot7/Gunbot XT Edition - MacOs package/ ./gunthy-macos
Loading config...
Loading exchange - poloniex
(node:11637) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: statusCode 422
(node:11637) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've been trying to upgrade for weeks and I can't get past this bug. Can anyone help?

**Comment by OstKos** [comment]
I got the same problem just for Kraken! Would be nice if someone know an answer that helps

**Comment by joemccann** [comment]
I realized I had another instance of Gunbot running on a separate host.  I
killed it and it solved the issue.
