### ISSUE TITLE
Something looks strange in TSSL algorithm

### ISSUE THREAD

**Issue by chenh3** [GuntharDeNiro/BTCT#401]
I have a setting for pair [USD-BTC] as 

"GAIN": 1.5,
"BUY_RANGE": 0.8,
"SELL_RANGE": 1,

when arrived the highest value 16999, gunbot replaced a sell order aright after the price drop a little bit to 16954. but with sell range 1, it should sell after the price drop lower than 16829?

the log look like the follows:
(1) before the price drop:
GBXT_v7.0.2 USD-BTC Round # 451
------------------------------------------------------------------------------------------------
XT Edition  Scanning bitfinex for trading opportunities 2018/01/06 16:55:34
------------------------------------------------------------------------------------------------
2018/01/06 16:55:35: USD-BTC Last Bid/Ask 16974.00000000/16975.00000000
------------------------------------------------------------------------------------------------
EMA1: 16595.490165160176 === EMA2: 16704.286879133026
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
HIGH BB: 16785.97486316 == SMA: 16536.46000000 == LOW BB: 16286.94513684
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
BTC/USD Money Flow Index is: 45.43847470253604
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: Got Trading History
2018/01/06 16:55:37: Checking Open Orders
Last trade P/L for USD-BTC was: -8.951 %
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: TrailingBuy limit 16363.94988638
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: Last price         16975.00000000   |  Target to buy:   16495.91722417
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: Stop limit     16495.917
------------------------------------------------------------------------------------------------
Price to buy is not in TSSL range
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: TrailingStop limit 17139.70000000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: Last price         16974.00000000   |  Target to sell:   16760.69500000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: StopLoss limit     16800.30000000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: Price of           USD-BTC is going   UP  
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: Moving StopLoss limit to     16804.26000000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: Moving TrailingStop limit to 17143.74000000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:37: Price to buy: 16495.91722417
2018/01/06 16:55:37: Last Bid/Strategy Exit Point: 16974.00000000/16760.695
2018/01/06 16:55:37: Last Ask/Strategy Entry Point: 16975.00000000/16495.91722417
┌───────────────────┬────────────────┬────────────┬─────────────┬────────────┬─────────────┐
│ XT Edition        │ Stop limit hit │ Can we buy │ Can we sell │ Panic sell │ Can average │
├───────────────────┼────────────────┼────────────┼─────────────┼────────────┼─────────────┤
│ Core checks       │       NO       │     NO     │     YES     │     NO     │      NO     │
└───────────────────┴────────────────┴────────────┴─────────────┴────────────┴─────────────┘
2018/01/06 16:55:37: Last Bid price USD-BTC: 16974 | Last Ask: 16975
2018/01/06 16:55:37: Balance USD: 370.88398
2018/01/06 16:55:37: Balance BTC: 0.016
2018/01/06 16:55:37: On Orders BTC: 0
Processing strategy tssl for USD-BTC on bitfinex
SELL CYCLE
2018/01/06 16:55:37: Entering sell cycle
Averaged bought price: 16513
┌───────────────────┬────────────────┬───────────┬───────────┬───────┬───────┬──────────┬─────────┐
│ XT Edition        │ SMA            │ LowBB     │ HighBB    │ Last  │ BTC   │ Last Buy │ Pair    │
├───────────────────┼────────────────┼───────────┼───────────┼───────┼───────┼──────────┼─────────┤
│ Sell cycle        │ 16536.46000000 │ 16286.945 │ 16785.975 │ 16974 │ 0.016 │ 16513    │ USD-BTC │
└───────────────────┴────────────────┴───────────┴───────────┴───────┴───────┴──────────┴─────────┘
************************************************************************************************
Gunbot XT says: Trailing Profit limits are still good...waiting to sell...
************************************************************************************************

(2) when the price drop a little bit:
GBXT_v7.0.2 USD-BTC Round # 452
------------------------------------------------------------------------------------------------
XT Edition  Scanning bitfinex for trading opportunities 2018/01/06 16:55:45
------------------------------------------------------------------------------------------------
2018/01/06 16:55:46: USD-BTC Last Bid/Ask 16967.00000000/16970.00000000
------------------------------------------------------------------------------------------------
EMA1: 16595.490165160176 === EMA2: 16704.286879133026
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
HIGH BB: 16785.97486316 == SMA: 16536.46000000 == LOW BB: 16286.94513684
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
BTC/USD Money Flow Index is: 45.43847470253604
------------------------------------------------------------------------------------------------
2018/01/06 16:55:49: Got Trading History
2018/01/06 16:55:51: Checking Open Orders
Last trade P/L for USD-BTC was: -8.951 %
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: TrailingBuy limit 16363.94988638
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: Last price         16970.00000000   |  Target to buy:   16495.91722417
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: Stop limit     16495.917
------------------------------------------------------------------------------------------------
Price to buy is not in TSSL range
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: TrailingStop limit 17143.74000000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: Last price         16967.00000000   |  Target to sell:   16760.69500000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: StopLoss limit     16804.26000000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: Price of           USD-BTC is going  DOWN 
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: Moving TrailingStop limit to 17136.67000000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: StopLoss limit is   16804.26000000
------------------------------------------------------------------------------------------------
2018/01/06 16:55:51: Price to buy: 16495.91722417
2018/01/06 16:55:51: Last Bid/Strategy Exit Point: 16967.00000000/16760.695
2018/01/06 16:55:51: Last Ask/Strategy Entry Point: 16970.00000000/16495.91722417
┌───────────────────┬────────────────┬────────────┬─────────────┬────────────┬─────────────┐
│ XT Edition.       │ Stop limit hit │ Can we buy │ Can we sell │ Panic sell │ Can average │
├───────────────────┼────────────────┼────────────┼─────────────┼────────────┼─────────────┤
│ Core checks       │       NO       │     NO     │     YES     │     NO     │      NO     │
└───────────────────┴────────────────┴────────────┴─────────────┴────────────┴─────────────┘
2018/01/06 16:55:51: Last Bid price USD-BTC: 16967 | Last Ask: 16970
2018/01/06 16:55:51: Balance USD: 370.88398
2018/01/06 16:55:51: Balance BTC: 0.016
2018/01/06 16:55:51: On Orders BTC: 0
Processing strategy tssl for USD-BTC on bitfinex
SELL CYCLE
2018/01/06 16:55:51: Entering sell cycle
Averaged bought price: 16513
┌───────────────────┬────────────────┬───────────┬───────────┬───────┬───────┬──────────┬─────────┐
│ XT Edition.       │ SMA            │ LowBB     │ HighBB    │ Last  │ BTC   │ Last Buy │ Pair    │
├───────────────────┼────────────────┼───────────┼───────────┼───────┼───────┼──────────┼─────────┤
│ Sell cycle        │ 16536.46000000 │ 16286.945 │ 16785.975 │ 16967 │ 0.016 │ 16513    │ USD-BTC │
└───────────────────┴────────────────┴───────────┴───────────┴───────┴───────┴──────────┴─────────┘
Original price: 16967
Original volume: 0.016
Rounded price: 16967
Rounded volume: 0.016
Sell opts: { symbol: 'BTCUSD',
  amount: '0.016',
  price: '16967',
  exchange: 'bitfinex',
  side: 'sell',
  type: 'exchange limit',
  is_hidden: false,
  is_postonly: false }
{ id: xxxxxxxxxx,
  cid: xxxxxxxxxxx,
  cid_date: '2018-01-06',
  gid: null,
  symbol: 'btcusd',
  exchange: 'bitfinex',
  price: '16967.0',
  avg_execution_price: '0.0',
  side: 'sell',
  type: 'exchange limit',
  timestamp: '1515257751.916878729',
  is_live: true,
  is_cancelled: false,
  is_hidden: false,
  oco_order: null,
  was_forced: false,
  original_amount: '0.016',
  remaining_amount: '0.016',
  executed_amount: '0.0',
  src: 'api',
  order_id: xxxxxxxxxx }
************************************************************************************************
Strategy tssl for USD-BTC on bitfinex -| Selling 0.016 of USD-BTC at rate 16967
************************************************************************************************

  my setting is as following:
        "tssl_my": {
            "NAME": "tssl",
            "BUY_LEVEL": 0.6,
            "GAIN": 1.5,
            "TRADING_LIMIT": 368,
            "FUNDS_RESERVE": 0.,
            "PERIOD": 15,
            "BUY_RANGE": 0.8,
            "SELL_RANGE": 1,
            "EMA1": 16,
            "EMA2": 8,
            "HIGH_BB": 35,
            "LOW_BB": 25,
            "STDV": 2,
            "SMAPERIOD": 50,
            "PANIC_SELL": false,
            "DOUBLE_UP": true,
            "DOUBLE_UP_CAP": 0.68,
            "DU_CAP_COUNT": 3,
            "DU_METHOD": "HIGHBB",
            "DU_BUYDOWN": 3,
            "RSI_BUY_ENABLED": false,
            "RSI_SELL_ENABLED": false,
            "RSI_BUY_LEVEL": 30,
            "RSI_SELL_LEVEL": 70,
            "TSSL_TARGET_ONLY": true,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "OKKIES_MODE": true,
            "BTC_MONEY_FLOW": 35,
            "MIN_VOLUME_TO_BUY": 30,
            "MIN_VOLUME_TO_SELL": 30,
            "TRADES_TIMEOUT": 300
        },

**Comment by chenh3** [comment]
In Version 7.0.2, I setup the "GAIN": 1.5 and "SELL_RANGE": 1, and found ALL of my trading benefit (more than 500 trades) are between 2.5% ~ 2.8%, even though the price of pair was up 20%. Is the result of tssl correct?

**Comment by BobWatson** [comment]
I have this exact issue - when the sell window is moved, I think it's being moved and immediately triggering the sell - i.e. price goes (for your settings) 100, 101.5 (triggers the tssl window to move), 102.5 (triggering the sell window to move to 102.5-1.03.5) - so now it matches and fires! Selling right before the rally.

**Comment by antoniojoaojr** [comment]
Trailling dont move when price is up in TSSL, its sell without moving tralling limits

**Comment by chenh3** [comment]
Does this bug fixes in V8.0.3?
