### ISSUE TITLE
[BUG] TSSL Selling

### ISSUE THREAD

**Issue by antoniojoaojr** [GuntharDeNiro/BTCT#403]
The sale in tssl is not being calculated, when the price rises too much it is selling in the upper limit and not increasing the trailing as it should, it did not accompany the price increase, it simply sold when it reached the upper limit.

Example:
![image](https://user-images.githubusercontent.com/1307333/34656612-9e74229e-f403-11e7-8e9a-486675e3e78b.png)

In the yellow mark, is the sold of the bot, but is wrong, the sold not be make in this point, this point is upper of trailling

**Comment by andremrtc** [comment]
same problem here

**Comment by andremrtc** [comment]
![tralling](https://user-images.githubusercontent.com/32331400/34718227-11080e46-f51d-11e7-93f5-b9af140a3013.png)

**Comment by antoniojoaojr** [comment]
The same problem happens during the purchase, instead of the window to watch the price drop, when it is inside the window, it simply makes the purchase, without descending the window as it should.
