### ISSUE TITLE
[BUG] Expired orders

### ISSUE THREAD

**Issue by Mtrade** [GuntharDeNiro/BTCT#404]
Orders placed can become expired (almost instantly) by the exchange but Gunbot still considers them open. As a result Gunbot remains in a "waiting for open orders" state for the pair and will not trade on that pair until restarted.
Occuring on binance as reported by various users but may be an issue on other exchanges as well.

**Comment by Mtrade** [comment]
An example, below is a log of this occurring as an order gets placed. Executed quantity is 0 and status is 'EXPIRED' but callback shows it as 'BOUGHT'. Subsequent callbacks in log then show 'waiting for open orders'.




2018/01/09 17:43:14: Last Bid price BTC-XLM: 0.00003931 | Last Ask: 0.00003932
2018/01/09 17:43:14: Balance BTC: 0.03687614
2018/01/09 17:43:14: Balance XLM: 0
2018/01/09 17:43:14: On Orders XLM: 0
Processing strategy tssl for BTC-XLM on binance
BUY CYCLE
2018/01/09 17:43:14: Entering buy cycle
product info: { minPrice: '0.00000001',
  maxPrice: '100000.00000000',
  minQty: '1.00000000',
  maxQty: '90000000.00000000',
  stepSize: '1.00000000',
  minNotional: '0.00200000' }
Original price: 0.00003932
Original volume: 508.64699898270595
Rounded price: 0.00003932
Rounded volume: 508
Order value: 0.019974560000000002
Buy Order Opts: { symbol: 'XLMBTC',
  side: 'BUY',
  type: 'LIMIT',
  timeInForce: 'IOC',
  quantity: 508,
  price: 0.00003932,
  timestamp: 1515537794094 }
{ symbol: 'XLMBTC',
  orderId: <__I removed this_>_,_
  clientOrderId: '<_I removed this_>',
  transactTime: 1515537794579,
  price: '0.00003932',
  origQty: '508.00000000',
  executedQty: '0.00000000',
  status: 'EXPIRED',
  timeInForce: 'IOC',
  type: 'LIMIT',
  side: 'BUY' }
┌───────────────────┬─────────────┬─────────────────────────┬─────────────────────────┬────────────┬────────────┬─────┬─────────┐
│ ɢƱҊβǾŦ XT Edition │ LowBB       │ HighBB                  │ Buy at                  │ Last       │ BTC        │ XLM │ Pair    │
├───────────────────┼─────────────┼─────────────────────────┼─────────────────────────┼────────────┼────────────┼─────┼─────────┤
│ Buy cycle         │ 0.00004036  │ 0.00004286              │ 0.000039713200000000005 │ 0.00003932 │ 0.03687614 │ 0   │ BTC-XLM │
├───────────────────┼─────────────┼─────────────────────────┼─────────────────────────┼────────────┼────────────┼─────┼─────────┤
│ Callbacks         │ Time to buy │ 0.000039713200000000005 │ BTC-XLM                 │            │            │     │         │
├───────────────────┼─────────────┼─────────────────────────┼─────────────────────────┼────────────┼────────────┴─────┴─────────┤
│ BOUGHT!!!         │ Amount:     │ 508.64699898            │ Rate:                   │ 0.00003932 │                            │

**Comment by seertenedos** [comment]
I can confirm it happens on bitfinex as well. Turning off "Cancel Orders" on the BOT config screen seems to stop the orders been cancelled right away and therefore fix the issue but it not really a viable solution to use.

**Comment by ddey94** [comment]
I can confirm this is happening on binance for me, Gunbot 7.0.2
But hey, I still made a few hundred USD profit in 4 days with GunBot, even with the missed opportunities! Great software! Looking forward to a fix for this issue!
