### ISSUE TITLE
[BUG] Double Up bug

### ISSUE THREAD

**Issue by lazyghost77** [GuntharDeNiro/BTCT#406]
On some of the pairs on which you enable Double Up the Gunbot stops working properly. Suddenly it's not using the trade limit defined in config(f.e. 0.002 BTC) but he thinks the new limit is the estimated value of your previous buy order. In the screenshot you can see ADA-BTC pair, and it was bought for 0.002 BTC and it's value has slipped down to 0.0014, and the Gunbot is trying buy for this estimated value.

![image](https://user-images.githubusercontent.com/25801048/34717798-f253ab02-f53c-11e7-84b7-8787cb952430.png)

**Comment by Nocoderdude** [comment]
As I've said at another bug posted by you, stop using bbrsistepgain, which is deprecated. Use bbstepgain and enable RSI. It's the same thing, but supported in the latest version. Many "bugs" may correct on their own.

**Comment by lazyghost77** [comment]
Dude! I already told you that is just a name of the strategy. Both RSI buy and sell is disabled!

**Comment by Nocoderdude** [comment]
I see you are using it on binance. Binance support was added in v7, the same time some strategies were deprecated. You could not have migrated it from v6. This strategy is there for legacy support. So stop configuring it like that and use a strategy that is supported in the latest version. As I've said, you may see many "bugs" resolve.

**Comment by lazyghost77** [comment]
Listen, you still don't understand how GB works. The name of the strategy doesn't change how it works. It is just a name, i can call it "catlitterrsistart" it will work exactly the same. The parameters within the strategy dictates what kind of buy and sell strats GB will use. And no.  I started using GB from 7.0.2 version and im using the template from 7.0.2 version(not from v6 or older) so there is no needless parameters in the config.

**Comment by GuntharDeNiro** [comment]
this is not a bug: this is exactly how DU works. Please refer to the wiki.
Thanks
