### ISSUE TITLE
[BUG] Bot don't work after a refresh of the pairs ...

### ISSUE THREAD

**Issue by Neewd** [GuntharDeNiro/BTCT#408]
Hello, 

I notice those last fays, since I am using the v7.0.2, when I refresh the config.js file with new pairs, or when I tweak few parameters on my configuration, the bot detect the changes, then relaunch the bot. 

<img width="718" alt="capture d ecran 2018-01-09 a 22 24 15" src="https://user-images.githubusercontent.com/2735205/34743987-007287e0-f58c-11e7-8144-781971217535.png">

But after that, the bot just won't work anymore, it's just rounding and cycling but he's doing nothing for trade, as you can see on the bot. 
I was thinking the problem was coming from my config.js file but even when I come back to my last config (same pairs as before when the bot was running) I got the same result. 

I trade on Bittrex, on a Raspberry Pi, with 5 pairs max, and with TSSL. 

If anyone could help I would be glad to hear an explanation :)

**Comment by GuntharDeNiro** [comment]
not reproducible
