### ISSUE TITLE
7.0.2 RSI undefined at Bittrex and Binance

### ISSUE THREAD

**Issue by Tonyrow** [GuntharDeNiro/BTCT#409]
RSI Undefined in 70-90% of requests at Bittrex and Binance. I am using RSI Sell as additional trigger assuming sell cannot be executed due to RSI Undefined. 
Please provide solution.

**Comment by lollerz46** [comment]
I have the same issue

**Comment by LetoAtre** [comment]
Running into the same problem. However, when i hit Apply Changes (without changing settings) when the bot is running the RSI is suddenly calculated and used.
