### ISSUE TITLE
RSI is undefined

### ISSUE THREAD

**Issue by Bruttagente** [GuntharDeNiro/BTCT#415]
I'm using bbstepgain with RSI confirmation for buy. But sometimes in the cycle I see for every pair: RSI is undefined. The bot can buy but show a red error:  "Gunbot XT says: RSI is undefined!!! Skipping this order"

**Comment by LetoAtre** [comment]
Running into the same problem. However, when i hit Apply Changes (without changing settings) when the bot is running the RSI is suddenly calculated and used.

**Comment by joemccann** [comment]
@Bruttagente @LetoAtre I found the solution

Increase your "bot_delay" until it starts properly calculating the RSI.  

I went from 1 -> 3 and it worked. Then I went to 1 -> 2, then it worked.  This is apparently "tuning" your bot but there is no documentation on it.  

Hope that helps.

**Comment by LetoAtre** [comment]
Thanks for the tip Joemccann but I have had my bot_delay at 5 and still have these issues. When I add a new coin to a strategy then the RSI for that coin is calculated but all other coins still get RSI undefined. Hitting apply changes works for a while but the messages start coming again in time. Kind of a dealbreaker now.
