### ISSUE TITLE
stop_limit creates sell orders at bought price instead of market price

### ISSUE THREAD

**Issue by acerolakirsche** [GuntharDeNiro/BTCT#42]
on polo:
as i can tell regarding the stop_limit is that the bot only creates sell-orders, that are not executet then. Then he waits on open orders.
The Bot tells in console at what rate he WANTS to sell.
BUT!, the stop-loss-sellprice then in open order at Polo is somethink completely different.
There the Sell-price is set at the original bought price.
Thats the reason, the order cant be executet.

![screen shot 2017-08-18 at 11 27 19](https://user-images.githubusercontent.com/30558780/29453017-872df9cc-8408-11e7-900b-a43127eef8d9.jpg)

![screen shot 2017-08-18 at 11 26 42](https://user-images.githubusercontent.com/30558780/29453034-931934fe-8408-11e7-8ea2-03d729e6194d.jpg)

**Comment by GuntharDeNiro** [comment]
aknowledged, fixing it in 4.0.6

**Comment by GuntharDeNiro** [comment]
fixed in v5
Thanks for reporting this!
