### ISSUE TITLE
Default config.js fault for binance BTC pair

### ISSUE THREAD

**Issue by snahsiub** [GuntharDeNiro/BTCT#421]
On the default config.js there is a pair "BTC-IOT" which generates on my end a 400 error when using the TV version:

Loading exchange - bittrex
Loading exchange - bitfinex
Loading exchange - binance
error: fetchMyTrades
Error: Response code 400

When you change 

		"binance": {
			"BTC-IOT": {
				"strategy": "emotionless",
				"override": {}
			}
		}

In for example

		"binance": {
			"BTC-BNB": {
				"strategy": "emotionless",
				"override": {}
			}
		}

It works and no longer the 400 error. I have no idea why this is.

**Comment by cryptowally** [comment]
This is because on Binance, there is no coin called "IOT".  The coin is called "IOTA".  The default config.js should be updated to have `BTC-IOTA` instead of `BTC-IOT`.
