### ISSUE TITLE
Still Getting EMA1 error with 4.0.5

### ISSUE THREAD

**Issue by SimpleSOS** [GuntharDeNiro/BTCT#44]
Aloha,

It's been an hour since you release 4.0.5.  I installed 4.0.5 fresh.  Only brought the config.js over from 4.0.4.

Running Poloniex. 

All pairs still Error EMA1

**Comment by fahrmairm** [comment]
+1
still get the error occasionally, maybe less than in 4.0.4, while running Poloniex. The error message has slightly changed. Now the error message seems empty:

2017/08/21 17:33:45: On Orders ETH: 0.00000000
Processing strategy BB for BTC_ETH on poloniex
Error on strategy BB for BTC_ETH on poloniex while getting ema1 -\ Error: 
2017/08/21 17:35:19: Kicking poloniex, receiving new tickers...
-------------------------------------------------------------------------

**Comment by BitFlipp3r** [comment]
confirmed with 4.0.5

`------------------------------------------------------------------------------------------------
 ɢՍͶβ๏Ł v4.0.5  Scanning poloniex for trading opportunities 2017/08/21 19:02:22
------------------------------------------------------------------------------------------------
 ɢՍͶƁ๏ͳ v4.0.5  Tips&Tricks: BTC_CLAM can be sold!!!
2017/08/21 19:02:27: There are some trading opportunities for BTC_CLAM at poloniex. Scanning Trade History
2017/08/21 19:02:27: Last Bid price BTC_CLAM: 0.001703 | Last Ask: 0.00171437
2017/08/21 19:02:27: Balance BTC: 0.08329323
2017/08/21 19:02:27: Balance CLAM: 0.00000000
2017/08/21 19:02:27: On Orders CLAM: 0.00000000
Processing strategy BB for BTC_CLAM on poloniex
Error on strategy BB for BTC_CLAM on poloniex while getting ema1 -\ Error:
------------------------------------------------------------------------------------------------
 ɢՍÑɃѺŦ v4.0.5  Scanning poloniex for trading opportunities 2017/08/21 19:02:28
------------------------------------------------------------------------------------------------
 ɢՍҊβøŦ v4.0.5  Tips&Tricks: BTC_ETH can be sold!!!
2017/08/21 19:05:22: There are some trading opportunities for BTC_ETH at poloniex. Scanning Trade History
2017/08/21 19:05:22: Last Bid price BTC_ETH: 0.08439999 | Last Ask: 0.0844369
2017/08/21 19:05:22: Balance BTC: 0.08329323
2017/08/21 19:05:22: Balance ETH: 0.00000000
2017/08/21 19:05:22: On Orders ETH: 0.00000000
Processing strategy BB for BTC_ETH on poloniex
Error on strategy BB for BTC_ETH on poloniex while getting ema1 -\ Error:
2017/08/21 19:06:45: Kicking poloniex, receiving new tickers...
------------------------------------------------------------------------------------------------
 ɢƱÑɮǾŁ v4.0.5  Scanning poloniex for trading opportunities 2017/08/21 19:06:46
------------------------------------------------------------------------------------------------
`

**Comment by fahrmairm** [comment]
after running a few hours now 4.0.5 I get the error on about 50% of "can be sold" and 100% of "can be bought" situations. Bot also has not bought anything for the last few hours even though opportunity
was there (There have been sells though of older stuff). Verbose mode does not reveal more details though

------------------------------------------------------------------------------------------------
 ɢƱͶß๏Ŧ v4.0.5  Scanning poloniex for trading opportunities 2017/08/21 20:08:30
------------------------------------------------------------------------------------------------
2017/08/21 20:08:30: BTC_ZEC Last Bid/Ask 0.06229211/0.06229212
2017/08/21 20:08:32: Got Trading History
2017/08/21 20:08:38: Price to buy: 0.059730702
2017/08/21 20:08:39: Got Open Orders
2017/08/21 20:08:39: Last Bid/Price to sell: 0.06229211/0.061348671
2017/08/21 20:08:39: Last Ask/Price to buy: 0.06229212/0.059730702
 ɢƱͶƁםŁ v4.0.5  Tips&Tricks: BTC_ZEC can be sold!!! 
2017/08/21 20:08:43: There are some trading opportunities for BTC_ZEC at poloniex. Scanning Trade History
2017/08/21 20:08:43: Last Bid price BTC_ZEC: 0.06229211 | Last Ask: 0.06229212
2017/08/21 20:08:43: Balance BTC: 0.24279690
2017/08/21 20:08:43: Balance ZEC: 0.00000000
2017/08/21 20:08:43: On Orders ZEC: 0.00000000
Processing strategy BB for BTC_ZEC on poloniex
Error on strategy BB for BTC_ZEC on poloniex while getting ema1 -\ Error: 
------------------------------------------------------------------------------------------------
 ɢՍÑßØŁ v4.0.5  Scanning poloniex for trading opportunities 2017/08/21 20:08:48
------------------------------------------------------------------------------------------------

**Comment by startef** [comment]
I can also still confirm the error right from the start with 4.0.5 currently on 100% of all possible occasions.

Processing strategy BB for BTC_XEM on poloniex
Error on strategy BB for BTC_XEM on poloniex while getting ema1 -\ Error:

**Comment by gsp-beta-admin** [comment]
+1

**Comment by fahrmairm** [comment]
I have copied the following lines from a 4.0.1 config file into the strategies/bb section of a 4.0.5 version of the config:

	"EMA1": 200,
	"EMA2": 50,

have not tested bittrex again, but on poloniex all ema- related errors seem to be gone afterwards. Maybe it is just a problem with missing default values

**Comment by SimpleSOS** [comment]
seems to be the case.

All EMA errors are gone after adding those 2 lines.

**Comment by utdrmac** [comment]
@SimpleSOS so can this be closed?

**Comment by GuntharDeNiro** [comment]
adding ema1 and ema2 values is the solution yet. I pushed the fix but forgot to update the default config.js,
THis issue can be closed.
