### ISSUE TITLE
Gunbot Bitfinex Issue

### ISSUE THREAD

**Issue by gunbot1234** [GuntharDeNiro/BTCT#445]
Hello please meybe someone can help.
When starting the bot i get the following error on Bitfinex (purchased 2 licences from gunbot.shop):
ON

Loading config...
Loading exchange - bitfinex

Errors

(node:4272) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 401
(node:4272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Bittrex is working fine...
What am i doing wrong?

**Comment by CiscoXL** [comment]
You need to set BOT_DELAY to 8
