### ISSUE TITLE
Error code at Bot Startup

### ISSUE THREAD

**Issue by kojak713** [GuntharDeNiro/BTCT#447]
Below is what I am seeing when I try to run the bot.  Firewall is configured to let 5000 in and out.

(node:1964) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [object Object]
(node:1964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Yoni2018** [comment]
Hi Guys,
Ive got the same issue on a new install using Binance.
I have configured the time and the ports and cleared DNS and everything i could think of.
When i start the bot i see blank black window and the error log say: 
(node:10668) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Response code 400
(node:10668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please help

**Comment by kojak713** [comment]
Same exact thing...

**Comment by creativefurniture** [comment]
I got the same error. First i got this error i changed the date&time settings everything was fine but now this error coming on my screen again.
