### ISSUE TITLE
Dashboard charts and trading stats causing hundreds of websock errors, freezing browser

### ISSUE THREAD

**Issue by monochromat13** [GuntharDeNiro/BTCT#457]
I am accessing Gunbot 8.0.3 on a Linux VPS from a remote IP address. When I try to load the main dashboard, the browser becomes unresponsive after a minute. I checked the console and noticed this error:

![screen shot 2018-01-26 at 5 23 18 pm](https://user-images.githubusercontent.com/34592700/35467001-5849410e-02be-11e8-9e8b-867fd05916f9.jpg)

Since I am accessing Gunbot from a remote IP and not localhost connection, I think it's generating hundreds of 404 errors... and no dashboard stats or charts.

**Comment by mjokic** [comment]
Same here. CPU usage on my machine goes crazy too.

**Comment by shaman79** [comment]
Same issue here. Any solution would be appreciated.

**Comment by shaman79** [comment]
Mine says something like "Cannot connect to ws://127.0.0.1:5497..."

**Comment by shaman79** [comment]
Figured it out. You have to set websocket address to the right one and open port on firewall. Anyway, the port is changing between restarts, so it would be nice to make it static and configurable.

**Comment by Syleron** [comment]
I have this problem as well.

**Comment by monochromat13** [comment]
I got this to work by setting a hostname in my websocket settings as well. But I agree, the port keeps changing which means it's not compatible with my firewall. Would be nice to choose a static port and just open that.

**Comment by mjokic** [comment]
I've managed to fixed it too by setting up hostname and allowing port in firewall.
Also i've noticed that port is random but in range 5000-6000, so enabling whole range in firewall make it work even on restarts.

Commands:
```
sudo ufw allow 4999:6001/tcp
sudo ufw allow 4999:6001/udp
```

Keep in mind to allow ssh too if you haven't already:
`sudo ufw allow <ssh port>`

**Comment by bhallouin** [comment]
@shaman79 @monochromat13 what do you mean by 
> setting a hostname in my websocket 

?

**Comment by dotpim** [comment]
Known issue. Fix is in development. Therefore closing the issue.
