### ISSUE TITLE
GunBot cannot make orders on Kraken

### ISSUE THREAD

**Issue by oeegor** [GuntharDeNiro/BTCT#46]
With default config and any tradeable pair:

```
Processing strategy BB for XXRPZEUR on kraken
Error on strategy BB for XXRPZEUR on kraken while buying -\ Error: General:Invalid arguments:volume
```

**Comment by GuntharDeNiro** [comment]
please specify the version you are running.
Thanks!

**Comment by oeegor** [comment]
Oh, I forgot, it's 4.0.5

**Comment by TheBitmap** [comment]
I too seem to be having the same (or very similar problem).  I purchased gunbot and kraken license yesterday, tried both 3.3.2 and 4.0.5.  On 4.0.5  I used bb strategy with default config (added ema lines).

I've had it running for over 24 hours, and no trades yet.  Trying to trade BTC against LTC, XMR, ETH, EOS, ETC, and others... no trades executed.   

No config errors, but it keeps saying "scanning kraken for trading opportunities" over and over.

**Comment by GuntharDeNiro** [comment]
ok i'll do some more tests on this. 
@TheBitmap your issue might be related to something else, please ping me on Telegram i will help.
Thanks!

**Comment by TheBitmap** [comment]
I reached out to you on Telegram Gunthar.  My user is also TheBitmap.  Thanks.

**Comment by TheBitmap** [comment]
Update:  I've had it Gunbot running for over 4 days straight, still no trades executed by GunBot.  I should have bought a Poloniex license instead....

**Comment by tocheto** [comment]
[config.js.txt](https://github.com/GuntharDeNiro/BTCT/files/1285996/config.js.txt)
I just spin up v 4.0.5 for polo and kraken, have error of missing ema1 value after a buy opportunity is found for Kraken. I have set the lines in the config file.
[gb405_kraken_log_sample.txt](https://github.com/GuntharDeNiro/BTCT/files/1285986/gb405_kraken_log_sample.txt)

**Comment by GuntharDeNiro** [comment]
feedback for this on v5 please?

**Comment by tocheto** [comment]
Working on v5! Thanks!
[krakenorderswork.txt](https://github.com/GuntharDeNiro/BTCT/files/1293881/krakenorderswork.txt)

**Comment by GuntharDeNiro** [comment]
ty! I'm closign this issue then
