### ISSUE TITLE
Performance: remove TradingView from Dashboard (8.0.3)

### ISSUE THREAD

**Issue by dotsoftware** [GuntharDeNiro/BTCT#461]
Please remove the TV info from the dashboard or make it optional. It uses so much memory that the website becomes laggy.

**Comment by imastud71** [comment]
I second that! Very laggy for me and I run on a good machine. The data is nice but the charts are unnecessary.

**Comment by pedroigp** [comment]
im having the same problem, linux VPS from contabo

**Comment by dotpim** [comment]
Fixed in the v9 GUI.
Dashboard charts are now built natively, we no longer rely on tradingview.
