### ISSUE TITLE
BTC/USD Money Flow Index is: Undefined

### ISSUE THREAD

**Issue by BigB117** [GuntharDeNiro/BTCT#465]
I'm running the bot currently on Kraken and I keep getting the "BTC/USD Money Flow Index is: Undefined" error. I'm also noticing that the bot isn't trading. Could the two be related? And more importantly, how do I get the Money Flow Index to be defined?

Thanks!

**Comment by franciscomaestre** [comment]
Same problem.

I reproduce this error with gunbo(7,8)t, gunbot-gui, zeno-gui (1.31,1.35) with any Kraken pair.

![screenshot of zeno gui - market bot](https://user-images.githubusercontent.com/2027043/35536978-de257720-0548-11e8-93c2-6793efd41593.png)

**Comment by crypt0troll** [comment]
i am getting this btc/usd undefined error also on kraken. Anyone got a solution?

**Comment by jsnx** [comment]
Same here on binance. It worked a while but from time to time this message does appear in the logs.

**Comment by CR030196** [comment]
I'm having the same problem on Kraken. A contact thought it might be because I had okkiees on but that didn't change anything

**Comment by Ghaazzz** [comment]
Same thing here!

**Comment by rehostclub** [comment]
I have this issue as well

**Comment by sp3sh** [comment]
same here for Bittrex

**Comment by Lifthrasyr** [comment]
I have the same problem on Kraken.

**Comment by BigB117** [comment]
Is it important that it is defined? Does the bot actually use that information for trades?

**Comment by halj77** [comment]
I am also receiving this message in the logs: BTC/USD Money Flow Index is: undefined

This is on Mac OS X 10.13.2, Bittrex as the exchange
