### ISSUE TITLE
having issues running gunbot for binance

### ISSUE THREAD

**Issue by satxbreadwallet** [GuntharDeNiro/BTCT#466]
hello
i keep getting the error in which the cmd window flashes closed.
the :5000 port window says the license is invalid

**Comment by sporty81** [comment]
I saw this issue myself. Was because I had the keys for Binance in the config twice, one of them was blank. Double check that you have the correct changes setup and delete any with blank keys.

**Comment by krusty45** [comment]
have you checked that you allow connection through your firewall I is in
your pc setting the wiki can show you if you need help
