### ISSUE TITLE
Error getting ema1 on Bittrex (v4.0.5)

### ISSUE THREAD

**Issue by rusca** [GuntharDeNiro/BTCT#47]
Hi,

I get the following error on Bittrex using the last version (4.0.5 Linux x64) on all pairs:

`Error on strategy BB for (PAIR HERE) on bittrex while getting ema1 -\ Error: Cannot read property '0' of null`

Thanks.

**Comment by MrG4dget** [comment]
Try adding ema values to the bb strategy section:

"EMA1": 200,
"EMA2": 50,

Should solve your issue

**Comment by GuntharDeNiro** [comment]
yes adding ema1 and ema2 as MrG4dget suggests is the solution. I'm closing this, feel free to reopen it if you still see the issue.
