### ISSUE TITLE
8.0 release not available for everyone?

### ISSUE THREAD

**Issue by stabenfeldt** [GuntharDeNiro/BTCT#474]
I received an email saying:
>  This upgrade is FREE for all current Six License Pack Gunbot Owners !
> Congrats ! YeY !

I ordered a *Bronze Pack* in December 2017.
Is this not entitled to an upgrade? What about the bugs in version 7? When will they be fixed? I noticed that quite a few of them was marked as resolved in version 8.

Please tell me that I'm mistaking. :-)

**Comment by cryptowally** [comment]
"Gunbot bronze" is not an official term of gunbot.  You should discuss with your reseller what this term is, as it's not part of the Gunbot branding, versioning or labeling.  Whatever "bronze" is, is something the reseller you bought Gunbot from has created on their own.  

Note: I do not speak for Gunbot myself, and I am only commenting as someone who has been around Gunbot for a while. I will mention that once a new release has been issued, such as "version 8", it is unlikely that any new bugfixes will come out for a previous version.   For example, when gunbot 4 was released, there were no more gunbot 3 fixes.  When gunbot 6 was released, there were no more gunbot 3, 4, or 5 releases.  

If you want the bug fixes and new features, you will likely need to move to version 8.

**Comment by stabenfeldt** [comment]
If I bought a license when version 7 was the latest, then I should be able to use that for version 8, should I not?

**Comment by cryptowally** [comment]
Yes, your version 7 license will work for version 8.  More specifically, all API keys that are licensed for version 7 should already be licensed for version 8.

**Comment by stabenfeldt** [comment]
Great, then it shows still work. :)

**Comment by stabenfeldt** [comment]
*.. Should still work.
