### ISSUE TITLE
Statitistics and TV charts view not working for all if multiple setups

### ISSUE THREAD

**Issue by mbb01** [GuntharDeNiro/BTCT#478]
Hi,

The statistics and tradeview charts on the dashboard don't work for all setups when having more than one running (i'm on 8.0.3). Let's say you have 4 running, the statistics and charts will only be shown on the setup that started the last. On the other setups the space where the statistics and TV chart would have been, stays empty.

Regards

**Comment by dotpim** [comment]
Known issue, is being fixed.
