### ISSUE TITLE
Gunthy GUI crash

### ISSUE THREAD

**Issue by Bruttagente** [GuntharDeNiro/BTCT#480]
After latest release update, my Gunthy GUI crashes. When I start it everything is ok, but after some times I cannot connect to it anymore returning me an "Unable to connect" error, although the bot is still working (I can see the gunthy-linx64 process). If I try to start the GUI again (without stopping the core) the log returns an "Empty logs" error.
Current Gunbot version : v8.0.3
Linux VPS

**Comment by dotpim** [comment]
Can you provide a bit more details?
When does this happen exactly, only when you are viewing the dashboard?

**Comment by Bruttagente** [comment]
It happens after some minutes I start the bot, 10-15 minutes. The core process is still running, but the GUI crashes and I cannot load the dashboard on localhost:5000 (and there is no gunthy-gui in process list). I'm running Ubuntu 16.04 x64 on Vultr VPS

**Comment by Bruttagente** [comment]
This is weird. I wanted to get back to previous gunbot version, reinstalled the server and with a fresh installation of the bot (without importing nothing) I still have this empty logs error

**Comment by NoPhaseNoKill** [comment]
I'm getting this exact same issue. Gunbot GUI looks to crash after 10-15 mins. On Linux AWS EC2 instance, all relevant ports are opened (3000, 5000-7000), am using nginx to externally face a port so that the GUI can be accessed. Ubuntu v16.04

**Comment by Bruttagente** [comment]
Ok, the GUI crashes as soon as I logout from the VPS console (using putty)
Anyway, I still have this empty logs error even with fresh OS and bot installation

**Comment by codepushr** [comment]
Same issue here.

**Comment by dotpim** [comment]
Fixed in the v9 GUI.
