### ISSUE TITLE
[BUG][8.0.3][7.0.2][Poloniex] Bot stops processing pairs

### ISSUE THREAD

**Issue by Nocoderdude** [GuntharDeNiro/BTCT#489]
After parsing a few pairs on Poloniex, the bot stops working. Confirmed on TSSL, EMOTIONLESS and BBSTEPGAIN. See attached image for output. I have always ran just 1 instance.

![capture2](https://user-images.githubusercontent.com/35117613/35783556-e5abeef2-0a11-11e8-80ac-cf220bebad7c.PNG)

I have tried every workaround there is:
- Increasing BOT_DELAY (up to 10)
- Changing my IP address
- Changing my API key.

However, older version 6.0.2 works fine. It stands to reason the culprit is a change that happened after version 6.0.2.

Further info: after running v602 for about half a day yesterday and half a day today, v803 suddenly works. Are there any other external services / servers / APIs Gunbot is reading, besides the exchange itself?

The same thing happened with v702 and the "cure" was the same: running v602 for a while.

**Comment by proiecteit** [comment]
I've encountered the same issue. Here are my details bellow:

- OS: Ubuntu 16.04.4 LTS / Kernel 4.4.0-116-generic
- Gunbot: 8.0.3 Lite. The same happens on 7.0.2 Lite
- Exchange: Poloniex
- Config file: https://gist.github.com/proiecteit/48c68798fee608bd27506c63a3093b83

If more details are required, please ask me.

**Comment by Nocoderdude** [comment]
After further testing, running the Windows build v6.0.2 works and fixes things. RPI build does not work.
