### ISSUE TITLE
Bitfinex EMA undefined if more than 5 pairs unless BOT_DELAY is 8

### ISSUE THREAD

**Issue by cryptowally** [GuntharDeNiro/BTCT#490]
Started up a Bitfinex instance with more than 5 pairs.  Randomly, some of the pairs will display undefined EMA1 and EMA2 values.  If I stop gunbot and restart, a different set of random pairs will have the undefined EMA1/2 values.

If I set a `BOT_DELAY` of 8, then there are no undefined values of EMA1 / EMA2.  This is a temporary workaround, but having this high of a bot delay seriously impacts ability of running through a decent number of coins in good amount of time.

I set debug mode to true and saw the following for the pairs that had the undefined EMA values:

```
------------------------------------------------------------------------------------------------
 ɢƱƝß๏Ŧ XT Edition  Scanning bitfinex for trading opportunities 2018/02/05 09:11:34
------------------------------------------------------------------------------------------------
2018/02/05 09:11:34: BTC-OMG Last Bid/Ask 0.00138710/0.00140040
Error: "Fetching OHLC data again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at <anonymous>
Error: "Fetching OHLC data again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at <anonymous>
Error: "Fetching OHLC data again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at <anonymous>
2018/02/05 09:11:35: Got Trading History
2018/02/05 09:11:35: Checking Open Orders
Last trade P/L for BTC-OMG was: 0.000 %
GBXT_v8.0.3 BTC-SAN Round # 1
------------------------------------------------------------------------------------------------
 ɢƱҊɃʘŦ XT Edition  Scanning bitfinex for trading opportunities 2018/02/05 09:11:37
------------------------------------------------------------------------------------------------
2018/02/05 09:11:37: BTC-SAN Last Bid/Ask 0.00020349/0.00020480
Error: "Fetching OHLC data again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at <anonymous>
Error: "Fetching OHLC data again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at <anonymous>
Error: "Fetching OHLC data again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at <anonymous>
2018/02/05 09:11:38: Got Trading History
2018/02/05 09:11:40: Checking Open Orders
Last trade P/L for BTC-SAN was: 0.000 %
GBXT_v8.0.3 BTC-EOS Round # 2
```

**Comment by kendoll30** [comment]
Hello,

I have the same problem on Kraken but the 8 seconds doesn't work.

2018/02/11 13:50:05: BTC-ETH Last Bid/Ask 0.10059000/0.10065000
Error: "Fetching balance again."
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
------------------------------------------------------------------------------------------------
EMA1: 0.10052517224289989 === EMA2: 0.10061736418320921
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
HIGH BB: 0.10082518 == SMA: 0.10011640 == LOW BB: 0.09940762
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
BTC/USD Money Flow Index is: undefined
------------------------------------------------------------------------------------------------
Error: "Fetching my trades again."
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: "Fetching open orders again."
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by cyrusmart** [comment]
if you have enabled debug mode, you will see this error, however, it should not treat as an error message, the error will normally display in "Errors" section.
