### ISSUE TITLE
Undefined Periods

### ISSUE THREAD

**Issue by CryptoM173** [GuntharDeNiro/BTCT#491]
I think the way time is defined on the exchanges differs between exchanges. On binance, 240 appears to be recognized as 4 hours, but bittrex throws errors on ANY period value over 30 which leads me to believe that 1 hour is defined as hour on their end rather than 60 minutes. Please also check to see how "DAY" is defined. Rather than 1440minutes, it may be likely that it is defined as 24 "hour" OR 1 "day". Unfortunately, as it stands, this means bittrex is only properly functioning on 1/5/15 minute periods.

Also, if someone can tell me how the periods are defined on each exchange for hour/day, I'd be happy to add a cheat sheet for all the exchanges in the wiki.

**Comment by shadowbladers** [comment]
Same issue here. Hope this gets fixed or a response from Gunthar.
