### ISSUE TITLE
[Bug] Telegram Bot always calculates P/L in BTC

### ISSUE THREAD

**Issue by jackywhlee** [GuntharDeNiro/BTCT#492]
At 2018/02/07 11:17:02
binance_eth says: SELLING ETH-IOTA at binance Rate: 0.00212817 - Amount: 239
Averaged bought price was: 0.002090295857740586
P/L for this trade is: 1.780%.
(This is about 65.00 USD)
ETH balance: 58.20184533
IOTA balance: 239

The bot is incorrectly calculating the P/L in BTC instead of ETH. All my pairs are using ETH pairs, even the telegram bot says  ETH balance, but it's calculating the 65 USD by:
0.002128 - 0.002090 = 0.009082
0.009082 * 7221 (BTC PRICE) = 65 USD (WRONG)
0.009082 * 724 (ETH PRICE) = 6.57 USD (CORRECT)

Please look into fixing this. I barely use BTC anymore and all my bot instances are running ETH as base pairs.

**Comment by Influence2** [comment]
I also noticed this. Same issue.

I also believe in the console even when your doing and ETH pair it says BTC profit on last trade, same goes with USDT trades.

**Comment by vorGrp** [comment]
While I don't consider this a bug, I do concur as a feature request that profits should be displayed in ETH for ETH pairs.

**Comment by Influence2** [comment]
It would be an enhancement if it didn't work for ETH, but since its statically coded for BTC its a bug.

**Comment by jackywhlee** [comment]
This is a bug. When someone tells you they made 100 usd profit when in fact it's 10 usd, it's a bug.
