### ISSUE TITLE
[BUG][8.0.3] Set BOUGHT_PRICE let bot sell with loss.

### ISSUE THREAD

**Issue by BeerK0in** [GuntharDeNiro/BTCT#495]
I have set the  `BOUGHT_PRICE` for Bittrex pairs using the emotionless strategy and with trades older than 30 days.
```json
"BTC-DGB": {"strategy": "emotionless","override": {"BOUGHT_PRICE": 0.00000772}},
```
After saving the config, GunBot sold the DGB at loss (looks like it could not read the `BOUGHT_PRICE`):
```
SELLING BTC-DGB at bittrex Rate: 0.00000399 - Amount: 1298.7012987
Averaged bought price was: 0
P/L for this trade is: 100.0%.
```
This has happened with all 5 pairs I have set the `BOUGHT_PRICE`. 

My emotionless settings:
```json
"emotionless": {
			"NAME": "emotionless",
			"TRADING_LIMIT": 0.0025,
			"FUNDS_RESERVE" : 0.5,
			"PERIOD": 15,
			"BUY_LEVEL": 0.9,
			"GAIN": 1.5,
			"EMA1": 16,
			"EMA2": 8,
			"HIGH_BB": 49,
			"LOW_BB": 49,
			"STDV": 2,
			"SMAPERIOD": 50,
			"PANIC_SELL": false,
			"DOUBLE_UP": false,
			"DOUBLE_UP_CAP": 1,
			"STOP_LIMIT": 80,
			"BUY_ENABLED": true,
			"SELL_ENABLED": true,
			"TA_ALWAYS_ON": false,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001,
			"TRADES_TIMEOUT": 300,
			"MICROTRADES" : true
		}
```

**Comment by adidonato** [comment]
The same just happened to me!

**Comment by ferninus** [comment]
I am having the problem that Bought Price is overriding the actual bought price on newly purchased coins.  This causes a sell at a loss.

**Comment by tulamidan** [comment]
Same happened to me. one coin was at -6% one at -11% and one at -46%
my safety net is at -60% atm
