### ISSUE TITLE
Unable to check master key.  Binance new API systeme

### ISSUE THREAD

**Issue by Thibault9238** [GuntharDeNiro/BTCT#497]
Hi, 
With the new API systeme on binance, the bot can't connect and is "unable to check master key".
Is this a well know issue ? 
is there a solution ?

**Comment by ddey94** [comment]
Binance is still down in some places in the world. They have servers across the globe some are up and some are down. Just wait. Mine said the same thing, just started working not too long ago.

**Comment by Thibault9238** [comment]
Yes you are right, It's working now. 
I'm closing this issue.
