### ISSUE TITLE
TradingView Ext. "Error on Strategy BB.... Error: "Fetching my Trades Again"

### ISSUE THREAD

**Issue by cre8ergb** [GuntharDeNiro/BTCT#500]
tradingview Bitfinex 8.0.3
"Error on Strategy BB for USD-BTC on bitfinix while getting trades -| .... Error: "Fetching my Trades Again"

ALSO Tried:
USDT-BTC
BTC-USD

BITFINEX doesn't have USDT only USD pairs
![bitfinex error strategy bb](https://user-images.githubusercontent.com/35176460/36078025-2c7d89f6-0f37-11e8-9898-1c1f503077ab.png)

**Comment by cristianm** [comment]
I have similar issue with Bitfinex:

GBXT_v8.0.3 BTC-LTC Round # 1
------------------------------------------------------------------------------------------------
 ɢՍΠɃʘŦ XT Edition  Scanning bitfinex for trading opportunities 2018/02/11 14:18:58
------------------------------------------------------------------------------------------------
2018/02/11 14:18:59: BTC-LTC Last Bid/Ask 0.01832500/0.01833900
Error: "Fetching balance again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
------------------------------------------------------------------------------------------------
EMA1: 0.01831673056780797 === EMA2: 0.01832116605418099
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
HIGH BB: 0.01836721 == SMA: 0.01832205 == LOW BB: 0.01827689
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
BTC/USD Money Flow Index is: 49.435161372263465
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
RSI: 50.56913096154278
------------------------------------------------------------------------------------------------
Error: "Fetching my trades again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: "Fetching open orders again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
GBXT_v8.0.3 BTC-LTC Round # 2
------------------------------------------------------------------------------------------------
 ɢƱΠßøͳ XT Edition  Scanning bitfinex for trading opportunities 2018/02/11 14:19:13
------------------------------------------------------------------------------------------------
2018/02/11 14:19:13: BTC-LTC Last Bid/Ask 0.01831900/0.01832900
Error: "Fetching balance again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
------------------------------------------------------------------------------------------------
EMA1: 0.01831673056780797 === EMA2: 0.01832116605418099
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
HIGH BB: 0.01836721 == SMA: 0.01832205 == LOW BB: 0.01827689
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
BTC/USD Money Flow Index is: 49.435161372263465
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
RSI: 50.56913096154278
------------------------------------------------------------------------------------------------
Error: "Fetching my trades again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: "Fetching open orders again."
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
Errors
Modify message
