### ISSUE TITLE
Error: Issue creating sell order

### ISSUE THREAD

**Issue by kendoll30** [GuntharDeNiro/BTCT#501]
Hello,

Gunbot doesn't sell on Kraken and pairs BTC-XRP and BTC-ETH

Check out the below screenshot. All settings are Emotionless default.

![error](https://user-images.githubusercontent.com/36370293/36090105-41810884-0fdf-11e8-958b-25df16132570.jpg)

**Comment by mbdash** [comment]
Got the same issue on Binance USDT-BTC

**Comment by davepro305** [comment]
Happend to me when buying on Binance. Changing buylimit to 0.002 solved it but now it's happening again when selling EOS-BTC. I had 1.98 EOS to sell and I'm stuck with 0.98 of dust but it should have sell the 1 (it worked manualy)
