### ISSUE TITLE
Gunbot 8.0 dont start

### ISSUE THREAD

**Issue by Apollopt** [GuntharDeNiro/BTCT#509]
Hello Guys,

Everytime i start gunbot using UI version it just keeps open a popup over and over and nothing else happen.
Did anyone had this issue already? How to solve it?

Thanks in advance.

**Comment by Apollopt** [comment]
I have checked the logs on the bottom part and it says cannot find master key... But i have only a single key for bittrex (key and secret). It it not enough?

**Comment by ferninus** [comment]
You need to make sure the single key you have is set to Master Key = True.  You can do this in the GUI by clicking edit next to the key record, or in the config.js by looking for the keys section and changing the line that says MASTER_KEY=False to True.

**Comment by ferninus** [comment]
Sorry wrong bot config rules, in Gunbot config.js
Make sure your key and secret are on the lines that say Master Key and Master Secret under the exchange name Bittrex.
