### ISSUE TITLE
Waiting to sell...Safety Switch is on...

### ISSUE THREAD

**Issue by Pedrolx** [GuntharDeNiro/BTCT#511]
Hello, 

I purchased the gunbot LT today and I am trying to set it up.
I managed to set it up on Kraken (or at least I believe so) with the currency pair ETH-EUR using the gunther GUI (gunthy), I set up my strategies.. 

But the bot has been running for hours now and after several hundred rounds I only get the above message (it doesn't trade it doesn't do anything): Waiting to sell...Safety Switch is on... 

I have changed the timeout trades option more times that I can think of too, even set it to zero, But it still does this non-end. 

Is there a way to solve this ???

**Comment by tt5oh** [comment]
Check under Bot settings timeout-buy, timeout-sell. From when you click start or change the strategy it will wait that period defined there before it will buy/sell. Read through the whole Wiki.

https://github.com/GuntharDeNiro/BTCT/wiki/Configuring-Gunbot
