### ISSUE TITLE
Dust causing incorrect average price - Selling for a loss

### ISSUE THREAD

**Issue by creamyyy** [GuntharDeNiro/BTCT#514]
There are 2 issues:
1. Dust is not being sold
2. Average bought price is not taking into consideration unit count

This case:
8th Jan 2018
VEN Bought price 0.00026913
VEN dust balance 0.993 (Can round this up to 1)

Gunbot:
26 Feb 2018
BUY 10 units of VEN at 0.00059879
Average bought price according to Gunbot: 0.0002898
Actual average bought price (rounding dust up) should be: 0.000568821

26 Feb 2018
SELL 10 units of VEN at 0.00059735 (didn't sell dust, this is also selling at a loss)
According to gunbot, profit is: 106%
Actual P/L: -0.241%

Average bought price needs to account for units held.

**Comment by miwi-fbsd** [comment]
which exchange?
