### ISSUE TITLE
Gunbot isn't buying. "Price to Buy:0" and "Price to Sell:0"

### ISSUE THREAD

**Issue by BigB117** [GuntharDeNiro/BTCT#517]
I'm running a StepgainTSSL strat on Poloniex v8.0.3. I'm noticing that Gunbot isn't actually calculating "price to buy" and "price to sell" for the USDT-BTC pair. I also notice that the bot isn't buying BTC when it can be! I'm running 2 pairs, and it trades USDT-ETC just fine.

What's going on?

**Comment by ferninus** [comment]
I am having the same issue.  Gunbot is not calculating Sell Price on Bittrex USDT pairs.  Will only calculate Buy Price on pairs with balance >0.  i.e.  BTC balance > 0 buy price is calculated, XVG balance = 0 no buy price is calculated.

**Comment by BigB117** [comment]
I was guided to the solution. Simply buy and sell a tiny position in whatever pair you're wanting to trade in so that your trading bot has a reference point to start from. A simple 0.001 BTC buy and sell transaction will do.

From what I'm told, this simple step is required for every fiat pair you're wanting to run. Transactions with BTC as base coin doesn't require this manual step.

Enjoy your trading!
