### ISSUE TITLE
API Key changed due to Binance HACK

### ISSUE THREAD

**Issue by fireblasterGB** [GuntharDeNiro/BTCT#522]
Hi my original API has been deleted by Binance. How do I go around having the new API assigned?

@RayRaiGB

**Comment by M0da** [comment]
add new api key on Binance then new key ( non master key ) on Gunbot

**Comment by fireblasterGB** [comment]
Hi MOda, just tried that and it says invalid license contact gunther

**Comment by M0da** [comment]
hey, you need to keep your Master Key from Gunther then add the new one from binance as a second key in Gunbot...

![image](https://user-images.githubusercontent.com/34057245/37175682-8e2605d8-231a-11e8-9c53-5920f818315a.png)

**Comment by fireblasterGB** [comment]
Yes I tried that and I get 
![capture](https://user-images.githubusercontent.com/35716283/37176242-a2258788-22d0-11e8-92f7-642979ffdaeb.JPG)

**Comment by fireblasterGB** [comment]
All good now, managed to get them changed via the reseller :)
