### ISSUE TITLE
8.0.3 Ask and Bid labels are reversed in USDT pairs on Bittrex.

### ISSUE THREAD

**Issue by ferninus** [GuntharDeNiro/BTCT#525]
I noticed on the dashboard page with my Bittrex USDT pairs that the ask and bid prices displayed are reversed.
![bittrex ask-bid](https://user-images.githubusercontent.com/3681823/37260842-c93b4020-2554-11e8-8548-fdf006e6a03e.JPG)
![gunthy ask-bid](https://user-images.githubusercontent.com/3681823/37260843-cd80374e-2554-11e8-92d2-4772d703db3b.JPG)

**Comment by dotpim** [comment]
Fixed in the v9 GUI.
