### ISSUE TITLE
Error message: Cannot read property '0' of null - version 4.0.5

### ISSUE THREAD

**Issue by vicdr** [GuntharDeNiro/BTCT#53]
"Error on strategy BB for BTC-XRP on bittrex while getting ema1 -\ Error: Cannot read property '0' of null"
Happens to all pairs...

**Comment by MrG4dget** [comment]
Try adding ema values to the bb strategy section:

"EMA1": 200,
"EMA2": 50,

Should solve your issue.

@Gunthar: maybe add this info the te release notes?

**Comment by MrG4dget** [comment]
Check out closed issue #47

**Comment by vicdr** [comment]
Thankyou for your assistance.
