### ISSUE TITLE
General Pure Stepgain Question

### ISSUE THREAD

**Issue by oldskoolnix** [GuntharDeNiro/BTCT#530]
From the manual page:

"You can decide to use one or more levels of step gains by using the following configs:
BUYLVL: 3, // buy level you want your gunbot to reach (example: i want my gunbot to buy when price reaches level 3)
SELLLVL: 3, // sell level you want your gunbot to reach (example: i want my gunbot to sell when price reaches level 3)"

Given:
BUYLVL:  1
BUYLVL1:  3
BUYLVL2:  5
BUYLVL3:  10

SELLLVL:  1
SELLLVL1:  3
SELLLVL3:  5
SELLLVL3:  10

How do I specify GB to utilize all levels?  e.g.  Start at BUYLVL1, but if trend is still downward, try BUYLVL2, if still downward trend, then BUYLVL3?  Get the best buylevel possible based on params?

Would I still set BUYLVL:1

Thank you

**Comment by criptonauta** [comment]
Correct. As per Gunthar's answer:

>  SELLVL is the starting point not the ending point

The same applies when buying, so BUYLVL:1 says to start at BUYLVL1 and try to reach BUYLVL3 if possible.
