### ISSUE TITLE
Unhandled 'error' event restarts safe switch 10-20 times a day

### ISSUE THREAD

**Issue by davepro305** [GuntharDeNiro/BTCT#531]
After getting this error, the "rounds" restarts to 1 again and the safe switch timer is on again like if it was the first start. The problem is that I get this error 10-20 times a day so if the safe switch is set to 10 minutes by default (I changed it to 1 minute), the bot is in "safe mode" 100 to 200 minutes a day!

Anyway to stop having this kind of error?

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)

**Comment by Cryptopia2018** [comment]
I have been getting the same error and about 20 times a day also??? Any help please!

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
