### ISSUE TITLE
Is gunbot buying when market is dropping?

### ISSUE THREAD

**Issue by davepro305** [GuntharDeNiro/BTCT#532]
I use bbstepgain with its default settings. The market was going down today for most coins. Gunbot bought a little bit of everything within 1 hour (12-15 different coins). I understand that it bought them at their lowest bb price at the moment but it was CLEAR that it was during a down tread. So it continued to go down as it was predictable and now it won't sell them (for now, I know). But my question is this : is the "tread watcher" also active before buying a coin like it is before selling? It makes no sense to only consider the "lowest price of the moment" and not check the previous price tendance and to buy a coin when it's clearely dropping. It should buy it at its lowest, after a drop and when it is begining to go up again, no?

**Comment by rakanalh** [comment]
hey @davepro305, did you figure it out? am interested in knowing the solution to this as well since am stuck with USDT-BTC because of a similar trade the bot did while BTC was dumping down.

**Comment by davepro305** [comment]
Sort of,
Stepgain is using buylvl1-2-3 to set goals to reach. They say that as long as the trend goes down, it won't buy and try to reach lower levels. But I still find that it buys quickly.

From gunbot wiki : "Stepgain is similar to gain, but here you set a minimum buy level below the lowest EMA at that moment, and a second, even lower buy level. Gunbot will buy when the price stops dropping after reaching the first buy level, or when it keeps dropping and reaches the second buy level."

**Comment by davepro305** [comment]
@rakanalh You should check the TSSL strategy. It works the way I think the bot should work. It will buy only after a drop, when the market is starting to go up again. 

https://github.com/GuntharDeNiro/BTCT/wiki/TSSL

The default settings were too sensitive and the bot was still buying a little fast. I'm still trying to tune it right but you should do your own backtesting with tradingview.

https://thecryptobot.com/2018/03/01/gunbot-backtesting-with-allansters-scripts/

Good luck!
