### ISSUE TITLE
Gunbot V9.4.3 ARM-Release with old GUI?

### ISSUE THREAD

**Issue by H256** [GuntharDeNiro/BTCT#536]
Is it correct that the ARM (arm.zip) version of V9.4.3 contains a GUI V1.2.3 instead of V2.0.1 ?

**Comment by enesg** [comment]
I also confirm that the ARM version contains the old GUI (version 1.2.3). Today I have also installed 9.4.3 build 516, but still have the same issue.

**Comment by H256** [comment]
Any info on this yet? I would really like to use the cool new GUI on my Raspberry PI wich I only bought for GB ;)

**Comment by GuntharDeNiro** [comment]
coming up v9.5.1 fixed this. Please feel free to close this issue as soon as you can confirm. Release is scheduled for tomorrow Monday 30 of April

**Comment by H256** [comment]
@GuntharDeNiro  thanks alot, it's fixed now! 👍
