### ISSUE TITLE
Missing average bought price - TV

### ISSUE THREAD

**Issue by yoshilee** [GuntharDeNiro/BTCT#538]
Hi guys,

when receiving an incoming sell alert for a coin it looks like that. Shouldn´t there be a value for average bought price?

![tv](https://user-images.githubusercontent.com/33607000/39203500-42c89d12-47f5-11e8-8db3-4542ff1d6d83.jpg)

**Comment by yoshilee** [comment]
Was that issue already adressed in 516 or coming up with next builds? 
After updating, i did not restart the bot yet (actual doing just TV trading).
Thanks!

**Comment by GuntharDeNiro** [comment]
coming up v9.5.1 fixed this. Please feel free to close this issue as soon as you can confirm. Release is scheduled for tomorrow Monday 30 of April

**Comment by yoshilee** [comment]
It seems working well now!
Thanks
