### ISSUE TITLE
V9.4.3 ERROR REPORT: connsec is not a function

### ISSUE THREAD

**Issue by duongngocmanh** [GuntharDeNiro/BTCT#539]
I have downloaded v9.4.3 but when I run it, it popped up the error: CONNSEC IS NOT A FUNCTION. I have tried on my vps and 2 of my home computer.
I dont know why. Pls help.

**Comment by kingdeatt** [comment]
It said: "You are using a not legit license. Or your license has been blocked"

**Comment by GuntharDeNiro** [comment]
Please contact @exquitas or @narkotix in telegram to solve this issue
