### ISSUE TITLE
Gunbot v9.4.3 (ARM): No working charts on GUI dashboard

### ISSUE THREAD

**Issue by enesg** [GuntharDeNiro/BTCT#540]
There is no chart displayed on the GUI dashboard. I had dit issue on v8.0.3 and still have it on v9.4.3 (build 514 + 516).

See below:
![screenshot](https://user-images.githubusercontent.com/9738996/39327044-1dc6d968-4997-11e8-94fe-6bdaf40f2b38.PNG)

**Comment by barneygumball18** [comment]
Same problem here. Have struck it before on previous versions. Need to do some live help, this program can be very erratic sometimes

**Comment by GuntharDeNiro** [comment]
coming up v9.5.1 fixed this. Please feel free to close this issue as soon as you can confirm. Release is scheduled for tomorrow Monday 30 of April

**Comment by enesg** [comment]
The issue is fixed now with release v9.5.1. Thanks for the quick service!
