### ISSUE TITLE
[CRITICAL] Price to buy and price to sell are reversed!

### ISSUE THREAD

**Issue by shaman79** [GuntharDeNiro/BTCT#541]
Hi, looking at the chart data in dashboard I just seen this:

  "priceToBuy": 0.00004534115796884705,
  "priceToSell": 0.00004377814486215539

This BTC-STR pair is traded by emotionless strategy. The numbers above are obviously switched. Is this a real issue or just chart data glitch?

**Comment by GuntharDeNiro** [comment]
they are not related to the same trade: price to buy is at actual market conditions, price to sell is based on your latest buy order.
