### ISSUE TITLE
Poloniex Timeout

### ISSUE THREAD

**Issue by BitFlipp3r** [GuntharDeNiro/BTCT#542]
```
FUCKTIMEOUT
We coudnt get ask/bid
Detected config changes...
Loading config...
Loading exchange - poloniex
Unable to connect to exchange. Please if this error persists, stop Gunbot, wait a few minutes and then start it again...
Loading config...
Loading exchange - poloniex
=== RECOMMENDED CURRENCIES TO TRADE ===

GBRT_v9.4.3 (Build 516) BTC-LSK Round # 1
------------------------------------------------------------------------------------------------
 ɢƱΠɃõŁ RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:19:20
------------------------------------------------------------------------------------------------
All good...keep calm and Gunbot.
GBRT_v9.4.3 (Build 516) BTC-LTC Round # 1
------------------------------------------------------------------------------------------------
 ɢՍÑ฿۝Ŧ RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:19:27
------------------------------------------------------------------------------------------------
FUCKTIMEOUT
FUCKTIMEOUT
FUCKTIMEOUT
GBRT_v9.4.3 (Build 516) BTC-XRP Round # 1
------------------------------------------------------------------------------------------------
 ɢՍҊɮ๏Ł RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:21:29
------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.4.3 (Build 516) BTC-BCH Round # 1
------------------------------------------------------------------------------------------------
 ɢƱÑß۝Ł RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:22:31
------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.4.3 (Build 516) BTC-BTS Round # 1
------------------------------------------------------------------------------------------------
 ɢƱΠƁѺͳ RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:23:33
------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.4.3 (Build 516) BTC-EMC2 Round # 1
------------------------------------------------------------------------------------------------
 ɢƱŋɃǾͳ RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:24:35
------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.4.3 (Build 516) BTC-ETH Round # 1
------------------------------------------------------------------------------------------------
 ɢՍͶβõŁ RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:25:37
------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.4.3 (Build 516) BTC-DASH Round # 1
------------------------------------------------------------------------------------------------
 ɢƱҊßøŦ RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:26:39
------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.4.3 (Build 516) BTC-XMR Round # 1
------------------------------------------------------------------------------------------------

```

I see this almost all the time with v9.x. Trading on poloniex with emotionless-strategy. v8 did not have this issue.

With debug enabled the massage is as follows:

```
 ZRX: { available: 0, onOrders: 0 } }
Awesome level 2 is working!!!
FUCKTIMEOUT
Error: FUCKTIMEOUT
    at errorHandler (/snapshot/v943_516/ctx-wrapper.js:0:0)
    at <anonymous>
GBRT_v9.4.3 (Build 516) BTC-XRP Round # 1
------------------------------------------------------------------------------------------------
 ɢƱΠɮ๏ͳ RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:37:34
------------------------------------------------------------------------------------------------
Awesome level 1 is working!!!

```

```
 ZRX: { available: 0, onOrders: 0 } }
Awesome level 2 is working!!!
Awesome level 4 is working!!!
FUCKTIMEOUT
Error: FUCKTIMEOUT
    at errorHandler (/snapshot/v943_516/ctx-wrapper.js:0:0)
    at <anonymous>
FUCKTIMEOUT
Error: FUCKTIMEOUT
    at errorHandler (/snapshot/v943_516/ctx-wrapper.js:0:0)
    at <anonymous>
GBRT_v9.4.3 (Build 516) BTC-LTC Round # 1
------------------------------------------------------------------------------------------------
 ɢՍΠβ๏ͳ RT Edition  Scanning poloniex for trading opportunities 2018/04/27 16:33:42
------------------------------------------------------------------------------------------------

```

**Comment by BitFlipp3r** [comment]
Using ./gunthy-linux64.

**Comment by BitFlipp3r** [comment]
Increasing BOT_DELAY does not prevent the timeout. I tried up to 30, which makes the cycles quite long already, but there is still 80% timeout.

**Comment by Pedrolx** [comment]
I have a similar issue . This version seems a lot heavier than the previous one.

**Comment by BitFlipp3r** [comment]
Same with v9.5.1
Bot has been down for more than 5 min during update. Timeout right after restart:

``

[bitflip@sirius lin]$ ./gunthy-linx64
Loading config...
Loading exchange - poloniex
GBRT_v9.5.1 (Build 531) BTC-LSK Round # 1
------------------------------------------------------------------------------------------------                                                                       ɢƱΠß๏Ŧ RT Edition  Scanning poloniex for trading opportunities 2018/04/30 21:18:12------------------------------------------------------------------------------------------------                                                                      FUCKTIMEOUT                                                                        We coudnt get ask/bid
GBRT_v9.5.1 (Build 531) BTC-LTC Round # 1                                          ------------------------------------------------------------------------------------------------
 ɢՍҊßØŦ RT Edition  Scanning poloniex for trading opportunities 2018/04/30 21:19:14------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.5.1 (Build 531) BTC-XRP Round # 1
------------------------------------------------------------------------------------------------
 ɢՍͶɮøͳ RT Edition  Scanning poloniex for trading opportunities 2018/04/30 21:20:16------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.5.1 (Build 531) BTC-BCH Round # 1
------------------------------------------------------------------------------------------------
 ɢՍͶβםŁ RT Edition  Scanning poloniex for trading opportunities 2018/04/30 21:21:18------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.5.1 (Build 531) BTC-BTS Round # 1
------------------------------------------------------------------------------------------------
 ɢՍƝßøŁ RT Edition  Scanning poloniex for trading opportunities 2018/04/30 21:22:20------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.5.1 (Build 531) BTC-EMC2 Round # 1
------------------------------------------------------------------------------------------------
 ɢՍƝɃ๏Ŧ RT Edition  Scanning poloniex for trading opportunities 2018/04/30 21:23:22------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.5.1 (Build 531) BTC-ETH Round # 1
------------------------------------------------------------------------------------------------
 ɢƱŋβõŁ RT Edition  Scanning poloniex for trading opportunities 2018/04/30 21:24:25------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
GBRT_v9.5.1 (Build 531) BTC-DASH Round # 1
------------------------------------------------------------------------------------------------
 ɢƱŋɃõŁ RT Edition  Scanning poloniex for trading opportunities 2018/04/30 21:25:27------------------------------------------------------------------------------------------------
FUCKTIMEOUT
We coudnt get ask/bid
``

**Comment by datadecipher** [comment]
Is my issue #553 same as this?

**Comment by Zeroccool** [comment]
Same issue. Is there an solution?

**Comment by ruphu5** [comment]
Same issue here.

**Comment by karenmkrohn** [comment]
Hi- were you able to figure out what was wrong?  I am seeing something similar.  https://pastebin.com/9TrSFHTx

**Comment by BitFlipp3r** [comment]
Seems to be resolved. Maybe Polo changed its api restrictions.

**Comment by geobray** [comment]
My GB (both gunthy-gui and gunthy-linx64) in TradingView mode is working just fine on poloniex for BUY and SELL orders, but is giving this FUCKTIMEOUT error on LONG/SHORT.

2018/07/10 01:08:50 Checking for new emails ɢՍƝß۝Ŧ v9.5.1 (Build 532) TRADINGVIEW Edition
2018/07/10 01:08:50 Done
emailParsed { timestamp: 1531148930579,
  type: 'long',
  exchange: 'poloniex',
  pair: 'BTC-ETH' }
2018/07/10 01:08:50 Done fetching all messages!

2018/07/10 01:08:51: Received a MARGIN-BUY order...
0.013963249007876249
0.07161657
BTC-ETH
[ { timestamp: 1531148930581,
    type: 'long',
    exchange: 'poloniex',
    pair: 'BTC-ETH' } ]
...

[ { timestamp: 1531148930581,
    type: 'long',
    exchange: 'poloniex',
    pair: 'BTC-ETH' } ]
Error: FUCKTIMEOUT
    at errorHandler (/snapshot/v951_528/ctx-wrapper.js:0:0)
    at <anonymous>
undefined

2018/07/10 01:24:12: Received a MARGIN-BUY order...
0.013968700611912898
0.07158862
BTC-ETH
(node:21915) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: undefined is not a function
(node:21915) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Tried BOT_DELAY values of 10,30, 300, 900 with no change.

**Comment by campinzon** [comment]
Gunthar, I have the same problem, do you have any progress in solving this issue?
