### ISSUE TITLE
[GBRT-v9.4.3-b516] Incorrect Profit / Loss calculation on telegram notifications with DU enabled and used.

### ISSUE THREAD

**Issue by imatimba** [GuntharDeNiro/BTCT#544]
First of all telegram notifications improved a lot with the release of v9, so thanks for that.  
But there is a problem with the calculation of the profit if the pair was bought several times because of DU.  
It only shows the profit of the base TRADING_LIMIT you set, not of the total amount you have.  
For example:  

Buys:

> At 2018/04/24 21:34:09 Gunbot says: BUYING BTC-GNT at bittrex- Rate: 0.00006516 - Amount: 38.3670963781461
> BTC balance: 0.3699473
> GNT balance: 0
> Check this trade chart here https://www.tradingview.com/chart/?symbol=bittrex:GNTBTC
> (GBRT-v9.4.3-b514)

> At 2018/04/25 01:29:20 Gunbot says: AVERAGING DOWN BTC-GNT at bittrex Rate: 0.00006166 - Amount: 30.93102382
> Previous Averaged bought price was: 0.0000654765664160401
> This is the DU attempt number 1 of 3
> BTC balance: 0.3503832
> GNT balance: 30.93102382
> Check this trade chart here https://www.tradingview.com/chart/?symbol=bittrex:GNTBTC
> (GBRT-v9.4.3-b514)

> At 2018/04/25 12:04:50 Gunbot says: AVERAGING DOWN BTC-GNT at bittrex Rate: 0.00005855 - Amount: 61.86204764
> Previous Averaged bought price was: 0.00006371779448621555
> This is the DU attempt number 2 of 3
> BTC balance: 0.31744374
> GNT balance: 61.86204764
> Check this trade chart here https://www.tradingview.com/chart/?symbol=bittrex:GNTBTC
> (GBRT-v9.4.3-b514)

Sell:

> At 2018/04/26 00:07:24
> Gunbot says: SELLING BTC-GNT at bittrex Rate: 0.00006327 - Amount: 123.72409528
> Averaged bought price was: 0.00006128
> P/L is about : 0.00007880 BTC (3.152%).
> (This is about 0.6926 USD)
> BTC balance: 0.31702437
> GNT balance: 123.72409528
> Check this trade chart here https://www.tradingview.com/chart/?symbol=bittrex:GNTBTC
> (GBRT-v9.4.3-b516)

The profit would be:  
(123.72 x 0.00006327) - (123.72 x 0.00006128) = 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0.00782776 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 0.00758156 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; = 0.00024620  

So, about 3 times the profit in satoshis compared to what it says in the notification, because it bought a few times doing DU.

**Comment by GuntharDeNiro** [comment]
coming up v9.5.1 fixed this. Please feel free to close this issue as soon as you can confirm. Release is scheduled for tomorrow Monday 30 of April

**Comment by imatimba** [comment]
Hey thanks @GuntharDeNiro, I've been testing the new version and indeed the BTC profit is fixed.  
But for the USD estimate is still using TRADING_LIMIT to calculate.  

> At 2018/05/01 08:55:53
> Gunbot1 says: SELLING BTC-ADA at bittrex Rate: 0.00003918 - Amount: 129.53367874
> Averaged bought price was: 0.00003757
> P/L is about : 0.0002089 BTC (4.116%).
> (This is about 0.9314 USD)
> BTC balance: 0.24259938
> ADA balance: 129.53367874
> Check this trade chart here https://www.tradingview.com/chart/?symbol=bittrex:ADABTC
> (GBRT-v9.5.1-b531)

It did 2 buys on ADA and the BTC profit is correct but the USD estimate should be close to 2 USD
