### ISSUE TITLE
TrailMe! Price to Buyundefined

### ISSUE THREAD

**Issue by shaman79** [GuntharDeNiro/BTCT#545]
I am getting this error message in logs when using TSSL on Polo.

TrailMe! Price to Buyundefined

**Comment by GuntharDeNiro** [comment]
coming up v9.5.1 fixed this. Please feel free to close this issue as soon as you can confirm. Release is scheduled for tomorrow Monday 30 of April

**Comment by shaman79** [comment]
In GBRT_v9.5.1 (Build 531) the problem still persists.

**Comment by j33zy** [comment]
Still got this error with newest release (GBRT-v9.5.1-b532)

**Comment by bpeterz** [comment]
I have this issue too (build 532)

**Comment by cor1988** [comment]
Same issue over here. 
Binance: BBSTEPGAIN with RT enabled % Trail_me_RT enabled.
