### ISSUE TITLE
TV plugin: if no balance for buy order, buy order does not terminate & prevents other buy orders

### ISSUE THREAD

**Issue by mx3214** [GuntharDeNiro/BTCT#546]
Essentially: 
-when a buy alert is sent, and that currency is not available (eg no USDT in my account (because all it of it has been used in positions), -the buy alert with the non-present currency keeps recurring & does not terminate (as RETRY_TV ORDER set to true)
 -this prevents subsequent buy orders where there is available currency being executed (I can send you log if required)

This does not happen with sell orders ie if there is not enough balance for a sell order, that terminates straight away, even with RETRY_TV_order set to true

`2018/04/29 15:15:04 Checking for new emails ɢՍƝƁםŦ v9.4.3 (Build 514) TRADINGVIEW Edition 
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' } ]
2018/04/29 15:15:04: Checking prices...
2018/04/29 15:15:04 Done
emailParsed { timestamp: 1525011304273,
  type: 'buy',
  exchange: 'binance',
  pair: 'USDT-BTC' }
2018/04/29 15:15:04 Done fetching all messages!
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' },
  { timestamp: 1525011304274,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-BTC' } ]
2018/04/29 15:15:04: Received a BUY order...
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' },
  { timestamp: 1525011304274,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-BTC' } ]
product info: { minPrice: '0.00000001',
  maxPrice: '100000.00000000',
  minQty: '1.00000000',
  maxQty: '90000000.00000000',
  stepSize: '1.00000000',
  minNotional: '0.01000000' }
Original price: 0.00125533
Original volume: 8762.636119586085
price decimal place: 8
volume decimal place: 0
Rounded price: 0.00125533
Rounded volume: 8763
Order value: 11.00045679
Buy Order Opts: { symbol: 'XRPETH',
  side: 'BUY',
  type: 'MARKET',
  quantity: 8763,
  timestamp: 1525011305713 }
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' },
  { timestamp: 1525011304274,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-BTC' } ]
2018/04/29 15:15:05 Checking for new emails ɢƱƝβ۝Ł v9.4.3 (Build 514) TRADINGVIEW Edition 
Nothing to fetch
Error: "Error: Response code 400{\"code\":-2010,\"msg\":\"Account has insufficient balance for requested action.\"}"
    at errorHandler (C:\snapshot\v943_514\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
undefined
undefined
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' },
  { timestamp: 1525011304274,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-BTC' } ]
2018/04/29 15:15:06: Looking for pending orders...
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' },
  { timestamp: 1525011304274,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-BTC' } ]
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' },
  { timestamp: 1525011304274,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-BTC' } ]
2018/04/29 15:15:07 Checking for new emails ɢƱŋɃѺŁ v9.4.3 (Build 514) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' },
  { timestamp: 1525011304274,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-BTC' } ]
2018/04/29 15:15:07: Checking prices...
[ { timestamp: 1525011256098,
    type: 'buy',
    exchange: 'binance',
    pair: 'ETH-XRP' },
  { timestamp: 1525011304274,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-BTC' } ]`

I thought this could be solved if I set RETRY_TV ORDER to false, and the buy order with the insufficient currency does terminate with a message like INSUFFICIENT_FUNDS, depending on the exchange, but 
-if two alerts occur within 1 min of each, eg BUY_BITTREX_ETH-XRP first & then BUY_BITTREX_USDT-BTC (and  for example I don’t have ETH in my balance, but I do have USDT) 
-GB will try to place the ETH XRP order, then eventually say insufficient funds, and then BOTH the ETH-XRP, and USDT-BTC orders will be cancelled.

`2018/04/29 16:36:45 Checking for new emails ɢՍΠßõŁ v9.4.3 (Build 516) TRADINGVIEW Edition 
2018/04/29 16:36:45 Done
2018/04/29 16:36:45 Done
emailParsed { timestamp: 1525016205882,
  type: 'buy',
  exchange: 'bittrex',
  pair: 'ETH-XRP' }
emailParsed { timestamp: 1525016205882,
  type: 'buy',
  exchange: 'bittrex',
  pair: 'USDT-BTC' }
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' } ]
2018/04/29 16:36:45: Looking for pending orders...
2018/04/29 16:36:46 Done fetching all messages!
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' } ]
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' } ]
2018/04/29 16:36:46: Checking prices...
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' } ]
2018/04/29 16:36:46: Received a BUY order...
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' } ]
2018/04/29 16:36:47 Checking for new emails ɢՍͶß๏Ł v9.4.3 (Build 516) TRADINGVIEW Edition 
2018/04/29 16:36:47 Done
2018/04/29 16:36:47 Done
emailParsed { timestamp: 1525016207880,
  type: 'buy',
  exchange: 'bittrex',
  pair: 'USDT-BTC' }
emailParsed { timestamp: 1525016207880,
  type: 'buy',
  exchange: 'bittrex',
  pair: 'ETH-XRP' }
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:36:48 Done fetching all messages!
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:36:49 Checking for new emails ɢՍÑƁ۝Ŧ v9.4.3 (Build 516) TRADINGVIEW Edition 
2018/04/29 16:36:49 Done
emailParsed { timestamp: 1525016209894,
  type: 'buy',
  exchange: 'bittrex',
  pair: 'ETH-XRP' }
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:36:50 Done fetching all messages!
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:36:51 Checking for new emails ɢՍΠƁøŁ v9.4.3 (Build 516) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:36:53 Checking for new emails ɢƱŋɃØŁ v9.4.3 (Build 516) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:36:55 Checking for new emails ɢՍͶ฿ѺŦ v9.4.3 (Build 516) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:36:57 Checking for new emails ɢƱͶßѺͳ v9.4.3 (Build 516) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:36:59 Checking for new emails ɢՍƝɃøͳ v9.4.3 (Build 516) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
[ { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016205882,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'USDT-BTC' },
  { timestamp: 1525016207880,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' },
  { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:37:01 Checking for new emails ɢƱÑɃøŁ v9.4.3 (Build 516) TRADINGVIEW Edition 
Nothing to fetch
Error: "Fetching balance again."
    at errorHandler (C:\snapshot\v943_516\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
undefined
[ { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:37:01: Looking for pending orders...
[ { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
[ { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:37:02: Checking prices...
[ { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:37:02: Received a BUY order...
[ { timestamp: 1525016209895,
    type: 'buy',
    exchange: 'bittrex',
    pair: 'ETH-XRP' } ]
2018/04/29 16:37:03 Checking for new emails ɢƱҊßםŦ v9.4.3 (Build 516) TRADINGVIEW Edition 
Nothing to fetch
Error: {"success":false,"message":"INSUFFICIENT_FUNDS","result":null}
    at errorHandler (C:\snapshot\v943_516\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
undefined
undefined
2018/04/29 16:37:05 Checking for new emails ɢՍÑßǾŦ v9.4.3 (Build 516) TRADINGVIEW Edition 
Nothing to fetch`

**Comment by phatwila** [comment]
Looks like i'm having a similar issue too, any workarounds for this?

018/08/01 14:01:34 Checking for new emails ɢƱŋɃ๏Ł v9.5.1 (Build 532) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
2018/08/01 14:01:34: Looking for pending orders...
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
2018/08/01 14:01:36: Checking prices...
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
2018/08/01 14:01:36: Received a BUY order...
2018/08/01 14:01:36 Checking for new emails ɢՍҊβ۝Ŧ v9.5.1 (Build 532) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
product info: { minPrice: '0.72360000',
  maxPrice: '72.35900000',
  minQty: '0.01000000',
  maxQty: '10000000.00000000',
  stepSize: '0.01000000',
  minNotional: '10.00000000' }
Original price: 7.2242
Original volume: 692.1181584120042
price decimal place: 4
volume decimal place: 2
Rounded price: 7.2242
Rounded volume: 692.12
Order value: 5000.013304
Buy Order Opts: { symbol: 'EOSUSDT',
  side: 'BUY',
  type: 'MARKET',
  quantity: 692.12,
  timestamp: 1533146496911 }
Error: "Error: Response code 400{\"code\":-2010,\"msg\":\"Account has insufficient balance for requested action.\"}"
    at errorHandler (/snapshot/v951_528/ctx-wrapper.js:0:0)
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)
undefined
undefined
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
2018/08/01 14:01:37: Looking for pending orders...
2018/08/01 14:01:38 Checking for new emails ɢՍÑ฿õŁ v9.5.1 (Build 532) TRADINGVIEW Edition 
Nothing to fetch
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
[ { timestamp: 1533146476605,
    type: 'buy',
    exchange: 'binance',
    pair: 'USDT-EOS' } ]
2018/08/01 14:01:39: Checking prices...
