### ISSUE TITLE
Binance memory issues

### ISSUE THREAD

**Issue by Pedrolx** [GuntharDeNiro/BTCT#547]
ver 9.4.3 seems a lot heavier than the previous version. Binance for instance seems to get stuck a lot on 'loading config file' and keeps repeating this message, completely eating up the CPU memory.

Also after a while of letting the bot run, there seems to be a huge delay (of several hours) between what the bot is computing and actual trading chart (meaing the bot will say that the time is say 07:30 when time is 10:30) and I've lost a few sells because of this.

Poloniex has become impossible to use.

**Comment by GuntharDeNiro** [comment]
The charts are up to date to UTC and always sync with exchange. I've assigned this issue to our GUI devs so they can enlighten us. Feedback wanted please

**Comment by gaud13** [comment]
a good start may be to eliminate all the download from "suggested pairs" when we have that option turned off. i ran in debug mode for a bit and noticed there is no way to stop the bot from trying to get all that info on every cycle even though i have it turned off.
