### ISSUE TITLE
GB 9.4.3 mac memory issue. Bitfinex

### ISSUE THREAD

**Issue by Tungsten183** [GuntharDeNiro/BTCT#548]
Hi

when I keep running GB on my mac it keeps choking the system. When I add up all the memory on Activity Monitor it usually doesn't show more then 1 GB but when I shut down GB it frees up 5GB of my RAM. 
Is there a fix for this? 

Thx

**Comment by GuntharDeNiro** [comment]
Please update to latest and feel free to reopen this if you experience the same issue.
