### ISSUE TITLE
4.0.5 Watch mode still buy

### ISSUE THREAD

**Issue by OnlyC** [GuntharDeNiro/BTCT#55]
"WATCH_MODE": true, in my config.js but GB still buying.

**Comment by jadiesel** [comment]
You should also set "BUY_ENABLED": false

**Comment by GuntharDeNiro** [comment]
acknowledged
Thanks!

**Comment by smportis** [comment]
What does Watch Mode do?

**Comment by GuntharDeNiro** [comment]
Fixed in v5
Thanks for reporting this
