### ISSUE TITLE
bug binance SMA cross off

### ISSUE THREAD

**Issue by brad486** [GuntharDeNiro/BTCT#552]
I have been using the tradingview plugin for a couple months on binance. Using fast and slow sma settings. With a few minor problems.

** I have found that the "SMA cross" is way off and buying random. Please fix. 

Great bot

**Comment by GuntharDeNiro** [comment]
Gunbot executes the alert from Tradingview plugin, doesnt control the sma cross. I think something is to be fixed on your tv script?
