### ISSUE TITLE
Error: [Poloniex] - Status Code 422 in some pairs

### ISSUE THREAD

**Issue by datadecipher** [GuntharDeNiro/BTCT#553]
Hi,

I am getting status code 422 error in callback for some pairs on Poloniex.

I tried finding solution here but couldn't fix it. Also, changed API key twice but no help. Any solution to this?

Note - Using Gunbot for 1 year now and running on same exchange successfully.

**Comment by datadecipher** [comment]
One pattern that I noticed - The Status code 422 is only coming in those pairs that are bought.

**Comment by GuntharDeNiro** [comment]
Send me your config.js please, this is a support request, waiting for you on telegram not on a bug tracker.
Thanks
