### ISSUE TITLE
RT selling works ; RT buying is not ; Bittrex with version v9.5.1 RT - Build 532

### ISSUE THREAD

**Issue by Majestic81** [GuntharDeNiro/BTCT#560]
1.RT selling works ; RT buying is not ; Bittrex with version v9.5.1 RT - Build 532 [ISSUE]
2.RT sold with WATCHMODE ON [ISSUE]

I've added the statusbar overview, RT sell history and RT settings as screenshots.

Hope this helps ; as more people on the Discords have the same issue as me.
PS : I don't want to sell, I just want to use the RT strategy to accumulate coin during the down trends.

![btcdoge rt stats 1](https://user-images.githubusercontent.com/38986848/39648309-1ba34224-4fe2-11e8-8bfd-3b67e4b17f92.PNG)
![btcdoge rt stats 2](https://user-images.githubusercontent.com/38986848/39648310-1bba37f4-4fe2-11e8-8a04-8fa5f99f2996.PNG)
![btcdoge rt stats 3](https://user-images.githubusercontent.com/38986848/39648312-1bd3df38-4fe2-11e8-9b32-ae7f7ab4abbd.PNG)
![btcdoge rt stats 4](https://user-images.githubusercontent.com/38986848/39648313-1bec613e-4fe2-11e8-9b52-b1f4d85de037.PNG)
![btcdoge rt stats 5](https://user-images.githubusercontent.com/38986848/39648315-1c073d10-4fe2-11e8-95b2-0c824eba19c1.PNG)
![ethxrp rt stats 1](https://user-images.githubusercontent.com/38986848/39648316-1c1d5ef6-4fe2-11e8-9887-f495b5191524.PNG)
![ethxrp rt stats 2](https://user-images.githubusercontent.com/38986848/39648317-1c47af26-4fe2-11e8-9574-fb6ba41cc51f.PNG)

**Comment by GuntharDeNiro** [comment]
The RT_BUY is a sell: you have sell disabled
