### ISSUE TITLE
Gunbot-gui: the color in the log messages are stripped out

### ISSUE THREAD

**Issue by enesg** [GuntharDeNiro/BTCT#561]
The log messages in gunbot-gui has almost no color. See the screenshot.
![screenshot](https://user-images.githubusercontent.com/9738996/39655860-64df6624-4ffc-11e8-8d42-d1ee60e87afe.PNG)

I use at the moment the last release (v9.5.1 build 532) of the arm package.

**Comment by GuntharDeNiro** [comment]
arm package is known for this issue
