### ISSUE TITLE
RT issue v9.5.1

### ISSUE THREAD

**Issue by Alfonsvmv** [GuntharDeNiro/BTCT#563]
Hello,

I have an issue with RT mode, during the RT mode let say the buy order was 100, then go down to 94 and sells, but the bot waits till hit 100 again to buy again instead of re buy around the RT sell (94 in this case). This can occur multiple times making the sell target very hard to reach (buy high and sell low multiple times).
I have try multiple lvls of RT sell and RT rebuy even have try with trail me on. 

If there is some way to fix this in the strategy settings that will be great, if not I think that would be good change in the control philosophy, to set the rebuy value around the RT sell and not near the first buy (or previous buy) range. is better to lose the trading fees than the actual % set in the RT sell.

Cheers

**Comment by Steempunker** [comment]
Same problem, i came here looking for a solution (i thought i may have set it up wrong}.
Problem is...
It sells when price drops {as expected)  goes down further (nothing happens) goes down again (still nothing) then goes up and above original price and it buys.

**Comment by ddey94** [comment]
This is to prevent RTBuy/BuyBack Loops

**Comment by Majestic81** [comment]
I have the same issue and tested this over a couple of days now ; loosing Base Balance at every trade.

![image](https://user-images.githubusercontent.com/38986848/39809587-7caa7b70-5382-11e8-8254-02c172e29821.png)

**Comment by Steempunker** [comment]
Is anything happening about this issue? its been two weeks since this issue has been raised, we have had a substantial drop across USDT and crypto. If RT was working we would have gained but i suspect a lot of us lost money. Why is this issue not being progressed?

**Comment by GLock-PPC** [comment]
Same issue here on Emotionless strategy (and others) NOT buying back....

Any progress?
