### ISSUE TITLE
Gunbot GUI - no graphs, JSON data stripped

### ISSUE THREAD

**Issue by shaman79** [GuntharDeNiro/BTCT#564]
For Poloniex the GUI is not showing any charts at dashboard. The JSON data returned from server are incomplete, therefore the resulting JSON has invalid syntax and it is not possible to plot the graph. I noticed that the data sent are rather big, around 1,5MB. For Kraken it is working fine and the data for graph has several kB.

**Comment by GuntharDeNiro** [comment]
Not a bug, possibly a misconfiguration, please rely to your reseller for support on this.
