### ISSUE TITLE
Custom MACDH not selling

### ISSUE THREAD

**Issue by shaman79** [GuntharDeNiro/BTCT#567]
According to the wiki the MACDH strategy should sell when histogram goes from positive to negative values, but this does not happen. 

It is working for BUY (negative->positive), but not for SELL (positive->negative). 

I checked also the usual suspects like min volumes to buy/sell and confirmations (all false). I am testing on Kraken trading EUR pairs.

**Comment by rafetaslan** [comment]
i tried it usd pairs in bitfinex macd and macdh are not selling. i tried different pairs and periods. any idea?

**Comment by shaman79** [comment]
No, no idea. I am in contact with Gunthar. I want to check if all the sell conditions are really met, but most likely this is a bug.
