### ISSUE TITLE
Gunbot 9.5.1 (532) Ignoring BOUGHT_PRICE

### ISSUE THREAD

**Issue by imastud71** [GuntharDeNiro/BTCT#568]
BOUGHT_PRICE override was added to the config.js to sell some old bags but the logs still show a "WARNING: we couldnt get a BOUGHT PRICE, please manually override it using config.js.  This is the case on many coins I have.  Running on Bittrex.

**Comment by GuntharDeNiro** [comment]
please provide the config.js

**Comment by GuntharDeNiro** [comment]
Please provide your config.js

**Comment by imastud71** [comment]
Here is the config.js in .zip.
[config.zip](https://github.com/GuntharDeNiro/BTCT/files/1998069/config.zip)
Here is a screen shot of one of the errors:
![image](https://user-images.githubusercontent.com/34729527/39963378-28c42f7e-562f-11e8-8931-1021b138ae2c.png)
