### ISSUE TITLE
Close all buys implementation

### ISSUE THREAD

**Issue by Cleberw3b** [GuntharDeNiro/BTCT#57]
I was thinking about the bot and time like this when bitcoin is being pumping. Maybe the bot could have a button or trigger that should sell all pairs even with loss to prevent further losses. 

Could it be implemented?

Thx

**Comment by arttus** [comment]
There is already a PANIC_SELL and BUY_ENABLED options available in config.js.

**Comment by mikebussy3334** [comment]
What about the option to panic sell? I never used it, not sure what it does
exactly. but panic sell sounds like what you wanting to do.

**Comment by Cleberw3b** [comment]
Sounds like it, I already debagged my portifolio manually. Next time I will try this option.

**Comment by softgripper** [comment]
It would be great if we could tie a market exit based on BTC-USDT

So if BTC starts to trend - like 5% it would add that gain to the panic sell for anything trading against BTC.

Because I sleep, if BTC surges against USD most of my alt portfolio is bagged, possibly forever - and I can’t prevent this without manual intervention.  It’s not the alt that is performing badly, it’s that BTC is performing well vs USD.

**Comment by vicdr** [comment]
If implemented, hopefully that would be an optional setting... I wouldn't want that "feature".

**Comment by BitFlipp3r** [comment]
> So if BTC starts to trend - like 5% it would add that gain to the panic sell for anything trading against BTC.

> Because I sleep, if BTC surges against USD most of my alt portfolio is bagged, possibly forever - and I can’t prevent this without manual intervention. It’s not the alt that is performing badly, it’s that BTC is performing well vs USD.

Same here. But I would rather have the bot to stop buying during BTC Pump.

**Comment by GuntharDeNiro** [comment]
yes panic sell is the trick.
THanks!

**Comment by Utone** [comment]
I accidentally left some panic sell options in override (and with find and replace turned about 6 pairs to true) over night... I noticed some pairs really had a huge amount of sells, sweet...

Then I noticed the PANIC SELL:true values... Ohh...no... But contrary to my expectation almost all sells were at a profit! 👍 (Does gb default back to regular setting behaviour after one panic sell?) I might try this more often...
