### ISSUE TITLE
Gunbot 9.5.1 Build 532 not selling on SMACROSS custom strategy

### ISSUE THREAD

**Issue by TyPaul2** [GuntharDeNiro/BTCT#571]
Gunbot 9.5.1 Build 532 not selling on SMACROSS custom strategy.  I also tried MACD & MACDH custom strategies and found same issue. Is there something I can do to remedy this? I am trading on Binance.  If this is a Gunbot issue, how soon will this it be fixed?

**Comment by rafetaslan** [comment]
Same issue at #567 #565

**Comment by gaud13** [comment]
i think custom is having issues calculating the sma's and it gets worse the longer it runs

**Comment by gaud13** [comment]
ps. i will buy or sell 1nce after u start up the bot then wont trade again at least this has been my experience after getting buy_level out of the way

**Comment by Pedrolx** [comment]
same issue, tried MACD bought twice without selling.

**Comment by F-Phoenix** [comment]
same issue here with MACD and MACDH. Keeps buying and not a single sell. I am using GUNBOT v9.5.1 (build 532) on binance using USDT as  base coin by the way.

**Comment by F-Phoenix** [comment]
is there a workaround to fix this while we wait for the next release? thanks

**Comment by Romalian** [comment]
Same as f-Phoenix. MACD strategy don't sell out...
I will put a TV alert to sell, waiting for the issue resolved.
