### ISSUE TITLE
dashboard graph

### ISSUE THREAD

**Issue by gaud13** [GuntharDeNiro/BTCT#572]
why dont we jst use the TV graph on the pairs tab and superimpose the buy sell lines then we ca set it up so the indicators that we r using for each pair is shown on the graph ?

**Comment by GuntharDeNiro** [comment]
because we ant to build our own charts so to draw what gunbot really sees

**Comment by gaud13** [comment]
k perhaps an enhancement suggestion to add band sma's ema's ect when using these indicators to help tweek our settings from where the bot buys to where we want it to buy
