### ISSUE TITLE
Gunbot 9.5.1 Build 532: "TrailMe! Price to Buyundefined" when enabling "TRAIL_ME_RT"

### ISSUE THREAD

**Issue by GitHubGiggity** [GuntharDeNiro/BTCT#575]
Example of error on my log on one of my pairs:
---------------------------------------------------------

GBRT_v9.5.1 (Build 532) BTC-NANO Round # 2

 ɢƱҊɮøͳ RT Edition  Scanning binance for trading opportunities 2018/05/12 18:26:53

2018/05/12 18:26:55: TrailingBuy limit 0.00073655

2018/05/12 18:26:55: Last price         0.00073950   |  Target to buy:   0.00074407

2018/05/12 18:26:55: Stop limit     0.00074399000

2018/05/12 18:26:55: Price of           BTC-NANO is going   DOWN  

2018/05/12 18:26:55: Moving Stop limit to     0.00074394

2018/05/12 18:26:55: Moving TrailingBuy limit to 0.00073506

2018/05/12 18:26:55: TrailingStop limit 0.00075138

2018/05/12 18:26:55: Last price         0.00073890   |  Target to sell:   NaN

2018/05/12 18:26:55: StopLoss limit     0.00074241

Price to sell is not in TSSL range

TrailMe! RT enabled

2018/05/12 18:26:55: TrailingBuy limit 0.000738036

2018/05/12 18:26:55: Last price         0.0007395   |  Target to RTbuy:   0.0007821892500000001

2018/05/12 18:26:55: Stop limit     0.0007439640000000001

2018/05/12 18:26:55: Price of           BTC-NANO is going   DOWN  

2018/05/12 18:26:55: Moving Stop limit to     0.000742458

2018/05/12 18:26:55: Moving TrailingBuy limit to 0.0007365420000000001

TrailMe! Price to Buyundefined

**Comment by GitHubGiggity** [comment]
Here is another log pair with same error at the end:
---------------------------------------------------------

GBRT_v9.5.1 (Build 532) BTC-BCC Round # 5

 ɢƱͶɮ๏ͳ RT Edition  Scanning binance for trading opportunities 2018/05/12 18:41:37

2018/05/12 18:41:39: TrailingBuy limit 0.16932770

2018/05/12 18:41:39: Last price         0.17057500   |  Target to buy:   0.17026211

2018/05/12 18:41:39: Stop limit     0.17034980

Price to buy is not in TSSL range

2018/05/12 18:41:39: TrailingStop limit 0.17292227

2018/05/12 18:41:39: Last price         0.17048500   |  Target to sell:   0.17189093

2018/05/12 18:41:39: StopLoss limit     0.17085958

Price to sell is not in TSSL range

TrailMe! RT enabled


2018/05/12 18:41:39: TrailingBuy limit 0.16322706213

2018/05/12 18:41:39: Last price         0.170575   |  Target to RTbuy:   0.16388259249999998

2018/05/12 18:41:39: Stop limit     0.16453812

Price to buy is not in TrailMe range
TrailMe! Price to Buyundefined

**Comment by gjtokkel** [comment]
Same issue here when tssl enabled for rt.
Build 532

Price to sell is not in TSSL range
------------------------------------------------------------------------------------------------
TrailMe! RT enabled
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
2018/05/21 16:07:50: TrailingBuy limit 0.07789720553999999
------------------------------------------------------------------------------------------------
2018/05/21 16:07:50: Last price         0.083187   |  Target to RTbuy:   0.07836740999999998
------------------------------------------------------------------------------------------------
2018/05/21 16:07:50: Stop limit     0.078837614
------------------------------------------------------------------------------------------------
Price to buy is not in TrailMe range
TrailMe! Price to Buyundefined
------------------------------------------------------------------------------------------------
┌───────────────────┬─────────────────────────┬─────────────────────────┬────────────────────────┬────────────────┬───────────────────┬───────────────────┬──────────┐
│ ɢՍÑβםŁ RT Edition │ Stop limit hit          │ Can we buy              │ Can we sell            │ Panic sell     │ Can average       │ REVERSAL TRADE    │          │
├───────────────────┼─────────────────────────┼─────────────────────────┼────────────────────────┼────────────────┼───────────────────┼───────────────────┤          │
│ Core checks       │       NO

**Comment by Zeroccool** [comment]
Same issue
