### ISSUE TITLE
RSI settings

### ISSUE THREAD

**Issue by gaud13** [GuntharDeNiro/BTCT#588]
it apears u like to use TV RSI values which are often inaccurate on binance leading to missed trade opertunities. i would prefer RSI to be calculated according to the pages i watch (binance)

**Comment by Tungsten183** [comment]
As I understand GB calculates RSI by itself using SMAPERIOD as RSI length. So if you set SMAPERIOD to 50, RSI will be calculated by the last 50 candles.

At this point I like to hijack this topic:

I have been playing around with RSI the past week and noticed sometimes huge differences compared to GB RSI / TV RSI / Exchange RSI. All on the same timeframe, same length setting ofcourse. Usually all three were different, sometimes by as much as 10 points. 
Other users were not reporting such big differences though.
Could it have something to do with my bot settings?

Thanks

**Comment by gaud13** [comment]
to re hijack this :D a) if im using BB i need the smaperiod to be set for BB and B) this big differences i believe is that they are often set to the same period BUT 1 is set to 14,close another is set to 14,open and another is set to 14, hlc3 and so forth. it would seem simple to add a few categories for use to close our settings wouldn't it ?
