### ISSUE TITLE
Feature Request:  allow TRADING_LIMIT to be a percentage of the base of the traded pair

### ISSUE THREAD

**Issue by BigBri41** [GuntharDeNiro/BTCT#592]
I think it would be a neat feature to allow TRADING_LIMIT to remain the way that it currently is as well as be set to a percentage.  You could differentiate a decimal entry from a percentage entry by just looking for % at the end of the value.  With decimal notation only, an unattended bot will only make linear profit.  If percentage notation existed, the bot could be left unattended and exponential profits could be achieved.

**Comment by litwi1rm** [comment]
A slight modification of this idea would be to allow both decimal entry and a percentage utilizing whichever is higher. This might help ensure a minimum amount is used for the trading limit but allow for a higher limit if the funds are available.
