### ISSUE TITLE
Gunbot V9.5.1 Fetching Balance again issue on Binance

### ISSUE THREAD

**Issue by khalidpak2004** [GuntharDeNiro/BTCT#603]
Dear All,
I am using gunbot V9.5.1 on Binance exchange and from start i am facing issue when ever i am starting the bot i works fine and after 30 to 40 minutes it starts showing fetching balance again, Fetching order detail again with every pair scan and also stops working after some time and display the error unable to connect to the exchange.
after that i have to stop bot wait for a while restart system and some time have to update time then again bot starts working but it does not work continuously.
i increased delay time in bot setting and support guy also check the system but problem is still there and now support staff also stopped resonding
please help me to solve the issue

**Comment by AVGibby** [comment]
Same issue I am having.
