### ISSUE TITLE
405 Bought Price Calculations

### ISSUE THREAD

**Issue by YoJeff** [GuntharDeNiro/BTCT#61]
The "Averaged bought price" calculations are occasionally wrong, at least on polo.   

Perhaps gunbot is not taking into account polo's vig?   It reaches too far back.

**Comment by YoJeff** [comment]
More docs

Here is the buy:

> │ ɢƱƝßםŦ v4.0.5 │ EMA1        │ EMA2        │ Buy at        │ Last       │ BTC        │ GAME       │ Pair     │
> │ Buy cycle     │ 0.00048575  │ 0.00048578  │ 0.00047652075 │ 0.00045464 │ 0.30543125 │ 0.00000000 │ BTC_GAME │
> │ Callbacks     │ Time to buy │ 0.00045464  │ BTC_GAME      │            │            │            │          │
> │ BOUGHT!!!     │ Amount:     │ 21.99542495 │ Rate:         │ 0.00045464 │                                    │

It did indeed buy 21.995.   And it paid 0.00045463.

From Polo:
> 2017-08-30 14:02:51 | Buy | 0.00045463 | 21.99542495 | 0.00999978

After commissions it should be:
> Balance: 21.9404,  Price:  .0004557

However the next cycle says:
>Balance GAME: 21.94043639
>Averaged bought price: 0.0004727505522195214

**Comment by GuntharDeNiro** [comment]
quantity is taken in consideration in the avg price calculation buddy

**Comment by YoJeff** [comment]
Still wrong.   SettledQty / PricePaid != gunbotcost
