### ISSUE TITLE
V10 - Binance Error 400

### ISSUE THREAD

**Issue by H256** [GuntharDeNiro/BTCT#618]
Hi, first off: Great new Bot! :) 
I've upgraded my bot to the latest release of Version 10. 
Everything was done like mentioned inside the Wiki.

All my licensed exchanges work except for binance, where i receive this error:
```
Error: Error: Response code 400
    at errorHandler (C:\snapshot\gunbot-public\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unable to connect to binance
Please if this error persists, stop Gunbot, wait a few minutes and then start it again...
```

In v9 this works.

Is there any way to get binance working in V10?

**Comment by H256** [comment]
OMG, sorry, seems to be my local time sync. :(

**Comment by lenso01** [comment]
@H256 I have same problem? 
How did you resolve?

**Comment by H256** [comment]
@lenso01 I have synced my system clock and restarted the bot. After that it worked.
