### ISSUE TITLE
[v10.7.2] Issues with input in Trading Pairs screen

### ISSUE THREAD

**Issue by enesg** [GuntharDeNiro/BTCT#637]
In version 10.7.2 build 836 I have the following data entry issues in Trading Pairs screen.
There is a difference in handling when I enter the name of the pair in lowercase or capital letters. 

So when I try to add for example "BTC-ETH" (in capital) and click on Add button, the message "Pair added"  appears on the right corner of the screen. Then all the input fields are cleared out and the pair is added.
When I try to add for example "btc-eth" (in lowercase) and click on Add button, no message appears on the right corner of the screen, the input fields are not cleared out (which is actually handy for add many pairs), the pair is added.

Also when I have added a pair already and try to add it again by entering the pair name in capital letters I receive the message that the pair is already added (which is correct). This doesn't happen when I enter the pair name in lowercase, or half-capital, half-lowercase (for example "btc-ETH".

I need also scroll down when there are many pairs added to check if the pair is added actually, so it would be great when the pairs are showed in an inner frame or list so that I don't have to scroll-up and down all the time.

Also when I try to update a strategy for a pair I found some issues.
When I change the strategy for an pair and click on another pair directly, the change is not applied.
It is also possible to clear the strategy out for a pair completely by leave it blank, I'm not sure if this is ok.

**Comment by grumpy-kitty** [comment]
Should be fixed. Open a new issue if it occurs in the latest version.
