### ISSUE TITLE
Missing coins pair parameter!

### ISSUE THREAD

**Issue by slizkejjoe** [GuntharDeNiro/BTCT#64]
Hello, i have this problem - i have all settings by the manual. Please help.

**Comment by utdrmac** [comment]
This is not a support area. Use the forums. This is for bugs in the software. Please close this and use the https://gunthy.org/index.php?topic=27.0 forums or ask for help in the Telegram group.

**Comment by vicdr** [comment]
Seriously? There is no help forthcoming in the forums.

**Comment by utdrmac** [comment]
@vicdr Yes, seriously. Github issues are not for support, they are for reporting bugs. Ask for help in the Telegram group. Many, many active people there to assist. Please close this issue.

**Comment by vicdr** [comment]
@utdrmac ... I know full well what github is for, but hey, listen, i don't really give  a damn for your "protocols" I'm really peeved off that i've bought a product that doesn't work properly, has cost me a ton of money in losses and i can't get support for the issues... who or what is telegram group? i can't find it even in a web search, frankly i wish i'd never bought this rubbish

**Comment by utdrmac** [comment]
You should have received an invite to the Telegram group from the person you purchased the license from. The program does in fact work and works awesome.

Link your forms post here so I can find it and I'll assist you there.

**Comment by utdrmac** [comment]
@vicdr If you are on 3.3.2, which I suspect you are, you are not providing all necessary information to start. A quick google search revealed this page: https://gunthy.org/index.php?topic=316.0

**Comment by vicdr** [comment]
@utdrmac , no i'm not... i'm on 4.0.5 ... 3.3.2 gui is too tall vertically to fit on 2017 surface pro screen and is not re-sizeable.

**Comment by utdrmac** [comment]
@vicdr I'm on 4.0.5 too and this is my config. http://termbin.com/pgio Been working decent for the past several days. If you are still having issues, please talk to the person you bought the license from and get the Telegram invite link and join the 2000+ people already there. Please close this issue as well. Thanks.
