### ISSUE TITLE
V10 Gunbot does not buy!

### ISSUE THREAD

**Issue by mcgregor4** [GuntharDeNiro/BTCT#642]
Running on Linux Mint, I have coins that start with A-L on a V9 bot running a BBTSSL strategy, have a V10 836 Bot running letters M-Z exact same strategy. V9 Bot over past 9 days made over 30 trades. V10 bot made 2 trades. The bot does not seem to want to buy, there are funds, etc and the other normal stuff you would expect to see, it just does not buy. I can supply logs if you need them. Surely I am not the only person on this planet seeing this issue.

**Comment by ecab081** [comment]
Also seeing this issue, running it  on Ubuntu 18.  I have tried custom strategy  of bb-gain, tssl and bbta.  I had my low bb set to 5 then put it to 15 and nothing.  The only time the bot put a buy order in was when i turned on tp buy.   As of now i am letting the bot run on bbta on bittrex.

**Comment by enesg** [comment]
I experience also the same issue. I have tried emotionless and tssl strategy, but no difference.
I have also set for example in tssl buy level to 0.2 and buy range 0.5. It says for approximately all the pairs "looking to buy". In gunbot V9 it should made much more buys.

**Comment by Deadmansclick009** [comment]
Same problem for me on Ubuntu , ive got back to version 9. Might run slower, but i prefer the layout and defo the Gui, the Gui on v9 is better than v10. On v10 the Charts are very poor. come on guys Backward step there!

**Comment by sgaduuw** [comment]
I too am seeing something similar.
With Callback Messages enabled, the GUI will notify me when a pair is ready to buy/sell or has reached a stop limit, but it will not act upon it.
Debug log shows nothing resembling errors or warnings, and I am able to manually trade through the GUI

**Comment by Deadmansclick009** [comment]
Hey sgaduuw i have gone back to using the V9.5.1 - Build 532 which works fine although its Version 9. I did find that V10.7.2 - Build 830 was a working version of 10. I went back to version 9 as i prefer the GUI Build, much cleaner. Hope this helps. . . .

**Comment by enesg** [comment]
I have migrated back to V9 too which works much better. I'm looking out for a much stabler release of V10.
