### ISSUE TITLE
Unable to connect Binance

### ISSUE THREAD

**Issue by jotaperez3** [GuntharDeNiro/BTCT#650]
I have this error,

Error: {}
    at errorHandler (/snapshot/Gunbot-master/ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unable to connect to binance
Please if this error persists, stop Gunbot, wait a few minutes and then start it again...

I did the last recommendation "stop Gunbot, wait a few minutes and then start it again..."but the error is the same.

**Comment by the-scott-davis** [comment]
I have this same problem on both Mac and Windows. I have tried all the time-drift fixes etc, none of which work. I have given up and moved to a different exchange for now, but I'd love to hear of a definitive solution for this issue.

**Comment by jotaperez3** [comment]
The problems are of the exchange or the software?

**Comment by Hampden** [comment]
I also have this issue.  I was able to get the error when creating a trading pair:

LTC-ETH  binance  MACD

It went away when I deleted the pair and created:

BTC-ETH  binance  MACD

Maybe 'LTC-ETH' is not a valid trading pair and this trips an error?

**Comment by yashspatel23** [comment]
The structure for writing trading pairs is always BASE-QUOTE. So it should be ETH-LTC instead of the other way around. This will make it work in binance.

**Comment by Hampden** [comment]
Thanks.  In this case it's obvious which is base, but how do I know what is
base for:

BTC-USDT
Or
ETH-USDT

?

Hampden

**Comment by yashspatel23** [comment]
Great question!

Fiat always trumps crypto when it comes to determining which is base. So USDT would be base

**Comment by grumpy-kitty** [comment]
Should be fixed. Open a new issue if you encounter this using the latest version and have used all known methods of fixing connection issues.
