### ISSUE TITLE
Errors in latest version 10.7.2_b837

### ISSUE THREAD

**Issue by kanendosei** [GuntharDeNiro/BTCT#657]
I keep getting the following errors:

```
10/19/2018 @ 12:50PM
BTC-TRIG@binance
or: Cannot read property '0' of undefined
```

And:

```
10/19/2018 @ 12:16PM
BTC-XRP@binance
{"code":"ESOCKETTIMEDOUT","connect":false}
```

I've tried many settings, but they persist, even when I set the timeout to 300 in the Bot. This did not happen on pre-v10.x builds.  I am on Linux, btw.

**Comment by CryRoy** [comment]
I get the same ESOCKETTIMEDOUT error all the time on windows

**Comment by emotionlesstrader** [comment]
I get the same thing constantly

-Regards,

Johnny Ricco
