### ISSUE TITLE
405 stepgain buy skips lvl1 and lvl2 values

### ISSUE THREAD

**Issue by afhdyt** [GuntharDeNiro/BTCT#67]
Using the stepgain strategy, gunbot skips lvl1 and lvl2 buy values and reads only the buy value at lvl3. Since I put my lvl3 value at 50 (50%), it has never put in a trade since so far theres no 50% downmove from the MA value yet. I put my lvl1 and lvl2 at 2 and 4. I have been running for the 3 days with no trades.

**Comment by utdrmac** [comment]
That's correct behavior. See the wiki: wiki.gunthy.org/index.php/Stepgain Please close this issue.
