### ISSUE TITLE
After upgrading to v11 portfolio value empty.

### ISSUE THREAD

**Issue by litwi1rm** [GuntharDeNiro/BTCT#671]
![image](https://user-images.githubusercontent.com/7134135/48768019-12cd0900-ec86-11e8-929a-87ec3794fb02.png)

**Comment by Qwatton** [comment]
Probably just the market at the moment, there may actually be nothing there lol,

In all seriousness though, give the bot a while to load, let it process your pairs a few times and then reload the page, seems to work for me. It seems that the bot just needs to go through your pairs before it can confirm the total balance.

**Comment by litwi1rm** [comment]
Yeah I had the exact same thoughts. It has made trades since upgrading, and its been 3 days since I've upgraded, not sure how much time it needs if 3 days isn't enough.

**Comment by Qwatton** [comment]
Hi,

3 days is definitely more than enough, issue should sort itself out within around 30 minutes tops, what's your BOT_DELAY currently set to? It may be an issue with pulling prices from the exchange, try to increase your BOT_DELAY under exchange settings by 1 or 2 seconds and then close your browser, give it a minute and then reopen the GUI, let me know if the issue still persists
Qwatton

**Comment by litwi1rm** [comment]
It was 1, I updated to 3. Closed browser for 10 minutes, opened for another 20 minutes with nothing so far.

**Comment by ajemptage** [comment]
Same problem here. I tried increasing the delay all the way up to 10 and still no luck.

**Comment by ajemptage** [comment]
Any news on this?

**Comment by Qwatton** [comment]
If you're still having this issue I would personally suggest that you reinstall gunbot. You can make a copy of your Config.js file first and saving this somewhere else to ensure you still have your settings and exchanges saved, once you've saved the config.js file to a different location, delete the gunbot 'win' and/or 'macos' files and fresh download and reinstall Gunbot v11, copy your config.js file back over and replace the one that installs with Gunbot and you're good to go again, I had a similar issue before on VPS and a fresh install sorted things out for me, for Binance you should have the Delay setting on the exchanges settings tab to atleast 3 seconds, this gives the bot time to process each pair sufficiently and check for trading opportunities and price changes before moving on, anything less than this could cause it to miss pairs and could also cause issues for the GUI.
Let me know if the issue still persists after a reinstall,
Any error messages in the command prompt or red error tags appearing on the web GUI?

**Comment by ajemptage** [comment]
Still no luck I'm afraid. Fresh install, completely wiped browser, set bot_delay and binance exchange delay to 5. Still shows zero portfolio balance after an hour.

**Comment by ajemptage** [comment]
Sorry, missed the last question. No errors in GUI or console.
I also tried running it on my mac too with the same result.
V10 worked perfectly with the same settings.

**Comment by R3DEY3UK** [comment]
I also have this issue with V11.7.5 Stable.

**Comment by H256** [comment]
I also have this issue plus it does not load any values into the dashboard  :(

**Comment by ajemptage** [comment]
Is this being looked in to?

**Comment by R3DEY3UK** [comment]
I stumbled across a fix. 

Delete your tradings pairs and re-add them via settings & save.

It auto updated my portfolio balance, once I had done this. All is working well :)

Good luck!

**Comment by ajemptage** [comment]
Glad you got it worked out on your end. Unfortunately I tried this and still no good.
I even started with a fresh config file and re-added the pairs to the fresh install.

**Comment by MareG76** [comment]
Did the patch 906 actually help someone with this problem cause I still have empty portfolio value ?

**Comment by Qwatton** [comment]
Sorry for the delay in getting back.
What Strategy are you guys using? Apparently this is a glitch frequently experienced when using the emotionless strategy. Also, @Ajemptage did you remove and re-add your pairs using the web GUI or through editing your config.js file? 
@MareG76
Did you complete uninstall and reinstall for the latest update?

**Comment by Qwatton** [comment]
I would also clear your pairs list prior to uninstalling and then add them back in once you've installed the latrst update.

**Comment by MareG76** [comment]
I did a fresh install, made all the inputs from scratch and still nothing. I'm using gain strategy on both buy and sell

**Comment by yashspatel23** [comment]
If you are still having an issue with portfolio value not showing up, what are your trading pairs?

**Comment by MareG76** [comment]
ETH market on Binance: ADA, BAT, BCD, EOS, ETC, HOT, LTC, NANO, NEO, PAX, TRX, XLM, XRP, ZRX

**Comment by yashspatel23** [comment]
That’s the issue - we don’t support Portfolio Value with base as ETH yet. Portfolio value is currently limited to showing you the value of traded pairs with bases in fiat and BTC.

Supporting ETH as base is currently underdevelopment and will be added soon.

**Comment by MareG76** [comment]
Sorry then, I missed that info...Thanks

**Comment by litwi1rm** [comment]
v11.7.6 patch fixed my issue thanks.

**Comment by ajemptage** [comment]
Hi, sorry for the silence. I use Starter edition right now, can I use the 11.7.6 patch? I don't see it available if I look at the releases for starter.
