### ISSUE TITLE
V11 starter edition empty portfolio balance

### ISSUE THREAD

**Issue by ajemptage** [GuntharDeNiro/BTCT#679]
Hi, I see in another (closed) issue that the latest patch fixed this for standard edition and higher licenses, but under the downloads for starter edition the latest patch is not available. Will the 11.7.6 patch be available for starter edition licenses?

**Comment by DaBill73** [comment]
The best fix combination that I've had with this is ensure that you download the latest version, and then download the TimeSyncTool & install that.  Then run the bot.  Most of the time the Portfolio information reflects accurately after that.

**Comment by Singman33** [comment]
TimeSyncTool ? What's that ?
