### ISSUE TITLE
Bot appears to be in sell mode despite not having any balance

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#68]
Running on Bittrex. Sample output. Notice there is 0 balance of BCC. So why is the bot on "level 2 to sell" when there is no balance to sell?

```
2017/09/01 16:42:22: USDT-BCC Last Bid/Ask 646.3/648.89999999
2017/09/01 16:42:23: Got Trading History
2017/09/01 16:42:23: Averaged bought price: 354.822
2017/09/01 16:42:23: Price to sell: 360.499152
2017/09/01 16:42:23: EMA1: 644.52270807/EMA2: 644.36777963
2017/09/01 16:42:23: Price to buy: 634.0578951559199
2017/09/01 16:42:24: Got Open Orders
2017/09/01 16:42:24: Last Bid/Price to sell: 646.3/360.499152
2017/09/01 16:42:24: Last Ask/Price to buy: 648.89999999/634.0578951559199
2017/09/01 16:42:24: Trend for USDT-BCC:    DOWN!!!
2017/09/01 16:42:24: We are on level 2 to sell (bought/sell at): 354.822/360.499152
 ɢƱΠβØŦ v4.0.5  Tips&Tricks: USDT-BCC can be sold, checking conditions...
2017/09/01 16:42:24: There are some trading opportunities for USDT-BCC at bittrex. Scanning Trade History
2017/09/01 16:42:24: Last Bid price USDT-BCC: 646.3 | Last Ask: 648.89999999
2017/09/01 16:42:24: Balance USDT: 6468.236
2017/09/01 16:42:24: Balance BCC: 0
2017/09/01 16:42:24: On Orders BCC: 0
2017/09/01 16:42:24: Trend for USDT-BCC:    DOWN!!!
Processing strategy STEPGAIN for USDT-BCC on bittrex
```

**Comment by GuntharDeNiro** [comment]
before to process the pair "Processing strategy STEPGAIN for USDT-BCC on bittrex" the bot gets prices and checks conditions for all pairs in yoru config.js
During the processing protocol of the pair > Processing strategy STEPGAIN for USDT-BCC on bittrex it decides if the coin needs to be bought or sold.
Thanks!

**Comment by utdrmac** [comment]
@GuntharDeNiro to present a better user experience, don't you think the bot should make all those decisions BEFORE output to the screen and then only output to the screen appropriate/correct information? The bot just prints out so much info, some of which, like this, is inaccurate/misleading.

**Comment by jadiesel** [comment]
You are not using a full featured release of the bot, you are using a release candidate. The logs spew out the info because we asked for it, it is helpful to test and analyze how things are working, not because it is user friendly.  When there is a real release, there may be an actual user interface.   If this is not good for you, you should be using the latest version release, which is 3.3.2.

**Comment by utdrmac** [comment]
Yes, this is an RC. I'm testing it. I have observed that it is producing inaccurate output. That is my bug report. A lot of the information is misleading as to what the bot is "actually" doing at that time. Instead of dismissing this bug, @GuntharDeNiro should have left it open so that when final release happens, he can revisit this bug and make sure that the output does in fact match the current behavior.
