### ISSUE TITLE
BOUGHT_PRICE does not work

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#69]
Config:
```
"BTC_LTC":   { "strategy": "stepgain", "override": { "BTC_TRADING_LIMIT": 0.05, "BOUGHT_PRICE": 0.01780000 } },
```

Log:
```
2017/09/01 20:01:06: BTC_LTC Last Bid/Ask 0.01799927/0.018
2017/09/01 20:01:07: Got Trading History
2017/09/01 20:01:09: Averaged bought price: 0.014640136037365135
2017/09/01 20:01:09: Price to sell: 0.014874378213962975
2017/09/01 20:01:09: EMA1: 0.01703491/EMA2: 0.01703469
2017/09/01 20:01:10: Got Open Orders
2017/09/01 20:01:10: Last Bid/Price to sell: 0.01799927/0.014874378213962975
2017/09/01 20:01:10: Last Ask/Price to buy: 0.018/0.016762134960000005
2017/09/01 20:01:10: Trend for BTC_LTC:    DOWN!!!
2017/09/01 20:01:10: We are on level 2 to sell (bought/sell at): 0.014640136037365135/0.014874378213962975
```

That is all kinds of absolutely wrong. Every calculation should have been based off BOUGHT_PRICE of 0.0178

The bot immediately sold my LTC because it saw STEPGAIN profit based on order history and a down trend.

It should NOT have done this! It should have waited for STEPGAIN profit based on BOUGHT_PRICE

**Comment by utdrmac** [comment]
https://gunthy.org/index.php/topic,1133.0.html

**Comment by utdrmac** [comment]
BOUGHT_PRICE actually adds to the averaging functionality of the order book. It does NOT give a true override of the price if there is previous history. The above feature request is to create a new variable that allows for a true override of BOUGHT_PRICE, essentially ignoring all previous trade history.

**Comment by GuntharDeNiro** [comment]
BOUGHT_PRICE is meant for deposited coins only with no previously orders on yoru order book. DO NOT use BOUGHT_PRICE if your order book have previous buy orders.
Thanks!

**Comment by utdrmac** [comment]
@GuntharDeNiro Maybe changing the parameter to DEPOSIT_PRICE, since it is for "deposited coins", so that it is more intuitive of a parameter and not mistaken for something it is not?

**Comment by jadiesel** [comment]
Or maybe someone who cares could put it in the wiki... and we could start having actual documentation? That's a win-win.

**Comment by lenardbang** [comment]
while trading many pairs, and some of them having multiple trades daily, with time i start getting this error:
WARNING: we couldnt get a BOUGHT PRICE for BTC-DCR, Please manually override it using config.js.

If the Bought Price setting in config is only for deposits, what am I supposed to do if this happens? Over the time it starts spamming this for 10+ pairs and more. All of those are obviously NOT deposits though...

**Comment by utdrmac** [comment]
@GuntharDeNiro I think a lot of people's "issues" with the bot does in fact come from lack of proper documentation. Since this is closed source, we, the users, can only guess at how things are working based on setting names and such. As a developer, the way you have programmed the bot and the way you think are different from what everyone else thinks.

**Comment by utdrmac** [comment]
Don't take that as an insult. It is typical behavior of all developers; myself included (I'm a C/C++/PHP/Go/Python developer). Developers write the code and therefore have an understanding that users don't. So when a user complains X doesn't work, developers usually go "well duh, that's obvious" when in fact it truly is NOT obvious to users because they didn't write the code.

**Comment by GuntharDeNiro** [comment]
I'm just stating what the code actually does which is what i wrote in the comment:
"BOUGHT_PRICE is meant for deposited coins only with no previously orders on yoru order book. DO NOT use BOUGHT_PRICE if your order book have previous buy orders.
Thanks!"
Please keep dramas out of this issue tracker, lol, insults are welcome in PM 3>

**Comment by ferninus** [comment]
@GuntharDeNiro can you use BOUGHT_PRICE to set the price for bought coins in a pair you are also actively trading?
