### ISSUE TITLE
got several of these errors on 4.0.5

### ISSUE THREAD

**Issue by purplepeanut** [GuntharDeNiro/BTCT#70]
`Error on strategy BB for BTC-ETC on bittrex while getting balances -| Error: RequestError: Error: read ECONNRESET`

**Comment by GuntharDeNiro** [comment]
It shoudl be fixed in v5
Please let me know once you get a chance to test it

**Comment by purplepeanut** [comment]
I will let you know as soon as able. When do you expect it will be released?

**Comment by GuntharDeNiro** [comment]
fixed in v5.
Thanks for reporting this!
