### ISSUE TITLE
Still getting error "while getting ema1" on 4.0.5

### ISSUE THREAD

**Issue by murm78** [GuntharDeNiro/BTCT#71]
![image](https://user-images.githubusercontent.com/31592215/30003952-07c19232-907b-11e7-8188-3d28d76e4233.png)

This error only came up on pairs where I had a 0 balance on the alt. 
Don't know what other information would be helpful to provide, but would be happy to do so.

**Comment by murm78** [comment]
I did double check and replaced gunthy.exe again. Still getting the same error on multiple pairs.

**Comment by GuntharDeNiro** [comment]
add EMA1 and EMA2 variables in config.js for the bb strategy.

**Comment by murm78** [comment]
Where can I find more info about the meaning of these variables? For example some strategies have "EMA1": 200, "EMA2": 50 
while others use
"EMA1": 2000, "EMA2": 1000. 
Do I have to subscribe to GBU or bug you for this information, or are these things spelled out on the forums and I just haven't found it?
