### ISSUE TITLE
C:\snapshot\gblackv12\ctx\js\bitfinex.js:0:0

### ISSUE THREAD

**Issue by Yanosh777** [GuntharDeNiro/BTCT#713]
Hello. Please help me. Getting these errors.
I`ve checked My API`s on bitfinex and all options are open except withdraw

error<>
at errorhundler <C:\snapshot\gblackv12\ctx\js\bitfinex.js:0:0>
at <anonimouse>
at process._tickCallback <internal/process/next_tick.js:188:7>
error<>
errorhundler <C:\snapshot\gblackv12\ctx\js\ctx-wrapper.js:0:0>
at <anonimouse>
at process._tickCallback <internal/process/next_tick.js:188:7>
Unable to connect to bitfinex
Please is this error persist stop gunbot wait a few minutes and then start it again....

Thank you

**Comment by grumpy-kitty** [comment]
Make sure that you're running the latest version and try a new API key. If issues persist contact support staff on Telegram.
