### ISSUE TITLE
HttpApiError: ZERO_OR_NEGATIVE_NOT_ALLOWED

### ISSUE THREAD

**Issue by firemound** [GuntharDeNiro/BTCT#72]
Using Bittrex I'm getting the below error:

`7|gunbot-v |  ɢՍҊ฿õͳ v4.0.5  Tips&Tricks: BTC-ETH can be sold!!!
7|gunbot-v | 2017/09/03 16:01:07: There are some trading opportunities for BTC-ETH at bittrex. Scanning Trade History
7|gunbot-v | 2017/09/03 16:01:07: Last Bid price BTC-ETH: 0.075689 | Last Ask: 0.075698
7|gunbot-v | 2017/09/03 16:01:07: Balance BTC: 0.35480417
7|gunbot-v | 2017/09/03 16:01:07: Balance ETH: 22.67472
7|gunbot-v | 2017/09/03 16:01:07: On Orders ETH: 0
7|gunbot-v | Processing strategy BB for BTC-ETH on bittrex
7|gunbot-v | ┌───────────────┬────────────┬─────────────┬─────────────┬──────────┬──────────┬──────────┬─────────┐
7|gunbot-v | │ ɢƱÑɃʘŁ v4.0.5 │ SMA        │ LowBB       │ HighBB      │ Last     │ ETH      │ Last Buy │ Pair    │
7|gunbot-v | ├───────────────┼────────────┼─────────────┼─────────────┼──────────┼──────────┼──────────┼─────────┤
7|gunbot-v | │ Sell cycle    │ 0.07554726 │ 0.075304375 │ 0.075790148 │ 0.075689 │ 22.67472 │ 388      │ BTC-ETH │
7|gunbot-v | └───────────────┴────────────┴─────────────┴─────────────┴──────────┴──────────┴──────────┴─────────┘
7|gunbot-v | Error on strategy BB for BTC-ETH on bittrex while selling -| Error: HttpApiError: ZERO_OR_NEGATIVE_NOT_ALLOWED`

This is after setting the BOUGHT_PRICE override on the pair following this warning:

`7|gunbot-v | WARNING: we couldnt get a BOUGHT PRICE for BTC-ETH, Please manually override it using config.js`

Is there something else I can do in the config to fix this? Attached is the log; should be easier to read.
[ZERO_OR_NEGATIVE_NOT_ALLOWED.txt](https://github.com/GuntharDeNiro/BTCT/files/1273050/ZERO_OR_NEGATIVE_NOT_ALLOWED.txt)

**Comment by GuntharDeNiro** [comment]
need to see your config file please, it seems like your bot is passing zero or negative value as volume or price.

**Comment by firemound** [comment]
Config attached.
[config.txt](https://github.com/GuntharDeNiro/BTCT/files/1273264/config.txt)

**Comment by firemound** [comment]
I also got around the issue by manually opening buy and sell orders for the pair. So I no longer need the bought price override; not getting this error anymore...

**Comment by GuntharDeNiro** [comment]
I dont see this anymore from v5.0.1 and above. Free to reopen this issue with more details if it happens again.
Thanks!
