### ISSUE TITLE
Kraken bug: Insufficient Funds

### ISSUE THREAD

**Issue by i6media** [GuntharDeNiro/BTCT#747]
I'm experiencing a problem where Gunbot tried to sell 0.5 BTC on Kraken but couldn't due to "insufficient funds". Therefore I missed a sell and lost a lot of money by that.

A forum entry of 2017 said that "it's a problem from Kraken" which cannot be handled:
https://gunthy.org/forum/index.php?topic=1381.0

I've researched this for a little bit and it seems to be a rounding issue, which maybe can be fixed on the Gunbot side: 
https://github.com/ccxt/ccxt/issues/393

**Comment by CryptoDodo** [comment]
Can you try to lower your MVTB and MVTS settings?
It helped me to solve it for me...

**Comment by i6media** [comment]
I think this resolved the issue.
