### ISSUE TITLE
Bittrex - buy order did not fill, later canceled, but bot still registers profits

### ISSUE THREAD

**Issue by TenaciousJai** [GuntharDeNiro/BTCT#75]
I hit a sell limit for LSKBTC on bittrex, which posted the sell order, but due to market conditions it did not fill immediately.  Some time later it canceled for an unknown reason (maybe something set by the bot, not sure), but after the order canceled the bot just picked up the tokens as available to sell without dropping the profit value from the calculation.

This was the first order of this pair, so it should have stayed at 0 after that order fell off.  

I'm not sure if there's even a feasible way for the bot to determine if an order was canceled so that it can adjust accordingly, but thought it was worth mentioning.

Thanks for the awesome product, day 1 is already posting some results for me.

**Comment by GuntharDeNiro** [comment]
i think this is from 3.3.2 which is not tracked here.
