### ISSUE TITLE
"INVALID LICENSE FOR [XXX]!!! Please contact your reseller!" using a Gunthy wallet with 1000 GUNTHY

### ISSUE THREAD

**Issue by litwi1rm** [GuntharDeNiro/BTCT#753]
Binance expired my api key/secret and I tried to update the new API key/seceret and getting the following error on startup of Gunbot. 

`0|gunthy-linux  | Loading config...`
`0|gunthy-linux  | info: socket.io started`
`0|gunthy-linux  | GUI Server Deployed: http://localhost:5000`
`0|gunthy-linux  | Your Gunthy token balance is: 1000 in wallet: 0xXXXX`
`0|gunthy-linux  | Your license type is: V12 - STANDARD`
`0|gunthy-linux  | Tradingview Plugin Access: false`
`0|gunthy-linux  | Market Maker Plugin Access: false`
`0|gunthy-linux  |`
`0|gunthy-linux  | Your user rank: 100`
`0|gunthy-linux  | You can have up to 1 exchanges to run simultaneously`
`0|gunthy-linux  | Your registered exchanges:`
`0|gunthy-linux  | BINANCE: XXXX`
`0|gunthy-linux  | INVALID LICENSE FOR BINANCE!!! Please contact your reseller!`

If I put in my old api key/secret pair I do not get the invalid license for binance error but I get an error connecting to binance and it crashes gunbot.

I've tried to use the "Swap Exchanges" to update my api key but get a gui error "Stop trying to update licenses you dont have.

I understand support should be dealt with via my reseller, but I have been unable to get a response from my reseller (hello@gunbot.com).

I thought having the Gunthy wallet was going to prevent the need to work through the reseller when we need to update our api keys?

**Comment by GunbotKitty** [comment]
Contact support on Telegram.
