### ISSUE TITLE
405 bought the pair even when it was already present- Double buy disabled:

### ISSUE THREAD

**Issue by krunalbarot** [GuntharDeNiro/BTCT#76]
Hi,

I got a buy on one of the bag which was already present. Not sure how and why it triggered . Can you please look into it ? 

------------------------------------------------------------------------------------------------
 ɢƱҊɃʘŁ v4.0.5  Scanning poloniex for trading opportunities 2017/09/06 05:02:38
------------------------------------------------------------------------------------------------
2017/09/06 05:02:38: BTC_DGB Last Bid/Ask 0.00000428/0.0000043
2017/09/06 05:02:39: Got Trading History
2017/09/06 05:02:40: Averaged bought price: 0.0000051799999999999995
2017/09/06 05:02:40: Price to sell: 0.000005278419999999999
2017/09/06 05:02:40: EMA1: 0.00000442/EMA2: 0.00000442
2017/09/06 05:02:40: Price to buy: 0.00000434928
2017/09/06 05:02:40: Got Open Orders
2017/09/06 05:02:40: Last Bid/Price to sell: 0.00000428/0.000005278419999999999
2017/09/06 05:02:40: Last Ask/Price to buy: 0.0000043/0.00000434928
2017/09/06 05:02:40: Trend for BTC_DGB:    UP!!!   
2017/09/06 05:02:40: We are on level 2 to sell (bought/sell at): 0.0000051799999999999995/0.000005278419999999999
 ɢƱҊ฿Øͳ v4.0.5  Tips&Tricks: BTC_DGB can be bought, checking balances... 
2017/09/06 05:02:40: There are some trading opportunities for BTC_DGB at poloniex. Scanning Trade History
2017/09/06 05:02:40: Last Bid price BTC_DGB: 0.00000428 | Last Ask: 0.0000043
2017/09/06 05:02:40: Balance BTC: 0.08356807
2017/09/06 05:02:40: Balance DGB: 192.56806632
2017/09/06 05:02:40: On Orders DGB: 0.00000000
2017/09/06 05:02:40: Trend for BTC_DGB:    UP!!!   
Processing strategy STEPGAIN for BTC_DGB on poloniex
┌───────────────┬─────────────┬──────────────┬───────────────┬───────────┬────────────┬──────────────┬─────────┐
│ ɢƱҊƁøͳ v4.0.5 │ EMA1        │ EMA2         │ Buy at        │ Last      │ BTC        │ DGB          │ Pair    │
├───────────────┼─────────────┼──────────────┼───────────────┼───────────┼────────────┼──────────────┼─────────┤
│ Buy cycle     │ 0.00000442  │ 0.00000442   │ 0.00000434928 │ 0.0000043 │ 0.08356807 │ 192.56806632 │ BTC_DGB │
├───────────────┼─────────────┼──────────────┼───────────────┼───────────┼────────────┼──────────────┼─────────┤
│ Callbacks     │ Time to buy │ 0.0000043    │ BTC_DGB       │           │            │              │         │
├───────────────┼─────────────┼──────────────┼───────────────┼───────────┼────────────┴──────────────┴─────────┤
│ BOUGHT!!!     │ Amount:     │ 232.55813953 │ Rate:         │ 0.0000043 │                                     │
└───────────────┴─────────────┴──────────────┴───────────────┴───────────┴─────────────────────────────────────┘
2017/09/06 05:02:41: Kicking poloniex, receiving new tickers...

The stepgain settings are as below:

"stepgain": {
            "BTC_TRADING_LIMIT": 0.0001,
            "PERIOD": 15,
            "BUYLVL1": 1.5,
            "BUYLVL2": 1.6,
            "BUYLVL3": 70,
            "SELLLVL1": 1.5,
            "SELLLVL2": 1.6,
            "SELLLVL3": 70,
            "BUYLVL": 2,
            "SELLLVL": 2,
            "LASTPOINTS": 4,
            "AVGPOINTS": 20,
            "AVGMINIMUM": 1.0e-8,
            "EMA1": 4,
            "EMA2": 2,
            "PANIC_SELL": false,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.001,
            "MIN_VOLUME_TO_SELL": 0.001
        },

**Comment by krunalbarot** [comment]
another example for the above one --

------------------------------------------------------------------------------------------------
 ɢƱŋɮѺŁ v4.0.5  Scanning poloniex for trading opportunities 2017/09/06 12:30:57
------------------------------------------------------------------------------------------------
2017/09/06 12:30:57: BTC_XMR Last Bid/Ask 0.02619864/0.02620815
2017/09/06 12:30:58: Got Trading History
2017/09/06 12:31:00: Averaged bought price: 0.02900022
2017/09/06 12:31:00: Price to sell: 0.029551224180000002
2017/09/06 12:31:00: EMA1: 0.02668797/EMA2: 0.02668102
2017/09/06 12:31:00: Price to buy: 0.02625412368
2017/09/06 12:31:00: Got Open Orders
2017/09/06 12:31:00: Last Bid/Price to sell: 0.02619864/0.029551224180000002
2017/09/06 12:31:00: Last Ask/Price to buy: 0.02620815/0.02625412368
2017/09/06 12:31:00: Trend for BTC_XMR:    UP!!!   
2017/09/06 12:31:00: We are on level 2 to sell (bought/sell at): 0.02900022/0.029551224180000002
 ɢƱҊɃ๏Ł v4.0.5  Tips&Tricks: BTC_XMR can be bought, checking balances... 
2017/09/06 12:31:00: There are some trading opportunities for BTC_XMR at poloniex. Scanning Trade History
2017/09/06 12:31:00: Last Bid price BTC_XMR: 0.02619864 | Last Ask: 0.02620815
2017/09/06 12:31:00: Balance BTC: 0.08470131
2017/09/06 12:31:00: Balance XMR: 0.03489504
2017/09/06 12:31:00: On Orders XMR: 0.00000000
2017/09/06 12:31:00: Trend for BTC_XMR:    UP!!!   
Processing strategy STEPGAIN for BTC_XMR on poloniex
┌───────────────┬─────────────┬────────────┬───────────────┬────────────┬────────────┬────────────┬─────────┐
│ ɢՍͶɃѺŁ v4.0.5 │ EMA1        │ EMA2       │ Buy at        │ Last       │ BTC        │ XMR        │ Pair    │
├───────────────┼─────────────┼────────────┼───────────────┼────────────┼────────────┼────────────┼─────────┤
│ Buy cycle     │ 0.02668797  │ 0.02668102 │ 0.02625412368 │ 0.02620815 │ 0.08470131 │ 0.03489504 │ BTC_XMR │
├───────────────┼─────────────┼────────────┼───────────────┼────────────┼────────────┼────────────┼─────────┤
│ Callbacks     │ Time to buy │ 0.02620815 │ BTC_XMR       │            │            │            │         │
├───────────────┼─────────────┼────────────┼───────────────┼────────────┼────────────┴────────────┴─────────┤
│ BOUGHT!!!     │ Amount:     │ 0.03815607 │ Rate:         │ 0.02620815 │                                   │
└───────────────┴─────────────┴────────────┴───────────────┴────────────┴───────────────────────────────────┘

**Comment by utdrmac** [comment]
Related #73

**Comment by GuntharDeNiro** [comment]
This is not a bug: 
2017/09/06 05:02:40: Balance DGB: 192.56806632
Last Ask/Price to buy: 0.0000043
192*0.0000043= DUST
The bot ignores it and keeps buying.
You can trigger this using MIN_VOLUME_TO_BUY and MIN_VOLUME_TO_SELL in config settings.
Thanks!
~Gun

**Comment by krunalbarot** [comment]
But the logs says 
2017/09/06 05:02:40: Balance DGB: 192.56806632

then why would it try to buy ??

**Comment by GuntharDeNiro** [comment]
@krunalbarot wtf guys.....if you have "dust" you cant even sell it. Please attempt to use some logic before to spam the issue tracker or any other chat

**Comment by utdrmac** [comment]
@GuntharDeNiro The setting is called MIN **VOLUME** not MIN VALUE. 192.56 is not dust per the definition of the parameter. 192.568 > 0.001 therefore this is an issue.

**Comment by antaeusgr** [comment]
Guys, @GuntharDeNiro is right on this one. 192.568 * 0.0000043 = 0.0008280424 < 0.001 BTC. Next time, remember that this variable (MIN VOLUME) no matter the name, refers to the BTC value.

**Comment by utdrmac** [comment]
@antaeusgr Completely understood. That's not the problem. The problem is that nowhere does it state that MIN_VOLUME is expressed in BTC. (Official docs: https://github.com/GuntharDeNiro/BTCT/releases) Because the docs lack this, one can only go off the basis of the name of the parameter. The word "VOLUME" referrers to quantity, not total value. 192.568 units of bananas * 0.0000043 (price per banana) = total value of bananas owned; not volume of bananas. The volume of bananas is 192.568. Thus the confusion: 192.568 volume > 0.001 min_volume.  Had the parameter been named MIN_VALUE or some better docs given explaining this calculation, this wouldn't be an issue. Do you see my point of view? I'm just discussing here.

**Comment by antaeusgr** [comment]
Yes I agree with you @utrmac, it would be nice if some variables were renamed. another example is when trading ETH pairs, it still says max BTC limit to trade - though you can find documentation about the gunbot e.g. in the gunbot wiki by diesel. But you know with code even a small change may require a lot of work from the developer, so I don't know if it worth the time to fix that, he could though just add a small text section explaining some of the ambiguous variables in the repository.
