### ISSUE TITLE
Bot needs to respond to HUP requests to reload config

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#8]
On linux, the bot doesn't always recognize that the config file has changed. Instead of restarting the bot, bot should respond to `kill -HUP` to reload the config manually.

**Comment by jayp0** [comment]
It does responds to kill -HUP and reloads both -config.js and ALLPAIRS-params.js
but it also resets prices calculation.

**Comment by utdrmac** [comment]
@jayp0 I tried this and it killed the bot instead of reloading config. v3.3.2

**Comment by jayp0** [comment]
I re-checked this and you are right, gunbot does not handle HUP properly.  
When it's launched from pm2, it sounds like it handles HUP with that 'Activating hot reconfig...' but its not. :(
