### ISSUE TITLE
v4.0.5 sells coins and immediately re-buys at higher price (GAIN strategy, not BB)

### ISSUE THREAD

**Issue by murm78** [GuntharDeNiro/BTCT#80]
Perhaps I misunderstood the GAIN strategy. Is the bot supposed to wait and see if it can sell at a better price, or will it simply sell as soon as the minimum %GAIN is met?

Comparing the times of the buy orders and the price chart, it does not look like the new buys respect the specified buy level either (3% below EMA).

Here is the order book:

![image](https://user-images.githubusercontent.com/31592215/30234784-9d196920-94b5-11e7-8c99-1befc7cda3ca.png)

Config is as follows:

	"bot": {
		"debug": true,
		"period_storage_ticker": 2000,
		"interval_ticker_update": 30000,
		"timeout_buy": 60000,
		"timeout_sell": 60000,
		"WATCH_MODE": false,
		"VERBOSE": true
	},
	"strategies": {
		"bb": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 15,
			"GAIN": 0.6,
			"HIGH_BB": 45,
			"LOW_BB": 45,
			"EMA1": 480,
			"EMA2": 240,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
		},
		"gain": {
			"BTC_TRADING_LIMIT": 0.01,
			"PERIOD": 30,
			"BUY_LEVEL": 3,
			"GAIN": 1,
			"EMA1": 480,
			"EMA2": 240,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 60,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001
		}

**Comment by GuntharDeNiro** [comment]
GAIN is to "sell" not to buy, the bot follows what you have as buy strategy. If it is pure gain, it buys at % below EMA you specify in BUY_LEVEL

**Comment by murm78** [comment]
It was pure gain. If you look at the price chart at that time it did not buy 3% below the EMA. Bot had been running more than 24 hours so it had enough data to correctly calculate EMA.

So why was this marked invalid?

Please confirm, bot will sell coins as soon as minimum %GAIN is met, and does not wait to see if the price continues to rise?
