### ISSUE TITLE
Multiple Purchases sell LOSES money (not Sh*t coins: RISE, BAT)

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#81]
I have experienced this phenomenon in 3.3.2 (I know, I know this is for v405 bugs, bear with me). 

On multiple occasions, I have seen GB on StepGain buy coins multiple times in a row, and then sell them at the LAST purchased price, not the AVERAGE purchase price or the highest purchase price, both of which would be valid. 

This has resulted in GB selling at a LOSS, which it is not supposed to do. 

You may have fixed this in later versions, but I wanted to post it in the event that you have not. Two things come from this: 1, the multiple buy bug, and 2, the idea that multiple purchases might not be a bad idea, IF GB is programmed to use the average of the multiple buys or some other way to guarantee not to have a loss and to meet the parameters of the buy/sell strategy being used. 

Here are two examples of multiple buys. 

If you have fixed this already, sorry to waste your time! 

Love your tool. Glad it appears to be selling well. 

FIRST EXAMPLE: MULTIPLE BUYS, NO LOSS:
![screen shot 2017-09-09 at 3 47 29 pm](https://user-images.githubusercontent.com/7082654/30253773-526b22e0-9651-11e7-8209-c8a31837bd82.png)

2ND EXAMPLE, MULTIPLE BUYS, SOLD AT A LOSS:
![screen shot 2017-09-08 at 7 36 48 pm](https://user-images.githubusercontent.com/7082654/30249191-744a8e14-95fc-11e7-845d-f12974129f88.png)

**Comment by smportis** [comment]
SIMILAR but not exactly the same as issue 73

**Comment by GuntharDeNiro** [comment]
not supported version.
