### ISSUE TITLE
INSUFFICIENT_FUNDS Because of Rounding from Bittrex

### ISSUE THREAD

**Issue by pjlwealth** [GuntharDeNiro/BTCT#86]
Error Message:
Error on strategy BB for BTC-??? on bittrex while selling -| Error: HttpApiError: INSUFFICIENT_FUNDS

What i see, its rounding the available coin and rounding to the 6th. Am i missing something in the config?

Balance ARK: 13.67989**1**

![screen shot 2017-09-11 at 3 59 45 am](https://user-images.githubusercontent.com/31854775/30278635-eb22e96e-96d8-11e7-9ac2-3d14f8b814e5.png)

Balance in Bittrex for ARK: 13.67989**056**
![screen shot 2017-09-11 at 4 00 09 am](https://user-images.githubusercontent.com/31854775/30278639-ed018b1e-96d8-11e7-8196-40a5cda44d8d.png)

This is my config, without including KEYS
[config_nokey.txt](https://github.com/GuntharDeNiro/BTCT/files/1292817/config_nokey.txt)

**Comment by nAffie** [comment]
Getting that same error. Using bbstepgain as strategy.

**Comment by vertygo411** [comment]
Also getting that error, pure BB, on bittrex. Confirmed I do have sufficient funds.

**Comment by GuntharDeNiro** [comment]
aknowledged, will push a fix in a few

**Comment by sylance** [comment]
Don't know if this is obvious, but when you say a push will come in a few, does that mean on server side or will there be a new executable to download?  I got the same error, so I shut down v5 and went back to v3.3.2.

**Comment by GuntharDeNiro** [comment]
Fixed in v5.0.2
Thanks for reporting this!
