### ISSUE TITLE
Feature Request: Set maximum price to buy in all strategies

### ISSUE THREAD

**Issue by defvader** [GuntharDeNiro/BTCT#87]
Hello! It would be a huge benefit to be able to set a firm price for the bot not to buy above in both BB and Stepgain strategies. There have been many instances where, for example, I have had the bot make many successful trades and then the bot almost immediately buys back, after a sell, on a falling coin and wipe out the profit I had obtained. The ability to set a max price to buy would ensure that this would not happen. And although it may also cause some successful future trades to be missed, I would prefer that to having a profit loss on previous trades. Thank you for reading.

**Comment by GuntharDeNiro** [comment]
or maybe we could use again back the dont buy above lowest ema like we had in 1000trades and in the actual gain/stepgain family.

**Comment by GuntharDeNiro** [comment]
fixed in v5.0.5
Thanks for reporting this!
