### ISSUE TITLE
8 api calls per second is very persistant

### ISSUE THREAD

**Issue by jadiesel** [GuntharDeNiro/BTCT#88]
I'm getting the 8 API request error on most of my pairs every minute at Poloniex. I rarely go longer than a minute without getting one.   This is without proxy. Could this be related to me running 63 pairs? plus all USDT plus all ETH (In seperate but linked accounts) - they all get the message.
I do ignore it, but it sure looks like it is going to cause a problem.

![image](https://user-images.githubusercontent.com/20715803/30284898-f2ce7bb6-96e1-11e7-981c-dcfab6f40971.png)

**Comment by ThecRw** [comment]
I have the same issue, however, I'm running one pair only (pure BB with standard settings):

![image](https://user-images.githubusercontent.com/31865936/30295414-6e29305c-9738-11e7-933d-f6819f45a33d.png)

After some time I start getting connection timeout:

![image](https://user-images.githubusercontent.com/31865936/30295435-80aafbca-9738-11e7-98c9-3180d0a803da.png)

**Comment by GuntharDeNiro** [comment]
@jadiesel are you using a different instance for each market with different api key?
Anyway i will try to add a bot timing back so people with just a few pairs to trade would make it more human

**Comment by jadiesel** [comment]
Yes, I run 1 bot for each exchange/pair, with their own API key

**Comment by GuntharDeNiro** [comment]
Added BOT_DELAY config setting: you can now slow down your bot to avoid API call limit if you are processing only a few pairs.
Thanks for reporting this!
