### ISSUE TITLE
Bot needs to allow X cycles to pass after startup before acting on data

### ISSUE THREAD

**Issue by tandyuk** [GuntharDeNiro/BTCT#90]
In this load of the bot, you see it start, calculate some EMA's based on something, immediately see $price <  Lower BB, BUY.

In reality low, high and sma are the same, leading to the bot purchasing at within 5% of the top BB.

Please add some kind of delay or sanity check on whether the newly calculated EMA/BB's are still current before acting on them. 

config:
                        "BTC-LTC": {
                                "strategy": "bb",
                                "override": {
                                        "BTC_TRADING_LIMIT": 0.05
                                }
                        },
   
        "strategies": {
                "bb": {
                        "BTC_TRADING_LIMIT": 0.01,
                        "PERIOD": 15,
                        "EMA1": 2,
                        "EMA2": 4,
                        "GAIN": 2,
                        "HIGH_BB": 40,
                        "LOW_BB": 40,
                        "STDV": 2,
                        "SMAPERIOD": 50,
                        "PANIC_SELL": false,
                        "DOUBLE_UP": false,
                        "STOP_LIMIT": 60,
                        "BUY_ENABLED": true,
                        "MIN_VOLUME_TO_BUY": 0.0001,
                        "MIN_VOLUME_TO_SELL": 0.005

                },
    

root@gunbot:/home/james/GUNBOT_V5_0_1# ./gunthy-linx64
Loading config...
Loading exchange kraken
Loading exchange bittrex
------------------------------------------------------------------------------------------------
 ɢՍÑßʘͳ v5.0.1  Scanning bittrex for trading opportunities 2017/09/12 01:48:22
------------------------------------------------------------------------------------------------
2017/09/12 01:48:22: BTC-LTC Last Bid/Ask 0.01630291/0.01630564
------------------------------------------------------------------------------------------------
 ɢƱÑƁѺͳ v5.0.1  Scanning kraken for trading opportunities 2017/09/12 01:48:22
------------------------------------------------------------------------------------------------
2017/09/12 01:48:23: Got Trading History
2017/09/12 01:48:23: Price to buy: 0.01634900
2017/09/12 01:48:23: BCHXBT Last Bid/Ask 0.13200000/0.13202000
2017/09/12 01:48:23: Got Open Orders
2017/09/12 01:48:23: Last Bid/Price to sell: 0.01630291/0.01634900
2017/09/12 01:48:23: Last Ask/Price to buy: 0.01630564/0.01634900
------------------------------------------------------------------------------------------------
HIGH BB: 0.01634900 == SMA: 0.01634900 == LOW BB: 0.01634900
------------------------------------------------------------------------------------------------
 ɢƱÑɃøŦ v5.0.1  Tips&Tricks: BTC-LTC can be bought!!!
2017/09/12 01:48:23: There are some trading opportunities for BTC-LTC at bittrex. Scanning Trade History
2017/09/12 01:48:23: Last Bid price BTC-LTC: 0.01630291 | Last Ask: 0.01630564
2017/09/12 01:48:23: Balance BTC: 0.53822345
2017/09/12 01:48:23: Balance LTC: 0
2017/09/12 01:48:23: On Orders LTC: 0
Processing strategy BB for BTC-LTC on bittrex
0.016349
┌───────────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬─────┬─────────┐
│ ɢՍͶɃѺŁ v5.0.1 │ LowBB       │ HighBB      │ Buy at      │ Last       │ BTC        │ LTC │ Pair    │
├───────────────┼─────────────┼─────────────┼─────────────┼────────────┼────────────┼─────┼─────────┤
│ Buy cycle     │ 0.01634900  │ 0.01634900  │ 0.016349000 │ 0.01630564 │ 0.53822345 │ 0   │ BTC-LTC │
├───────────────┼─────────────┼─────────────┼─────────────┼────────────┼────────────┼─────┼─────────┤
│ Callbacks     │ Time to buy │ 0.016349000 │ BTC-LTC     │            │            │     │         │
├───────────────┼─────────────┼─────────────┼─────────────┼────────────┼────────────┴─────┴─────────┤
│ BOUGHT!!!     │ Amount:     │ 3.06642364  │ Rate:       │ 0.01630564 │                            │
└───────────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────────────────────┘

------------------------------------------------------------------------------------------------
 ɢƱΠ฿øͳ v5.0.1  Scanning bittrex for trading opportunities 2017/09/12 01:48:38
------------------------------------------------------------------------------------------------
2017/09/12 01:48:38: BTC-LTC Last Bid/Ask 0.01630565/0.01631590
2017/09/12 01:48:39: Got Trading History
2017/09/12 01:48:39: Price to buy: 0.01634900
2017/09/12 01:48:39: Averaged bought price: 0
2017/09/12 01:48:39: Price to sell: 0
2017/09/12 01:48:39: EMA1: 0.00017283/EMA2: 0.00017286
2017/09/12 01:48:39: Price to buy: 0.00016989

2017/09/12 01:48:40: Got Open Orders
2017/09/12 01:48:40: Last Bid/Price to sell: 0.01630565/0.01663175
2017/09/12 01:48:40: Last Ask/Price to buy: 0.01631590/0.01634900
------------------------------------------------------------------------------------------------
HIGH BB: 0.01634900 == SMA: 0.01634900 == LOW BB: 0.01634900
------------------------------------------------------------------------------------------------
 ɢƱŋɮØŦ v5.0.1  Tips&Tricks: BTC-LTC can be bought!!!
2017/09/12 01:48:40: There are some trading opportunities for BTC-LTC at bittrex. Scanning Trade History
2017/09/12 01:48:40: Last Bid price BTC-LTC: 0.01630565 | Last Ask: 0.0163159
2017/09/12 01:48:40: Balance BTC: 0.48809848
2017/09/12 01:48:40: Balance LTC: 3.0664236
2017/09/12 01:48:40: On Orders LTC: 0
Processing strategy BB for BTC-LTC on bittrex
2017/09/12 01:48:40: To sell we need 0.00012500007493335 BTC for fees - We have: 0.48809848 BTC
┌─────────────────┬────────────┬─────────────┬──────────┬───────────────────────┬───────────┬────────────┬─────────┐
│ ɢƱΠβõŁ v5.0.1   │ SMA        │ LowBB       │ HighBB   │ Last                  │ LTC       │ Last Buy   │ Pair    │
├─────────────────┼────────────┼─────────────┼──────────┼───────────────────────┼───────────┼────────────┼─────────┤
│ Sell cycle      │ 0.01634900 │ 0.016349    │ 0.016349 │ 0.01630565            │ 3.0664236 │ 0.01630564 │ BTC-LTC │
├─────────────────┼────────────┼─────────────┼──────────┼───────────────────────┼───────────┴────────────┴─────────┤
│ GUNBOT CALLBACK │ Sell price │ 0.016631753 │ Result   │ DOUBLE_UP is disabled │                                  │
└─────────────────┴────────────┴─────────────┴──────────┴───────────────────────┴──────────────────────────────────┘

https://s.tradingview.com/x/1HRp2OVM/

Prior to this, I had been running the bot with buy_enabled=false, and watching=true for about 2 hours,

**Comment by lucidqdreams** [comment]
+1
I started the bot and within 5 minutes it had brought some of every pair I had listed.  Some of it was a good buy, some of it clearly seemed like it was at a peak.

**Comment by nicholas-eden** [comment]
I experienced the same problem.  Loaded up v5 for the first time.  Within minutes, it bought everything, some of which was well above the BB.

**Comment by GuntharDeNiro** [comment]
This should be fixed in v5.0.2
Please send feedback when i release it: tuned BB calculation so yu shoul dhave correct values from beginning now.
Thanks!

**Comment by GuntharDeNiro** [comment]
we now have "close" history and we can have good values since very first cycle (v505)
