### ISSUE TITLE
BB calculations changing constanly

### ISSUE THREAD

**Issue by ThecRw** [GuntharDeNiro/BTCT#95]
I've been checking my GB v5 and I've noticed something about the BB calculation for some pairs. After I get the right conf for BB, the bot runs fine, but eventually there is going to be a cycle with a very, very different high and low BB calculation (very tight, eventually the same as current price). When this happens, the bot gives a buy warning, meaning, it would buy on that point. Then on the next cycle the "right" High and Low BB come back again and remains for several cycles until the same tight cycle repeats... I only run one pair at the moment (ETH) and I have it in watch mode to make sure I do not buy anything by accident.

I'm attaching a log file were you can see this happening several times in a few minutes/cycles.

Strategy is "bbstepgain" and here are the confs:

=============
	"bot": {
		"debug": false, 

		"period_storage_ticker": 2000, 
		"interval_ticker_update": 20000, 

		"timeout_buy": 60000, 
		"timeout_sell": 60000, 

		"WATCH_MODE": true, 
		"VERBOSE": true, 
		"TV_GAIN": 0.6, 
		"TV_TRADING_LIMIT": 0.001 
	},

===============

		"bbstepgain": {
			"BTC_TRADING_LIMIT": 0.001,
			"PERIOD": 15,
			"HIGH_BB": 45,
			"LOW_BB": 10,
			"STDV": 2,
			"SMAPERIOD": 50,
			"SELLLVL1": 1,
			"SELLLVL2": 2,
			"SELLLVL3": 70,
			"SELLLVL": 2,
			"LASTPOINTS": 5,
			"AVGPOINTS": 50,
			"AVGMINIMUM": 0.00000001,
			"EMA1": 2,
			"EMA2": 4,
			"PANIC_SELL": false,
			"DOUBLE_UP": true,
			"STOP_LIMIT": 90,
			"BUY_ENABLED": true,
			"MIN_VOLUME_TO_BUY": 0.001,
			"MIN_VOLUME_TO_SELL": 0.001

		},

Let me know if you need anything else

[gunbot-out-1.zip](https://github.com/GuntharDeNiro/BTCT/files/1299202/gunbot-out-1.zip)

**Comment by GuntharDeNiro** [comment]
Fixed in v5.0.2
Thanks for reporting this!
