### ISSUE TITLE
v502 - Selling at unfillable price after manual price insert

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#96]
When adding a coin with an old purchase (bag) in Bittrex, and I manually add the BOUGHT_PRICE in the override for the coin in the config file, the Bot does not print that (averaged) value in the output: 

![screen shot 2017-09-13 at 3 21 50 pm](https://user-images.githubusercontent.com/7082654/30398989-e1b5bf62-9897-11e7-94e4-e6fec2ad67aa.png)

I'm also not sure if it is using the correct value or not to get a sell price.

**Comment by dobcrypto** [comment]
Have the same problem.
Wrote Gunthar, he knows, waiting answer/decision.

**Comment by smportis** [comment]
Additional info: (thanks dobcrypto FYI). 
It does use the value, but places an unfillable order to sell at too high a price: 

See sell price for BTC_ETC:
![screen shot 2017-09-13 at 3 28 20 pm](https://user-images.githubusercontent.com/7082654/30399171-660b9124-9898-11e7-8e9a-db2dd6f90d4f.png)

ACTUAL PRICE is much lower: 
![screen shot 2017-09-13 at 3 28 39 pm](https://user-images.githubusercontent.com/7082654/30399172-687f89f6-9898-11e7-9294-3dac5b66cd11.png)

**Comment by smportis** [comment]
Continues to try to sell that order after manual and automatic cancellation.

**Comment by dobcrypto** [comment]
@smportis that was with my bot on 4.0.5, maybe its "STOP_LIMIT"?

**Comment by GuntharDeNiro** [comment]
can you please guys complete the informations you provided, defining the strategy you using?
THanks!

**Comment by dobcrypto** [comment]
@GuntharDeNiro 
"BTC-XLM": {"strategy": "bbgain", "override": { "GAIN": 0.6, "BOUGHT_PRICE": 5.67e-6}},
"BTC-GUP": {"strategy": "bbgain", "override": { "GAIN": 0.6, "BOUGHT_PRICE": 6.633e-5}}
        "bbgain": {
            "BTC_TRADING_LIMIT": 0.005,
            "PERIOD": 15,
            "GAIN": 1.1,
            "HIGH_BB": 45,
            "LOW_BB": 40,
            "STDV": 2,
            "SMAPERIOD": 80,
            "EMA1": 200,
            "EMA2": 50,
            "PANIC_SELL": false,
            "DOUBLE_UP": false,
            "STOP_LIMIT": 60,
            "BUY_ENABLED": true,
            "MIN_VOLUME_TO_BUY": 0.0051,
            "MIN_VOLUME_TO_SELL": 0.0051
"period_storage_ticker": 1500,
"interval_ticker_update": 5000,

**Comment by GuntharDeNiro** [comment]
fixed in v5.0.3 
thanks for reporting this!
