### ISSUE TITLE
[5.0.2] Changing period_storage_ticker and interval_ticker_update the BB remain unchanged 

### ISSUE THREAD

**Issue by Gnorbe** [GuntharDeNiro/BTCT#97]
[GB 5.0.2] Changing the parameters **period_storage_ticker**; **interval_ticker_update**; **Period**, **Smaperiod**, the bb remain unchanged. The only parameter that seems to have effect on BB is **STDV**, but it seems impossible tune **both BB** just the STDV parameter.

I compare the BB calculated by Gunbot with the BB displayed in the Poloniex chart with SMA = 50 and Candlesticks = 15min; and assume that BB does not need time to be calculated by Gunbot, but they are shown correct from the first cycle.

Example with only one pair with BB strategy:

Config.js:

	"pairs": {
		"poloniex": {	
		
				"BTC_XMR": {
				"strategy": "bb",
				"override": {}
			}

	"bot": {
		"debug": false, 

		"period_storage_ticker": 2000, 
		"interval_ticker_update": 25000, 

		"timeout_buy": 60000, 
		"timeout_sell": 60000, 

		"WATCH_MODE": true, 
		"VERBOSE": true, 
		"TV_GAIN": 0.6, 
		"TV_TRADING_LIMIT": 0.001,
		"BOT_DELAY": 1
	},

		"strategies": {
		"bb": {
			"BTC_TRADING_LIMIT": 0.0001, 
			"PERIOD": 15, 
			"EMA1": 2, 
			"EMA2": 4, 
			"GAIN": 2, 
			"HIGH_BB": 40, 
			"LOW_BB": 40, 
			"STDV": 2, 
			"SMAPERIOD": 50, 
			"PANIC_SELL": false, 
			"DOUBLE_UP": true, 
			"STOP_LIMIT": 60, 
			"BUY_ENABLED": false, 
			"MIN_VOLUME_TO_BUY": 0.0001, 
			"MIN_VOLUME_TO_SELL": 0.0001 

		},

Poloniex chart: **High BB=0.02881** -  **SMA=0.02751** - **Low BB=0.02620** 

Gunbot results:

 v5.0.2  Scanning poloniex for trading opportunities 2017/09/13 22:49:43
------------------------------------------------------------------------------------------------
2017/09/13 22:49:43: BTC_XMR Last Bid/Ask 0.02806000/0.02813697
2017/09/13 22:49:44: Got Trading History
2017/09/13 22:49:45: Price to buy: 0.02797077
2017/09/13 22:49:46: Got Open Orders
2017/09/13 22:49:46: Last Bid/Price to sell: 0.02806000/0.02810346
2017/09/13 22:49:46: Last Ask/Price to buy: 0.02813697/0.02797077
------------------------------------------------------------------------------------------------
HIGH BB: 0.02836884 == SMA: 0.02803711 == LOW BB: 0.02770539

The indicators calculated by Gunbot, in particular the Low BB, do not coincide with the Poloniex chart.
I try to fine-tune the bb by changing different parameters, some example:

"period_storage_ticker": 1000, 
"interval_ticker_update": 20000, 
Gunbot result: HIGH BB: 0.02836815 == SMA: 0.02803753 == LOW BB: 0.02770691

"period_storage_ticker": 500, 
"interval_ticker_update": 50000, 
Gunbot Results:HIGH BB: 0.02836800 == SMA: 0.02803772 == LOW BB: 0.02770744

"period_storage_ticker": 1, 
"interval_ticker_update": 25000, 
Gunbot Results: HIGH BB: 0.02836985 == SMA: 0.02803826 == LOW BB: 0.02770666

"SMAPERIOD": 150, 
Gunbot results: HIGH BB: 0.02837144 == SMA: 0.02803932 == LOW BB: 0.02770719

"PERIOD": 120, 
Gunbot results: HIGH BB: 0.02837135 == SMA: 0.02803951 == LOW BB: 0.02770767

Note that small similar changes in values from one cycle to another are normally also without modifying the parameters, and that the problem is the LowBB.

Only the STDV parameter has effect on the bb. 

"STDV": 11, 
Gunbot results:  HIGH BB: 0.02986260 == SMA: 0.02803999 == LOW BB: 0.02621737
**At this point the LowBB is correct but the HigBB is too high.**

Is it normal that by modifying the parameters listed above BBs do not change significantly? For example, what are the correct parameters for BBs like Poloniex chart with the BTC_XMR pair?

**Comment by utdrmac** [comment]
I'm pretty sure that period_storage_ticker has nothing to do with BB calculations. BB calculations come from historical candlestick data provided by Polo API. period_storage_ticker relates to the web-socket connection as new trade data happens live.

**Comment by Gnorbe** [comment]
"period_storage_ticker": 2000, // number of prices to store to calculate TA indicators
From: https://github.com/GuntharDeNiro/BTCT/releases/tag/v501

**Comment by GuntharDeNiro** [comment]
i have seen people getting the exact poloniex BB values indeed, please someone else confirms/denies
Thanks!

**Comment by GuntharDeNiro** [comment]
fixed in v5.0.5
Thanks for reporting this!
