### ISSUE TITLE
Typo to terminal "On Orders" should be "Open Orders" v502

### ISSUE THREAD

**Issue by smportis** [GuntharDeNiro/BTCT#98]
Is this a typo? "On Orders" should be "Open Orders"?

![screen shot 2017-09-13 at 4 58 07 pm](https://user-images.githubusercontent.com/7082654/30403154-f4532b06-98a5-11e7-8de8-15a8040fe683.png)

![screen shot 2017-09-13 at 4 58 49 pm](https://user-images.githubusercontent.com/7082654/30403106-c9ea1b5e-98a5-11e7-953e-e6afd29bf43b.png)

**Comment by GuntharDeNiro** [comment]
it is "how many SNT you have on orders.
